### ISSUE TITLE
`createResource` doesnt track loading value

### ISSUE THREAD

**Issue by kirill-dev-pro** [solidjs/solid#1004]
### Describe the bug

Hi there, I have following example component with `createResource`

```js
function Example() {
  const [resource] = createResource(ExampeleGetApi)

  if (resource.error) {
    return <p>Error loading resource</p>
  }

  if (resource.loading) {
    return <p>Loading...</p>
  }

  return <p>{JSON.stringify(resource())}</p>
}
```

and it will never go from loading state even when resource successfully loaded. I suppose its a bug and `resource.loading` should be tracked as mentioned in docs

| loading, error, and latest are reactive getters and can be tracked.

Example on stackblitz bellow

### Your Example Website or App

https://stackblitz.com/edit/vitejs-vite-3dwep9?file=src/App.tsx

### Steps to Reproduce the Bug or Issue

1. Open stackblitz example
2. Run

### Expected behavior

As a developer I expect that once resource is loaded view will update with data

### Platform

Version: 
- solid-js 1.4.2
- vite 2.9.9

### Additional context

Component works fine if you remove checking for loading

**Comment by LXSMNSYC** [comment]
Summary: Component functions only evaluate *once*

```js
function Example() {
  const [resource] = createResource(ExampeleGetApi)
  
  return (
    <Switch fallback={<p>{JSON.stringify(resource())}</p>}>
      <Match when={resource.error}>
        <p>Error loading resource</p>
      </Match>
      <Match when={resource.loading}>
        <p>Loading...</p>
      </Match>
    </Switch>
  );
}
```

**Comment by kirill-dev-pro** [comment]
Is this intentional behavior?

**Comment by atk** [comment]
It's a direct consequence of solid's mental model: render once, encapsulate changes into side effects. If you put the change into the rendered component, it's going to lose reactivity. You can easily remedy this by returning a function that returns the value if you absolutely must do it manually (otherwise, Suspense and ErrorBoundary are the preferred solution):

```ts
function Example() {
  const [resource] = createResource(ExampeleGetApi)

  return () => {
    if (resource.error) {
      return <p>Error loading resource</p>
    }

    if (resource.loading) {
      return <p>Loading...</p>
    }

    return <p>{JSON.stringify(resource())}</p>
  }
}
```

**Comment by LXSMNSYC** [comment]
> Is this intentional behavior?

This is by design, and one of Solid's better features to achieve optimal performance

**Comment by kirill-dev-pro** [comment]
@atk @LXSMNSYC @edemaine thatnk you guys, now I have a better understanding of how solid is different from react. 
Its not a bug so I will close this issue. Hope it will be helpful for someone like me to find it in google later
