### ISSUE TITLE
Strict equality operator (`===`) does not work in `produce` 

### ISSUE THREAD

**Issue by izreit** [solidjs/solid#1006]
### Describe the bug

Hi there, I found that an object property in `produce()` is not evaluated as "strict equal" even it is compared with itself.

```typescript
const [state, setState] = createStore({ obj: { value: 0 }});
const increment = () => setState(
  produce(state => {
    console.log(state.obj.value === state.obj.value); // ==> true, as expected
    console.log(state.obj === state.obj); // ==> false (!)
  })
);
```

I could not find any description about the equality in `produce()` in neither [the API reference][api-ref] nor [tutorial][tutorial-produce] so I'm not sure if this is a bug... but it is not very intuitive at least.  It seems no [unit test][tests] considers this.

I think the implementation may be able to cache the proxy and reuse it for the same property access to avoid this behavior.

[api-ref]: https://www.solidjs.com/docs/latest/api#produce
[tutorial-produce]: https://www.solidjs.com/tutorial/stores_mutation?solved
[tests]: https://github.com/solidjs/solid/blob/d1d0c243cada62e4d1cb9f172ed31bf13cab3b07/packages/solid/store/test/modifiers.spec.ts#L103-L206

### Your Example Website or App

https://playground.solidjs.com/?version=1.4.1#NobwRAdghgtgpmAXGGUCWEwBowBcCeADgsrgM4Ae2YZA9gK4BOAxiWGjIbY7gAQi9GcCABM4jXgF9eAM0a0YvADo1aAGzQiAtACsyAegDucAEYqA3EogcuPfr2ZCouOAGVc3OFl6F5I+qxSsvKKKnQa2nr6ZB5CFlZWMvQQzLhotBC8AMIMEC6MABQAlPxWvA4ZMbzAMc5evGRwuO51ALq8ALwOTi7ungUCtCY6iPYAblBq9HCjAAxSkkWWEGUVEFUYjnDweZ28xZ0AfA1NLS4Fq+W+tP6sBbUuR6WZ5a-MlepwAHRqtADm91wdS+Qx0nQ6XQe31BS14+n04OOMkmjX2AEIipdXlCQcMvhMpnAANRE5avKSYl5LBIvIS4JiZC4vcoAHhM9FwHkyBGIHRU7M5GRUvAyWQ0zAA1h0QJshDtcJJDljygAFehkAAWvHg9hxoPxk2mUixLP0Aq5Sqpy0kNKEonEBQOHWOLJyyXycMO3hEtGY9HlXz+TQAomptsJcAAhfAASREFzAUEIhBURQxyzAklaQA

### Steps to Reproduce the Bug or Issue

1. Go to the above playground.
2. Click the button "Push me 0".
3. See Console. ("false" is printed by line 9 (evaluates `state.obj === state.obj`))

### Expected behavior

I expected that `state.obj === state.obj` is evaluated to `true` as like ordinary JavaScript.

### Platform

- OS: Windows 11
- Browser: Chrome
- Version: 101.0.4951.67

Also confirmed the same behavior on Firefox 100.0.1 and Edge 101.0.1210.47 on Windows 11.

**Comment by Ferotiq** [comment]
objects are strictly equal to each other in normal JS? Since when?

**Comment by ryansolid** [comment]
Yeah it's a different proxy object because it's mutable. Hmm.. you could call `unwrap` on both sides. I'm not sure if there is a better approach than that. I usually compare values but I can see some scenario where you might want to compare the underlying object.

**Comment by izreit** [comment]
Thanks for the quick response. I didn't know `unwrap`.

> Yeah it's a different proxy object because it's mutable. (snip) I'm not sure if there is a better approach than that.

As I mentioned above, how about caching proxies?  Because any handlers in [setterTraps][setter-traps] depend on its arguments only, I think we can safely replace the [following line in `get`][get-handler]:

```typescript
return isWrappable(value) ? new Proxy(value, setterTraps) : value;
```

with a caching version such as:

```typescript
return (
  isWrappable(value)
    ? (cache.get(target, property) ?? cache.add(target, property, new Proxy(value, setterTrap))
    : value
);
```

if we have a kind of `cache` implementation. It can be implemented with `WeakMap` or maybe with a `Symbol` (like `$RAW` in the current implementation). 

I think this makes `produce` more intuitive and less object creation, memory consumption and GC cost slightly.

[setter-traps]: https://github.com/solidjs/solid/blob/d1d0c243cada62e4d1cb9f172ed31bf13cab3b07/packages/solid/store/src/modifiers.ts#L120-L136
[get-handler]: https://github.com/solidjs/solid/blob/d1d0c243cada62e4d1cb9f172ed31bf13cab3b07/packages/solid/store/src/modifiers.ts#L124

**Comment by izreit** [comment]
> Comparing to the store outside would still be different but it is what it is.

Yeah I agree. Comparing to the outside store may be impossible without operator overloading in JavaScript.
