### ISSUE TITLE
Portal doesn't respect mount

### ISSUE THREAD

**Issue by darklight9811** [solidjs/solid#1035]
### Describe the bug

The doc is not clear on this and the lack of jsdoc makes hard to understand what exactly mount should be doing here. But I can't get Portal to respect the container I want to place it on.

### Your Example Website or App

https://stackblitz.com/edit/vitejs-vite-rmmpmx?file=src/App.tsx

### Steps to Reproduce the Bug or Issue

1. You can check out the example app

### Expected behavior

The portal content to be placed inside mount element

### Platform

- OS: linux
- Browser: firefox
- Version: 1.3 - 1.4

**Comment by otonashixav** [comment]
You should specify the element to mount to via the `mount` prop: https://stackblitz.com/edit/vitejs-vite-dexn6s?file=src/App.tsx
