### ISSUE TITLE
npx degit solidjs/templates/js my-app error "could not download"

### ISSUE THREAD

**Issue by AlexMBFlow** [solidjs/solid#1050]
could not download https://github.com/solidjs/templates/archive/492c5a21b0cd8613ecc279fd92b63031250f3073.tar.gz

I can't install this template and this link doesn't work. https://prnt.sc/QXSKTIdbkzul

How to solve this problem?

**Comment by ryansolid** [comment]
Need more information. Platform, OS, etc.. The template appears to download and haven't received any other reports of this.

**Comment by AlexMBFlow** [comment]
> Need more information. Platform, OS, etc.. The template appears to download and haven't received any other reports of this.

Platform: Desktop
OS: Wiindows 10
Ide: Vscode

I can't open this link in the browser, even with VPN enabled

**Comment by AlexMBFlow** [comment]
I have solved this problem. I had a miner XDD

**Comment by ryansolid** [comment]
Ok yeah I'm travelling on the road, and was getting in from my hotel room so I had nothing. Glad it's solved.

**Comment by solisadeqi** [comment]
This resolved the issue: NODE_TLS_REJECT_UNAUTHORIZED=0 npx degit solidjs/templates/js ui
