### ISSUE TITLE
Unnecessary rerenders

### ISSUE THREAD

**Issue by darklight9811** [solidjs/solid#1056]
### Describe the bug

I don't know if I should report to the stitches team, but since this only happens on Solid I decided to report here. 

### Your Example Website or App

https://stackblitz.com/edit/vitejs-vite-qegjgn?file=src/App.tsx

### Steps to Reproduce the Bug or Issue

1. Create a component that uses a css utility from stitches (see example)
2. Nest two of those component and put a For component inside
3. Console log the render call of the For component

Tried to wrap props of the Box component inside a memo, to wrap the utility call of the stitches method on a memo and to wrap the children into the children utility method and memo. Nothing worked.

### Expected behavior

The render callback of the For component to only be called once.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/20667774/173273301-962e2779-bc43-4ad2-88ff-9e383a6586d3.png)
PS: Animation, Flex and Title are components using css utility on the class prop

### Platform

- OS: linux
- Browser: firefox
- Version: 1.4.2

**Comment by otonashixav** [comment]
The `css` function destructures props (https://github.com/stitchesjs/stitches/blob/canary/packages/core/src/features/css.js#L158). This means you probably shouldn't pass anything but the `css` prop in to apply styling i.e.
```ts
  const className = createMemo(() => wrapper({ css: props.css }));
```
Any other prop passed in will be accessed when destructuring and cause the memo to rerun when it changes.

**Comment by darklight9811** [comment]
@otonashixav this worked

``` jsx
export default function Flex ({children, ...props}) {
  return (
    <div class={wrapper(props)}>
      {children}
    </div>
  )
}
```

But any way of fixing this solid side? Because I can think of several agnostic libs that would break integration and scare solid newcomers. Since solid is starting to grow fast, resolving any issue of people coming to solid with their other tools might help make them stay. Since this is a hard to understand bug too.

**Comment by otonashixav** [comment]
Doing that will break reactivity (https://docs.solidjs.com/reference/tracking#destructuring-props). If you aren't using the prop passthrough behaviour of stitches then there's no need to pass all the props, only the `css` prop. I don't think many agnostic libraries handle props themselves.

**Comment by Brendan-csel** [comment]
Doing this works too.
```
function Box(props: any) {
  const [local, other] = splitProps(props, ["children"]);
  const className = createMemo(() => wrapper(other));
...
```

**Comment by darklight9811** [comment]
@Brendan-csel is splitting faster than prop destructuring?

@otonashixav sadly there are variants too (for example disabled prop turning into a specific style inside the css utility method), so I can't pass only the css prop.

**Comment by Brendan-csel** [comment]
Splitting keeps the properties of `other` reactive - which you loose if you destructure (as mentioned by @otonashixav).

**Comment by ryansolid** [comment]
> @Brendan-csel is splitting faster than prop destructuring?

It's not, but it's not broken. Prop destructuring will break things. Like immediate children are no longer reactive in your example.

**Comment by otonashixav** [comment]
I didn't know about variant props -- you should pass all the relevant props, not just `css`, to the wrapper. If using `splitProps` you should make sure to pick out (or omit) the unrelated props, otherwise the wrapper will rerun unnecessarily when an unrelated prop changes.

**Comment by darklight9811** [comment]
@otonashixav @Brendan-csel sent an issue to the stitches team, will close it here since there is nothing solid can do I think. But thanks for the support.

**Comment by darklight9811** [comment]
@otonashixav @Brendan-csel what should I do in case I need to access a reactive variable inside the style? For example a variant with children or onClick.

**Comment by otonashixav** [comment]
I don't know enough about how stitches works to say. My first instinct is to check `"children" in props` instead, but depending on what you want (`props.children !== undefined`?) that might not work.
