### ISSUE TITLE
JSX compilation optimizing multiple reactive values causes inconsistent behaviour

### ISSUE THREAD

**Issue by otonashixav** [solidjs/solid#1061]
### Describe the bug

JSX is compiled. When one (possibly) reactive value is read in the JSX, it is compiled to one effect with a simple set operation e.g. for the reproduction linked below:
```ts
effect(() => _el$.value = text().value);
```

However, when more than one reactive value is read in the JSX, it is compiled to one effect which checks each reactive value for equality with its previous value before setting it:
```ts
effect(_p$ => {
      const _v$ = text().value,
            _v$2 = signal();

      _v$ !== _p$._v$ && (_el$.value = _p$._v$ = _v$);
      _v$2 !== _p$._v$2 && setAttribute(_el$, "if-i-am-uncommented-reset-stops-working", _p$._v$2 = _v$2);
      return _p$;
    }, {
      _v$: undefined,
      _v$2: undefined
    });
```

If the previous and current values are identical, the value is set in the single value case, but not set in the multiple value case. 

### Your Example Website or App

https://playground.solidjs.com/?hash=-1319904713&version=1.4.1

### Steps to Reproduce the Bug or Issue

1. Edit the text
2. Click `Reset`
3. The text resets to "Edit Me"
4. Uncomment `// if-i-am-uncommented-reset-stops-working={signal()}`
5. Edit the text
6. Click `Reset`
7. The text does not reset

### Expected behavior

The outcome should not change when the comment is uncommented. 

I think this mostly affects cases where there is user input (e.g. `value`, `checked`), so maybe those could be special cased to always set the new value, as that would be intended in most cases. 

### Platform

- OS: Windows
- Browser: Firefox
- Version: 101.0.1

### Additional context

Discord help thread: https://discord.com/channels/722131463138705510/722349143024205824/987219176340996106

**Comment by ryansolid** [comment]
What do you suggest? Assuming we can't just remove the optimization in most cases, as sometimes rewriting the DOM has side effects. Things like "src" attributes.

This issue almost always has to do with input fields I think. Just an hour ago I made a change so that `value` is always individually wrapped. Not sure what else to do.

**Comment by otonashixav** [comment]
I think this mostly affects cases where there is user input (e.g. `value`, `checked`), so maybe those could be special cased to always set the new value.
