### ISSUE TITLE
Issue rendering with Fragment  <></>  ( out of order rendering / parse error )

### ISSUE THREAD

**Issue by LiQuidProQuo** [solidjs/solid#1071]
### Describe the bug

**WORLD**Hello .

Incorrect rendering order
https://playground.solidjs.com/?hash=-1334550019&version=1.4.1

```html
 <div>
       Hello <><b>{'WORLD'}</b></>.
 </div>
```

![image](https://user-images.githubusercontent.com/105608035/174931792-81a7fb01-53be-4ab4-b3ab-f5b15ce3c504.png)

-----

https://playground.solidjs.com/?hash=-1738191781&version=1.4.1

```html
<div>
   <div>
     <>{"WORLD"}</>
   </div>
</div>

```

```
/main.tsx: Property arguments[0] of CallExpression expected node to be of a type ["Expression","SpreadElement","JSXNamespacedName","ArgumentPlaceholder"] but instead got undefined
```

### Your Example Website or App

https://playground.solidjs.com/?hash=-1334550019&version=1.4.1

### Steps to Reproduce the Bug or Issue

see repro in playground.

### Expected behavior

content of fragment should render in order.

Hello **World**.

and should not cause errors.

**Comment by ryansolid** [comment]
I can fix this but curious why you are using fragments like this. Is there something you are trying to achieve?

**Comment by LiQuidProQuo** [comment]
it was discovered incidentally, when I (mis)used `<></>` to silence a type error

https://playground.solidjs.com/?hash=-1259118341&version=1.4.1

**Comment by ryansolid** [comment]
Ok yeah. I'm pretty sure the solution is to compile it away as if it doesn't exist. Of course I need to detect that case first but yeah sure.

**Comment by ryansolid** [comment]
Yeah this is taking too much time to figure out right now. I'm just going to throw with a more human readable error. Atleast for now.

**Comment by LiQuidProQuo** [comment]
I only tested it with a simple modified test under dom.spec and fragments , so I don't really know the wider implications.

```js
    path.get("children").forEach(child=>{
      if (child.isJSXFragment()) {
        const fragmentChildren = child.node.children
        child.replaceWithMultiple(fragmentChildren )
      }
    })
```

this will come before or after `filterChildren(path.get("children"))` 
https://github.com/ryansolid/dom-expressions/commit/74e757e881a13f44ab884f2ea75f50e959d4cf4d#diff-a9df2c51ba8fab92870f64f43f93a10e151c352b72ee4a1b6dfaa5eb97677750R618

----

https://astexplorer.net/#/gist/735c0d4397fe5b51f8dd8a45f6e6804e/e8bae2a3fff9e23d38da28bb5185e1e7dff6062e

**Comment by ryansolid** [comment]
Yeah I was playing with stuff like this but I was hitting edge cases. I think just saying no support makes the most sense right now.
