### ISSUE TITLE
data-hk attribute varies for lazy / async components

### ISSUE THREAD

**Issue by knpwrs** [solidjs/solid#1075]
### Describe the bug

`data-hk` (usually) contains the same values for SSR-rendered pages which do not contain lazy or async components when rendered with renderToStringAsync. On pages which contain lazy or async components the IDs can vary greatly, usually by growing in size on each page refresh.

### Your Example Website or App

https://github.com/knpwrs/solid-ssr

### Steps to Reproduce the Bug or Issue

1. Clone the example repo and run `npm run dev` (unfortunately this does not run in Stackblitz)
2. View the page source when viewing `/` in your browser and refresh the view source page a bunch of times. Notice that the `data-hk` attributes are usually the same (very rarely they change but not as often as with async components).
3. View the page source when viewing `/about` in your browser and refresh the view source page a bunch of times. This page contains an async component. Notice that `data-hk` changes on nearly every render. The ID usually grows on each render until it resets back to the first state.

### Expected behavior

I would expect `data-hk` to be stable across renders, though I don't actually know if this is a problem.

### Screenshots or Videos

`/`:

<img width="615" alt="image" src="https://user-images.githubusercontent.com/174864/175193906-4cbe11d6-337d-4e8c-be6a-7720e47100ea.png">

`/about`:

<img width="406" alt="image" src="https://user-images.githubusercontent.com/174864/175193981-d8bf8a4f-5922-4688-8836-9e821dbc4899.png">

<img width="548" alt="image" src="https://user-images.githubusercontent.com/174864/175194002-dd04d030-14d8-4ebd-a1dc-9715df7e3f5b.png">

<img width="635" alt="image" src="https://user-images.githubusercontent.com/174864/175194028-b045748c-314c-4cb4-99da-2d3934b58f07.png">

<img width="635" alt="image" src="https://user-images.githubusercontent.com/174864/175194054-1973b2c5-be3e-4b50-bc47-759e080e08be.png">

<img width="903" alt="image" src="https://user-images.githubusercontent.com/174864/175194078-b3ea332a-0c1c-442d-b9f6-d7a7389d373c.png">

<img width="1059" alt="image" src="https://user-images.githubusercontent.com/174864/175194105-a81d8f4b-6d37-47ae-9d11-0f0308a50f9d.png">

etc until:

<img width="598" alt="image" src="https://user-images.githubusercontent.com/174864/175194215-42d160b3-21df-421e-9156-7d724ea8ba62.png">

### Platform

- macOS 12.1
- Solid 1.4.4
- Node 18.2.0
- Vite 2.9.12
- Firefox 101.0

### Additional context

The speed of refrehsing doesn't appear to matter. I was taking my time taking each of those screenshots, pasting, and then refreshing, going back and forth between this issues tab and the dev server tab.

**Comment by ryansolid** [comment]
Interesting.. I wouldn't expect this to happen as it is hierarchal and picks up its ID from its parent and resumes as it lazy loads and so on. Is this possibly related to Vite dev mode I wonder?

**Comment by knpwrs** [comment]
It looks like it happens in the production build as well:

1. `npm run build`
2. `npm start`

What would be the best way to go about debugging this?

**Comment by ryansolid** [comment]
Ah I see the problem. Not that I expected it to manifest this way, but the dev console gave me a hint. Your app doesn't hydrate. It actually re-renders. And the reason for that is you render outside of the hydrate call. And actually server render it outside of the server render call. I guess it taps into a global that isn't being cleaned up and pushes the numbers larger.

I was able to fix your app by making 2 small changes to the entry files.

In entry.server.jsx
```js
const app = createApp({ url });
const renderPromise = renderToStringAsync(() => app);

// should be
const renderPromise = renderToStringAsync(() => createApp({ url }));
```

In entry.client.jsx
```js
hydrate(
  createApp(window.hydration),
  document.getElementById('root') as HTMLElement,
);

// should be
hydrate(
  () => createApp(window.hydration),
  document.getElementById('root') as HTMLElement,
);
```

Solid reads everything based on the reactive context. Its entry points take functions, so the work (rendering) is done in them not outside and passed in.

This should resolve your issue.

**Comment by knpwrs** [comment]
Awesome! That did the trick. The only thing I see happening now is that the server renders `<HomeTitle>Home</HomeTitle>` but then when the client hydrates it renders `<HomeTitle />`, so the title appears and then goes away. The element is in the dom but it has no text content. The CSS appears to be hydrating correctly and I don't see any errors in the console.

**Comment by ryansolid** [comment]
Yeah this seems to be an issue with solid-styled-components that showed up because a change in hydration made in 1.4. I need to make a change in solid-styled-components to make this work. Thanks for bringing this to my attention.

**Comment by ryansolid** [comment]
Ok solid-styled-components 0.28.2 should fix this. In addition you need to add `solid-styled-components` to your `noExternals`.

**Comment by knpwrs** [comment]
That fixed it, thank you!
