### ISSUE TITLE
Suspense components inside For loop are not being rendered correctly, when wrapped with SuspenseList.

### ISSUE THREAD

**Issue by minht11** [solidjs/solid#1082]
### Describe the bug

`Suspense` components inside `For` loop are not being rendered correctly, when wrapped with `SuspenseList`
```tsx
import { render } from "solid-js/web";
import {
  Suspense,
  SuspenseList,
  For,
  createResource,
  createSignal
} from "solid-js";
import * as styles from "./styles.module.css";

const createArray = () => Array.from({ length: 2 });

function getRandomInt(min, max) {
  return Math.random() * (max - min) + min;
}

const wait = (duration) => {
  return new Promise((resolve) =>
    setTimeout(() => resolve(duration), duration)
  );
};

const ListItem = (props) => {
  const [value] = createResource(() => wait(getRandomInt(100, 1000)));

  return <div class={styles.listItem}>{value()}</div>;
};

const ListItemSuspense = () => (
  <Suspense fallback={<div class={styles.listItem}>Loading</div>}>
    <ListItem />
  </Suspense>
);

const List = (props) => (
  <div class={styles.section}>
    <h4>{props.label || "Without delay"}</h4>
    <For each={props.items}>{(a) => <ListItemSuspense />}</For>
  </div>
);

const ListWithDelay = (props) => {
  const [items, setItems] = createSignal([]);

  setTimeout(() => {
    setItems(createArray());
  }, 1000);

  return <List items={items()} label={`With delay ${props.label || ""}`} />;
};

const App = () => {
  return (
    <div>
      <List items={createArray()} />
      <ListWithDelay />
      <SuspenseList revealOrder="together">
        <List items={createArray()} />
        <ListWithDelay label="(Not Working)" />
      </SuspenseList>
    </div>
  );
};

render(App, document.getElementById("app"));
  ```

### Your Example Website or App

https://codesandbox.io/s/solidjs-suspense-list-issue-m8c4u2?file=/index.js

### Steps to Reproduce the Bug or Issue

1. Go to reproduction link.
2. Observe that items inside `For` loop are not being rendered correctly, when wrapped with `SuspenseList`.

### Expected behavior

SuspenseList works correctly inside Suspense items inside `For` loop.

### Screenshots or Videos

https://user-images.githubusercontent.com/8914032/175792724-b5b55fc2-5ba3-4d62-a2b9-1107ae97b65f.mov

### Platform

- OS: macOS
- Browser: All
- Version: 1.4.4

**Comment by ryansolid** [comment]
I have a quick solution but it is imperfect. The problem being SuspenseList order matters, and we can't determine order outside of initial render. So this sort of conditionals and delays break things. In hindsight I probably should have put React's direct descendant stipulation on this. I may still in the future.
