### ISSUE TITLE
Support stores as-is for classList and style

### ISSUE THREAD

**Issue by fabiospampinato** [solidjs/solid#1083]
### Describe the bug

Stores don't seem to work as-is as values for classList or styles.

### Your Example Website or App

https://playground.solidjs.com/?hash=1362539358&version=1.4.1

### Steps to Reproduce the Bug or Issue

Click the link.

### Expected behavior

I'd expect the `disabled` class to be toggled back and forth on the button. I think that's desirable because this syntax is super clean.

### Platform

All.

**Comment by ryansolid** [comment]
Ok. Hmm that is unexpected since internally it just iterates and accesses properties. Thanks for reporting.

**Comment by ryansolid** [comment]
I see it now. It's because Solid's compiler doesn't think these could be reactive and doesn't wrap them so they never subscribe. Tricky exception to the heuristic.
