### ISSUE TITLE
Numbers in fragments cause an error

### ISSUE THREAD

**Issue by thetarnav** [solidjs/solid#1093]
### Describe the bug

After updating to `1.4.5` my app stopped rendering, and only this error was visible:

![image](https://user-images.githubusercontent.com/24491503/176895884-5a302ad5-e372-45ed-808b-46fd9fa0e6a1.png)

From what I gathered, putting a number value to a fragment of sorts has been causing it.

E.g.
```tsx
<div>{[123, "Hello"]}</div>
// or
<div>{[123]}</div>
// or
<div>{() => <>{4} is even!</>}</div>

// while this works:
<div>Count {count()}</div>
```

### Your Example Website or App

https://stackblitz.com/edit/vitejs-vite-b7ynk3?file=src%2Fmain.jsx

### Steps to Reproduce the Bug or Issue

1. Put a number value to a fragment (array) in JSX
2. Open the browser console to see the error

### Expected behavior

JSX accepts numbers, so should fragments.

### Platform

- OS: [e.g. Windows]
- Browser: [e.g. Chrome, Opera]

**Comment by LXSMNSYC** [comment]
This was the cause: https://github.com/ryansolid/dom-expressions/blob/main/packages/dom-expressions/src/client.js#L456

Must've been a typo. I think it was intended to be written as `item.toString()`

**Comment by ryansolid** [comment]
Yeah all me.. Sorry.. clearly need a test for this case. I was so happy streamlining this logic a little and thought the tests already covered it.
