### ISSUE TITLE
Uncaught TypeError: x is not a function for render from "solid-js/web" for static builds

### ISSUE THREAD

**Issue by justkash** [solidjs/solid#1094]
### Describe the bug
EDIT:
After playing around with the setup a little bit more, the problem seems to be isolated to the `Router` component.

With the following `index.tsx`, I am able run a dev build fine using the command `vite`. However, building for a static output using either the `vite build` or `vite serve` command produces the error `Uncaught TypeError: code is not a function` as shown below.
```ts
import type { Component } from "solid-js"
import { render, createComponent } from "solid-js/web"
import { Router, Routes, Route } from "solid-app-router"

const TestApp: Component = (props) => <div>app</div>;
const TestPrivacy: Component = (props) => <div>privacy</div>;
const TestTerms: Component = (props) => <div>terms</div>;

const RoutedApp: Component = (props) => (<Router>
  <Routes>
    <Route path="/" component={TestApp} />
    <Route path="/privacy" component={TestPrivacy} />
    <Route path="/terms" component={TestTerms} />
  </Routes>
</Router>)

render(RoutedApp, document.getElementById("root") as HTMLElement)
```
```
Uncaught TypeError: code is not a function
    render http://localhost:8080/assets/index.73295c27.js:425
    createRoot http://localhost:8080/assets/index.73295c27.js:97
    runUpdates http://localhost:8080/assets/index.73295c27.js:262
    createRoot http://localhost:8080/assets/index.73295c27.js:97
    render http://localhost:8080/assets/index.73295c27.js:423
    <anonymous> http://localhost:8080/assets/index.73295c27.js:582
[index.73295c27.js:425:53](http://localhost:8080/assets/index.73295c27.js)
    render http://localhost:8080/assets/index.73295c27.js:425
    createRoot http://localhost:8080/assets/index.73295c27.js:97
    runUpdates http://localhost:8080/assets/index.73295c27.js:262
    createRoot http://localhost:8080/assets/index.73295c27.js:97
    render http://localhost:8080/assets/index.73295c27.js:423
    <anonymous> http://localhost:8080/assets/index.73295c27.js:582
    InnerModuleEvaluation self-hosted:2325
    evaluation self-hosted:2286
```

This is the config file used for the project; I turned off minifying to be able to read the static output better.
```ts
// vite.config.js 
import { defineConfig } from 'vite';
import solidPlugin from 'vite-plugin-solid';

export default defineConfig({
  plugins: [solidPlugin()],
  build: {
    minify: false,
    minifyIdentifiers: false,
    minifySyntax: false,
  },
});
```

This first image shows the call to the render function with createComponent as the first argument; apparently the call to `createComponent` doesn't return a function.
<img width="1840" alt="Screen Shot 2022-07-01 at 9 37 54 PM" src="https://user-images.githubusercontent.com/1018534/176985245-9579e6fe-1037-441c-a657-a130e4e45527.png">

This second image shows the `render` function and shows the location of the error on line 425 where `code` is called as a function.
<img width="1840" alt="Screen Shot 2022-07-01 at 9 38 23 PM" src="https://user-images.githubusercontent.com/1018534/176985249-938000ed-44c8-4202-b312-5bc84152e064.png">
`

### Your Example Website or App

N/A

### Steps to Reproduce the Bug or Issue

1. Build using `vite`
2. Build using `vite build` or `vite serve`
3. Note that the page loads for the development build, but not for the static builds

### Expected behavior

I expected the static build to behave the same as the development (`vite` command) build.

### Platform

- OS: macOS
- Browser: Firefox, Chrome
- Version: 102.0 (Firefox)

**Comment by LXSMNSYC** [comment]
`render(<TestApp />, document.getElementById("root") as HTMLElement)`
should be
`render(() => <TestApp />, document.getElementById("root") as HTMLElement)`
or
`render(TestApp, document.getElementById("root") as HTMLElement)`

**Comment by justkash** [comment]
> `render(<TestApp />, document.getElementById("root") as HTMLElement)` should be `render(() => <TestApp />, document.getElementById("root") as HTMLElement)` or `render(TestApp, document.getElementById("root") as HTMLElement)`

You're right, my test setup was wrong; I have updated the `index.tsx` code snipet. But, the problem looks like it appears from the `Router` component now.

**Comment by justkash** [comment]
> `render(<TestApp />, document.getElementById("root") as HTMLElement)` should be `render(() => <TestApp />, document.getElementById("root") as HTMLElement)` or `render(TestApp, document.getElementById("root") as HTMLElement)`

You are right, the problem is due to how I was passing a component into the `component` prop to the `Route` component; the prop expects a function, so you cannot pass a component like `<ComponentName val="test" />`. Instead, you must either pass the name by itself (which is a function) or create a lambda function like `() => <ComponentName val="test" />`.

The problem with this is that the development build and the production build behaves differently; the development build allows for a component like this: `<Route path ="/" component={<TestComponent name="test" />}`. However, this fails for a static build to the `dist` folder.
