### ISSUE TITLE
Using `observable()` outside of a `createRoot()` or `render()` call doesn't behave as expected

### ISSUE THREAD

**Issue by jorroll** [solidjs/solid#1110]
### Describe the bug

When using `solid-js` primatives outside of solidjs (e.g. in React), attempting to use the [`observable()` function](https://github.com/solidjs/solid/blob/f9fe3e498d247fc84012602de644937420ef9a3c/packages/solid/src/reactive/observable.ts#L25) will warn that you are attempting to `createComputed()` outside of a `createRoot()` call or a `render()` call because of this line:
https://github.com/solidjs/solid/blob/f9fe3e498d247fc84012602de644937420ef9a3c/packages/solid/src/reactive/observable.ts#L34-L38

Is there any downside to fixing this warning with the following:

```diff
export function observable<T>(input: Accessor<T>) {
  const $$observable = getSymbol();
  return {
    subscribe(observer: ObservableObserver<T>) {
      if (!(observer instanceof Object) || observer == null) {
        throw new TypeError("Expected the observer to be an object.");
      }
      const handler = "next" in observer ? observer.next.bind(observer) : observer;
      let complete = false;

+      const dispose = createRoot((disposer) => {
+        createComputed(() => {
+          // Would we need the `complete` variable here? When the `disposer` is called
+          // will that clean up this Computed?
+          if (complete) return;
+          const v = input();
+          untrack(() => handler(v));
+        });
+
+        return disposer;
+      });

      return {
        unsubscribe() {
          complete = true;
+          dispose();
        }
      };
    },
    [$$observable]() {
      return this;
    }
  };
}
```

### Your Example Website or App

none

### Steps to Reproduce the Bug or Issue

This issue seems simple enough as to not need a reproduction. 

### Expected behavior

See the "describe this bug" section

### Platform

N/a

### Additional context

Would this change also eliminate the need for the `completed` variable?

**Comment by ryansolid** [comment]
Yeah we have no need for anything after the unsubscribe is called. Having separate root disposal is unnecessary for most things, but keeping the computed around is equally pointless.

I guess the other question is teardown the otherway. Like if the context that holds observable is released in a Solid app. Create Root prevents it from being disposed naturally. Whereas right now that computed is cleared if the parent scope is released. So tempted to register an `onCleanup` that disposes. But `onCleanup` outside of a root will complain too. So it's more like:

```diff
export function observable<T>(input: Accessor<T>) {
  const $$observable = getSymbol();
  return {
    subscribe(observer: ObservableObserver<T>) {
      if (!(observer instanceof Object) || observer == null) {
        throw new TypeError("Expected the observer to be an object.");
      }
      const handler = "next" in observer ? observer.next.bind(observer) : observer;
      let complete = false;

+      const dispose = createRoot((disposer) => {
+        createComputed(() => {
+          const v = input();
+          untrack(() => handler(v));
+        });
+
+        return disposer;
+      });

+    // if part of Solid tree, there is an owner so register cleanup
+    if(getOwner()) onCleanup(dispose);

      return {
        unsubscribe() {
+          dispose();
        }
      };
    },
    [$$observable]() {
      return this;
    }
  };
}
```

The only question is it worth doing this? Mostly in any context Solid Signals are driving an app I imagine there already would be a root. I guess the exception is something driven purely off signals. I guess subscriptions could happen at any time. I also wonder if this whole solution is inefficient and there should be a single computed driving all subscriptions. Let's not worry about that now and keep with above.

**Comment by ryansolid** [comment]
Yeah not really concerned with performance here. I did think the use case originally was to use RxJS in Solid so one could drive it starting with an expression. So as long as it has that one line I pointed out, it is probably worth doing. I was just not picturing having a Solid app without a root. Like I assumed there would be other effects/memos etc.
