### ISSUE TITLE
Uncaught Error after enabling scheduling

### ISSUE THREAD

**Issue by thetarnav** [solidjs/solid#1122]
### Describe the bug

I have tried enabling the scheduling in the solid implementation of the last UI benchmark: https://github.com/uhyo/ui-library-benchmark.

```ts
import { enableScheduling } from "solid-js"
enableScheduling()
```

But it broke the application — after I tried to type in the input, the console was spammed by this error:

![image](https://user-images.githubusercontent.com/24491503/179351897-3fb890aa-d3ac-4684-86ff-69bc9cc54f68.png)

I've recreated the breaking benchmark here: https://stackblitz.com/edit/vitejs-vite-srnwbb?file=src%2Findex.tsx

This demo seems to be working fine though after updating: https://codesandbox.io/s/scheduling-circles-w-slowdown-forked-99l9g7?file=/index.js

### Your Example Website or App

https://stackblitz.com/edit/vitejs-vite-srnwbb?file=src%2Findex.tsx

### Steps to Reproduce the Bug or Issue

1. Try typing in the input
2. Open the console to see errors

### Expected behavior

Calling `enableScheduling` shouldn't break the application.

### Platform

- OS: Windows
- Browser: Chrome, Opera
- Version: 1.4.7

**Comment by otonashixav** [comment]
Minimal reproduction: https://playground.solidjs.com/?hash=-2045179172&version=1.4.1

This should be more consistent than the one I posted on discord a few days ago, hopefully. 

1. Click button
2. Read console

---

* OS: Windows 10
* Browser: Edge, Chrome, Firefox

**Comment by ryansolid** [comment]
Yeah, I see it. It's mechanical. My mechanism for doing sub chains involves resetting the queue, and banking on the next write to do an independent update. But we also queue creation here; in this case, the queue isn't defined as it isn't in a write. Need to rethink the approach slightly.

**Comment by ryansolid** [comment]
I was just looking at this benchmark, to try to determine desired behavior and it is super buggy. Every implementation does different things and even React crashes on certain DOM operations. I'm having a hard time figuring out where the issues are. I fixed the error but it doesn't seem to be working. I will dig further but really broken set of tests.
