### ISSUE TITLE
createStore, createMutable  nesting top level array store loses reactivity

### ISSUE THREAD

**Issue by LiQuidProQuo** [solidjs/solid#1127]
### Describe the bug

in solid, a top level array store is defined like this 
```js
let [store,setStore] = createStore(['a','b','c'])
```

```js
// top level array
let [storeA,setStore] = createStore(['a','b','c'])
// assigned to another store property
let [storeB,setStoreB] = createStore({store:storeA})
// storeA is no longer reactive
```

## createStore
**fails**
https://playground.solidjs.com/?hash=1795155654&version=1.4.1

additionally there is a difference in how setStore set the  value (with setStoreB) 
when the prop  is derived from from a top level array store 
or from the nested prop of a store. ( see how identity changes ) 

**nested(works)**
https://playground.solidjs.com/?hash=1415722947&version=1.4.1

## createMutable
**fails**
https://playground.solidjs.com/?hash=-1759307730&version=1.4.1

**nested (works)**
https://playground.solidjs.com/?hash=209370556&version=1.4.1

### Your Example Website or App

*

### Steps to Reproduce the Bug or Issue

see repro

### Expected behavior

it is expected that top level array will retain reactivity when it is set as another store property.

similarly to how it is preserved when the array is not coming from a top-level array, but a nested property.

### Platform

playground

**Comment by ryansolid** [comment]
Oh that's tricky. It's because top-level needs completely different processing rules and if overwritten I guess it modifies the original array. Will need to think about this one.

**Comment by ryansolid** [comment]
I don't actually isn't a bug now that I've looked. Or rather there is little to be done.

The spreading losing reference to A is expected. Store setting arrays is a replacement operation so spreading like that creates a new array which is no longer the reference to the original.

This doesn't pass the heuristic so it doesn't track
```js
<div>{storeA}</div>
```
There is no reactive access in the expression so there is no updates. Whereas `store.nested` does. 

We aren't changing the heuristic as literally, everything would need to be tracked at that point. The message is as simple as it has ever been. Reactive access tracks.

**Comment by LiQuidProQuo** [comment]
interesting, that eluded me. 


the good thing is that all these cases are working in the 1.5.0 branch
```jsx
      <div>{(storeA[$TRACK],storeA)}</div>
      <div>{(storeA.map((v)=>v))}</div>
      <div>{([...storeA])}</div>
      <div>{storeA.toString()}</div>
```

this case, caught me by surprise, because it actually rendered the whole array, but didn't register a top level tracking

```html
<div>{storeA}</div>
```
https://playground.solidjs.com/?hash=-727633904&version=1.5.0-beta.2

**Comment by ryansolid** [comment]
Also it's just
```js
<div>{storeA[$TRACK]}</div>
```
TRACK returns the object now
