### ISSUE TITLE
Effects that dispose their owner can continue to fire

### ISSUE THREAD

**Issue by Bubz43** [solidjs/solid#1151]
### Describe the bug

An effect which calls dispose of its owning root will continue to fire if `onCleanup` in the same root accesses something reactive. 

### Your Example Website or App

https://playground.solidjs.com/?hash=-963043878&version=1.4.1

### Steps to Reproduce the Bug or Issue

1. Click the button once.
2. Click the button again and look at the console, previous effects which should be dispose will still fire.
3. Continue clicking and the effects will keep stacking up.

### Expected behavior

I would expect what I do in the `onCleanup` function not to affect disposal. 

### Platform

- OS: Linux
- Browser: Vivaldi/Firefox

### Additional context

The problem can be avoided by untracking in the cleanup, or delaying the disposal in the effect through something like `queueMicrotask`.

**Comment by ryansolid** [comment]
Oh interesting. I guess we aren't untracking `onCleanup` we should.

**Comment by LiQuidProQuo** [comment]
the cleanup callback has the same owner as the effect the `dispose()` was called from 
![image](https://user-images.githubusercontent.com/105608035/183552575-031e2974-2440-4109-9a9f-fbb46e67dad1.png)

untracked cleanup, works for that use case
https://playground.solidjs.com/?hash=-371961240&version=1.4.1

or calling dispose not in the effect.
https://playground.solidjs.com/?hash=-1477293559&version=1.4.1
