### ISSUE TITLE
classList not working when use splitProps for class

### ISSUE THREAD

**Issue by diontools** [solidjs/solid#1161]
### Describe the bug

The following code will not work for classList passed to props.

```tsx
const [local, other] = splitProps(props, ['class'])
return <div {...other} class={`${local.class} other-class`} />
```

### Your Example Website or App

https://playground.solidjs.com/?version=1.4.1#NobwRAdghgtgpmAXGGUCWEwBowBcCeADgsrgM4Ae2YZA9gK4BOAxiWGjIbY7gAQi9GcCABM4jXgF9eAM0a0YvADo1aAGzQiAtACsyAegDucAEYqlEDlx79eZQhtwAFeYTJTZ8xQHI6G7XreFhbMtBBkfBH4anC8ALy8IrTM9PAQuAB0zEJQuHAAojFpuAAUvgQx3gCUFlExGRgQ4gASACoAsgAy8bwABha8vBlCIvwDg7yhatyIgnAiANzjkuMZJuqjIOODMmG4WsZoAOYAFriz62qLyxb9osmpwpkncFAiGVCExKIAwidoVxKdTgNQgFhk9AgzFwaDCvB+Ci4TXSAEYSoRXGRZlAIPgqmMIINQuE+MBpswoGosLxaLgXowALo9eyOFy0NzozHU4DeZhqKBkMjeBmgwbjIS4JiEgA8IjQADd+BllbT6dI+QKyHEQL0ACQgcmUrL8wXSVXiLQawW9SQAPhGvDyFHOvAAcrTeAB1bgAawwR3hJrInTQEWl+jl8ttFhWYIgEKhMLhCM4YSeACZOeysbwcXiCUSwhFeGTkpTqebGcyHGhnJis25uSLxuK4JLGDLI0qVXTxHaHU6XQB5ADS4cj0YgsfBkOhsMJKaRTwAzA2c3n8VtCZMi6TDVSab2qwkWbW2RyMdnubygyGIsLRcptxKpbxZQruxlK+rb6HcNr92NTU71wft5kdOBnVmUdxwVSdpwgIRRHEEoSnxOJJ0GaVMImaVFzTVFJiDOJvEuERvCI4C-21ARvBGbxZlwRh6FiSRpH0HCsPw5FcHTSjBRIsiKKtYNqJAWj6MY5jWPYzi324ld+K1UiNmE38Iho3g6PmBjHWkqRZPGcNbSwcYkhSYoMiONtCjgYoACF8AASREEoVE+QgVCqABCCxQTASQGSAA

### Steps to Reproduce the Bug or Issue

None

### Expected behavior

classList will works

### Platform

- OS: Windows
- Browser: Chrome, Firefox
- Version: Windows10, Chrome104, Firefox103

**Comment by lxsmnsyc** [comment]
`class` overrides `classList` and vice versa, it depends on the order they have been assigned. In this case, it works as expected since `class` is assigned after `classList`

**Comment by ryansolid** [comment]
Relevant issue: https://github.com/solidjs/solid/issues/751

**Comment by diontools** [comment]
Thank you for your response.
The code below seems to work well, but should I stop using `class` and `classList` at the same time?

```tsx
const [local, other] = splitProps(props, ['class', 'classList'])
return <div {...other} class={`${local.class} other-class`} classList={local.classList} />
```

**Comment by ryansolid** [comment]
Just be aware they can overwrite each other and last one wins. `classList` as I said is a bit unfortunate for this reason. I think that if you have multiple things that are dynamic I'd lean towards merging them yourself to get predictable behavior.

Like maybe this:
```js
const [local, other] = splitProps(props, ['class', 'classList'])
return <div {...other} class="other-class" classList={{...local.classList, [local.class]: true}} />
```

**Comment by diontools** [comment]
I'm sorry. I found this issue in [the document](https://www.solidjs.com/docs/latest/api#classlist) of  the English version. (I was reading the Japanese version.)
I will merge `class` into `classList` as you suggested.
Thank you very much.
