### ISSUE TITLE
Extract values from props directly will keep it in initial state

### ISSUE THREAD

**Issue by hUwUtao** [solidjs/solid#1163]
### Describe the bug

When I click the button, both `<ExtractValuesFromProps />` and `<KeepPropsAsAValue />` should render its children with parent "signal" but `ExtractValuesFromProps` children prop won't change

### Your Example Website or App

https://playground.solidjs.com/?version=1.4.1#NobwRAdghgtgpmAXGGUCWEwBowBcCeADgsrgM4Ae2YZA9gK4BOAxiWGjIbY7gAQi9GcCABM4jXgF9eAM0a0YvADo1aAGzQiAtACsyAegDucAEYqA3EogcuPfr2ZCouOAGU0Ac2hqsvAApQQhC4fvKEZFKy8ooqdBraehZWVjL0EMy4aLQQvACiFLiMUBkAalBq9HBkAGLRobThABQCzAAWaGoiQVKI-oHCIWFkAJT8VryCcLhMOQA8AHwgbR1dwpKz+vPmvPr6Du2d3YbZAOR8bVAQHnBWkskQqemZ2bwA0nBwhPXhAIJkP2UKnBGoQhr0AkFBg0RmMcpNpow5otQdCAHTLQ5rDZbW73R4ZLI5ADCDGC4kaoxA4wc2TIfGAzFJuF8ZCmJLSuAAurwALwOJwudxecqNAAMw0scMZEDpvAwjjg8GCvN4FN5814rNw7OCjUZHLVAGpeABGCX3CZCBE5RrUiazEz0XC4F4EYg8lSO53ZFS8bJEjTMADWPJA8qEStwknmdomvFm+UKxVwgMqNTqQ0W+t1w3W+kTRVK5TTtQU3zIGodEk2sft70+5b+AOLcCzTIpefrXyGTdTrdr8ZM1ZjcLj-GzuA7sY2XpdEBHE3NEDuECsQTEjEaap5lZ1LmHvhEtGY9EjqOuuFyakVAwAQvgAJIiW1gKCEQgqYYAQiXYEknKAA

### Steps to Reproduce the Bug or Issue

sample ^

### Expected behavior

3 number should increase when I click the button
exact behavior (with react) on stackblitz [on Stackblitz](https://stackblitz.com/edit/react-playground-practice-fxd2d1?file=index.js,index.html)

### Platform

- OS: Both Windows and Linux
- Browser: Edge
- Version: 104.0.1293.47

**Comment by SoonIter** [comment]
```jsx
function ExtractValuesFromProps(props: ParentProps) {
  return <>{props.children}</>; 
}
```
Don`t split your props too early.It`ll destruct the reactivity.

**Comment by SoonIter** [comment]
```jsx
function ExtractValuesFromProps(props: ParentProps) {
  const getChildren = () => props.children
  const _children = children(() => props.children);
  return <>{getChildren()} {_children()} {props.children}</>; 
}
```
Only to get access to reactive value in the "View" part is a good way.

**Comment by ryansolid** [comment]
This is well-documented and expected behavior. Components in React re-render where in Solid they do not. So one cannot expect identical behavior.

For an explanation read: https://www.solidjs.com/guides/faq#why-do-i-lose-reactivity-when-i-destructure-props
Also worth reading the Reactivity Getting Started section: https://www.solidjs.com/guides/reactivity#considerations
