### ISSUE TITLE
SolidJs JSX types are incorrect when running TypeScript to `nodenext` or `node16` module resolution

### ISSUE THREAD

**Issue by leebeydoun** [solidjs/solid#1168]
### Describe the bug

TypeScript version 4.7 allows users to specify module resolution as `nodenext` or `node16`. When specified module resolution will use `node`'s ESM resolution. Enabling this flag in a Solid Js project will result in type errors being report:
![image](https://user-images.githubusercontent.com/56801187/184976600-5ee9b3a7-87c8-4b4e-9cee-4505913a524b.png)

### Your Example Website or App

https://github.com/leebeydoun/solid-js-node16-error-repo

### Steps to Reproduce the Bug or Issue

1. Create start solid template: `npx degit solidjs/templates/ts my-app`
2. Update `moduleResolution` field in `tsconfig` to be `nodenext` or `node16`
3. Install dependencies
4. View any `.tsx` file, and you will see type errors

### Expected behavior

No type errors, should just work.

### Platform

- OS: MacOs
- TypeScript version ^4.7.4

**Comment by milesj** [comment]
To fix this, each of these `exports` conditions w(https://github.com/solidjs/solid/blob/main/packages/solid/package.json#L41) will need a `"types": "..."` entry.

**Comment by ryansolid** [comment]
There were changes made to address this in the upcoming Solid 1.5. I don't know if they succeeded. But you might want to try Solid `1.5.0-beta.4` and see if this resolves the issue.

**Comment by leebeydoun** [comment]
Tested on `1.5.0-beta.4`, same issue sadly.

Not certain if this is the issue, but as far as I can tell, the `solid-js` `package.json` doesn't specify an export for `solid-js/jsx-runtime`. Also in `jsx-runtime.d.ts` it should be:

```ts
export * from './types/jsx.js` // note the extension.
```
The other `*.d.ts` files have extensions on their imports in the `solid-js` package downloaded from `npm`.

**Comment by ryansolid** [comment]
I did make updates in 1.5.0-beta.5. Hopefully that helps.

**Comment by leebeydoun** [comment]
Just tested it out. The types appear to be working correctly and everything looks good. Thanks for fixing.

**Comment by jon301** [comment]
@leebeydoun I've cloned your repo (https://github.com/leebeydoun/solid-js-node16-error-repo) and updated to `1.5.0-beta.5` but I still get some errors

![CleanShot 2022-08-24 at 11 31 23@2x](https://user-images.githubusercontent.com/122108/186384078-6f1111a6-fd77-4af4-8f0f-5dd5c14315ba.png)

**Comment by leebeydoun** [comment]
Apologies, bit of an oversight on my part. The repo doesn’t include type module in the package json. If you add it the errors will go away in beta-5 but are present in beta-4

**Comment by ryansolid** [comment]
11.5 is released now.
