### ISSUE TITLE
Solid class name encoding breaks support for UnoCSS

### ISSUE THREAD

**Issue by zaydek** [solidjs/solid#1169]
### Describe the bug

I was experimenting with Solid and UnoCSS when I noticed that I couldn’t use arbitrary selector syntax e.g. `[selector]:[property:value]`. Specifically, when using the `&` as a selector, it appears Solid’s class names are encoded (by Babel I assume) which breaks support for tools like UnoCSS that rely on scanning class names. Note that this doesn’t happen with Tailwind -- I assume Tailwind uses a different technique to scan class names.

- Here is the original issue from UnoCSS https://github.com/unocss/unocss/issues/1431
- Here is a repro that demonstrates the breaking use case https://github.com/zaydek/solid-unocss-arbitrary-variant-bug

I’m not sure if this is something that should be fixed by Solid (how Babel encodes class names?) or if UnoCSS should be able to decode HTML entities in class names.

--

This is the original issue inlined:

> Hi, thank you for your work on UnoCSS. I am working with Solid and I am trying to use UnoCSS’s arbitrary selector feature which works in the playground.
> 
> Given the following code:
> 
> ```tsx
> function App() {
>   return <>
>     <div class="[color:red]">Hello, world!</div>
>     <div class="[&>*]:[color:red]">
>       <div>Hello, world!</div>
>       <div>Hello, world!</div>
>       <div>Hello, world!</div>
>       <div>Hello, world!</div>
>     </div>
>   </>
> }
> ```
> 
> I expected all lines to be red but I’m only seeing the first line render as red.
> 
> Here’s a MVP repro: https://github.com/zaydek/solid-unocss-arbitrary-variant-bug.
> 
> Here is the playground version using the same code and config (I originally copied the config from the playground): https://uno.antfu.me/play/?html=DwEwlgbgBAxgNgQwM5ILwCIDaMD2ccBOAXAQKYgC66AfABKlz4A0UA7oXCAITAD04EagChQkWIhQZMAMmoAqCkWx5CJclWFQoowfUY4W7Apx79Im7QLoNmbDtz5WhWndf2H7ppy6t7bRk0dzETNBIA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAqrhJQL5xZQQhwDkAV1YBjOnX5IkGAB6RY6bAENBAG3iYc%2BIiWCkAFMlQ16jOgC44AbSrHaDZq30BKSqgC6Sds6RA&options=N4IgLgTghgdgzgMwPYQLYgFwKgGzgUwF8g.
> 
> Is there something I’m doing wrong? Thank you.

### Your Example Website or App

https://github.com/zaydek/solid-unocss-arbitrary-variant-bug

### Steps to Reproduce the Bug or Issue

1. Open https://github.com/zaydek/solid-unocss-arbitrary-variant-bug
2. Run `npx vite dev`
3. See that the first line is red but consecutive lines aren’t -- this demonstrates the `&` selector breaks, as @chris-zhu confirmed Solid source is encoded `&` as an HTML entity

### Expected behavior

I want to be able to use tools like UnoCSS. Currently, only Tailwind works when attempting to use arbitrary selector syntax.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by lxsmnsyc** [comment]
UnoCSS should probably run before Solid's transforms. We can't really fix it on Solid's side because of how HTML works, the template needs to be escaped properly.

**Comment by zaydek** [comment]
Thanks @lxsmnsyc. In that case I’ll politely tag @chris-zhu and @antfu.

**Comment by lxsmnsyc** [comment]
Have you tried `enforce: "pre"` on UnoCSS' Vite plugin or `enforce: "post"` on Solid's?

**Comment by zaydek** [comment]
@lxsmnsyc No I haven’t seen that option. I’ll definitely try that -- I do `enforce: "pre"` for `unocss({ ... })` and `enforce: "post"` on `solid({ ... })` in the Vite config yes?

**Comment by lxsmnsyc** [comment]
```js
{
  ...unoCSS(),
  enforce: 'pre'
}
```

**Comment by zaydek** [comment]
Thanks, I’ll check if that works and also follow Chris’s recommendation to try the official Vite Solid starter because he was suggesting it works there.

**Comment by zaydek** [comment]
@lxsmnsyc `{ enforce: "post" }` on Solid works but `{ enforce: "pre" }` on UnoCSS breaks something else, see screenshot.

<img width="1065" alt="Screen Shot 2022-08-20 at 7 11 22 AM" src="https://user-images.githubusercontent.com/58870766/185750468-1371be96-12a6-4332-8768-1769ee6d653e.png">

If I change the import to `uno.css` it's the same thing. Thank you for helping me fix this. Is there any reason not to use `{ enforce: "post" }` with Solid?

**Comment by zaydek** [comment]
OK I’m gonna close this issue. The following is working for me:

```tsx
import { defineConfig } from "vite"
import solid from "vite-plugin-solid"
import unocss from "unocss/vite"

export default defineConfig({
  plugins: [
    unocss(),
    solid({
      hot: false,
    }),
  ],
  server: {
    port: 3000,
  },
  build: {
    target: "esnext",
  },
})
```

Thank you for helping me debug @lxsmnsyc.

**Comment by lxsmnsyc** [comment]
I'm not sure why would you want to turn off HMR. If that works for you that's fine, but I don't see it being "solved".

**Comment by zaydek** [comment]
Oh sorry, that‘s unrelated. I’ll edit that. I just have issues with HMR for development so I turn it off. Thanks for the catch.
