### ISSUE TITLE
context doesn't work when children are being passed

### ISSUE THREAD

**Issue by OrJDev** [solidjs/solid#1172]
### Describe the bug

so this is my component:
![Screenshot_3](https://user-images.githubusercontent.com/91349014/186055505-504af78f-2a7f-4268-9cad-0ee2e7b17b7a.png)

passing an element as child to "SolidTrpc":
![Screenshot_6](https://user-images.githubusercontent.com/91349014/186054854-546590b6-19dd-4ff0-b078-db1a430ba017.png)
rendering:
![Screenshot_7](https://user-images.githubusercontent.com/91349014/186055044-c7bad8de-a76c-4385-96ea-52a820d0a6d5.png)

context doesn't work in the "Home" component and keys length == 0

passing element as prop:
![Screenshot_8](https://user-images.githubusercontent.com/91349014/186055149-01226161-bf56-4e02-9c96-148b7534fb8f.png)
rendering:
![Screenshot_2](https://user-images.githubusercontent.com/91349014/186054176-0ab5728c-e6a3-4995-a8f4-0cae97accdcc.png)

context does work in the "Home" component and keys length == 3 (as expected)

### Your Example Website or App

N/A

### Steps to Reproduce the Bug or Issue

N/A

### Expected behavior

using this src
![Screenshot_3](https://user-images.githubusercontent.com/91349014/186054342-ba7c42e8-3b9e-4786-82e1-b132faf0b907.png)

im expecting to see this:
![Screenshot_5](https://user-images.githubusercontent.com/91349014/186054530-07211aae-6f4c-48ec-a6ae-b22213e9cdfb.png)

but instead im seeing this:
![Screenshot_4](https://user-images.githubusercontent.com/91349014/186054443-4e5fc76a-7354-45b8-a1cb-ef2a598aa3ff.png)

### Platform

- OS: Windows
- Browser: Chrome
- Version: Browser Version 104.0.5112.82 (Official Build) (64-bit)

**Comment by lxsmnsyc** [comment]
We highly discourage prop destructuring, and that's the root cause of your issue, mainly in the SolidTrpc component.

The reason this happens is:
- accessing children props creates the node
- you are destructuring the props for children
- which means you are creating the node ahead without the context being mounted as a parent.
