### ISSUE TITLE
Hydration bug with children and spread props after updating to v1.5

### ISSUE THREAD

**Issue by mishimalisa** [solidjs/solid#1188]
### Describe the bug

It seems hydration is broken using this pattern:
```js
const [l, p] = splitProps(props, ["children"]);
<div {...p}>
  {l.children}
  <div></div>
</div>
```
Error:
`TypeError: Cannot read properties of null (reading 'nextSibling')`

### Your Example Website or App

https://stackblitz.com/edit/vitejs-vite-heeavs?file=src/App.tsx

### Steps to Reproduce the Bug or Issue

1. Run npm run dev
2. See console error
3. Notice that component is throwing an error that is being handled by `ErrorBoundary`

### Expected behavior

Component not throwing an error after hydration.
It should render the same way it came from the server.

### Platform

- OS: Linux
- Browser: Chrome
- Version: 104.0

**Comment by mishimalisa** [comment]
More reproductions of probably the same bug:

It duplicate classes after hydration (no error):
https://stackblitz.com/edit/vitejs-vite-tr1jqj?file=src/App.tsx

It loses reactivity after hydration (no error):
https://stackblitz.com/edit/vitejs-vite-apaj3a?file=src/App.tsx

**Comment by ryansolid** [comment]
Thanks. I will investigate. The cool thing in 1.5 is that the split props stuff shouldn't be necessary anymore.. You should be able to just spread now.

**Comment by ryansolid** [comment]
Yeah these seem to all be the same issue. Try 1.5.2 which should have the fix.
