### ISSUE TITLE
Dynamic throws error on hydration if it is shown on client but hidden on server

### ISSUE THREAD

**Issue by CalLavicka** [solidjs/solid#1190]
### Describe the bug

For most elements, if you hydrate them but they were never rendered on the server, they just do a client-side render. However, `Dynamic` just crashes if it tries to render during hydration but never server-rendered. This can happen with a `Show` component like so:
```javascript
<Show when={!isServer}>
  <Dynamic component="div">Test</Dynamic>
</Show>
```
`TypeError: Cannot read properties of undefined (reading 'cloneNode')`

Replacing that `Dynamic` with a simple div (or any other component/element) will cause it to work correctly.

### Your Example Website or App

https://stackblitz.com/edit/vitejs-vite-n2fxzw?file=src/App.tsx

### Steps to Reproduce the Bug or Issue

1. Run `turbo dev`
2. See that nothing renders, and there is an error in the console.
3. Go to `src/App.tsx`, delete the `Dynamic` from the `Show` component.
4. Observe that things correctly hydrate on the client ("Test1" is rendered)

### Expected behavior

`Dynamic` should act the same as any other html element when hydrating on the client, meaning it should do a client-side render if it wasn't rendered on the server. So, "Test2" should show up on the client.

### Platform

- OS: macOS
- Browser: Chrome
- Version: 104

### Additional context

Tested on both 1.5.1 and 1.4.2 of solid

**Comment by lxsmnsyc** [comment]
One of the core rules of SSR and Hydration is that the server render and the initial client render should be the same. In your case since the server render isn't the same with the client render, there's already a hydration mismatch.

The workaround here is, instead of using `isServer`, you need to use a boolean signal that toggles on mount.

**Comment by CalLavicka** [comment]
That's fair, and I've worked around this behavior in my project. However, I don't think crashing on a (seemingly valid) workflow is correct behavior, and it's inconsistent with how every other element behaves on this type of mismatch, which is why I think it should be fixed.

**Comment by ryansolid** [comment]
There are thousands of ways things can fail if they mismatch and no way to fix them all. Even in making this work it'd be until the next thing. In this case, we actually don't have the template it wants to find but it doesn't know that until it goes to clone it.

I can give a slightly less cryptic error maybe on missing templates in dev, but it wouldn't be Dynamic specific.

**Comment by CalLavicka** [comment]
Why not make every other element also throw an error then? There seems to be an intentional choice to allow this behavior for other things - a check which, if the element isn't in the registry during hydration, creates it. It's only `Dynamic` where this fails because it doesn't have a template. But, if this is always bad, I don't think it should work for other elements. At least I think throwing a warning in dev mode, even if the template exists, would be a good idea.

Right now I could see users relying on this behavior, then suddenly they swap a component out for `Dynamic` and everything breaks.

**Comment by lxsmnsyc** [comment]
Technically it already throws an error for other components as well, not just Dynamic.

**Comment by ryansolid** [comment]
Yeah the fact that it "works" for the others is incidental, like it doesn't end up on a code path where it is impacted here, but it could depending on how the element is used. I guess the suggestion is if hydrating and there is a template miss we should always throw, instead of creating from that point. Let's introduce a warning in Dev and see how that goes.
