### ISSUE TITLE
`textContent` fails on hydration if initial value is empty

### ISSUE THREAD

**Issue by CalLavicka** [solidjs/solid#1193]
### Describe the bug

When hydrating an element that uses `textContent` to set its text, an error is thrown if the initial value is an empty string (or any nullish value).  This seems to be because it is looking for a text node in the HTML that is sent to the client, but there is no initial text node that it can find. This doesn't happen if you just put the string contents as a child of the node.

`TypeError: Cannot set properties of null (setting 'data')`

### Your Example Website or App

https://stackblitz.com/edit/vitejs-vite-7rnkme?file=src/App.tsx

### Steps to Reproduce the Bug or Issue

1. Run `turbo dev`
2. Observe that an empty button appears on the screen, but it's text does not get changed after hydration, and an error is thrown in the console
3. In `App.tsx`, change the initial value of the signal to be non-empty
4. Observe that things now work correctly

### Expected behavior

An empty button should appear from SSR, but after hydration the mount effect should set the text "test" into the button.

### Platform

- OS:  macOS
- Browser: Chrome
- Version: 104

**Comment by ryansolid** [comment]
Hmm.. couple options here, but the simplest is to mirror the hydration and client update results by inserting an empty text node and updating the text on run. We may want to consider more involved code gen in the future but this is pretty minimal and should do the trick for now.

Thanks for reporting the issue. Will have a fix shortly.
