### ISSUE TITLE
Can't build SolidJS on Windows

### ISSUE THREAD

**Issue by lostpebble** [solidjs/solid#1209]
### Describe the bug

Hi,

I've been trying to build SolidJS today, but can't seem to get it to work.

Following the guidelines in CONTRIBUTING.md, I run `pnpm install` and it seems to finish- but it does have some peer dependency issues:

```
F:\dev\github\solid> pnpm install
Scope: all 6 workspace projects
 WARN  A pnpm-lock.yaml file exists. The current configuration prohibits to read or write a lockfile
Already up to date
Progress: resolved 379, reused 365, downloaded 0, added 0, done
 ERR_PNPM_PEER_DEP_ISSUES  Unmet peer dependencies

.
├─┬ jest-ts-webcompat-resolver 1.0.0
│ └── ✕ missing peer jest-resolve@"*"
└─┬ solid-jest 0.2.0
  └── ✕ missing peer babel-preset-solid@^1.0.0
Peer dependencies that should be installed:
  babel-preset-solid@^1.0.0  jest-resolve@"*"

packages/babel-preset-solid
└─┬ babel-plugin-jsx-dom-expressions 0.34.5
  ├── ✕ missing peer @babel/core@^7.0.0
  └─┬ @babel/plugin-syntax-jsx 7.18.6
    └── ✕ missing peer @babel/core@^7.0.0-0
Peer dependencies that should be installed:
  @babel/core@">=7.0.0 <8.0.0"

hint: If you want peer dependencies to be automatically installed, add "auto-install-peers=true" to an .npmrc file at the root of your project.
hint: If you don't want pnpm to fail on peer dependency issues, add "strict-peer-dependencies=false" to an .npmrc file at the root of your project.
```

After that I try and build the project with `pnpm run build`, but unfortunately that doesn't work:

```
F:\dev\github\solid> pnpm run build

> solid-js@1.0.0 build F:\dev\github\solid
> turbo run build

←[91m←[1;31;7m ERROR ←[0m←[31m error preparing engine: the given task has not been registered←[0m←[0m
←[41m←[30m ELIFECYCLE ←[39m←[49m ←[31mCommand failed with exit code 1.←[39m
```

Is there something I'm doing wrong? Or is the build maybe not compatible with Windows ?

### Your Example Website or App

https://github.com/solidjs/solid

### Steps to Reproduce the Bug or Issue

1. Clone the fresh repository
2. Run `pnpm install`
3. Run `pnpm run build`

### Expected behavior

It builds as expected.

### Platform

- OS: Windows
- Version: latest main branch

**Comment by Genuifx** [comment]
look like turborepo's issue

**Comment by lostpebble** [comment]
The error certainly comes from turborepo- but it could also be that something it requires to run is not setup properly on solid's side. "the given task has not been registered".

Upon running `pnpm install` inside WSL (linux) - everything installed without issue and there are no peer dependency issues- rather strange. Might be some other dependency build tools which are failing in Windows.

I've now managed to get it to work and build completely on WSL - so this is definitely a Windows issue it seems.

**Comment by Flower-F** [comment]
I tried it in my Windows system, but no errors found. I used the git bash as my terminal instead of the power shell.

**Comment by mikekidder** [comment]
> I tried it in my Windows system, but no errors found. I used the git bash as my terminal instead of the power shell.

FWIW - I can also build Solid source turborepo in Windows 10 (Powershell 7.2/5.2).  
May no longer be an issue?

node - 16.15.0
npm - 8.7.0
pnpm - 7.13.5

**Comment by ryansolid** [comment]
@lostpebble is this still an issue/blocking? Not really sure what to do with this one. Lacking other reports and realistically no one really looking into I'm tempted to close.

**Comment by orenelbaum** [comment]
I can also build on windows with powershell. I think that you should close this issue for now and if @lostpebble says he still can't build we can reopen it.

**Comment by aifrim** [comment]
Since WSL & WSL2 I haven't built anything directly in Windows.

This seems to be a Turbo Repo problem. Maybe related to this? https://github.com/vercel/turbo/issues/2291

**Comment by lostpebble** [comment]
I just tried to build on Windows again, and the issue seems to have been resolved. I used PowerShell I've always been using it, even with the original error).

So, thanks- I'll close this one.
