### ISSUE TITLE
<Dynamic> re-renders when reactive property change using spread syntax

### ISSUE THREAD

**Issue by weijarz** [solidjs/solid#1227]
### Describe the bug

<https://playground.solidjs.com/?hash=-487692270&version=1.4.1>

When property 'class' changes, the <Dynamic> will do a full re-redner.
Not only `class` attribute, but all attributes includes 'data-' attributes will cause a re-render.

```ts
import { ComponentProps, createSignal, JSX, onCleanup, onMount } from 'solid-js'
import { Dynamic, render } from 'solid-js/web'

function App() {
  let i = 0
  const [className, setClassName] = createSignal('')

  return (
    <>
      <DynamicComponent componentProps={{ class: className() }}>
        <MyView />
      </DynamicComponent>
      <button onclick={() => { setClassName('btn' + i++) }}>
        Change class name
      </button>
    </>
  )
}

type DynamicComponentProps = {
  componentProps: ComponentProps<'div'>
  children: JSX.Element
}

function DynamicComponent(props: DynamicComponentProps) {
  return (
    <Dynamic component='div' {...props.componentProps}>
      {props.children}
    </Dynamic>
  )
}

function MyView() {
  console.log('Create my view')
  return <h1>My view </h1>
}

render(() => <App />, document.getElementById("app")!);
```

### Your Example Website or App

https://playground.solidjs.com/?hash=-487692270&version=1.4.1

### Steps to Reproduce the Bug or Issue

When using spread syntax on <Dynamic>

### Expected behavior

It should not re-render like other components.

### Platform

- OS: Linux
- Browser: Chrome, Firefox

**Comment by ryansolid** [comment]
Fixed in 1.5.5
