### ISSUE TITLE
Something wrong with `classList`

### ISSUE THREAD

**Issue by iamcco** [solidjs/solid#1228]
### Describe the bug

code:
```
      <div
        class={`container`}
        classList={{
          title: true,
        }}
      >

```
In the page:

![image](https://user-images.githubusercontent.com/5492542/190299946-04b51261-361c-467b-8130-20bcce54ee21.png)

### Your Example Website or App

No

### Steps to Reproduce the Bug or Issue

See above

### Expected behavior

It should be add `title` to class.

### Platform

- OS: macOS
- Browser: Chrome
- Version: 104.0.5112.101

### Additional context

SolidJS version: 1.5.4

**Comment by mdynnl** [comment]
It's a bug at [`1.4.1`](https://playground.solidjs.com/?hash=538563761&version=1.4.1), already fixed at [`1.4.2`](https://playground.solidjs.com/?hash=1618105808&version=1.4.2) and still working at [`1.5.4`](https://playground.solidjs.com/?hash=1835011437&version=1.5.4). 
It's recommended that you use a repro using <https://playground.solidjs.com/> or online ide such as codesandbox, stackblitz, etc.
