### ISSUE TITLE
Optional chaining is mis-transformed when transforming JSX expressions

### ISSUE THREAD

**Issue by danieltroger** [solidjs/solid#1230]
### Describe the bug

`<div>{updating_accessor()}</div>` is transformed to `insert(_el$, updating_accessor);` but `<div>{updating_accessor?.()}</div>` is transformed to `insert(_el$, updating_accessor?.());`, leading to way much more being re-rendered than should be.

### Your Example Website or App

There's a typo here it says "Your bug will may get fixed much faster" it should say either "will" or "may". IMO the steps listed below are enough.

### Steps to Reproduce the Bug or Issue

1. Go to https://playground.solidjs.com/?hash=7820092&version=1.4.1
2. Check the console, you'll see "Counter rendered" being printed super often

Compare to https://playground.solidjs.com/?hash=-1700158092&version=1.4.1 where you can see the number still updating but the `Counter` function only being executed once

### Expected behavior

`<div>{updating_accessor?.()}</div>` being transformed to `insert(_el$, () => updating_accessor?.());`

### Platform

- OS: macOS
- Browser: Chrome and Firefox
- Version: 105 in both

**Comment by ryansolid** [comment]
I believe this is fixed in babel-plugin-jsx-dom-expressions 0.34.9. You will need to blowout your package lock. I will bump version in next Solid release.

**Comment by danieltroger** [comment]
Thank you for the quick fix!

Removing the entry from yarn.lock didn't work (I'm using yarn 3.2.2) it just installed babel-plugin-jsx-dom-expressions@0.33.14 again. Will update solid-js (am on 1.4.8) once I'm done with something for tight a deadline as I'm afraid of the breaking changes causing trouble when updating, and see if it works then. For now I just wrote `<div>{() => updating_accessor?.()}</div>` as a workaround.
