### ISSUE TITLE
Some weird bug while rendering elements

### ISSUE THREAD

**Issue by 0xHexE** [solidjs/solid#1234]
### Describe the bug

![image](https://user-images.githubusercontent.com/29942725/191054534-362f8d8e-2390-417b-9182-955fdee4b9f9.png)

### Your Example Website or App

https://stackblitz.com/edit/solid-vite-rimzwc?file=src/index.tsx

### Steps to Reproduce the Bug or Issue

Create one component and put another component inside it. It renders the first element which is the child then it renders the parent one. It should be inverse.

### Expected behavior

It should render A then B.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/29942725/191055039-4b5f1dd3-9876-4d6c-9e3c-d36ea56b07d0.png)

### Platform

- OS: Linux
- Browser: Firefox]
- Version: Latest 104

**Comment by lxsmnsyc** [comment]
You are destructuring, it prompts `children` to be constructed first. 

To explain:

```js
// Since props are a bunch of getters, and `children` is a getter,
// destructuring, or any form of synchronous access, will cause `children`
// to render first.
function A({ children }) {
  console.log('A');
  return <>{children}</>;
}

function B({ children }) {
  console.log('B');
  return <>{children}</>;
}

<A>
  <B>Hello world</B>
</A>
// compiled as
A({
  get children() {
    return B({ children: 'Hello world' })
  },
})
```

**Comment by 0xHexE** [comment]
Thanks, guys. It works when I remove the destructuring.
