### ISSUE TITLE
splitProps causing hydration error (input placeholder)

### ISSUE THREAD

**Issue by EthanStandel** [solidjs/solid#1244]
For this component

```tsx
const MyInput = (props) => {
  const [local, native] = splitProps(props, ["label"])

  return <label>
    <span>{local.label}</span>
    <input {...native} />
  </label>;
}
```

If I render it with a placeholder

```tsx
<MyInput placeholder="Hello" />
```

I get this on the ErrorBoundary (yes this is all there is to see)

![image](https://user-images.githubusercontent.com/16840301/188053217-0ceac925-737b-4967-802e-91bfcc500c88.png)

![image](https://user-images.githubusercontent.com/16840301/188053835-798befc3-9f28-4fd6-b04c-f17304d23a31.png)

The server render looks like it works fine and there's no errors in my dev console. Also it looks like this works fine in another SolidJS project I have so it's definitely a solid-start problem.

**Comment by ryansolid** [comment]
As far as I can tell this should be fixed in the latest. It was a compiler error addressed in babel-preset-solid 1.5.6 (babel-plugin-jsx-dom-expressions v0.34.10),

**Comment by ryansolid** [comment]
Had another person corroborate. Closing. Reopen if this issue still persists.

**Comment by EthanStandel** [comment]
Looks all good now, thaks @ryansolid !
