### ISSUE TITLE
Using transitions with suspense and @tanstack/solid-query breaks reactivity.

### ISSUE THREAD

**Issue by jeski-bright** [solidjs/solid#1249]
### Describe the bug

Using an asynchronous resource with a transition & suspense results in parts of the UI using the "new" state where others are stuck with the old one.

However, it gets even worse if you don't use the `isTransitioning` accessor from `useTransition`, in which case the suspended view never resolves.

### Your Example Website or App

https://stackblitz.com/edit/vitejs-vite-vzwfve?file=package-lock.json,src%2FApp.tsx,vite.config.ts

### Steps to Reproduce the Bug or Issue

Issue A:
1. Click on the 'Show' button and wait for the promise to resolve
2. See that the button still states `Show`, however it should display `Hide`

Issue B:
1. Comment out line 40: ` {isTransitioning() && 'Is transitioning'}`,
2. Click on the `Show`.

### Expected behavior

Issue A:
Button has text `Show` instead of `Hide`

Issue B:
The `Resolved` text is never visible on screen

### Platform

- OS: macOS
- Browser: Chrome
- Version: 1.5.6

### Additional context

This might be an issue in [`solid-query`](https://github.com/TanStack/query), however since this issue breaks the core reactivity, reporting it here.

**Comment by jeski-bright** [comment]
It seems I have found a workaround for `solid-query`, however I don't know what part was the culprit, probably some never-resolved promises (?).

**Comment by ryansolid** [comment]
Nothing so sinister. This was a code path that I've never hit. I wrote code to handle a situation but I hadn't actually hit it and was missing the step where queued effects in the Transition got moved back to the main effects queue. The way solid-query uses resources is a little but unusual so we hit this for the first time. I was able to streamline this and actually overall reduce code which is cool.

**Comment by jeski-bright** [comment]
That was quick :) Thanks!

However there's still something fishy going on when you replace 
```js
<div>{query.data? 'Message': 'never'}</div>
```
with
```js
<Show when={query.data}>Message</Show>
```
The transition still hangs.

Please see https://github.com/TanStack/query/pull/4224#discussion_r980687179

**Comment by ryansolid** [comment]
Oh I see interesting. Yeah still a timing issue. The Transition basically gets cancelled by the refetch before the change settles. And cancellation doesn't trigger the existing work. I think this could be fixed in the library by separating the refetch out of the batch. But I should still handle this better here.

**Comment by ryansolid** [comment]
Ok think I got it. That example at least seems to work.

**Comment by jeski-bright** [comment]
Yes indeed!

I've built solid locally & tested `solid-query` against https://github.com/solidjs/solid/commit/ea2c976add11b20798267c1fa218672189955ef6 and everything worked with the test case for transitions added (the version with `<Show when={query.data}...`) 🎉 

What bothers me a bit though is that now my workaround breaks this exact case, whereas `<div>{query.data? 'Message': 'never'}</div>` still works. I think there still might be some edge-case.

**Comment by ryansolid** [comment]
Hmm.. I'd love to understand this a bit more. But a bit involved to actually follow what scenario is broken. I did take this change through my Solid demos and it seems good. I'm gathering while this fixes a gap we had there probably is still a further gap. This Solid Query stuff is really outside of how we've used this in the past, but I did notice the over execution of the current implementation so I'd rather clean it up.

I think I'm going to release this, but if possible lets take a look deeper.

**Comment by jeski-bright** [comment]
Understood. I'll try to reproduce this with the most recent version & see if it still affects my app, though I will probably have time over the weekend. If I encounter anything I'll try to reduce it to some minimal example.

**Comment by jeski-bright** [comment]
Okay, I was able to create an example of the broken behaviour: https://stackblitz.com/edit/solidjs-templates-vyxwsu?file=src/App.tsx

When you navigate from the dashboard link to `Test 1` and then `Test 2` and so on, the page always renders `Test 1`, even though the `params.id` clearly changes, as is shown in the `createEffect`. Now if you wrap the output of the `Test` component in a `div`, it starts to work correctly.

I am also getting a ```computations created outside a `createRoot` or `render` will never be disposed``` warning on first navigation to the test component, regardless of the above mentioned wrapping, so this might be something with `solid-query`. I'll open an issue there if you confirm this isn't something in solid's core.

**Comment by ryansolid** [comment]
No it's a Solid bug related directly to the warning. Solid isn't resuming transition properly in that location.
