### ISSUE TITLE
Passing the `info` prop in a resource fetcher breaks type inference for `createResource<T>`

### ISSUE THREAD

**Issue by ivancuric** [solidjs/solid#1250]
### Describe the bug

Passing the `info` prop in a resource fetcher breaks type inference for `createResource<T>` and it's inferred as `Resource<unknown>`. Without it the type is correctly inferred to be  `Resource<number | undefined>`

### Your Example Website or App

https://stackblitz.com/edit/vitejs-vite-wku3ye?file=src%2FApp.tsx

**Comment by otonashixav** [comment]
This is a typescript issue, see https://github.com/microsoft/TypeScript/issues/49618.

**Comment by ryansolid** [comment]
Nothing to be done here and since a fix to TS in the linked bug would just fix this, no action we can take.
