### ISSUE TITLE
When I quickly click the button to increase to about 30, the page starts to get stuck

### ISSUE THREAD

**Issue by imaxing** [solidjs/solid#1267]
### Describe the bug

When I quickly click the button to increase to about 30, the page starts to get stuck

doc: https://www.solidjs.com/tutorial/introduction_memos

codesandbox: https://codesandbox.io/s/jm21mv?file=/src/main.tsx

### Your Example Website or App

https://codesandbox.io/s/jm21mv?file=/src/main.tsx

### Steps to Reproduce the Bug or Issue

1. quickly click the button to increase to about 30

### Expected behavior

The page will render normally when I click the button quickly

### Platform

- OS: macOS
- Browser: Chrome
- Version: 1.4.1

**Comment by zihan-ch** [comment]
The function that computed the numbers uses recursion. A large number of operations cause it to run extremely slow. This is not a bug of solid. The page runs slowly because for every single number that you can see on the screen, the browser needs to calculate it one time.

And did you notice the `solve` button under the page? This page is just about how to improve its performance. After you clicked the `solve` button, the problem disappeared because it has used the `createMemo` function. The `createMemo` function creates memory of the dependencies and the results and it does not need to calculate the number every time.

**Comment by zihan-ch** [comment]
If I use Chinese to explain it: 这个页面就是在告诉你在按那个`solve`的按钮前代码是有问题的，计算结果是一样的但是会被计算非常多次，因此就会导致它非常卡，而当按下`solve`时，它会帮你把代码改成使用`createMemo`的，然后每次进行计算时它会发现那个`count`没变，就不需要调用fibonacci重新计算（就是这个特别耗时间、性能），然后性能问题就解决了

**Comment by zihan-ch** [comment]
Actually the issue is what the page is teaching you😆

**Comment by ryansolid** [comment]
Thank you for the explanation.

If there are ways to improve the language for the tutorial to make it more clear don't hesitate to let us know/make a PR.

**Comment by imaxing** [comment]
> If I use Chinese to explain it: 这个页面就是在告诉你在按那个`solve`的按钮前代码是有问题的，计算结果是一样的但是会被计算非常多次，因此就会导致它非常卡，而当按下`solve`时，它会帮你把代码改成使用`createMemo`的，然后每次进行计算时它会发现那个`count`没变，就不需要调用fibonacci重新计算（就是这个特别耗时间、性能），然后性能问题就解决了

多谢大佬指点, 刚开始学习! 惭愧惭愧~~

**Comment by imaxing** [comment]
> The function that computed the numbers uses recursion. A large number of operations cause it to run extremely slow. This is not a bug of solid. The page runs slowly because for every single number that you can see on the screen, the browser needs to calculate it one time.
> 
> And did you notice the `solve` button under the page? This page is just about how to improve its performance. After you clicked the `solve` button, the problem disappeared because it has used the `createMemo` function. The `createMemo` function creates memory of the dependencies and the results and it does not need to calculate the number every time.

I try to click the solve button and then continue to click the count button. I find that the page still gets stuck

**Comment by zihan-ch** [comment]
大佬？我十三岁诶...

**Comment by zihan-ch** [comment]
> > If I use Chinese to explain it: 这个页面就是在告诉你在按那个`solve`的按钮前代码是有问题的，计算结果是一样的但是会被计算非常多次，因此就会导致它非常卡，而当按下`solve`时，它会帮你把代码改成使用`createMemo`的，然后每次进行计算时它会发现那个`count`没变，就不需要调用fibonacci重新计算（就是这个特别耗时间、性能），然后性能问题就解决了
> 
> 多谢大佬指点, 刚开始学习! 惭愧惭愧~~

大佬？我十三岁诶...
到三十七以上的确还是卡，毕竟算斐波纳切，电脑是有点累的。实际应用不会有问题的，这是电脑本身算力不行。不管怎样这也不是solid的问题吧...你不会没看懂这个教程的代码在叫你干嘛吧，难道你认为solid会帮你一起把计算的部分也给带上？

**Comment by imaxing** [comment]
> > > If I use Chinese to explain it: 这个页面就是在告诉你在按那个`solve`的按钮前代码是有问题的，计算结果是一样的但是会被计算非常多次，因此就会导致它非常卡，而当按下`solve`时，它会帮你把代码改成使用`createMemo`的，然后每次进行计算时它会发现那个`count`没变，就不需要调用fibonacci重新计算（就是这个特别耗时间、性能），然后性能问题就解决了
> > 
> > 
> > 多谢大佬指点, 刚开始学习! 惭愧惭愧~~
> 
> 大佬？我十三岁诶... 到三十七以上的确还是卡，毕竟算斐波纳切，电脑是有点累的。实际应用不会有问题的，这是电脑本身算力不行。不管怎样这也不是solid的问题吧...你不会没看懂这个教程的代码在叫你干嘛吧，难道你认为solid会帮你一起把计算的部分也给带上？

不要误会, 只是觉得你做了解释出于尊敬叫声大佬, 跟年龄无关哈.
usememo倒也不至于看不懂, 只是技术比较菜不明原理多了问一下
既然教程本身就是要表达这么个意思那是我自身的问题😹
