### ISSUE TITLE
Unwrapped values passed to event handlers under Index are only evaluated once

### ISSUE THREAD

**Issue by johndunderhill** [solidjs/solid#1268]
### Describe the bug

I have a simple list in Solid using an Index component with a signal that looks something like this:

```
<Index each={getAlerts()}>
  <p>{item().name}</p>
  <div onClick={[setAlertSeen, item().alertId]}>X</div>
</Index>
```

When I update the list, I build a completely new list and pass it to the signal (`setAlerts(newList)`).  It's an async inbound snapshot update--not much else I can do here.

This works, except...if I add three items to the list, and then remove the middle item, when I click the new second (formerly third) item, it passes the click handler the alertId for the removed item.

It seems `<Index>` is re-using DOM nodes, but doesn't update the data passed to the click handler (`item().alertId` in this case).

If I change to a `<For>`, the problem goes away, but then it re-renders the whole list, top to bottom, every time I change it (not unexpected; don't have a better solution at this point).

### Your Example Website or App

https://stackblitz.com/edit/solidjs-templates-5jyphq?file=src%2FApp.tsx

### Steps to Reproduce the Bug or Issue

1. Create an Index component to display a list from a signal that passes unique data from the item to a click handler.
2. Create a list with at least three items.
3. Remove one of the middle items by passing in a new list to the signal.
4. Click on the item which moved up in the list.
5. The click handler will receive the data for the removed item.

### Expected behavior

When the list is updated by Index, I would expect the parameter to the click handler to be updated, just like the visible text.

### Platform

- OS: Windows 10, up-to-date
- Browser: Chrome, up-to-date

**Comment by ryansolid** [comment]
This looks like you want `<For>` but need nested reactivity.  I'd recommend the first 2 lessons of the store section of the tutorial: https://www.solidjs.com/tutorial/stores_nested_reactivity

That being said you can also solve your issue by wrapping the expression in a function:
```js
<Index each={getAlerts()}>
  <p>{item().name}</p>
  <div onClick={[setAlertSeen, () => item().alertId]}>X</div>
</Index>
```
Right now it runs immediately and gets stored on the element. This will lazy evaluate. If you are curious why this doesn't autowrap, it is because the array can be passed in at runtime where we can't do static analysis.

All this said you probably should use `<For>`

**Comment by johndunderhill** [comment]
Thank you for your response.  In this scenario I get notified by the back end when new data is available, and handed a large data structure containing the new data (a snapshot).  I have to traverse that and build up a new array of objects to display (or something similar to get it onto the screen).

What is the best way handle this in Solid without (a) re-rendering everything, or (b) doing my own manual diffing?  Is there any solution?

I read the section in the tutorial, but this doesn't seem all that applicable.  I'm not concerned about user-initiated editing of a small portion of the tree here.  The data I'm displaying can't be edited in this view.  But there can be a lot of it, and it gets updated in real time by the back end.

If I created a store, as you suggest, what do I do with it?

**Comment by ryansolid** [comment]
Yeah Stores have a diffing tool. I've been waffling on the best API to give people for this for the past couple of years. But it's doable. The latest approach is something that we've been doing in Solid 1.5. My hope was that it could get incorporated into data-fetching libraries but you can wire it yourself. Something like this (this is something I just handwrot code, I didn't test this).

```ts
import type { Signal } from "solid-js"
import { createStore, reconcile } from "solid-js/store";
import type { ReconcileOptions } from "solid-js/store";

function createDeepSignal<T>(value: T, options: ReconcileOptions): Signal<T> {
  const [store, setStore] = createStore({
    value
  });
  return [
    () => store.value,
    (v: T) => {
      const unwrapped = unwrap(store.value);
      typeof v === "function" && (v = v(unwrapped));
      setStore("value", reconcile(v));
      return store.value;
    }
  ] as Signal<T>;
}

function createResourceStore(fetcher, options) {
  return createResource(fetcher, {
    storage: (init) => createDeepSignal(init, options.reconcileOptions),
    ...options
  });
}
```

The `reconcile` helper is the key here.. But default it uses `id` as the key. But you can set it custom via options. https://www.solidjs.com/docs/latest/api#reconcile

I know this is something that we need to probably smooth over still it's difficult to make the decisions for everyone so I've been going piece by piece to get there.

**Comment by johndunderhill** [comment]
Thank you, Ryan.  I agree it's hard to design something to handle every case.  You've done a great job with the API so far.  Just looking for patturns I can replicate.  I will look more closely at `reconcile`.  Appreciate all you do.
