### ISSUE TITLE
Setting style property to undefined should unset the style

### ISSUE THREAD

**Issue by timothyallan** [solidjs/solid#1299]
### Describe the bug

Setting a style property to undefined keeps the old style. 

Discussion here: https://discord.com/channels/722131463138705510/1032794840016097360

### Your Example Website or App

https://playground.solidjs.com/?hash=1124045020&version=1.4.1

### Steps to Reproduce the Bug or Issue

Click the button in the playground, the style still remains even though it's been set to undefined. Inspecting the element shows that the red color is still present.

### Expected behavior

The style should be 'unset' to an empty value.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by ryansolid** [comment]
I see.. `el.style.setProperty("background-color", undefined)` is a no-op. I'm used to doing empty strings for a lot of this stuff.. but that's because these things take strings. I don't think others think that way so this is probably worth adding a small helper to handle falsy values. Thanks for reporting.

**Comment by liuyike98** [comment]
> 明白了。。 是无操作。我习惯于为很多这些东西做空字符串。但那是因为这些东西需要字符串。我不认为其他人会这样想，所以这可能值得添加一个小助手来处理虚假值。感谢您的举报。`el.style.setProperty("background-color", undefined)`

aha, i need it

**Comment by ryansolid** [comment]
Fixed. Thanks @sirenkovladd. 

In the future might move this into a helper as it generates a decent amount of code. But I can't do that outside of a minor as it would need to match on both sides.
