### ISSUE TITLE
Creating a store from another breaks read-write segregation

### ISSUE THREAD

**Issue by thetarnav** [solidjs/solid#1300]
### Describe the bug

You can easily create a store from a "read-only" proxy returned by another, gaining write access to the state and causing reactive updates to the original store.
Stores will already mutate the original object, so you must be aware of passing existing references to stores. This is why it is not that big of a deal.
But the fact that there is no warning message when doing this is a bit worrying, as you might have to do the idea that a given object is used in other stores already. It almost feels like this is an intended feature, as it works incredibly well.

```ts
const [original, setOriginal] = createStore({ count: 0 });
const [hijacked, setHijacked] = createStore(original);
setHijacked("count", p => ++p) // works
```

on the other hand, creating a mutable out of an existing store is not working 🎉

### Your Example Website or App

https://playground.solidjs.com/?hash=-1354398022&version=1.6.0

### Steps to Reproduce the Bug or Issue

When you click on the button, the updates made to the new store are reflected in the original.
Also there is no warning in the console when doing it: https://codesandbox.io/s/wlx4wh?file=/src/main.tsx

### Expected behavior

There should at least be a warning in the console

### Platform

- OS: Windows
- Browser: Opera
- Version: 91.0.4516.67

**Comment by ryansolid** [comment]
Yeah this intended and would be prohibitive to do a different way. And Im not sure we could warn because any set of the proxy with part of itself would have the same characteristics. Like moving items in array. When you consider depth too I think trying to communicate this would be near impossible.

Mutables not working is interesting and probably requires more consideration.

**Comment by thetarnav** [comment]
It is still scary that this is possible ...but only because I know about it. In practice, a scenario where this would cause a bug in app logic seems extremely rare.
I don't want this to be prevented really, since it would have performance implications.
But if only in dev, store nodes had a—unique to the store—symbol property, that would be cleared if the node gets deeply removed from the store. Every time a node is added, the store symbols could be compared, and a warning logged.
Not sure if there is a way to tell when a node gets removed from a store, and not just moved from one place to another ...or if this is even worth it.

> Mutables not working is interesting and probably requires more consideration.

When I said that mutables are not working, I meant that `createStore` and `createMutable` don't affect each other. Two mutables will have the same behavior as the stores.
https://playground.solidjs.com/?hash=469751698&version=1.6.0

**Comment by ryansolid** [comment]
Yeah I don't think it makes sense to even try to restrict this. Like it is what it is. Stores are shared references there is no denying that. The restriction is very arbitrary and constraining. While it is possible to get around read/write, it's in the same category to me as people passing their own getter/setter props to get around 2 way binding. This is just like if you are trying to do something hard enough, well I guess you can.

**Comment by samuelstroschein** [comment]
@ryansolid this issue can be closed with GitHub's new "not planned" option and thereby declutter solid's open issues. (this issue has the "wontfix" label)
