### ISSUE TITLE
Cannot redefine property

### ISSUE THREAD

**Issue by juanrgm** [solidjs/solid#1301]
### Describe the bug

Can't override a property returned by `splitProps`.

### Your Example Website or App

https://playground.solidjs.com/?version=1.6.0#NobwRAdghgtgpmAXGGUCWEwBowBcCeADgsrgM4Ae2YZA9gK4BOAxiWGjIbY7gAQi9GcCABM4jXgF9eAM0a0YvADo1aAGzQiAtACsyAegDucAEYqA3EogcuPfr3iMA5nAAK8wmSy8yhDbndaTylZeUUVOg1tPQsrKzgKWz4ZeghmXDRaCF4AYQYIXHEACgxAz0R7ZnVuAH4KslxGDCcpAEp+K15eKogG3mBff0KRMrIAXV4AXh8-NACPMhKIUe9gFSq1bhUx1sts3n19XlwAC3lDMmUwAFU0qHonE74AFSI4AFFGeUYKnKgICC0PhCMQyDBwXiEDziAgVDZbMCdbpZPqOFwjBZTBziFyjIqDObDFYdfZdeE-K4glRYJGSXZIoS4JjZAA8AD4QGi4BigmQAHTkyQs-RsvaSOIQISiYpFdqTNm8Fl5VKFCQi7wiWjMejwAp8ly4d5qOC63AAIXwAEkREUVFBCIQVK0AIT0zCSMZAA

### Steps to Reproduce the Bug or Issue

```ts
import { render } from "solid-js/web";
import { mergeProps, splitProps } from "solid-js";

export function Counter(inProps: { color?: string }) {
  const [splittedProps] = splitProps(inProps, ["color"]);
  // throws "Uncaught TypeError: Cannot redefine property: color"
  const mergedProps = mergeProps(splittedProps, {
    color: "red",
  });
  return <>{mergedProps.color}</>;
}

render(() => <Counter />, document.getElementById("app")!);
```

### Expected behavior

https://playground.solidjs.com/?version=1.5.9#NobwRAdghgtgpmAXGGUCWEwBowBcCeADgsrgM4Ae2YZA9gK4BOAxiWGjIbY7gAQi9GcCABM4jXgF9eAM0a0YvADo1aAGzQiAtACsyAegDucAEYqA3EogcuPfr3iMA5nAAK8wmSy8yhDbndaTylZeUUVOg1tPQsrKzgKWz4ZeghmXDRaCF4AYQYIXHEACgxAz0R7ZnVuAH4KslxGDCcpAEp+K15eKogG3mBff0KRMrIAXV4AXh8-NACPMhKIUe9gFSq1bhUx1sts7qy+xxcRhamHcRdRosG54ZWO-a6N7gqVIREVLE62va6hXBMbIAHgAfCBjnBTkEyAA6F6MSTA-SgvaSOIQISiYpFdqTUG8YF5VKFCQo7wiWjMejwAqwly4ACiajgtNwACF8ABJERFFRQQiEFStACEuysYEkYyAA

### Platform

- Browser: Chrome
- Version: 106

**Comment by icode** [comment]
I had the same problem, at solidjs 1.6.0, it work will at 1.5.7, and solid-icons can not work with 1.6.0
