### ISSUE TITLE
render and destroy solidjs components (for using golden-layout library)

### ISSUE THREAD

**Issue by solid-droid** [solidjs/solid#1306]
I am trying to use golden-layout library with solidjs.
https://golden-layout.com/ 

golden-layout library have 4 process:
1. initializing 
```js
 layout = new GoldenLayout( config, $('#layoutContainer') ); 
```
 
2. Registring components for windows generated by golden-layout  
```js
import { lazy } from "solid-js";
import { render } from "solid-js/web";
layout.registerComponent( 'testComponent' , function( container, state ){
      render(() => lazy(() => import('./SolidComponent')) , container.getElement()[0] );  //renderLine**
    });
```
3. window gets an inbuilt close button => which removes the SolidComponent from DOM when clicked

4. to bringBack the window => below code recreates the SolidComponent  => internally it calls renderLine**
```js
  const addWindow = name => {
    const root = layout?.root.contentItems[ 0 ] || layout?.root;
    root?.addChild( {
      type: 'component',
      componentName: name,
      componentState: {  }
    });
  }
addWindow ('testComponent');
```
--------------

**Requirement / Issue :** 
1. need to render a fresh copy of SolidComponent (when a window is created)
2. need to destroy/dispose the existing SolidComponent (when a window is closed - FYI we have close button click callback )

**Progress**
1. Without Lazy the rendering of SolidComponent only happens once.
2. With Lazy the rendering of SolidComponent happens multiple times.  
    But Lazy seems to keep the old js still running (old html destroyed by golden-layout but old copies of js not destroyed)
    
**is there a way to destroy lazy rendered components ?  
or is there a better way to use golden-layout library ?**

**Comment by ryansolid** [comment]
That's not the way to render a lazy component might be the issue:

At minimum it should be:

```js
import { lazy } from "solid-js";
import { render } from "solid-js/web";
layout.registerComponent( 'testComponent' , function( container, state ){
      render(() => lazy(() => import('./SolidComponent'))() , container.getElement()[0] );  //renderLine**
    });
```
Lazy returns a component definition that should run. So instead of returning lazy you should be calling it. Usually you instantiate it in JSX though.

**Comment by solid-droid** [comment]
Ok.. now.. its behaving similar to without lazy.. cool..  

render() lets me render a component (html + js + nested components) anywhere i want.  
is there any method i can use to destroy it (html + js + nested components).

**Comment by Brendan-csel** [comment]
I believe `render()` returns a `dispose` function.  So perhaps you could save that somewhere and call it later. 
https://www.solidjs.com/docs/latest/api#rendering

**Comment by solid-droid** [comment]
Yeah that seems to be what iam looking for.  

in codepen(without golden-layout) its triggering onMount() on next render()
but in my project(with golden-layout) - dispose is working, but for some reason onMount() is not triggering.

will post the update if i have any update.

**Comment by solid-droid** [comment]
Ok i dont know why, but
```js
 dispose = render(() => lazy(() => import('./SolidComponent')) , container.getElement()[0] );
```
this seems to work perfectly..
it generates everything.. and dispose () destroys everything..  
[By adding cleanUp() able to destroy window/global level event listeners]
and on next render , onMount also works fine.
