### ISSUE TITLE
Resource's error won't be set if used in createRenderEffect

### ISSUE THREAD

**Issue by w1ndy** [solidjs/solid#1309]
### Describe the bug

If a resource is used in createRenderEffect, it's error will not be set if the resource fetcher throws:
```javascript
const [res] = createResource(async () => {
  throw 'test'
})
createRenderEffect(() => console.log(res()))
```

Wondering if this is an issue or an expected behavior... Thanks!

### Your Example Website or App

https://playground.solidjs.com/?version=1.4.1#NobwRAdghgtgpmAXGGUCWEwBowBcCeADgsrgM4Ae2YZA9gK4BOAxiWGjIbY7gAQi9GcCABM4jXgF9eAM0a0YvADo1aAGzQiAtACsyAegDucAEYqA3EogcuPfr2ZCouOACVhYxgFEZMuM1wsBycXdzomVilZeUUVOg1tPQsrKxl6CAC0WgheAGEGCBdGAAoASn4rXgdssj5gITIAXV4AXmC4Zzc4cJY4YqgyfAzeMtaAPgqcqt5cAAt5Q14AchdapcqpUo3HDtCPcR8-AOLRlonmGvU4ADo1WgBzYoay0q2poVwmHOKNqoAeERoABuY1+0z+AGVDGhcMxZqCptNwQBZZxw3iGWbCFoCBq3WhQQEQe5SMZ3QkYe5-fSo2HwsFIv609GY7G47rXcTyCSSMbssicxjcqTU5n0xHg-RQmFwhGM-SAkEbN6SFIQISicQncpnXh-fLpIq8fRjIIiWjMejwQrXe5wXBeNRwa24ABC+AAkiIfmAoIRCCpSgBCUqWTCSRpAA

### Steps to Reproduce the Bug or Issue

Run the example

### Expected behavior

The result panel should show "test" instead of "loading"

### Platform

- OS: macOS
- Browser: Firefox
- Version: 106.0.1

**Comment by mdynnl** [comment]
`Switch` operates top-down and currently `loading` is not set to `false` on resource error (maybe it should) so either `error` needs to be read first or be caught by `ErrorBoundary` wrapping the component reading the resource

**Comment by ryansolid** [comment]
Yeah loading should be set to false I think. We should fix that.

**Comment by w1ndy** [comment]
> `Switch` operates top-down and currently `loading` is not set to `false` on resource error (maybe it should) so either `error` needs to be read first or be caught by `ErrorBoundary` wrapping the component reading the resource

I don't know if it's related to Switch... If I comment out createRenderEffect, the example produces correct output regardless of the order of Match

**Comment by w1ndy** [comment]
https://github.com/solidjs/solid/blob/cafc51f6fc2e3ddf24b40cae00b77cf879051c9e/packages/solid/src/reactive/signal.ts#L607

I suspect this is the root cause of this problem... `createRenderEffect` seems to have higher priority over signal setters, so when it throws, the queue stops executing the rest of computation, effectively skipping the resetting of the loading state.

Maybe we can just return `undefined` here?
