### ISSUE TITLE
`ClassList` not applied when using together with `class` in nested components or when `class` comes later

### ISSUE THREAD

**Issue by yw662** [solidjs/solid#1313]
### Describe the bug

```ts
const D: Component<JSX.IntrinsicElements['div']> = (props) => (
  <div {...props} class={styles.foo} classList={{...props.classList}}>
    {JSON.stringify(props.classList)}
  </div>
);

const C = () => <D classList={{ [styles.bar]: true }} />;

const E = () =><div class={styles.foo} classList={{ [styles.bar]: true }}>E</div>
const F = () =><div classList={{ [styles.bar]: true }} class={styles.foo}>F</div>

const App: Component = () => {
  return (
    <div class={styles.App}>
      <C />
      <E />
      <F />
    </div>
  );
};
```

`[styles.bar]` should be applied to all 3 components. However only `E` works.

### Your Example Website or App

https://stackblitz.com/edit/solidjs-templates-h4zylc?file=src%2FApp.tsx

### Steps to Reproduce the Bug or Issue

Just open the link.

### Expected behavior

In the given link, the text with yellow background should all be colored red indicating class `[styles.bar]` being applied.

### Platform

- OS: Any
- Browser: Any
- Version: 1.6.0

**Comment by Brendan-csel** [comment]
I think it is recommended to avoid mixing `class` and `classList`.  From the docs...

_"It's also possible, but dangerous, to mix class and classList. The main safe situation is when class is set to a static string (or nothing), and classList is reactive. (class could also be set to a static computed value as in class={baseClass()}, but then it should appear before any classList pseudo-attributes.) If both class and classList are reactive, you can get unexpected behavior: when the class value changes, Solid sets the entire class attribute, so will overwrite any toggles made by classList."_

**Comment by yw662** [comment]
I can imagine how things can be ruined with both attributes reactive, but this is static and compile time, it is just `classList` comes before `class`.
As it says:
>  The main safe situation is when class is set to a static string (or nothing), and classList is reactive. (class could also be set to a static computed value as in class={baseClass()}, but then it should appear before any classList pseudo-attributes.)

Class is indeed a static string in this case, if we look at build artifacts. It is not like "class is static and classList is dynamic", because both is static, but it is also not the case that "classList should become later if class is computed", because it is not. Leaving this issue like this could make it uncomfortable to use solid with module CSS, even when everything is static.

Or maybe let's just change the type definition to ensure that `class` and `classList` can not be mixed, so that typescript will tell.

**Comment by Brendan-csel** [comment]
> Or maybe let's just change the type definition to ensure that class and classList can not be mixed, so that typescript will tell.

Spreads make that tricky I think.

**Comment by yw662** [comment]
I would always avoid things like "class before classList solves F", its behavior should not rely on which one comes first.
I will avoid class and always use classList in my future projects.

**Comment by Brendan-csel** [comment]
Looks related.  Moving the spread to be first gets the initial classes mixed properly - but as soon as you have something reactive, like toggling disabled in your case, the mix is lost and the latest update wins...

https://playground.solidjs.com/anonymous/7ebcdf9f-baa6-42eb-b468-18dcda40cd88
