### ISSUE TITLE
Solid 1.6 mergeProps results in undefined entries

### ISSUE THREAD

**Issue by martinpengellyphillips** [solidjs/solid#1316]
### Describe the bug

Updated to Solid 1.6 and found that Solid Select now [breaks](https://github.com/thisbeyond/solid-select/issues/28) when relying on default options. It seems `mergeProps` is the cause.

For this code:

```jsx

const createSelect = (props: CreateSelectProps) => {
  const config = mergeProps(
    {
      multiple: false,
      disabled: false,
      optionToValue: (option: Option): SingleValue => option,
      isOptionDisabled: (option: Option) => false,
    },
    props
  );
...
```

In 1.5, `config` would have the defaults for `isOptionDisabled` etc correctly defined. In 1.6 they are now all `undefined` resulting in breaking logic later.

```
CONFIG: 
Object { options: (5) […], … }
   isOptionDisabled: undefined   // <---- should be defined default function
​   options: Array(5) [ "apple", "banana", "pear", … ]
   ...
```

Note that `props` passed to `createSelect` came from this code in the `Select` component:

```jsx

const Select: Component<SelectProps> = (props) => {
  const [selectProps, local] = splitProps(
    mergeProps(
      {
        format: ((data, type) => data) as CommonProps["format"],
        placeholder: "Select...",
        readonly: typeof props.options !== "function",
        loading: false,
        loadingPlaceholder: "Loading...",
        emptyPlaceholder: "No options",
      },
      props
    ),
    [
      "options",
      "optionToValue",
      "isOptionDisabled",
      "multiple",
      "disabled",
      "onInput",
      "onChange",
      "onBlur",
      "onFocus",
    ]
  );
  const select = createSelect(selectProps);
```

### Your Example Website or App

https://github.com/thisbeyond/solid-select/issues/28

### Steps to Reproduce the Bug or Issue

1. Install Solid Select with Solid 1.6
2. Create a plain `<Select options={['a', 'b', 'c']}/>`
3. Attempt to interact with the select by clicking on it. Error occurs.

### Expected behavior

No error.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by mdynnl** [comment]
workaround <https://playground.solidjs.com/?hash=-1845137203&version=1.6>

**Comment by LiQuidProQuo** [comment]
in a way this looks like it is as "intended", `SplitProps`, returns all the requests keys, even if they don't exist
like it does for the proxied version. 

the difference is, the proxied version looks up in all the merged sources until it finds a source with a value.
the non-proxied version, "flatten" the sources and returns the latest key merge value.

this creates inconsistency between proxied and non-proxied merging 


SplitProps can avoid returning undefined keys for the non-proxied. that too creates inconsistency 
but will make this use case work. 

alternatively, look into implementing sources lookup logic similar to the proxied version, which can also fix this use case. 
and create a more consistent solution, albeit more involved.

**Comment by ryansolid** [comment]
Hmm.. interesting. I guess Solid's original merge code was even more limiting than I ever realized. I was trying to avoid the pass through lookup and hoping merging would be sufficient. Let me see what I can do.

**Comment by LiQuidProQuo** [comment]
@ryansolid  added another possible approach for the fix 
https://github.com/solidjs/solid/pull/1320

**Comment by ryansolid** [comment]
Yeah that feels too specific to this interaction and not as generalized. We aren't going to patch other things with undefined symbols.

**Comment by LiQuidProQuo** [comment]
agreed, now last question, why are we patching the prop as non-configurable
