### ISSUE TITLE
createMutable has error on Map API

### ISSUE THREAD

**Issue by dream2023** [solidjs/solid#1318]
### Describe the bug

```ts
import { createMutable } from "solid-js/store";

const m = createMutable(new Map())
m.has('key')
```

### Your Example Website or App

https://stackblitz.com/edit/solidjs-templates-gfpexv?file=src/App.tsx

### Steps to Reproduce the Bug or Issue

open example app and open chrome devtools

### Expected behavior

work fine with Map

### Screenshots or Videos

![1667016449499](https://user-images.githubusercontent.com/19297757/198813134-e288070f-a2e3-4f84-8ea4-b21711057c4d.png)

### Platform

- OS: [Windows]
- Browser: [Chrome]
- Version: [1.6.0]

**Comment by Brendan-csel** [comment]
I'm not sure putting a Map as the top level in a store is supported.  Solid won't react to changes in the content of a Map (or Set, etc) so it would only trigger if the whole Map was swapped out - which you can't really do at the top level anyway.

From the docs [section on stores](https://www.solidjs.com/docs/latest/api#createstore)...

> Classes are not wrapped, so objects like Date, HTMLElement, RegExp, Map, Set won't be granularly reactive as properties on a store.
