### ISSUE TITLE
Multiple createResource instances causes issues with refetch/mutate

### ISSUE THREAD

**Issue by 0bon** [solidjs/solid#1319]
### Describe the bug

Having more than one resource with refresh/mutate throws a "Cannot redeclare block-scoped variable 'refetch'.ts(2451)"

```
const [a, {mutate, refetch}] = createResource(...);
const [b, {mutate, refetch}] = createResource(...);
```

### Your Example Website or App

N/A

### Steps to Reproduce the Bug or Issue

N/A

### Expected behavior

Create multiple resource signals and being able to refresh any one or all resources.  The current method causes naming conflicts.

### Platform

latest solidjs version

**Comment by ryansolid** [comment]
This is because you can't have multiple of the same identifier. You could either hang them of a named variable:

```js
const [a, actionA] = createResource(...);
const [b, actionsB] = createResource(...);

actionsA.mutate() //etc...
```

Alternately you can name them:
```js
const [a, {mutate: mutateA, refetch: refetchA}] = createResource(...);
const [b, {mutate: mutateB, refetch: refetchB}] = createResource(...);
```

In any case this is JavaScript so there is nothing to be done.
