### ISSUE TITLE
[Bug] Whitespace Error Within JSX Components Involving New-Lines and Expressions

### ISSUE THREAD

**Issue by tcardlab** [solidjs/solid#1324]
### Describe the bug

When using components, either custom `e.g. <Test>` or from Solid.js `e.g. <Dynamic>`, involving a whitespace, newline, and blocks evaluated as expressions, an error is generated. This error is not generated for native elements and non-expression content. Potentially [vite-plugin-solid](https://github.com/solidjs/vite-plugin-solid) error, but I'm not familiar enough to make that call.

<hr/>

With whitespace, these cause an error:
```jsx
<Test> {/*<– whitespace*/}
  {props.title}
<Test>
```

```jsx
<Test> {/*<– whitespace*/}
  {'hello '+(()=>'world')()}
<Test>
```

Without whitespace, these will work:
```jsx
<Test>{/*<– no whitespace*/}
  {props.title}
<Test>
```

```jsx
<Test>{/*<– no whitespace*/}
  {'hello '+(()=>'world')()}
<Test>
```

<details>
<summary> Other Things That Still Work: </summary>

```jsx
<Test> {props.title} <Test>
```

```jsx
<Test>  {/*<– whitespace*/}
  {'hi'} 
<Test>
```

```jsx
<Test>  {/*<– whitespace*/}
  {'hi' + 'hi'} 
<Test>
```

```jsx
<Test>  {/*<– whitespace*/}
  hi
<Test>
```
</details>

<hr/>

Initial Discovery:
https://stackblitz.com/edit/solidjs-templates-5ybexv?file=src/components/Collapse.tsx

Realizing native DOM elements not effect, but all custom ones are:
https://stackblitz.com/edit/solidjs-templates-nfd3r4?file=src/components/Collapse.tsx

Note: I bumped the version in the example below, error still generated

### Your Example Website or App

https://stackblitz.com/edit/solidjs-templates-zepjyb?file=src/components/Collapse.tsx

### Steps to Reproduce the Bug or Issue

Provided stackblitz links should be sufficient.

### Expected behavior

I am seeing whitespace errors which is unlike native JS/HTML behavior.
These errors can be hard to debug as most web devs overlooks whitespace given JS/HTML is whitespace agnostic and designed to be minified.

### Platform

- OS: macOS
- Browser: Chrome
- Version: 106.0.5249.119

**Comment by yw662** [comment]
I don't think it is a bug though.
Let's say if the children is not a function, eg. `<div>{ }{sthElse}</div>`, this whitespace should be preserved but JSX syntax. So, in this situation, JSX syntax did nothing wrong to preserve the whitespace, even if it breaks the type requirement on children of the parent component.
And anyway it is always a good idea to not having whitespaces at the tail of a line.

However I am surprised that TypeScript failed to detect the issue.

**Comment by yw662** [comment]
indeed 
```
<Element><whitespace>
{children}
</Element>
```
is exactly
```
<Element>
{ }
{children}
</Element>
```
in JSX syntax.
I just wonder why TypeScript failed to detect the type error.

**Comment by ryansolid** [comment]
That is interesting. We are sort of a middleground between React and HTML in the conventions I've taken. This sort of detail is transform specific rather than spec'd anywhere. But if TS has issues that's more interesting. In a sense I'd rather align more with HTML in general for copy and paste type scenarios but it is hard in certain places to optimally preserve space because not all children are guaranteed to be treated like HTML especially with components. And consistency is probably the more important.
