### ISSUE TITLE
Stop leaking global variables during hydration

### ISSUE THREAD

**Issue by jculvey** [solidjs/solid#1325]
The `e` and `t` variables from the hydration script are sticking around as `window.e` and `window.t`. This can be seen in the default counter app created by: `npm init solid # bare, yes, yes`.

This is problematic when trying to bootstrap a solid app more than once in the same document. 

It looks like the code that causes this originates in the [dom expressions library](https://github.com/ryansolid/dom-expressions/blob/b2f42641eb3eef5c0455719e15bd729e14e1a778/packages/dom-expressions/src/server.js#L426). Please let me know if I should file this issue against a different repo.

**Comment by lxsmnsyc** [comment]
Ideally the script should only be injected once, but doesn't really matter if it reruns multiple times since the script checks if the variable exists. Renaming it should be better though

**Comment by ryansolid** [comment]
The minifier (terser, in the REPL) adds its own globals too which was unexpected.
