### ISSUE TITLE
Hydration warnings rendering table

### ISSUE THREAD

**Issue by viridia** [solidjs/solid#1329]
### Describe the bug

I'm rendering an HTML table, using a bunch of thin wrapper components ("Table" vs "table"). I'm getting a large number of hydration errors - basically one for every table cell. In fact, if you run this code, you'll see the correct table briefly for a moment, and then about 100ms later it gets blanked out.

Client-side rendering works fine.

I've winnowed down the wrappers as much as I can, there is nothing particularly special or weird about them. The only code that is left in each wrapper is the code to forward the class name from the wrapper to the native element, and the code to splitProps out the class name. If I remove those, the problem disappears.

I don't have a good theory as to the cause, although perhaps the level of nesting has something to do with it.

I've attached a stackblitz link which demonstrates the problem. I have also been able to reproduce the problem in two other solid-start projects, using the same code.

### Your Example Website or App

https://stackblitz.com/edit/solid-start-bare-ts-zijf6c?file=src/routes/index.tsx

### Steps to Reproduce the Bug or Issue

See stackblitz link

### Expected behavior

The table should be visible after hydration.

### Platform

- OS: macOS
- Browser: Edge

**Comment by Brendan-csel** [comment]
Link gives me...

![image](https://user-images.githubusercontent.com/1744490/199665579-cef56d40-deea-4060-996f-83f3e056b9fb.png)

TBH - I don't know what I'm talking about here but have overheard that it is important to include tags like `tbody` - otherwise the browser adds them for you which means the document no longer matches what is expected.  I may be wrong but perhaps something to check while you wait for someone more knowledgeable to respond.

**Comment by ryansolid** [comment]
Yes please share a new reproduction.

**Comment by viridia** [comment]
Unfortunately I have not had good luck with solid-start on stackblitz - it tends to be somewhat fragile, often I have to restart the container to get it to display the page. I have three different solid-start projects on stackblitz and they all exhibit the same problem.

The other alternative is to have you simply paste the following code into a solid-start project of your own:

```
import { css } from 'goober';
import { For, JSX, ParentComponent, splitProps } from 'solid-js';
import { Title } from 'solid-start';

const headerCss = css({
  backgroundColor: 'red',
  border: '2px solid green',
});

export default function Home() {
  return (
    <main>
      <Title>solid-start bare typescript</Title>
      <h1 classList={{ [headerCss]: true }}>Index</h1>
      <TableDemo />
    </main>
  );
}

const rows = [
  1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
];

const TableCell: ParentComponent<JSX.HTMLAttributes<HTMLTableCellElement>> = (
  props
) => {
  const [local, rest] = splitProps(props, ['class']);
  return (
    <td {...rest} classList={{ [local.class as string]: !!local.class }}>
      {props.children}
    </td>
  );
};

const TableRow: ParentComponent<JSX.HTMLAttributes<HTMLTableRowElement>> = (
  props
) => {
  const [local, rest] = splitProps(props, ['class']);
  return (
    <tr {...rest} classList={{ [local.class as string]: !!local.class }}>
      {props.children}
    </tr>
  );
};

const TableHead: ParentComponent<JSX.HTMLAttributes<HTMLTableSectionElement>> =
  (props) => {
    const [local, rest] = splitProps(props, ['class']);
    return (
      <thead {...rest} classList={{ [local.class as string]: !!local.class }}>
        {props.children}
      </thead>
    );
  };

const TableBody: ParentComponent<JSX.HTMLAttributes<HTMLTableSectionElement>> =
  (props) => {
    const [local, rest] = splitProps(props, ['class']);
    return (
      <tbody {...rest} classList={{ [local.class as string]: !!local.class }}>
        {props.children}
      </tbody>
    );
  };

export const Table: ParentComponent<JSX.HTMLAttributes<HTMLTableElement>> = (
  props
) => {
  const [local, rest] = splitProps(props, ['class', 'children']);
  return (
    <table {...rest} classList={{ [local.class as string]: !!local.class }}>
      {local.children}
    </table>
  );
};

function TableDemo() {
  return (
    <Table>
      <TableHead>
        <TableRow>
          <TableCell>Selected</TableCell>
          <TableCell>N</TableCell>
          <TableCell>2N</TableCell>
          <TableCell>
            N<sup>2</sup>
          </TableCell>
          <TableCell>
            N<sup>3</sup>
          </TableCell>
          <TableCell>
            N<sup>4</sup>
          </TableCell>
        </TableRow>
      </TableHead>
      <TableBody>
        <For each={rows}>
          {(n) => (
            <TableRow>
              <TableCell>N</TableCell>
              <TableCell>{n}</TableCell>
              <TableCell>{n * 2}</TableCell>
              <TableCell>{n * n}</TableCell>
              <TableCell>{n * n * n}</TableCell>
              <TableCell>{n * n * n}</TableCell>
            </TableRow>
          )}
        </For>
      </TableBody>
    </Table>
  );
}
```

**Comment by Brendan-csel** [comment]
If it helps other folks to debug, the issue can be reproduced with just...
```js
function TableDemo() {
  return (
    <table>
      <TableHead>
        <tr></tr>
      </TableHead>
    </table>
  );
}

const TableHead: ParentComponent<JSX.HTMLAttributes<HTMLTableSectionElement>> =
  (props) => {
    const [local, rest] = splitProps(props, ['class']);
    return (
      <thead {...rest} classList={{ [local.class as string]: !!local.class }}>
        {props.children}
      </thead>
    );
  };
```

Unable to find DOM nodes for hydration key: `0-0-0-0-0-0-0-0-0-1-0-0-0-0-2-1-0-0-2-1-1`

Document from server is:
```html
<table data-hk="0-0-0-0-0-0-0-0-0-1-0-0-0-0-2-1-0-0-2-0">
  <thead data-hk="0-0-0-0-0-0-0-0-0-1-0-0-0-0-2-1-0-0-2-1-0" class="">
    <tr data-hk="0-0-0-0-0-0-0-0-0-1-0-0-0-0-2-1-0-0-2-1-2"></tr>
  </thead>
</table>
```
And Elements after error is:
```html
<table data-hk="0-0-0-0-0-0-0-0-0-1-0-0-0-0-2-1-0-0-2-0">
  <thead data-hk="0-0-0-0-0-0-0-0-0-1-0-0-0-0-2-1-0-0-2-1-0" class="">
    <tr></tr>
  </thead>
</table>
```

Swapping out the `<TableHead>` for a plain `<thead>` works - so something weird about a component being used there.

**Comment by Brendan-csel** [comment]
Curiously if there are multiple `<tr>` (for example) the client will be looking for keys like:
```
...2-1-1
...2-1-2
...2-1-3
...2-1-4
```
...but the document will contain keys like...
```
...2-1-5
...2-1-6
...2-1-7
...2-1-8
```
It's almost like the children are being issued keys twice on the server and only the second set are written to the document.

**Comment by lxsmnsyc** [comment]
This is most likely with `splitProps`. What happens if you add `children` in the list of properties for `local`?

**Comment by Brendan-csel** [comment]
> This is most likely with splitProps. What happens if you add children in the list of properties for local?

Yes! Exactly this @viridia.  I was wondering why children was running twice and looked right over the "rest" spread.

Either do this:
```js
    const [local, rest] = splitProps(props, ['class', 'children']);
    return (
      <thead {...rest} classList={{ [local.class as string]: !!local.class }}>
        {props.children}
      </thead>
    );
```

or just 
```js
    const [local, rest] = splitProps(props, ['class']);
    return (
      <thead {...rest} classList={{ [local.class as string]: !!local.class }} />
    );

```

**Comment by viridia** [comment]
Yep, that works. Thanks everyone :)

**Comment by viridia** [comment]
I suspect the reason I wrote the code that was is because of React habits - I seem to recall that in React it's not recommended to pass 'children' as an attribute.

**Comment by ryansolid** [comment]
I think this is still a bug even if you don't hit it on the happy path. Compiler should be able to avoid it.
