### ISSUE TITLE
Prop spreads clobber other props if placed "first"

### ISSUE THREAD

**Issue by timothyallan** [solidjs/solid#1330]
### Describe the bug

Placing a props spread first in a component will set any remaining props to "true". Placing it last works fine.

Bonus points: It works fine in the playground and outputs the correct HTML. Link attached.

### Your Example Website or App

https://playground.solidjs.com/?version=1.6.1#NobwRAdghgtgpmAXGGUCWEwBowBcCeADgsrgM4Ae2YZA9gK4BOAxiWGjIbY7gAQi9GcCABM4jXgF9eAM0a0YvADo1aAGzQiAtACsyAegDucAEYqA3EogcuPfr2ZCouOAGU0Ac2hqps+YpU6DW09Cys4Cls+GXoIZlw0WgheAGEFLghhXAAVODJcAAoASn4rXgck-NkoAGs4AAV5QjJeAF57GVqGpsReAHJOuoA3KDV6OD6pSwgywThcJmSC2fKAHgA+FfLeVZE0If4AOmPB7tpm6U1WlRh8ABF9gEYVBzUoMjJrsFOtXHQ1QwYESvd5kPK8KAmIL0FwqTbJbaIgAS4gmLVuvAeQy2a30eyG8MRa3xvCuN3u+wATC9mG8Pl8fn80ACgSCPuDIdDYWAjicuo1zmRJISieUUUI+uj8Jj9jidnj9iLcSKitNJFYrDE4gkkqkGBAXIxiqUZgihAtGEsVqs0pwkllcvl9Cq1RqIEJROICsbWusdmlYobeM6sLwRLRmPR4AbDh55gBRNRwaO4ABC+AAkiJlmAoIRCCoigBCVVWMCSAC6QA

### Steps to Reproduce the Bug or Issue

`npx degit solidjs/templates/ts-unocss` a new project, update all the dependencies to current. 
```
  "devDependencies": {
    "@unocss/preset-mini": "^0.46.3",
    "@unocss/vite": "^0.46.3",
    "typescript": "^4.8.4",
    "vite": "^3.2.2",
    "vite-plugin-solid": "^2.3.10"
  },
  "dependencies": {
    "solid-js": "^1.6.1"
  }
  ```
Put this component somewhere
```
export function ComponentTest() {
  const fakeProps = { fakeProp: 'fakevalue' };

  return (
    <>
      <div {...fakeProps} id="myDiv1" class="fake-tailwind classes absolute">
        Here's my Div
      </div>
      <div id="myDiv2" class="fake-tailwind classes absolute" {...fakeProps}>
        Here's my Div
      </div>
    </>
  );
}
```

Look a the difference in compiled code, and the output divs:
![Screen Shot 2022-11-02 at 10 01 31 PM](https://user-images.githubusercontent.com/1995135/199645348-bf36486c-36d7-4058-86e7-2bb5b76fd1fb.png)

### Expected behavior

I'd really like to not have to worry about placement of the spread!

### Platform

MacOS Chrome/Safari/FF

**Comment by LiQuidProQuo** [comment]
reproducible in playground too
https://playground.solidjs.com/?hash=425446040&version=1.6.1

```html
 <div {...props} b="this is not" c={"this is working"}>
```

```html
<div b="true" c="this is working" fake="it">Here's my Div</div>
```
compiled output
```js
  spread(_el$2, mergeProps(props, {
      "b": true,
      "c": "this is working"
    }), false, true);
```

**Comment by ryansolid** [comment]
Remove package.lock and get latest babel plugin will fix this.
