### ISSUE TITLE
Exit animations are broken with `@motionone/solid` on solid-js@1.5.0 and up

### ISSUE THREAD

**Issue by jakst** [solidjs/solid#1333]
### Describe the bug

Looks like exit animations in @motionone/solid do not work anymore. Looks like it's broken on v1.5.0 and above, so I assume it's a bug in solid rather than with Motion One.

### Your Example Website or App

https://codesandbox.io/s/sandpack-project-forked-0gu6ff?file=/package.jsonjson

### Steps to Reproduce the Bug or Issue

Go to codesandbox and click the toggle button in the example multiple times. No exit animation.
Try downgrading solid-js to a version below v1.5.0. It works fine.

### Expected behavior

I expect exit animations in Motion One to work with all solid-js versions.

### Platform

- OS: MacOs
- Browser: Chrome
- Version: 105

**Comment by thetarnav** [comment]
hmmm I guess I need to look into motionone again.. there are few things that need to be improved anyway.

**Comment by thetarnav** [comment]
Looks like the @motionone/solid version in the example wasn't updated. The current version (10.14.3) works without any issues.
https://stackblitz.com/edit/github-dgb4gv?file=src%2FApp.tsx

This was the PR to motionone that fixed it for solid 1.5 -> https://github.com/motiondivision/motionone/pull/138

**Comment by jakst** [comment]
Yeah seems like it was fixed in v10.14.2. Not sure how I ended up with an older version, since I both installed the library locally and set up the sandbox on the same day that this issue was created when the fix was already published. Anyway, thanks for looking into into.
