### ISSUE TITLE
Failed to minimize multi-lined class string

### ISSUE THREAD

**Issue by lihe07** [solidjs/solid#1334]
I'm using unocss for styling, therefore the class attribute of some elements are quite long. So I write them in this way:
![Example](https://user-images.githubusercontent.com/53819558/186135198-18080dfd-5992-49c3-8ed9-7ea1d5d5764c.png)

I except these blanks can be removed automatically. However, the compressed file still contains extra blanks:
![Example](https://user-images.githubusercontent.com/53819558/186135714-333147b2-9c7f-4b72-97c6-4fce21a1c8c6.png)

My vite version: `v3.0.9` vite-plugin-solid: `2.3.0`

> This may not affect much, but the experience will definitely be better after this being addressed.

**Comment by ryansolid** [comment]
Something that I'm thinking is this isn't a sort of optimization we could apply anywhere. Like there may be a desire for that spacing in other attributes. Svelte does seem to special case `class` and `style` during compilation so there is some precedence.
