### ISSUE TITLE
useStore is undefined

### ISSUE THREAD

**Issue by 0bon** [solidjs/solid#1337]
### Describe the bug

I am trying to add a context to a page, but when running the code I get:
`Uncaught (in promise) TypeError: useStore is undefined`

Provider.tsx
```
export type StorageType = [
    field: StorageObject<any>,
    setField: StorageSetter<any, string>,
];


interface Props {
    children: any,
    store: StorageType
}

export const StorageContext = createContext<StorageType>();

export function StorageProvider(props: Props) {
    return (
        <StorageContext.Provider value={props.store}>
            {props.children}
        </StorageContext.Provider>
    );
}

export function useStore() {
    return useContext(StorageContext);
}
```
Parent.tsx
```
const [field, setField] = createLocalStorage<string, any>({
    prefix: 'prefix',
});

export default () => {
    return (
        <StorageProvider store={[field, setField]}>
            <Form />
        </StoreProvider>
    );
};
```

Form.tsx
```
const [field, setField] = useStore()!; // fails with useStore is undefined
....
```

### Your Example Website or App

N/A

### Steps to Reproduce the Bug or Issue

N/A

### Expected behavior

N/A

### Platform

linux, latest solidjs version

**Comment by ryansolid** [comment]
Did you import it in your file? `useStore is undefined` suggests the function isn't available at that scope.

**Comment by 0bon** [comment]
Yes.

```import { useStore } from '../Provider';```

**Comment by ryansolid** [comment]
Ok I will probably need a reproduction, because the error isn't suggesting it can't find the context, but that it can't find `useStore`, the function, which suggests it's an import, variable scope or bundler issue.

**Comment by 0bon** [comment]
Problem solved. I wasn't calling it in the function i.e:
```
const [field, setField] = useStore();
function xyz() {
   console.log(field.x);
}
```

Changing to the following fixed the issue:

```
function xyz() {
   const [field, setField] = useStore();
   console.log(field.x);
}
```
