### ISSUE TITLE
hydration crash with npm "Cannot read properties of null (reading 'nextSibling')"

### ISSUE THREAD

**Issue by samuelstroschein** [solidjs/solid#1345]
### Describe the bug

SolidJS hydration seems to behave differently with npm and pnpm, leading to a crash with npm but not with pnpm.

The bug was originally filed at https://github.com/chakra-ui/zag/issues/385. Any Zag component crashes during hydration but not when client-side rendered only via `render()`. Efforts to reproduce the issue yielded that running the repro with npm crashes while pnpm does not. 

```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'nextSibling')
    at index.page.tsx:14:3
    at Checkbox (index.page.tsx:20:34)
    at @solid-refresh:10:42
    at untrack (chunk-CGI4PW6R.js?v=14626c3e:447:12)
    at Object.fn (@solid-refresh:10:28)
    at runComputation (chunk-CGI4PW6R.js?v=14626c3e:751:22)
    at updateComputation (chunk-CGI4PW6R.js?v=14626c3e:734:3)
    at createMemo (chunk-CGI4PW6R.js?v=14626c3e:253:5)
    at hmrCompWrapper (@solid-refresh:7:20)
    at chunk-CGI4PW6R.js?v=14626c3e:555:1
```

### Your Example Website or App

https://stackblitz.com/edit/solidjs-templates-chv1jk?file=src/pages/index.page.tsx

### Steps to Reproduce the Bug or Issue

with npm:

1. Open the stackblitz link. 
2. Open the console (inspect)
3. npm i 
4. npm run dev
5. crash will appear in the console

with pnpm: 
1. Open the stackblitz link. 
2. Open the console (inspect)
3. pnpm i
4. pnpm run dev
5. works fine

### Expected behavior

No client-side crash during hydration when run with npm (or any other package manager). 

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/35429197/200822593-2af39eed-e3ef-433d-8dfe-3fc7a638926a.png)

### Platform

- OS: macOS
- Browser: Chrome
- Version: 107
- SolidJS: 1.6

### Additional context

You can download the project from Stackblitz. Running `npm i` and `pnpm i` locally seems to resolve the same SolidJS version.

**Comment by pawelblaszczyk5** [comment]
From my investigation it looks like It's related with nested elements with spread props overriding children. It works if the children prop is used instead of the JSX form. It worked until 1.6. I encountered the same problem, more info in linked issue :)

**Comment by ryansolid** [comment]
Thanks for reporting. The last release(1.5) was all about improving server-side Spreads, and this release(1.6) about the client. I would guess a change in the client logic is causing the slight mismatch.

**Comment by samuelstroschein** [comment]
@pawelblaszczyk5 The problem in this issue existed with v1.5 too. Might be unrelated to the other issue you filed. 

@ryansolid But why would npm crash and pnpm not?

**Comment by pawelblaszczyk5** [comment]
> @pawelblaszczyk5 The problem in this issue existed with v1.5 too. Might be unrelated to the other issue you filed.

Oh, yeah, you're right, I must have checked something incorrectly yesterday. It's not working on v1.5 also, it's the same issue. I also discovered it while trying to use zag 😄

**Comment by ryansolid** [comment]
Yeah it's a compiler bug. I found it and should get it out today.

**Comment by samuelstroschein** [comment]
@ryansolid the bug has not been solved. The [repro](https://stackblitz.com/edit/solidjs-templates-chv1jk) yields the same error with v1.6.2.

```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'nextSibling')
```

**Comment by ryansolid** [comment]
Make sure that the babel plugin has updated. babel-preset-solid 1.6.2 will ensure it. I updated the stackblitz template and I think it is working: https://stackblitz.com/edit/solidjs-templates-r53rfw?file=src/pages/index.page.tsx

**Comment by samuelstroschein** [comment]
I can confirm. Works. It seems like NPM has problems resolving babel-preset-solid though which might explain the difference between NPM and PNPM. 

If other people run into the issue, I manually added babel-preset-solid to the package JSON. See this [commit](https://github.com/inlang/inlang/commit/67ea1d0283cdbfa6796d6868b7397b327ebb9edb).
