### ISSUE TITLE
For component no update when reset array

### ISSUE THREAD

**Issue by Debbl** [solidjs/solid#1361]
### Describe the bug

index update is wrong when I click reset button.

<img width="498" alt="image" src="https://user-images.githubusercontent.com/61053131/201590662-418019b8-2030-4526-b283-1219d8de0ef8.png">

<img width="461" alt="image" src="https://user-images.githubusercontent.com/61053131/201590749-2d647513-c764-4de6-9ac3-1203643246e0.png">

### Your Example Website or App

https://stackblitz.com/edit/solidjs-templates-x7kdvr?file=src%2Findex.tsx

### Steps to Reproduce the Bug or Issue

1. Jumping click button
2. Click reset

### Expected behavior

I expected a correct index, but I got a wrong one.

### Screenshots or Videos

https://user-images.githubusercontent.com/61053131/201591625-38788e0d-73d3-4150-8c10-51d19651f0cd.mp4

### Platform

- OS: macOS
- Browser: Chrome
- Version: 1.5.1

**Comment by ryansolid** [comment]
It's because `<Tile>` is destructuring props. This loses reactivity and the values don't update properly. In this case `index` is reactive and it losing it where it is destructured.

That being said `<Index>` is probably the right choice for things that store primitive values like numbers or strings.

**Comment by Debbl** [comment]
Thank you very much. I should get the value through the `get method` of `props` to make it is reactivity.

**Comment by ryansolid** [comment]
Yeah you don't need to do much special. I fixed it by removing the restructure and just using like `props.i`
