### ISSUE TITLE
Infinite loop when this appears anywhere in DOM: <form><input id='host' /></form>

### ISSUE THREAD

**Issue by infi-pc** [solidjs/solid#1380]
### Describe the bug

when I put this example snippet anywhere, it starts an infinite loop:
```
<form>
  <input id='name' />
  <input id='host' />
</form>
```

### Your Example Website or App

https://playground.solidjs.com/anonymous/c8a88d61-4ee7-4533-a8b8-806b0fee982d

### Steps to Reproduce the Bug or Issue

- go to https://playground.solidjs.com/
- paste this anywhere into JSX
```
<form>
  <input id='name' />
  <input id='host' />
</form>
```
- focus one of rendered input fields

### Expected behavior

should not fall into infinite loop

### Screenshots or Videos

https://user-images.githubusercontent.com/2264725/203985494-952a515b-d217-4204-8568-b15689462bd8.mp4

### Platform

- OS: macOS
- Browser: Chrome, Firefox
- Version: latest

### Additional context

the loop here:
https://github.com/ryansolid/dom-expressions/blob/main/packages/dom-expressions/src/client.js#L370
I think it could be fixed by checking the node.parentNode before checking the host. 

an original issue where it happened: https://github.com/infi-pc/locatorjs/issues/80

**Comment by atk** [comment]
The issue here is that form field IDs are still referencing the fields on the form node, a leftover from MSIE. One needs to use getAttribute to work around this.

**Comment by ryansolid** [comment]
I see.. we want to check `host` before `parentNode` as that's the whole point. Our portals use a `host` property as do shadow roots. This is so we traverse that tree rather than just the parent tree. Host element takes precedence. And it isn't an attribute thing but a property thing. I suppose we can add another check.. maybe better to use a different property at this point.

**Comment by yw662** [comment]
Workaround: use `name` instead (

**Comment by LiQuidProQuo** [comment]
> maybe better to use a different property at this point.

non colliding name / Symbol might be better than always checking this additionally, 
for this rare edge case.

`(!node.contains(node.host))`

```js
node = node.host && node.host !== node && (!node.contains(node.host)) && node.host instanceof Node ? node.host : node.parentNode;
```
