### ISSUE TITLE
Overrided property by `undefined` in `mergeProps`

### ISSUE THREAD

**Issue by juanrgm** [solidjs/solid#1383]
> https://stackblitz.com/edit/github-pkoqsx?file=src%2Froot.tsx

```ts
import { mergeProps } from 'solid-js';

// @refresh reload
export default function Root() {
  const props = mergeProps(
    {
      value: 1,
    },
    {
      get value() {
        return undefined;
      },
    }
  );
  return <>props.value: {props.value}</>; // props.value: undefined
}
```

> https://playground.solidjs.com/anonymous/224b34ac-6a3a-4a9d-b837-f47c90398f94
```ts
import { render } from "solid-js/web";
import { mergeProps } from "solid-js";

function Root() {
  const props = mergeProps(
    {
      value: 1,
    },
    {
      get value() {
        return undefined;
      },
    }
  );
  return <>props.value: {props.value}</>; // props.value: 1
}

render(() => <Root />, document.getElementById("app")!);
```

**Comment by orenelbaum** [comment]
@ryansolid it's actually a Solid Start issue. It doesn't happen in a normal Solid project or even in Solid Start with SSR turned off.

**Comment by orenelbaum** [comment]
This issue happens only with SSR. It doesn't happen in a normal Solid project or with Solid Start with SSR turned off.

**Comment by ryansolid** [comment]
It's a DOM Expressions problem. But I consider SSR in Solid's responsibility. SolidStart is just a template/cli/collection of Vite plugins.

**Comment by orenelbaum** [comment]
I actually found the problem, it's in the server version of mergeProps, I'll fix it, I just want to make sure I fix it properly

**Comment by orenelbaum** [comment]
Another fun bug, if you replace the props object with:
```js
const props = mergeProps(() => ({ value: 1 }));
props.value = 2;
````
With ssr you'd get the value 2 but without ssr you'd get the value 1.

**Comment by orenelbaum** [comment]
I'll link this here for now
https://github.com/ryansolid/dom-expressions/commit/9d4385463ffa8719b3f22e7962e53fd7f1d30e08

**Comment by fongandrew** [comment]
Just wanted to note that this change caused an issue for me. The specific thing I was trying to do:

```jsx
// Replace `invalid` with `aria-invalid` since `invalid` isn't a proper HTML attribute
<input {...props} aria-invalid={props.invalid} invalid={undefined} />
```

The expectation was that this would work because `{ ...({ foo: 'bar' }), ...({ foo: undefined }) }` replaces the attribute with undefined in plain JavaScript. There are workarounds around (use `null` or `splitProps` instead) but this behavior was a bit unexpected.
