### ISSUE TITLE
Setter of object as prop in component not working

### ISSUE THREAD

**Issue by sysmat** [solidjs/solid#1388]
### Describe the bug

- edit: Setter<boolean> works fine
- setHuman: Setter<Human> not working

### Your Example Website or App

https://stackblitz.com/edit/solidjs-templates-zhnfha?file=src/App.tsx

### Steps to Reproduce the Bug or Issue

1. click edit
2. in input form change name 
3. click confirm button

### Expected behavior

Setter works for all types not just for boolean

### Platform

- OS: [Windows]
- Browser: [Chrome]
- Version: [e.g. 107.1]

**Comment by elite174** [comment]
@sysmat 
<img width="266" alt="image" src="https://user-images.githubusercontent.com/13636224/205081953-772e5ff4-e8ef-458c-be87-03e5104a5b18.png">
You need to change `name_ + index` to name for the input field and everything will work.
Just do this:

<img width="195" alt="image" src="https://user-images.githubusercontent.com/13636224/205082216-6a606cad-5f39-490c-8ccd-782df1395b6d.png">

**Comment by sysmat** [comment]
@elite174 hm, interesting 

but when I don't change input & submit value is still empty, probably bug in `"@felte/solid": "^1.2.6"` form

**Comment by elite174** [comment]
@sysmat seems like there's an answer for your question
https://github.com/pablo-abc/felte/issues/195

**Comment by sysmat** [comment]
- Yes I open a issue, initialValues solve the problem, but felte should recognize initial form values from form
- I'm from angular side and I'm trying solid I'm struggling with createResource for crud in side of felte submit function. 
-  Also typescript is unhappy with createResource function, but no errors in vite  and in browser work

```typescript
// Argument of type 'Accessor<number | undefined>' is not assignable to parameter of type 'ResourceFetcher<true, Human, unknown>'.
 const [user] = createResource<Human>(userId, fetchHuman);

```

**Comment by ryansolid** [comment]
Ok so I understand the state of this issue. There is a Felte issue? And there could also be a TypeScript issue?

**Comment by ryansolid** [comment]
Ok this looks like a Felte issue. If there is a specific createResource type issue feel free to report it.
