### ISSUE TITLE
jsdoc types - jsx children - No overload matches this call. Property 'children' is missing in type. ts(2769)

### ISSUE THREAD

**Issue by milahu** [solidjs/solid#1406]
### Describe the bug

App.jsx

```jsx
import { Show } from 'solid-js';

export default function App() {
  return (
    <Show when={true}>hello</Show>
  )
}
```

type error TS2769 at `Show`

```
No overload matches this call.
    Property 'children' is missing in type X but required in type Y. ts(2769)
```

stupid workaround

```jsx
import { Show } from 'solid-js';

export default function App() {
  return (
    <Show when={true} children={<>hello</>}></Show>
  )
}
```

### Your Example Website or App

https://stackblitz.com/edit/solidjs-templates-56uveg?file=src/App.jsx

### Steps to Reproduce the Bug or Issue

repro does NOT work on stackblitz

jsconfig.json: jsx = preserve, checkJs = true

```json
{
  "compilerOptions": {
    "module": "ESNext",
    "moduleResolution": "Node",
    "target": "ES2020",
    "jsx": "preserve",
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "checkJs": true,
  },
  "exclude": [
    "node_modules",
    "**/node_modules/*"
  ]
}
```

### Expected behavior

no type error

quickfix: make children optional

### Platform

solid-js 1.6.0
vscodium

**Comment by ryansolid** [comment]
Also make sure to set the `"jsxImportSource": "solid-js"` as you might end up with like React types if you aren't careful.

**Comment by milahu** [comment]
> set the `"jsxImportSource": "solid-js"`

yes, that was missing ... thanks!
