### ISSUE TITLE
store's behave unexpectedly when set to an empty object 

### ISSUE THREAD

**Issue by samuelstroschein** [solidjs/solid#1407]
### Describe the bug

Setting a store to an empty object results in no reactive change.

https://user-images.githubusercontent.com/35429197/206544654-29add4ef-9999-49e2-a88e-865785793daa.mov

I am aware that stores should be used for "fine-grained reactivity" but the click on `set store to {}` and `set store to user: undefined` yielded completely unexpected behavior and thus a bug. 

### Your Example Website or App

https://playground.solidjs.com/anonymous/273240de-7c13-473d-95e9-f36d4e0c2ed5

### Steps to Reproduce the Bug or Issue

1. Click on `set store user: samuel`
2. click on `set store to {}`

### Expected behavior

1. works as expected
2. expected "store is {}" to be displayed

### Platform

Solid Playground

### Additional context

Pressing `set store to user: undefined` also leads to unexpected behavior. Setting a variable to `const x = {user: undefined}` does not result in an empty object `{}`. I thought it might be relevant to this issue even though this behavior likely leads to no bugs.

**Comment by sshrshnv** [comment]
It isn't a bug. From docs:

> Objects are always shallowly merged. Set values to undefined to delete them from the Store.

https://www.solidjs.com/docs/latest#updating-stores

**Comment by ryansolid** [comment]
Yeah this is by design. I agree it isn't obvious but it keeps the top level API consistent and allows for it to be easier to batch multiple sets at the same time on the same object fine-grained.

**Comment by samuelstroschein** [comment]
Not good. That seems to make stores unusable if JSON.stringify is involved. 

JSON.stringify does not explicitly set a key to undefined but removes the key entirely. Setting a store from a parsed JSON subsequently breaks reactivity with stores. 

```
console.log(JSON.stringify({ user: undefined }))
>> {}
```

**Any idea to make stores work in JSON.stringify is involved?**

### Usecase

I currently use a store to mirror a key in local storage of a browser window. If the store is set, an effect is triggered that sets a key in local storage with `JSON.stringify`. Vice versa, if a change happens to local storage that is triggered by another window, the key is read from local storage to set the store in the _other window_. 

If one window sets a key (potentially the only key) of an object to undefined, the window where the change has been triggered is updating as expected. But serializing and storing the key in the triggering window leads to all other windows receiving on empty object `{}` that is used to set the store in their corresponding window. The latter subsequently does not trigger any updates.

**Comment by ryansolid** [comment]
You can move it down a key so that the setter instead of doing a merge does a replace. We only shallow merge.

So like
```js
setStore({ keyToBeReplaced: JSON.stringify(something) ])
```
This will actually replace. It's only things directly on the path that merge. So if you nest everything under a key you should be able to do this.
