### ISSUE TITLE
ssr: cannot find module 'path' (tslint)

### ISSUE THREAD

**Issue by thanhdatvo** [solidjs/solid#1415]
### Describe the bug

I try to import path in tsx file to run some logic in backend
But it returned error cannot find module 'path' (tslint)

### Your Example Website or App

https://ryanvocom-mzbphyuqrq-wl.a.run.app

### Steps to Reproduce the Bug or Issue

import path in tsx file

### Expected behavior

error: cannot find module 'path' (tslint)

### Platform

- OS: Linux
- Browser: Firefox

**Comment by lxsmnsyc** [comment]
I would recommend not using tslint anymore as [it is already deprecated and abandoned](https://github.com/palantir/tslint)

**Comment by thanh-vo-opun-ai** [comment]
@lxsmnsyc Sorry, I meant eslint (the one that vscode uses for tsx). 
Just come back to typescript after  5 years and I still think tslint is still being used for tsx.

**Comment by thanh-vo-opun-ai** [comment]
Basically I want to do some task in nodejs with fs and path, in server side, but could not find any example about this and then lint in vscode return error when I write the logic in tsx.
In nextjs I could do call "fs" and "path" in tsx.
I wonder if is there any way to overcome this, i.e create a function to process with fs and path in ts file and import that function to tsx, etc.
Solidjs is really amazing but somehow there are some missing examples/tutorial that make it hard for me to migrate from nextjs to this

**Comment by thanh-vo-opun-ai** [comment]
@ryansolid thanks for your response.
I believe I did. 
I will provide more detail after I come home today.

**Comment by ryansolid** [comment]
This looks like purely a typescript issue. Because SolidStart runs on multiple platforms and we don't default installing `@types/node` in projects. Which is probably why I don't see this issue in the solid-start repo as we have it in devDependencies.

I cloned your repo in stack Blitz and added `@types/node` and that seems to solve it: https://stackblitz.com/edit/github-lagvil?file=src%2Fentry-server.tsx

**Comment by thanh-vo-opun-ai** [comment]
Hi @ryansolid, 
Thank you,
I can now import fs and use it in server side.
But there is another problem related to server only variable
Will close this issue and open a new one!

**Comment by thanh-vo-opun-ai** [comment]
This problem has been resolved.
Please help to close this problem.
