### ISSUE TITLE
ssr - inline arrow function in JSX expression errors 

### ISSUE THREAD

**Issue by LiQuidProQuo** [solidjs/solid#1423]
### Describe the bug

using an arrow function in a JSX expression errors
for "Server side rendering" but not for "Client side rendering"
```
<div>
{() => {
   return "hello";
}}
</div>
```

```
/main.tsx: Property arguments[0] of CallExpression expected node to be of a type ["Expression","SpreadElement","JSXNamespacedName","ArgumentPlaceholder"] but instead got "BlockStatement"
```

### Your Example Website or App

https://playground.solidjs.com/anonymous/5f198028-a47b-4d3c-afb8-c24d45ded3a8

### Steps to Reproduce the Bug or Issue

![image](https://user-images.githubusercontent.com/105608035/207502269-00d9b36f-de6f-4f50-97b5-23b6019ac62f.png)

### Expected behavior

should  work like client rendering mode

### Platform

playground

**Comment by ryansolid** [comment]
Hah.. you find the funniest issues. I don't think there is any reason for this, if it wasn't an IIFE which seems to work.. But no point having it break I suppose so we should fix it even if I don't think there is a use case for this.

**Comment by orenelbaum** [comment]
Seems like this issue should be moved to Dom Expressions?

**Comment by lxsmnsyc** [comment]
> Seems like this issue should be moved to Dom Expressions?

It's fine here, for historical purposes

**Comment by LiQuidProQuo** [comment]
perhaps dom-expression should be moved here?
