### ISSUE TITLE
Abnormal calculated value

### ISSUE THREAD

**Issue by scscms** [solidjs/solid#1424]
### Describe the bug

import { render,effect } from "solid-js/web";
import { createSignal } from "solid-js";

function Counter() {
  const [count, setCount] = createSignal(0);
  const increment = () => setCount(count() + 1);
  setInterval(()=>{
      console.log('xxxx--->',count()) // Why two different values printed here when changed the count value
  },2000)
  effect(()=>{
    console.log(count())
  })
  return (
    <button type="button" onClick={increment}>
    <span>{count()}</span>次
    </button>
  );
}

render(() => <Counter />, document.getElementById("app")!);

### Your Example Website or App

https://playground.solidjs.com/anonymous/3330aa56-7de4-41d7-a472-4c1c7fd888c0

### Steps to Reproduce the Bug or Issue

1.click button
2.look console.log

### Expected behavior

expected print the only last value

### Platform

- OS: Windows10
- Browser: Chrome
- Version: 108.0.5359.124

**Comment by lxsmnsyc** [comment]
I don't see any issues...

**Comment by scscms** [comment]
click buton then print:
xxxx---> 0
xxxx---> 1
........
click again when the count()=2 then print:
xxxx---> 0
xxxx---> 2
xxxx---> 0
xxxx---> 2
........

**Comment by LiQuidProQuo** [comment]
This is a playground problem, every time  you edit the code, it uses the same iframe for output.
without explicit cleanup  you ended up with multiple intervals running for each edit.

1. you can manually `clearInterval` in solid `onCleanup` hook.
https://playground.solidjs.com/anonymous/88f46233-3bc4-416d-b9f2-2062acc6fc04

or just referesh the output, after an edit, to start fresh.
<img src="https://user-images.githubusercontent.com/105608035/207765819-8d609e0b-c05f-44d9-97ca-a6e46a485fa6.png" height=110>

**Comment by lxsmnsyc** [comment]
Well not a playground problem, just a memory leak. The same thing happens if you boot up a Vite app with the same code.

**Comment by LiQuidProQuo** [comment]
playground / hmr

though, the playground could just refresh.

**Comment by arnorhs** [comment]
fwiw you would not see the leaked signal if you use createEffect instead of effect, which i'm actually not familiar with: https://playground.solidjs.com/anonymous/bc37be78-caa1-4cef-892f-57ad0997b331

**Comment by ryansolid** [comment]
Yeah it doesn't really matter which you use `effect` is an alias for createRenderEffect. This is just HMR when you don't clean up. Closing.
