### ISSUE TITLE
[solid-element] custom element is not valid

### ISSUE THREAD

**Issue by Valar103769** [solidjs/solid#1425]
### Describe the bug

i pass the `a` and `arr` prop into `g2-render`, but it not avaliable
# Your Example Website or App

https://stackblitz.com/edit/solidjs-templates-h681is?file=src/MyComponent.tsx

i build a web component and ,i want use it in html and vue
but there not avaliable, can you help me? 

```js
// index.ts
import { customElement } from 'solid-element';
import MyComponent from './MyComponent';

customElement('g2-render', MyComponent);

```

```js
// MyComponent.tsx
import { Component, createEffect, onCleanup, onMount } from 'solid-js';

const MyComponent: Component<any> = (props) => {
  console.log('props', props);

  onMount(() => {
    console.log('onMount');
  });

  return (
    <div>
      {' '}
      MyComponent a:{props.a}- arr: {props.arr}
    </div>
  );
};

export default MyComponent;

```

```html
<!DOCTYPE html>
<html lang="en">
 
  <body>
   
    <script src="https://unpkg.com/vue@3/dist/vue.global.js"></script>

    <script src="/src/index.tsx" type="module"></script>

    // html
    <g2-render a="a" arr="JSON.Stringify([])"></g2-render>

    <script src="https://unpkg.com/vue@3/dist/vue.global.js"></script>

    <div id="app">
      {{ message }}
      <g2-render :a="message" :arr="arr"></g2-render>
    </div>

    <script>
      const { createApp } = Vue;

      createApp({
        data() {
          return {
            message: 'Hello Vue!',
          };
        },
      }).mount('#app');
    </script>
  </body>
</html>

```

### Expected behavior

the console is output and div's content is showen

### Platform

 System:
    OS: macOS 12.5.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 86.89 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
    Watchman: 2022.08.15.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 108.0.5359.98
    Firefox Developer Edition: 105.0
    Safari: 15.6.1

### Additional context

In addition, may I ask how to push to npm?
The steps are,
1. exec npm run build on local,
2. exec npm publish ?

**Comment by LiQuidProQuo** [comment]
vue app, passing/binding props to a solid custom element.

https://stackblitz.com/edit/solidjs-templates-mr7ego

**Comment by Valar103769** [comment]
> vue app, passing/binding props to a solid custom element.
> 
> https://stackblitz.com/edit/solidjs-templates-mr7ego

hi,  
```js
<my-solid-component a="message" :arr.prop="[...arr]"></my-solid-component>

```
what is `.prop` means? i find i must use it, @LiQuidProQuo

**Comment by LiQuidProQuo** [comment]
it forces vue, to bind to the element property ( as opposed to the attributes which you can only pass a string )
