### ISSUE TITLE
passed function prop self subscribes

### ISSUE THREAD

**Issue by illiaChaban** [solidjs/solid#1434]
### Describe the bug

The child component renders <span>{p.prop}</span> where `prop` is a function that returns a number. Somehow solid seems to automatically invoke the function. I'd expect it to just render `[object object]` to the HTML tree since it's not being (explicitely) invoked

### Your Example Website or App

https://playground.solidjs.com/anonymous/0eb59da7-7b62-455d-bec5-28c66a7dac3a

### Steps to Reproduce the Bug or Issue

1. click on the button
2. see the counter update on each click
3. look at console -> it logs that `p.prop` is a function

### Expected behavior

I wouldn't expect to see a number in the HTML tree since `p.prop` is never being invoked

### Platform

- macOS
- Chrom
- whatever the playground version is, it doesn't say

**Comment by lxsmnsyc** [comment]
Solid evaluating functions is by design, and is defined as a valid element.

**Comment by ryansolid** [comment]
Because control flow components need to be able to be dynamic we have to accept functions and unwrap them for insertion.
