### ISSUE TITLE
SSR render issue `!!function()`

### ISSUE THREAD

**Issue by Brendan-csel** [solidjs/solid#1443]
Seeing this behavior when starting from bare template.  Also tried updating to latest versions but same... 
```js
export default function Home() {
  const alwaysFalse = () => false;
  return (<>
    <h4>Inspect data-value on these paragraphs while refreshing the page...</h4>
    <p data-value={alwaysFalse()}>Server correctly renders data-value="false"</p>
    <p data-value={!!alwaysFalse()}>Server incorrectly renders data-value="true" - then updates client-side</p>
  </>
  );
}
```

Suggestion [on discord](https://discord.com/channels/722131463138705510/910635844119982080/1046176484341071932) in might be related to ` !!__vite_ssr_import_2__.escape(alwaysFalse, true), false)` not calling the function

[Repro link on stackblitz](https://stackblitz.com/edit/github-jkdvub?file=src%2Fcomponents%2FCounter.tsx) (thanks liquid)

**Comment by ryansolid** [comment]
Fixed in babel-plugin-jsx-dom-expressions 0.35.9. I will bump versions as well in the next solid release. But blowing out lock file should work now.
