### ISSUE TITLE
solid-js/html gives error when parsing a string to html

### ISSUE THREAD

**Issue by Tetrax-10** [solidjs/solid#1445]
### Describe the bug

```js
let output = "<div>Hi</div>"
let node = html`${output}`
console.log(node)
```

### Your Example Website or App

https://playground.solidjs.com/anonymous/6676001d-44fa-49c1-ba87-10940b4510c5

### Steps to Reproduce the Bug or Issue

go to that playground link and run the code

### Expected behavior

it should print a node like this
![image](https://user-images.githubusercontent.com/75513645/209467911-9402bfda-99e5-4bd0-b5d6-8200313d1778.png)

### Screenshots or Videos

Got this error
![image](https://user-images.githubusercontent.com/75513645/209467915-fdd83c4d-6ccc-4759-8b6a-1eb6fe49168d.png)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by orenelbaum** [comment]
It's not a bug, it's how tagged template literals work.
This:
```js
let output = "<div>Hi</div>"
let node = html`${output}`
```
is not equivalent to this:
```js
let node = html`<div>Hi</div>`
```

**Comment by Tetrax-10** [comment]
Then how do i make this work, is there any method that allows a variable as a input?
```js
let output = "<div>Hi</div>"
let node = html`${output}`
```

**Comment by orenelbaum** [comment]
You should look at how tagged template literals work.
The gist of it is that if you have a static template like in your example, you can do:
```js
let output = "<div>Hi</div>"
let node = html([output])
```
But if you try to do something dynamic like this
```js
const [count, setCount] = createSignal(0)
let output = `<div>${() => count()}</div>`
```
This won't work, `output` will be a string containing the stringified version of the function and not something you can work with.
If you want to work with this kind of syntax, it can't exist without a tag function.
You can achieve the same thing with a different syntax by doing
```js
let node = html(['<div>', '</div>'], () => count())
```
Which is equivalent to
```js
let node = html`<div>${() => count()}</div>`
```

**Comment by Tetrax-10** [comment]
That work thx 😍
