### ISSUE TITLE
`splitProps` is broken in 1.6.6

### ISSUE THREAD

**Issue by juanrgm** [solidjs/solid#1446]
### Describe the bug

`splitProps` returns undefined properties in SolidJS v1.6.6 (https://stackblitz.com/edit/angular-aejisc-h1nlkh?file=src%2FApp.tsx).

The same example it works in SolidJS v1.6.5 (https://stackblitz.com/edit/angular-aejisc-czn2cd?file=src%2FApp.tsx).

### Your Example Website or App

https://stackblitz.com/edit/angular-aejisc-h1nlkh?file=src%2FApp.tsx

### Steps to Reproduce the Bug or Issue

```ts
import { mergeProps, splitProps } from 'solid-js';

export default function App() {
  const inProps: { a?: any; b?: any } = mergeProps(() => ({}));
  const [props] = splitProps(inProps, ['a', 'b']);
  const keys = Object.keys(props);
  return <div>{JSON.stringify(keys)}</div>;
}
```

renders

`['a', 'b']`

### Expected behavior

`[]`

### Platform

- OS: Windows
- Browser: Chrome 108

**Comment by orenelbaum** [comment]
I think that the only way to solve this is by turning `splitProps` into a proxy
