### ISSUE TITLE
SSR: Cannot read properties of undefined (reading 'cloneNode') because getNextElement() is called without arguments

### ISSUE THREAD

**Issue by krymel** [solidjs/solid#1448]
### Describe the bug

Hi,

I'm working on getting SSR and hydration to work... I'm not using `solid-start` because I have my own simple project for doing SSG only and for learning purposes. I started over and over again with like 4 to 5 attempts but always end up with the same error and now I think it's less likely that it's only me doing something wrong here...? 

What I actually do is building and bundling code using `esbuild`, and of course with a Babel approach using `esbuild-plugin-solid` to make sure the JSX and SSR/DOM code generation works correctly...  (the dependency uses standard solid babel transform under the hood, see: https://github.com/amoutonbrady/esbuild-plugin-solid/blob/master/src/plugin.ts#L5)

For the server code bundle I have something like this:

```ts
import { build } from 'esbuild'
import { solidPlugin } from 'esbuild-plugin-solid'

// shortened and simplified
await build({
    bundle: true,
    format: 'esm',
    platform: 'node',
    // basePlugins has some more plugins for handling importing .css files etc., nothing that would deal with js/ts stuff
    plugins: [solidPlugin({ generate: 'ssr', hydratable: true }), ...basePlugins],
  })
```

For the client I build another code bundle:
```ts
// shortened and simplified
await build({
    bundle: true,
    platform: 'browser',
    plugins: [solidPlugin({ generate: 'dom', hydratable: true }), ...basePlugins],
    format: 'iife',
  })
```

On the server I use the server code bundle and after executing the code below in a `vm` context:

<img width="433" alt="Bildschirmfoto 2022-12-26 um 18 30 17" src="https://user-images.githubusercontent.com/87694/209572138-0f59eabc-d463-472d-8dbb-cd4304c58619.png">

Please note: The `render()` function here is not Solid's render function. It is my own runtime `render()` function that, when executed on server side, calls `renderToString()` and on the client a different runtime impl. is executed and calls Solid's `hydrate()`. 

`PageScript` is executed on server-side and injects the client-side code bundle (this is executed on server side) by returning a <script> tag pointing to that:

<img width="632" alt="Bildschirmfoto 2022-12-26 um 18 36 51" src="https://user-images.githubusercontent.com/87694/209572193-1cb15871-37ce-4100-bd23-becca554cc28.png">

You can see the result of this down below in the generated HTML code.
SSR (`renderToString()`) works well, the HTML code generated is served, see below:

<img width="1251" alt="Bildschirmfoto 2022-12-26 um 18 28 12" src="https://user-images.githubusercontent.com/87694/209572084-9974142b-50a8-4644-87a7-217f45ca3210.png">

I was double-checking my code several times and checking against `solid-ssr` examples. I cannot find any big difference, except that I'm not using rollup, but esbuild -- still the same Babel transform is used behind the scenes as part of `esbuild-plugin-solid`...

But then, on the client when my runtime calls,`hydrate(fn, document)` I always, whatever I do since months, run into:

```
index.ssg.js:1814 Uncaught TypeError: Cannot read properties of undefined (reading 'cloneNode')
    at getNextElement (index.ssg.js:1814:24)
    at index.ssg.js:1997:19
    at index.ssg.js:2003:5
    at index.ssg.js:679:58
    at updateFn (index.ssg.js:49:42)
    at runUpdates2 (index.ssg.js:373:21)
    at createRoot2 (index.ssg.js:53:16)
    at render2 (index.ssg.js:677:7)
    at hydrate$1 (index.ssg.js:823:23)
    at hydrate (index.ssg.js:1060:14)
 ```
    
 And of course this is undefined because Solid generates the following, broken code:
       
 ```ts
  // examples/homepage/src/pages/index.ssg.tsx
  var _tmpl$ = /* @__PURE__ */ template(`<div>foobar</div>`, 2);
  var _tmpl$2 = /* @__PURE__ */ template(`<script>console.log('test1')<\/script>`, 2);
  var Body = () => [getNextElement(_tmpl$), getNextElement(_tmpl$2)];
  var index_ssg_default = render(() => (() => {
    const _el$3 = getNextElement(), _el$8 = getNextMatch(_el$3.firstChild, "body"), _el$9 = _el$8.nextSibling, [_el$10, _co$2] = getNextMarker(_el$9.nextSibling), _el$11 = _el$10.nextSibling, [_el$12, _co$3] = getNextMarker(_el$11.nextSibling);
    createComponent(NoHydration, {});
    insert(_el$8, createComponent(Body, {}));
    insert(_el$3, createComponent(PageScript, {}), _el$10, _co$2);
    insert(_el$3, createComponent(LiveReload, {}), _el$12, _co$3);
    return _el$3;
  })());
 ```
 
 Broken, because `getNextElement()` always expects the first argument `template2` not to be undefined... but it's generated that way for `_el$3`.

```ts
function getNextElement(template2) {
    let node, key;
    if (!sharedConfig.context || !(node = sharedConfig.registry.get(key = getHydrationKey()))) {
      return template2.cloneNode(true); // <== error happens in this line, template2 is undefined, see below
    }
    if (sharedConfig.completed)
      sharedConfig.completed.add(node);
    sharedConfig.registry.delete(key);
    return node;
  }
``` 

I mean, this is more or less the most basic SSR example you can make.. idk, what I'm doing wrong here since months but I'm just lost and the generated code looks wrongs, so I guess opening a bug ticket is justified.

Please advice what I did wrong. I was following all the guides, read the code of the examples, the code of `solid-ssr` and also `solid-start` and couldn't find a cure for this.

@ryansolid Is it maybe, that one cannot rehydrate the whole document from `<html>` down but only form a specific DOM tree node such as inside of `<body>`?

Thanks and best!

### Your Example Website or App

https://codesandbox.io/s/flamboyant-sanne-duh3u3?file=/pages/index.ssg.js:63544-63584

### Steps to Reproduce the Bug or Issue

Just visit the StackBlitz and enjoy :)

### Expected behavior

Solid would generate code with doesn't break itself on `hydrate()` and that there would be some very simple example maybe for engineers to just realize what they are doing wrong just in case.

### Platform

- All browsers, all OS

### Additional context

`solid-js@1.6.6`
"esbuild": "^0.15.15",
"esbuild-plugin-solid": "^0.4.2", 

I also tried different versions of Solid, but nothing helps.

**Comment by ryansolid** [comment]
I haven't had a chance to look at this yet, but some perhaps useful info in the meantime. Certain templates can't be cloned anyway. Like ones that contain `<html>` so compiled code looks mostly correct to me. It should never be cloned in its whole lifetime because it should only be hit once, during hydration and it should match on hydration IDs. This mismatch is the source of the problem, but I will need to look why it is off.

**Comment by krymel** [comment]
Thank you Ryan, for having had a look at it so quickly. My idea was that the whole document would be generated by Solid on server side dynamically and rehydrated on client side 1:1, but it makes sense that it's problematic when the rehydration algo tries to clone unique elements like `<html>` and `<body>`. I'll try to see if I can get around that issue by separating the process of HTML code production on my side... first step would be generating a non-hydratable HTML document on server-side then inside of `<body>` I'd string-interpolate the result of the 2nd step hydratable SSG code generation run and append the client side code bundle just as before. That way there will be only be one top-level component inside `<body>` that is to rehydrate. That's not exactly optimal for my use case as it makes things more complicated, introduces overhead etc., but maybe I get it working this way. I'll give it a try and let you know asap

**Comment by krymel** [comment]
So I tried to generate `<html><head>...</head><body></body></html>` etc. on server side using an extra code build that has a configuration like this:

```ts
await build({
    entryPoints: [join(templatePathParsed.dir, '_document.tsx')],
    plugins: [solidPlugin({ generate: 'ssr', hydratable: false }), ...basePlugins],
  })
``` 

The call goes thru but then, for whatever reason `sharedConfig.context` is undefined:

```ts
function NoHydration(props) {
  sharedConfig.context.noHydrate = true; // <== error here
  return props.children;
}
```

```
Cannot set properties of undefined (setting 'noHydrate')
        at NoHydration (vm:module(0):484:34)
        at createComponent (vm:module(0):99:10)
        at Document (vm:module(0):567:17)
        at createComponent (vm:module(0):99:10)
```

The only thing I did was trying to render this: 

```tsx
export interface DocumentProps {
  Page: Function;
}

const Document = (props: DocumentProps) => {
  <html>
    <head>
      <title>Homepage1</title>
      <Hydrate />
    </head>
    <body>
      <props.Page />
    </body>
    <PageScript />
    <LiveReload />
  </html>
}
export default Document
```

The idea was that I'd pass `Page` as the page component via `vm`... the generated code by Solid is:

```js
// examples/homepage/src/pages/_document.tsx
var _tmpl$3 = ["<head><title>Homepage1</title>", "</head>"];
var _tmpl$23 = ["<html>", "<body>", "</body>", "", "</html>"];
var Document = (props) => {
  ssr(_tmpl$23, createComponent(NoHydration, {
    get children() {
      return ssr(_tmpl$3, escape(createComponent(Hydrate, {})));
    }
  }), escape(createComponent(props.Page, {})), escape(createComponent(PageScript, {})), escape(createComponent(LiveReload, {})));
}
```

I don't understand where `sharedConfig.context` would need to be initialized as it is clearly not initialized by the time `renderToString()` is called on `Document`.

@ryansolid  Unfortunately, I'm stuck again..  :/ I could hack some initialization code in but it feels weird?

**Comment by krymel** [comment]
I think I'll isolate both issues now into simple code examples that can be reproduced. I've seen that context issue before in a different situation and have been stuck there too; I think it was when using solid-start. Maybe I'm doing something fundamentally wrong but I really cannot see any stupid thing I'm doing here..

**Comment by krymel** [comment]
I did isolate the issue...

https://codesandbox.io/p/github/krymel/solid-ssrissues/draft/recursing-banach?file=%2Fscripts%2Fbuild.ts&selection=%5B%7B%22endColumn%22%3A1%2C%22endLineNumber%22%3A67%2C%22startColumn%22%3A1%2C%22startLineNumber%22%3A66%7D%5D

Repo is here:
https://github.com/krymel/solid-ssrissues

Really feels broken to me. It isn't able to render the very simple `_document.tsx` without that undefined error. 
I thought that maybe it's an outdated dependency, that's why I moved the few lines of the esbuild plugin into the project and directly call the up-to-date `babel-plugin-solid` for the transform in case that might have triggered the issue... but yeah, it's exactly the same broken behaviour as always.

**Comment by ryansolid** [comment]
Ok looking at the very first example there are 2 copies of Solid being pulled in which would mess everything up. I'm gathering the same is happening still because I see solid code in dist, but your build script is also importing solid code from a different location. It needs to set it as external or put `renderToString` in the built part.

**Comment by krymel** [comment]
Sorry for the noise. You're right. I've came up with a fully working example now. The demo is here:

   https://codesandbox.io/p/github/krymel/solid-ssg-esbuild/draft/laughing-sun

   https://iordm1-3000.preview.csb.app/
   
 Maybe it helps someone else who is stuggling with esbuild only approach:
   
   https://github.com/krymel/solid-ssg-esbuild
   
 Sorry, and thank you for your time!

**Comment by krymel** [comment]
@ryansolid First interesting find... the [solid-ssg-esbuild](https://github.com/krymel/solid-ssg-esbuild) repo works, although it has duplicate solid dependency bundled in. Now adding an esbuild deduplication plugin leads to an interesting behaviour. There is no error but all the hydration state doesn't end up in the serialized DOM leading to the initial signal state not being present but the click event working fine. Researching it further I found this explanation https://github.com/evanw/esbuild/issues/1038#issuecomment-805263902  and it seems like having the dependency twice bundled in is correct. Anyway, I'll now continue to debug why and where exactly the hydration state gets lost in translation.. a good lesson for understanding the implementation better..

**Comment by krymel** [comment]
@ryansolid So, I tried again, with the deduplication of the library. It is now definitely only included once. I changed the code back to the original example where the error happend that I've reported. The error reappeared: 

https://codesandbox.io/p/github/krymel/solid-ssg-esbuild/main

Live demo: https://n7cyd2-3000.preview.csb.app/

**Comment by krymel** [comment]
The only workaround that I found working for the moment is to bundle and render a document template separately with hydration disabled, then render a page (body content) template separately, with hydration enabled, bundle this single page template as client js too, deliver it and hydrate. The client js then has the solid js code double because of esbuild bundling strategy, deduplication leads to he error I talked about before (initial state not correctly rendered).

**Comment by ryansolid** [comment]
I see. Bundling the client twice is definitely an issue for Solid because reactivity works off a singleton as does the server context we use during SSR. I was hoping that was all it is. Now we are more likely dealing with a hydration mismatch. The ids start from the mount point. So as long as the server and client mount from the same element and render the same stuff we should be a match.

**Comment by krymel** [comment]
Thank you for your quick reply. 

Yes, this makes sense, but in the latest code, there is no splitting at all. The `index.tsx` is just one big template and the original error happens (the cloneNode error). The older commit I linked has the different templates implemented - and there it generally works, but only if I have the code bundled in double. 

It's a bit confusing - I hope I didn't overcomplicate my comments, sorry for that :)

**Comment by ryansolid** [comment]
> https://codesandbox.io/p/github/krymel/solid-ssg-esbuild/main
> Live demo: https://n7cyd2-3000.preview.csb.app/

This one is atleast easy for me to spot the problem. It's rendering from the HTML tag and trying to hydrate from the body so there is a mismatch because it doesn't find the template (starts at the HTML tag which is outside of the body). Change it to hydrate from the `document`.

**Comment by krymel** [comment]
Ah yeah, I forgot to change that after changing the template rendering. The mismatch is fixed now and the initial `0` shows, but the original error remains the same.

Happy new year btw!! :) Hope you'll have a wonderful new year. Wish you much luck, health and success!

**Comment by ryansolid** [comment]
Ok looking at this I've found a few things. 

1. For some reason while the code is updated the code running in the browser still isn't updated. I'm seeing it trying to hydrate the body. Maybe the build is cached or something. 
2. `context.pageClientScriptPath` is undefined .. context is undefined which causes a can't access `pageClientScriptPath` of undefined error. I'm gathering this is intended to be server only but it gets hydrated. Now arguably I can fix this with Solid to only do whats in the body. I hadn't considered this case because a script tag isn't allowed to be in the body. Which brings me to:
3. The final script tag is outside of the body. The browser corrects it to be inside but it messes with things a bit since the JSX walker is looking for it in the original location and finds null instead which provides a 3rd error.

When I correct all three of these things the page hydrates.

**Comment by krymel** [comment]
Hmm, ok, interesting. 

1. How do you mean "the code is not updated"? Do you mean `index-client.js`'s line `3493` in which the generated code states: ```js
const _el$ = getNextElement(), _el$6 = getNextMatch(_el$.firstChild, "body"), _el$7 = _el$6.firstChild, _el$8 = _el$7.nextSibling, _el$9 = _el$8.nextSibling, _el$10 = _el$9.firstChild, _el$11 = _el$10.nextSibling, [_el$12, _co$2] = getNextMarker(_el$11.nextSibling), _el$13 = _el$9.nextSibling, _el$14 = _el$13.nextSibling;
``` ?  

2. That's interesting too. I was running into that `undefined` before but then I added the `define` config option in the browser build to set the `context`. I did that and pushed my code to the repo before I added my previous comment. Just to be sure: Are we on the same (most recent) commit of https://github.com/krymel/solid-ssg-esbuild? 

On`esbuild` then transforms the `context` access into `define_context_default.pageClientScriptPath` in line `3497` of `index-client.js` and `define_context_default` is defined as 
```js
// <define:context>
  var define_context_default;
  var init_define_context = __esm({
    "<define:context>"() {
      define_context_default = { pageClientScriptPath: "index-client.js" };
    }
  });
``` before in line `11`.

How did you get an undefined value on `context.pageClientScriptPath`? In Node.js server runtime it is defined in line `42` in `lib/vm.ts`. I couldn't reproduce the undefined `pageClientScriptPath`. 

3. Yeah, here I used the `<script>` out of `<body>` just because the example in `solid-ssr` did it that way. I'm aware that the browser would move that in `<body>` but I thought that maybe there is some special requirement to put that `<script>` at that specific place. I moved it in `<body>` now but it doesn't seem to alter the situation.

> When I correct all three of these things the page hydrates.

Okay, cool, do you mean including changes to the solid codebase or just by fixing "user errors" on my side? Do you maybe have any code that you could share with me to get it running or a hint to where I could check in the solid codebase to tinker with a custom solid fork/build to make the changes necessary? I have some time and would love to work on that and PR, but I'm not a native english speaker, so I might have misunderstood the context of this.

Thanks a lot in advance.

**Comment by ryansolid** [comment]
I just meant fixing user stuff on your side. I was doing everything in the browser in codesandbox I modified the variable values while it was running to swap the element, set the context, and populate _el$13 (which was the one screwed up by the script tag in the body) and everything was good.

Looking at the codesandbox again now that it is updated we are back at two copies of Solid. There is a `getNextElement` and `getNextElement2` which is why they aren't seeing each other as one is being used in your hydrate call and the other injected by the compiler.

**Comment by krymel** [comment]
Oh, amazing! Well, thank you! It works pretty well now. I also updated the repo and sandbox. Cool.

I also think, ending up with 10KiB gzipped JS per page is pretty fine for me for now. Of course, there is always room for optimization but this is already pretty decent for my taste. I also find the simplicity of this solution (after the initial maze) quite attractive.

Well, in the end, the "bug" is not a really bug I guess, right? I hope that this was still interesting and productive in some sense. I also feel like I asked for quite a bunch of your valuable time and I'd like to give back a bit if easily possible. Is there a way for individuals to donate to you directly?

 Thanks a lot and best :)

**Comment by ryansolid** [comment]
I did end up mocking hydrate so with 1.6.7 onward you don't need to lazily import it to work.

Glad you are set now.

**Comment by krymel** [comment]
@ryansolid Great, thank you! While building upon the solution crafted here, I btw found out that you can activate dead code elimination for `isServer` as well. It requires to add the following subset of properties to `build`: 

```ts
import { build } from "esbuild"
build({
    ...restOfYourConfig,
    bundle: true,
    // activate aggressive AST-level optimizations
    minifySyntax: true,
    // define the variable top-level
    define: {
        "isServer": JSON.stringify(false)
    },
})
```

It also wipes `isServer` from the output (the top-level `isServer` won't even be defined in compile output).

And thanks to `solid@1.6.7`, the bundled (all-in) size with all optimization  applied and gzipped now is `4.59 KiB` and I didn't run terser or closure compiler on it, which would lead to some more 3-5% reduction in size.

This is amazing. Thank you!
