### ISSUE TITLE
`batch` and `runWithOwner` messes with catching errors by ErrorBoundary

### ISSUE THREAD

**Issue by thetarnav** [solidjs/solid#1452]
### Describe the bug

If throwing an error in an async callback, one needs to wrap it in `runWithOwner` so that `ErrorBoundary` is able to catch it. But when it happens inside `batch` as well, the error isn't getting caught.
Not only that, but since solid's primitives were used, it beaks solid execution as well instead of just letting the callback fail.
```ts
batch(() => runWithOwner(owner, () => {
  throw new Error("Batch and Throw in owner");
}))
```

This is possible because `runUpdates` has a code branch where `fn` is executed without being wrapped in `try catch`.

![image](https://user-images.githubusercontent.com/24491503/210089670-dcaf5da5-45a6-4bf6-a116-7327feff2155.png)

### Your Example Website or App

https://playground.solidjs.com/anonymous/18342ebe-bceb-48bc-8a98-cbe56b115f0d

### Expected behavior

Clicking any of the buttons (besides the last one) should result in an error being caught by ErrorBoundary, and the app would be able to continue functioning properly without freezing.

**Comment by ryansolid** [comment]
Hmm the better question is why Updates is not `null` at this time. The reason it isn't in a try block is that there should be something above it in a try block if Updates is defined. Something else is wrong.
