### ISSUE TITLE
Input loses focus when updated inside a `For` component

### ISSUE THREAD

**Issue by aminnairi** [solidjs/solid#1468]
### Describe the bug

When rendering multiple inputs that come from a signal inside a `For` component, and when updating one single input, pressing a key make the input lose focus, and thus only allow one single character at a time, forcing the user to manually focus the input again for subsequent inputs.

### Your Example Website or App

https://playground.solidjs.com/anonymous/cbaeccbb-4446-4b35-be10-e19aa27a0797

### Steps to Reproduce the Bug or Issue

1. Go to https://playground.solidjs.com/anonymous/cbaeccbb-4446-4b35-be10-e19aa27a0797
2. Fill in a text in the input text field
3. Click add
4. Try updating the created input
5. See that the focus is lost after hitting only one character

### Expected behavior

The input should not lose focus.

### Platform

- OS: [e.g. macOS, Windows, Linux] Arch Linux
- Browser: [e.g. Chrome, Safari, Firefox] Chromium
- Version: [e.g. 91.1] 108.0.5359.124 (Official Build) Arch Linux (64-bit)

### Additional context

This has been tested both on a computer and on the Solidjs Playground.

**Comment by ryansolid** [comment]
Solid's For component works off referential equality. So cloning the mutated object causes it to be recreated. The recommended approach is to use nested reactivity. Stores in particular. If you want to understand this behavior better we cover precisely this scenario is the tutorial in "Nested Reactivity" and "Create Store":

https://www.solidjs.com/tutorial/stores_nested_reactivity

**Comment by aminnairi** [comment]
Thank you for your quick response!

Indeed, I skipped this part of the tutorial (and probably many more interesting ones).

I managed to use nested reactivity to achieve what I was aiming to do thanks to the link you provided.

Here is the corrected example for the record:

https://playground.solidjs.com/anonymous/904c8aec-7fd4-442e-a6d7-690a06fa7f9c
