### ISSUE TITLE
`render` taking a component works in dev and fails in build

### ISSUE THREAD

**Issue by bigmistqke** [solidjs/solid#1471]
### Describe the bug

`render(<App />, document.getElementById("root"))` works in dev-mode and fails when build. 
It gives a type-error in dev, and I can not reproduce it in the playground, but it works with a blank project on my computer.

### Your Example Website or App

[codesandbox](https://codesandbox.io/s/solidjs-counter-forked-00d61y?file=/src/main.tsx)

### Steps to Reproduce the Bug or Issue

1.  `npx degit solidjs/templates/ts`
2.  replace `render(() => <App />, document.getElementById("root"))` with `render(<App />, document.getElementById("root"))`
3. `npm run dev ` &#8594; works
4. `npm run serve` &#8594; does not work

### Expected behavior

as a user I expect there to be no difference between `dev` and `serve`

### Platform

- macOS
- firefox
- 108.0.2

**Comment by ryansolid** [comment]
In general, HMR prevents us from having Dev and Prod being the same. You can turn it off in Dev(`hot: false) and it will get you the same error. For HMR to work we need extra wrappers. And this can change the behavior, especially in a case like this where a wrapper is missing (top-level).

TypeScript does complain as far as I can see:
> Argument of type 'Element' is not assignable to parameter of type '() => Element'.

I don't see much to do about this one.

**Comment by bigmistqke** [comment]
Mm, I see. so iiuc HMR wraps whatever is inside the render-function with another function that is being triggered once a file is saved, something like this? Couldn't the HMR-wrapper check if what it is receiving is a function or not, if necessary only give a `console.error` saying that you haven't passed in a function?

The original context of discovering this bug was a port of a react-project that was initially just written in js, in react you apparently can do `ReactDOM.render(<App/>)`, so the error was only showing up in build.
