### ISSUE TITLE
SyntaxError: The requested module 'solid-js/web' does not provide an export named 'SVGElements'

### ISSUE THREAD

**Issue by Jackie1210** [solidjs/solid#1480]
### Describe the bug

I was build a lib with `@mdx-js/mdx`. When i run `pnpm test` it cause following error

```bash
node:79444) ExperimentalWarning: VM Modules is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
 FAIL  tests/component.spec.tsx
  ● Test suite failed to run

    SyntaxError: The requested module 'solid-js/web' does not provide an export named 'SVGElements'
```

### Your Example Website or App

https://github.com/Jackie1210/smdx

### Steps to Reproduce the Bug or Issue

1. `pnpm install`
2. `pnpm test`

### Expected behavior

tests passed

### Platform

- OS: [macOS]

**Comment by ryansolid** [comment]
If I had to guess without looking this is a server vs client issue. Where the pulled in code is the server code but it's building client output.  We do export SVGElements from our client build as far as I can see. And it looks from the package JSON the libraries are mostly up to date. So that would be my guess.

**Comment by Jackie1210** [comment]
My tests is in **server** enviroment. This error occured because i needed `jsx-runtime` from `solid-js/h` as params of function `evaluate` I built this source code of solid-js, add it did not export `SVGElements` in `solid-js/web` pkg, which only export from `dom-expression/client` in client mode.

I found [#855 ](https://github.com/solidjs/solid/discussions/855) which has the same issue since 1.3.7, it there any chance this issue can be fixed?

**Comment by ryansolid** [comment]
`solid-js/h` is client only. It doesn't work on a server. Or at least on a server you don't want to use server build as our `h` function generates DOM elements. So you could run it on a server with JSDOM or similar but then it would be the client build you want.

**Comment by ryansolid** [comment]
I have been trying to figure out what expectation is here. solid-js/h and server build are not compatible. `h` actually produces DOM nodes. I am not even certain I can get a string-rendered compatible version of h working, along with a hydration-capable version as well. It's a ton of work and it might not pan out.

Basically fixing this error will just lead you to the next one.

If you want to use Solid JSX on the server use our transform `babel-preset-solid`.

**Comment by Jackie1210** [comment]
@ryansolid Thanks for your time. I will try client mode instead.
