### ISSUE TITLE
Resource doesn't refetch when store property changes

### ISSUE THREAD

**Issue by spiffytech** [solidjs/solid#1486]
### Describe the bug

I've created a resource that uses a field from a store as its input signal. When the field is updated, the resource doesn't refetch.

If I wrap the store field in a memo and pass _that_ to the resource, it works correctly.

### Your Example Website or App

https://playground.solidjs.com/anonymous/91cf0e0b-76dc-4d7d-a37f-7c9cb40587f0

### Steps to Reproduce the Bug or Issue

1. Create a store holding an object. Mine has an array property.
2. Create a resource that uses that store field as its signal
3. Update the store
4. Resource does not refetch

### Expected behavior

Resource reacts to the updated store property and refetches

### Platform

- OS: Fedora Linux
- Browser: Brave
- Version: Version 1.47.171 Chromium: 109.0.5414.87 (Official Build) (64-bit)

**Comment by ryansolid** [comment]
You can also just wrap it in a function:
```js
const [r1, { refetch }] = createResource(() => store.foo, () => {
    console.log("Resource1 fetching");
    return new Date();
  });
```
The property access is what reactively tracks. So it needs to be wrapped in a function for it to be reactive. Same with sing props here.

**Comment by spiffytech** [comment]
Ah, that makes sense.

Any chance of getting a TypeScript error when providing a store property as the resource signal? It feels unintuitive and footgun-y for that to not work, since store properties are reactive everywhere else.

I submitted [a docs PR](https://github.com/solidjs/solid-docs/pull/225) for this.

**Comment by ryansolid** [comment]
Yeah I mean we could but it would also be inaccurate. Also props are a consideration and they don't have types we could rely on. Like it is viable to pass in non-functions. Maybe that is too loose. I do think as you made the PR it is worth a note there. So thank you.
