### ISSUE TITLE
UI disappears + hydration warnings, with nested components and spreading props

### ISSUE THREAD

**Issue by soorria** [solidjs/solid#1492]
### Describe the bug

On initial page load, nested children disappear and a hydration warning occurs when (all) props are spread, there's 1+ "non-spread" props and `props.children` is used. UI also happens in a prod build (but no hydration warning in console).

Possibly related to #1485

### Your Example Website or App

https://stackblitz.com/github/soorria/solid-broken-hydration?file=src%2Froutes%2Findex.tsx

### Steps to Reproduce the Bug or Issue

1. Run `npm run dev`
2. Visit the index route, and the page will show `TEXT` for a bit before it disappears.

### Expected behavior

UI should not disappear, and there shouldn't be a hydration warning.

### Platform

- OS: MacOS on M1
- Browser: Brave
- Versions: 
	- Brave Chromium: 108.0.5359.128
	- solid-js: 1.6.9
	- solid-start: 0.2.16

### Additional context

Obvious workaround is to not spread _all_ props, and remove children with `splitProps`, but this seems like a bug anyway.

**Comment by ryansolid** [comment]
Yeah I was positive I had fixed this but I clearly have not. Thanks for reporting this.
