### ISSUE TITLE
Exception thrown in batch() after await inside createEffect leaves the app unresponsive.

### ISSUE THREAD

**Issue by orestisiam** [solidjs/solid#1498]
### Describe the bug

Similar to #1452, but now inside a createEffect. When we have a batch() call which throws an exception after an await, then the app remains unresponsive. This happens with or without the batch call being wrapped inside runWithOwner. The same code without batch() runs fine.

### Your Example Website or App

https://playground.solidjs.com/anonymous/5266c783-a247-411e-a39a-b12be0c1e16d

### Steps to Reproduce the Bug or Issue

1. Click on the button. The button count becomes '1' and the message gets updated to 'Dummy error runWithOwnerOnly'
2. Click on the button again. The button count becomes '2'  but the message is not updated.
3. The app is now unresponsive

### Expected behavior

Since the exception is handled, I would expect the app to continue responding to click events and state updates.

### Platform

- OS: Windows
- Browser: Chrome
- Version:  109.0.5414.75

**Comment by mdynnl** [comment]
minimal repro https://playground.solidjs.com/anonymous/a08c9e79-72ec-4110-9323-b29b90e5c688

batch isn't cleaning up `Updates` handling error
