### ISSUE TITLE
Dynamic component not pass props to children

### ISSUE THREAD

**Issue by ar53n** [solidjs/solid#1517]
### Describe the bug

Dynamic component not pass someProps to `props.children`

### Your Example Website or App

https://codesandbox.io/p/sandbox/infallible-fog-bmgnez?file=%2Fsrc%2FDropdown.jsx&selection=%5B%7B%22endColumn%22%3A29%2C%22endLineNumber%22%3A10%2C%22startColumn%22%3A29%2C%22startLineNumber%22%3A10%7D%5D

### Steps to Reproduce the Bug or Issue

1. We have two button
2. Add second button through Dynamic component and add `variant="outline"` in Dropdown.jsx
3. Fail! We don't see `variant="outline"` Button

### Expected behavior

As a user, I expected merge props to Button component in Dropdown component with Dynamic component and see Outline Button  

### Platform

- OS: macOS
- Browser: Chrome
- Version: 109
- Solidjs: 1.6.10

**Comment by thetarnav** [comment]
This is not what `<Dynamic>` component is for. It executes component function provided to the `component` prop, or creates an element if an element name is provided instead. It does not apply its props to a provided component that is already rendered.
If you log in your example what `c()` is, you'll see that it is a button element and not a component that could take props.
```ts
const c = children(() => props.children);

createEffect(() => {
  console.log(c()) // HTMLButtonElement
})
```
If I did this in your example, the props where passed properly. Although it needs to be structured a little better.
```ts
<Dropdown>
  {(props: any) => <Button {...props}>Learn Solid OUtline</Button>}
</Dropdown>

// in Dropdown
<Dynamic
  component={props.children} // children prop will be the function passed as children
  variant="outline"
/>
```
["fixed" example](https://codesandbox.io/p/sandbox/reverent-carlos-5b3vpd?file=%2Fsrc%2FApp.tsx&selection=%5B%7B%22endColumn%22%3A31%2C%22endLineNumber%22%3A5%2C%22startColumn%22%3A31%2C%22startLineNumber%22%3A5%7D%5D)

**Comment by ryansolid** [comment]
Yeah this is an interesting use case I've thought about. What if we could augment already rendered elements this way but it isn't how Dynamic works. I'm going to mark this as by design and close. But it is interesting.

**Comment by ar53n** [comment]
@thetarnav Thank you its really good solution.

@ryansolid hi Ryan, my main goal was to merge the property into children component and thought Dynamic component can help me, but if have any design solutions its will be good. Thank you

**Comment by ryansolid** [comment]
The challenge here is we don't really have component instances. We have the function that gets run and what that function returns, DOM elements. Our components are just functions that run once. Meaning they basically disappear at runtime.

**Comment by thetarnav** [comment]
btw if you want to use my solution, or something similar, you don't have to use Dynamic at all as the function in `props.children` likely won't change.
```tsx
<Dropdown>
  {(props: any) => <Button {...props}>Learn Solid OUtline</Button>}
</Dropdown>

// in Dropdown
const Child = props.children
return <Child variant="outline" />

// or
return props.children({ variant: "outline" })
```
