### ISSUE TITLE
Please add a docs section from people coming from React

### ISSUE THREAD

**Issue by leventdeniz** [solidjs/solid#1521]
### Describe the bug

I just spend way too much time with interactive state/children. I created signals, stores, mutables, mapArrays, just to find out my only issue was `const Component = ({ i, love, destructuring }) => ...` instead of `const Component = (props) => ...`.
`const Component = (props) =>  { const { i, love, destructuring} = props; ...}` also did not work.

It was painful. And the only place I found out about it was in a paragraph of a tutorial. Where I instead was looking for infos was the docs/API page.

Is there a way, a section for React devs trying Solid could be added?
It could contain things like 
```
! careful when destructuring props ! 
You may be used to this:
const UserGreeting = ({ firstName, lastName }) => (
  <div>Hello {firstName} {lastName}</div>
)
or
const UserGreeting = (props) => {
const { firstName, lastName } = props;
return (
  <div>Hello {firstName} {lastName}</div>
)}
and 
<ul>
{users.map(user => <UserGreeting {...user} />)}
</ul>

Instead  do this:
const UserGreeting = (props) => {
return (
  <div>Hello {props.firstName} {props.lastName}</div>
)}
<ul>
{users.map(user => <UserGreeting firstName={user.firstName} lastName={user.lastName} />)}
</ul>

```

### Your Example Website or App

https://www.solidjs.com/docs/latest/api

### Steps to Reproduce the Bug or Issue

1. Start new Project as a React Developer
2. Try to set up a store with reactive content (Array of Objects, eg `Array<{ firstName: string, lastName: string }>`)
3. Map over Array and pass it to Child Component

### Expected behavior

As a react developer i did not expect prop spreading/destructuring to break reactivity

### Platform

not relevant

**Comment by thetarnav** [comment]
Here is the repo for the current docs site: https://github.com/solidjs/solid-docs
And here is one for the new project: https://github.com/solidjs/solid-docs-next
You could make a suggestion there, but from what I know the new docs will have learning paths for people coming from different frameworks, including React of course. So the mention of not destructing props will most likely find it's way there.

**Comment by leventdeniz** [comment]
[This is what i was looking for](https://docs.solidjs.com/references/concepts/tracking#destructuring-props)
why is this not linked anywhere on the default docs  😢

**Comment by samuelstroschein** [comment]
Did you use a template? 

Adding eslint with solid's eslint plugin to templates should be a good idea?

**Comment by leventdeniz** [comment]
I did use the with-tailwindcss template with solid-start

**Comment by leventdeniz** [comment]
Added eslint and this is a MUST for anyone using solid for the first time, 100% would recommend for solid-start templates
