### ISSUE TITLE
Function children of error boundaries are not caught

### ISSUE THREAD

**Issue by Tanner-Scadden** [solidjs/solid#1543]
### Describe the bug

If children of errorboundaries are a function they bubble up to the next one. Please look at https://github.com/solidjs/solid/issues/1542 for a very similar issue with the suspense component. 

### Your Example Website or App

https://playground.solidjs.com/anonymous/60cf87b6-5ba3-48a4-9b4f-6aa0f6953a03

### Steps to Reproduce the Bug or Issue

Have a reusable ErrorBoundary Component
Pass a function into the ErrorBoundary as the child
Errors are bubbled up until a child is not a function

### Expected behavior

As a user, I expect to be able to make a reusable errorboundary wrapper that can accept children as a function and that errors will be caught and not bubble up

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

### Additional context
Wrapping the children with the utility `children` function seems to resolve this issue as well.
https://playground.solidjs.com/anonymous/e787c74b-cbee-427f-9ac0-b845bec1e6a7

_No response_

**Comment by ryansolid** [comment]
Unlike the Suspense one that errors, this seems to behave exactly as intended. More comments here: https://github.com/solidjs/solid/issues/1542#issuecomment-1426639825
