### ISSUE TITLE
Order of onCleanup makes it difficult to properly cleanup services dependent on each other 

### ISSUE THREAD

**Issue by jmagaram** [solidjs/solid#1562]
### Describe the bug

I wrote a few services and designed them so my construction functions returned the service and a `dispose` function. And then I called `dispose` inside my component's `onCleanup` method. But then I realized I wasn't using the platform to its fullest glory and decided to put `onCleanup` methods inside those services so all the cleanup would happen automatically. But from experimentation it doesn't work as I expect. In particular if I instantiate service A, B, and C, in that order, where C depends on B and B depends on A, the cleanup functions run in the order A then B then C. I need the child service C disposed before B and B disposed before A. I want it to work like how variables get popped off the stack. Below is a simplified example where the database gets cleaned up BEFORE the document subscription. It is awkward to work around the current behavior, unless I'm missing something.

For comparison, C# and .net have a `dispose` pattern that works very well and is battle tested over many years. [c# dispose docs](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/using-statement) . When you use a disposable in C#, you do it like `using (var a=...,var b=...) { ... }` and they get disposed in the opposite order they are instantiated. You can also nest using statements; when the using block exits the variables inside are disposed. The programmer has lots of control over the order of disposal.

I'm new to SolidJS so please forgive me if there is a very good reason for this. I started a discussion on discord and the people there confirmed cleanup events from the same parent are queued, not stacked. They didn't know why. There might be a very good reason for it. But as a newcomer, I find the current behavior hard to work with. It also isn't documented well. I'd like to see a way to have more control over the order of disposal, like C# and .net, or to opt-in to a behavior where it uses a stack vs queue which seems a lot more intuitive to me.

### Your Example Website or App

None needed - see steps to reproduce

### Steps to Reproduce the Bug or Issue

Database gets cleaned up BEFORE DocumentsSubscription.

```
type Database = string;
type Documents = string[];
type User = string;

const user = (): User => {
  // this actually monitors authentication events in Firebase and
  // updates the currently logged in user. Cleaning up unsubscribes from the
  // event handler.
  onCleanup(() => console.log("Cleaning up user"));
  return "bob";
};

const database = (options: string): Database => {
  // this activate a Firestore database. the cleanup waits for pending writes to
  // finish.
  onCleanup(() => console.log("Cleaning up database"));
  return "the database here";
};

const documentSubscription = (db: Database, user: User): Documents => {
  // this subscribes to Firestore events listening for changes to a specific
  // document query. cleaning up disconnects the event.
  onCleanup(() => console.log("Cleaning up the docs"));
  return user === "joe" ? ["a", "b", "c"] : ["x", "y", "z"];
};

export const ShowDocuments = (props: { user: User }) => {
  const db = () => database("some options");
  const docs = createMemo(() => documentSubscription(db(), props.user));
  return <div>You've got {docs.length} docs</div>;
};
```

### Expected behavior

Cleanup happens like a stack not a queue. So if C depends on B and B depends on A, cleanup happens in the order CBA. Or give the programmer more control with a `using` syntax like C#. Or change default behavior. Document behavior of onCleanup better.

### Platform

- OS: macOS
- Browser: Chrome, Safari
- Version: 1.6.10

**Comment by ryansolid** [comment]
Hmm... yeah this has never come up but I think it is fair. We execute child before parent. So why not reverse order of siblings. There was a similar question asked for `onError` calls which felt more awkward to me. But this I think makes more sense. Thanks for putting that out there.

**Comment by ryansolid** [comment]
In researching this I came across this issue and comment from React: https://github.com/facebook/react/issues/16728#issuecomment-584208473.

I like this answer in stating it should be non-deterministic. That being said in the terms of children before parent there is no guaranteed order between sibling children. Like if even if I reverse the current level all children levels will run first and not necessarily in order. I'd rather take an official stance of this being non-deterministic. That being said I have a hard time justifying not reversing it.

**Comment by jmagaram** [comment]
The complexities of this issue are way beyond my level of experience. I only started with Solid a couple weeks ago and don't presume to know the right thing to do here. Regardless I think the docs should explain the ordering and say it is non-deterministic if that is what you decide makes sense.

With .net the dispose pattern is deterministic; the programmer controls it using `using` blocks or just calling `dispose`.

Practically for my situation it is awkward to work around the queue behavior while still using `onCleanup`. See pseudo-code below. If the query only appears inside the JSX then it becomes tricky to register it for disposal. My code might work regardless of how things get disposed, but I feel more confident it is doing the right thing if it happens like a stack.
```ts
const [database, pushDisposable] = createDb(...) // onCleanup defined in the database
const realtimeQuery = createQuery(database, "select * where...")
pushDisposable(realtimeQuery)
```
It might help to know some real world use cases for `onCleanup`.

I do not totally understand the `React` situation with parent and child effects. If the parent is listening to a child node, and some code destroys the child, it sounds like the parent can't detach an event listener from the child by searching for the element in the DOM. And so that child node never gets garbage collected. But if the parent knows a child node might get removed, shouldn't it keep a reference to it for proper cleanup?

If you want to hedge your bets add a parameter to `onCleanup` after the callback so the programmer can control the order. Pushing seems it would be more common; isn't it more likely a second sibling would depend on the first rather than vice versa? `function onCleanup(fn: () => void, priority?: "push" | "enqueue"): void`

**Comment by LiQuidProQuo** [comment]
```js
                             cleanup order 
                       proposed           current
p                          9               9
├── c1                     8               4
│   ├── n1                 7               2
│   │   └── g1             6               1
│   └── n2                 5               3
└── c2                     4               8
    └── n3                 3               5
    └── n4  
         |a                2               6
         |b                1               7
```
**n4**  is the only owner, with 2 `onCleanup` , so we can see the order of owner with multiple handlers at the same level.
```
g1 -> n1 -> n2 -> c1 -> n3 -> n4.a -> n4.b -> c2 -> p
```

and this is likely the proposed order 
```
n4 -> n3 -> c2 -> n2 -> g1 -> n1 -> c1 -> p
```


this model may work nicely in react, but the moment you have random order of rendering this will mean nothing.
you can't just draw the graph and assume order. you will need to know about "virtual" re renders.
