### ISSUE TITLE
wrong refs assigned when element is commented inside `html` template string

### ISSUE THREAD

**Issue by trusktr** [solidjs/solid#1564]
### Describe the bug

When commenting out an element, the wrong `ref` functions get called for elements after the commented element.

```js
  onMount(() => {
    console.log('div: ' + div?.tagName) // logs "div: P"
    console.log('p: ' + p?.tagName) // logs "div: H1"
    console.log('h1: ' + h1?.tagName) // logs "div: undefined"
  })

  return html`
    <!--<div ref=${e => div = e}></div>-->
    <p ref=${e => p = e}></p>
    <h1 ref=${e => h1 = e}></h1>
  `
```

### Your Example Website or App

https://playground.solidjs.com/anonymous/57b4c6c4-0084-4d55-bb35-40d5eb98adf0

### Steps to Reproduce the Bug or Issue

See console. Uncomment the `<div>` element and refs work again.

### Expected behavior

The ref functions should be called for the correct elements.

### Screenshots or Videos

Console output:
```
div: P
p: H1
h1: undefined
```

### Platform

- OS: any
- Browser: any
- Version: any

**Comment by ryansolid** [comment]
Yeah I imagine HTML comments are broken in general. I never accounted for them.
