### ISSUE TITLE
Shared Icons(solid-icons) Rendered "only once".

### ISSUE THREAD

**Issue by anesdiaf** [solidjs/solid#1565]
### Hi,

I have an array of objects storing my links.
The variable is in a jsx file.

i mapped the array inside a component.
`./src/compnents/ContactContainer.jsx`

then i shared the component into two other components.
`./src/sections/Start.jsx`
`./src/compnents/Footer.jsx`

### The heart of the matter (The issue)

the icons are showing only in the latter component (Footer), but doesn't show on the other (Start).

### Your Example Website or App

https://github.com/anesdiaf/solid-portfolio

### Steps to Reproduce the Bug or Issue

1.Start the app.

### Expected behavior

I expected the icons to show in both components since i've used the same steps/way in react and it worked.

### Screenshots or Videos

![Screenshot 2023-02-20 044349](https://user-images.githubusercontent.com/10120682/220004879-4cefbb12-bde2-4cbd-8c71-fc48a7f12aa6.png)

### Platform

- OS: [Windows]
- Browser: [Chrome]

**Comment by ryansolid** [comment]
It's because JSX elements in Solid are real DOM nodes. The DOM has a rule where can only attach the same node in the DOM once. So by inserting in multiple places they are being moved. I suggest wrapping the icons themselves in a function call, and calling that function inside the JSX in your mapping component.

**Comment by anesdiaf** [comment]
Thank you sir,

Did what you advised me to do.
![code](https://user-images.githubusercontent.com/10120682/220012421-d3783eff-e104-45f8-ac65-07b7cbcfd770.png)
and it worked perfectly.
![Snapshot](https://user-images.githubusercontent.com/10120682/220012568-65feb526-5a28-4e45-8971-89a6167f9a64.png)

**Comment by kakserpom** [comment]
@anesdiaf `icon: () => <IoLogo....` would be shorter
