### ISSUE TITLE
An error occurred during hot update!

### ISSUE THREAD

**Issue by liuyike98** [solidjs/solid#1572]
### Describe the bug

When the first startup, everything is well. Click the add button you can see counter change.Click the plus button again after modifying the content of the CounterProvider.tsx file, and nothing will happen on the page

### Your Example Website or App

no,only happen when use vite hot update

### Steps to Reproduce the Bug or Issue

npm i 
npm start
click the add button, everything goes well
modify the content of CounterProvider file, save
click add button again, the counter no longer react

### Expected behavior

the counter should be normal

### Platform

windows chrome

**Comment by liuyike98** [comment]
[b1a62732-f8e7-46d0-b5b6-b1f6a4f583af.zip](https://github.com/solidjs/solid/files/10806786/b1a62732-f8e7-46d0-b5b6-b1f6a4f583af.zip)

**Comment by liuyike98** [comment]
I want to know what I missed?

**Comment by ryansolid** [comment]
This is a Solid Refresh based issue related to detached context. We have a PR for the fix. https://github.com/solidjs/solid-refresh/issues/24

I will close this as a duplicate for now. Track the issue there.

**Comment by liuyike98** [comment]
@ryansolid it seems that https://github.com/solidjs/solid-refresh/pull/34 doesn't work well on my demo

**Comment by lxsmnsyc** [comment]
@liuyike98 because it isn't merged yet. Please wait for it to be merged.

**Comment by lxsmnsyc** [comment]
> @lxsmnsyc i know, i just download your newest branch, build dist, and replace the node_modules,fix require,and run again, but it just like before, headache for this a lot...

vite-plugin-solid must be changed too. I also I have already tested this on Vite.

**Comment by liuyike98** [comment]
@lxsmnsyc thanks for your reply, hope to get it soon
