### ISSUE TITLE
Async functions not rendering?

### ISSUE THREAD

**Issue by YusufSuleman** [solidjs/solid#1580]
### Describe the bug

Hello, any async function I write doesn't work, it renders nothing. First I wrote the sidebar, it didn't render anything in the OtherPosts tag just empty, everything else rendered fine. I ignored and worked on Post, and it rendered fine until I made it async it didn't render like the previous function so I conclude that it is async causing it. Also, I put :any after the function name, as it was saying that it returns a Promise not an Element. I shouldn't have picked Typescript. 
Here is my code for Post.tsx:
```ts
import Sidebar from "./Sidebar"
import PocketBase from 'pocketbase';

async function Post() {
 
    const pb = new PocketBase('http://127.0.0.1:8090');

    const record = await pb.collection('posts').getFirstListItem("", {
        
    });
    
    return (
        <div class="content-body">
            <div class="post">
                <div class="title">{record.title}</div>
                    <p class="first-para">
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Nihil soluta iusto consequatur velit itaque! Doloribus ullam, explicabo facilis, ab ipsa atque eveniet reprehenderit quos earum facere expedita aliquam necessitatibus architecto.
                        Aspernatur, dignissimos illo! Exercitationem natus aperiam error, sequi molestias iste veritatis fuga, qui at, optio expedita perferendis. Velit repellat numquam tenetur laboriosam.
                        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Illo molestiae officiis, soluta exercitationem sunt obcaecati ipsum rem, tenetur sed commodi repellendus voluptatem minima esse ex recusandae consequuntur, fuga dolor dolorum!
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime fugit quos officia nesciunt excepturi facilis veritatis, eos quasi similique corrupti suscipit nam quisquam accusamus voluptatibus molestiae fugiat. Quibusdam, odio iure?
                    </p>

                    <p>
                        Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptas atque sunt nihil pariatur odit, aliquam mollitia libero optio ullam neque. Unde veniam maiores consectetur minima. Obcaecati unde aperiam expedita enim.
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur laborum aut non voluptatibus suscipit sequi nostrum, minus libero debitis. Nam, debitis! Officia porro excepturi dolores quam, ipsa alias doloremque error.
                        Lorem ipsum dolor sit, amet consectetur adipisicing elit. Facilis iure inventore rerum ab fugiat deleniti dicta sint exercitationem odio itaque! At iusto sapiente aliquid alias recusandae fugiat et perferendis sed.
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Tenetur ab error at architecto quo rem, sint accusantium expedita debitis aspernatur ipsam libero possimus quia. Praesentium accusamus rem qui incidunt nemo!
                    </p>
                    <p>
                        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Consequuntur autem sequi amet nihil modi magnam minus, laborum ipsum repellendus, doloribus reiciendis consequatur itaque dicta rerum? Sint corrupti aperiam tempore voluptatem.
                        Lorem ipsum dolor, sit amet consectetur adipisicing elit. Tempora delectus illo in eos error, tenetur dolor veniam debitis quaerat quod fuga magnam similique suscipit? Non quis error sit doloremque nulla.
                        Lorem ipsum dolor sit, amet consectetur adipisicing elit. Consequatur vel modi doloremque pariatur eveniet, dolorem voluptates obcaecati repellat inventore eius deleniti laboriosam. Quaerat voluptate quisquam recusandae similique blanditiis, explicabo numquam.
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis ipsa fuga nemo illo? Tempore sit omnis facilis mollitia delectus. Error laborum ratione accusamus distinctio ipsa dolor tempore laudantium tenetur ad.
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Sint quod itaque officiis asperiores impedit porro dolore laboriosam quaerat temporibus, animi libero eligendi, in ea iusto natus magni inventore quibusdam. Illo?
                    </p>
                    <p>
                        Lorem ipsum dolor, sit amet consectetur adipisicing elit. Neque earum excepturi fuga odio! Tempore at asperiores quia ducimus consequuntur? Eligendi veritatis tempora repellendus nihil harum adipisci? Harum nostrum aliquam deserunt.
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque illum praesentium corrupti dolor saepe voluptatem nemo officiis perspiciatis qui ipsam. Sapiente mollitia eaque praesentium dolor iusto autem iure ipsum aperiam!
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam iusto asperiores fuga sint repellendus, illum quia aperiam libero harum quos rem quasi ad suscipit molestiae nulla, incidunt eveniet minima numquam.
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat voluptatum culpa eveniet repudiandae voluptas? Repudiandae officiis necessitatibus, itaque perferendis obcaecati nisi nostrum accusantium aspernatur repellat rerum, dignissimos quaerat nulla quasi.
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod ut maxime pariatur rerum dolore. Laboriosam facilis, odit nemo sequi fugiat, praesentium voluptatem officiis optio natus delectus placeat qui, libero commodi.
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi ut voluptatibus nobis saepe facere quasi, odit repellendus quos quia consequuntur sint fuga, dolores porro facilis? Dignissimos in est fugit nam.
                        Lorem ipsum dolor, sit amet consectetur adipisicing elit. Recusandae, labore sit nesciunt laborum consectetur cumque, in cum natus quae ex unde asperiores, quia dicta accusantium voluptatibus maxime perspiciatis sint esse?
                    </p>
                
            </div>
            <Sidebar></Sidebar>
        </div>
    )
}

export default Post
```
Here is also OtherPosts.tsx:
```ts
import PocketBase from 'pocketbase';
import { For } from 'solid-js';
import PostPreview from './PostPreview';

async function getOtherPosts() {
    const pb = new PocketBase('http://127.0.0.1:8090');
    let recordsList
    try {
        recordsList = await pb.collection('posts').getList(0, 5 /* batch size */, {
            sort: '-created',
        });
    }
    catch {
        console.error("Error")
    }   
    return recordsList
}

const OtherPosts = async () => {

    const recordsList = await getOtherPosts();
    
    //console.log(records)
    
    return (
        <div>
            <PostPreview record={recordsList?.items.at(0)} ></PostPreview>
            <PostPreview record={recordsList?.items.at(1)}></PostPreview>
            <PostPreview record={recordsList?.items.at(2)}></PostPreview>
            <PostPreview record={recordsList?.items.at(3)}></PostPreview>
        </div>
    )
}

export default OtherPosts
```

I don't know if this is from PocketBase or from the functions being async. So I also made App.tsx async, and it didn't also work. So it is from async.
Example Website is a minimalified example of this. See Post.tsx in it.

### Your Example Website or App

https://stackblitz.com/edit/solidjs-templates-h3p9fe?file=src/Post.tsx

### Steps to Reproduce the Bug or Issue

Make a SolidJS app with solidjs/templates/ts
Make a .tsx file exporting a function for example, Post.tsx.
Export a function from it returning some HTML.
Put it as a tag in App.tsx
See if it works.
Make the function async
See if it disapears.

### Expected behavior

The HTML content, the async function is returning is displayed correctly, and is in the Element tab of DevTools.

### Platform

- OS: Arch Linux
- Browser: Chromium
- Version: 110.0.5481.177 (Official Build) Arch Linux (64-bit)

### Additional context

I am using TypeScript

**Comment by atk** [comment]
In solid, asynchronous parts are handled via `createResource`:

```js
function Post() {
    const pb = new PocketBase('http://127.0.0.1:8090');
    const record = createResource (() => pb.collection('posts').getFirstListItem("", { }));
    return <Suspense fallback={"loading"}>
     <h2>{record().title}</h2>
    </Suspense>
}
```

**Comment by YusufSuleman** [comment]
Quick reply, but after copy pasting, VS Code said this error with no quick fixes:
```
Type 'ResourceReturn<Record, unknown>' has no call signatures.
```
So I added the any type to record, and it fixed it, I went into the browser, it was empty, there was no h2 tag. The DevTools console said this:
```
Post.tsx:14 Uncaught (in promise) TypeError: record is not a function
    at Post.tsx:14:11
    at Object.fn (dev.js:212:58)
    at runComputation (dev.js:709:22)
    at updateComputation (dev.js:692:3)
    at createRenderEffect (dev.js:211:75)
    at insert (dev.js:212:3)
    at get children [as children] (Post.tsx:13:34)
    at Object.fn (dev.js:1667:49)
    at runComputation (dev.js:709:22)
    at updateComputation (dev.js:692:3)
```

**Comment by LiQuidProQuo** [comment]
https://www.solidjs.com/docs/latest/api#createresource
![image](https://user-images.githubusercontent.com/105608035/221351234-c15ff5b6-4611-4222-ac51-88b224f95381.png)

**Comment by emdede** [comment]
@YusufSuleman 
```So I added the any type to record, and it fixed it, I went into the browser, it was empty, there was no h2 tag.```

It seems you are misunderstanding what TypeScript does. It is mostly a developer tool. You don't have to comply with it to create working Javascript code. But it does tell you if there's likely an error in your code. The thing about Javascript is that it is very forgivable regarding types. This is why Typescript was introduced as a way to use Javascript but be able to avoid any unexpected type errors at Runtime. If TS tells you that something's wrong, you should always look at it. Either you know the code will be valid at runtime, then you can ignore the warning, or you should find out what TS is trying to tell you because there's likely a bug in your code.

In this case, like pointed out right here ☝️ , `createResource` actually returns an Array which you must destructure before using it - or call it directly `myResource[0]()` So, the TS warning was accurate.

**Comment by YusufSuleman** [comment]
Removed the any, and added the array and VS Code told me that it is possibly undefined, so I added an ? to the end here is my code now:
```ts
record[0]()?.title
```
No errors in DevTools Console and VS Code,  but I saw nothing, still no h2 tag.

**Comment by YusufSuleman** [comment]
`record.title` is undefined.

**Comment by LiQuidProQuo** [comment]
remove the `()` 
and call `record()` in the JSX

**Comment by YusufSuleman** [comment]
Still nothing, VS Code, says it maybe undefined, so I added a ?, Still nothing. I console logged and all of record is undefined.

**Comment by YusufSuleman** [comment]
@LiQuidProQuo ?

**Comment by emdede** [comment]
I respect the balls to plunge head-first into a completely new tech-stack. But in this case I think you missed some crucial first steps.

`const record = createResource(fetchFirstPost)[0]();` this accomplishes nothing. The `()` at the end basically means, `I want to know the result`. But when you call it immediately after `createResource` has run, it will not be there yet.

This `I want to know the result` here is what is called a signal `read`. Solid is very smart in that it will make parts of your application automatically update when you use those reads in your code. But in this case, Solid can't do anything. For a start, you can create an effect, which subscribes to any `reads` (and is therefore reactive) to console.log your result.
```
const [record] = createResource(fetchFirstPost)

createEffect(() => console.log('record data', record()))
```
You should now see the data successfully being logged in your console.
First there's a log of `undefined`, because your data has not yet fetched.
Then there's a second log that contains your data, and the code runs only because it is in a reactive scope. You have to be mindful about where and how you use your logic. Solid cannot magically make all your code reactive, you need to be explicit about it.

**Comment by YusufSuleman** [comment]
Sorry for replying late, got distracted a bit but after copy pasting that, I see first an undefined log then a log with the correct data. Still no text on the site. No h2 element either.

**Comment by LiQuidProQuo** [comment]
provide a reproduction (stackblitz) with the most up to date code.
it seem like your code changed since you originally posted this question.

There is no good way for us to follow up, if you are making changes that we can't see.

**Comment by YusufSuleman** [comment]
Good Morning, While copy pasting into stackblitz, and putting the Post tag in App.tsx to show that it's not working. It said that it returns a promise, I forgot to remove the async at the start it works now. Thanks.
