### ISSUE TITLE
Built-in For each loop doesn't seem to be reactive to changes in arrays of objects

### ISSUE THREAD

**Issue by drum445** [solidjs/solid#1582]
### Describe the bug

Demo below, when pressing the button, the change can be seen in both the `.map` version and the simple JSON dump, however, the `<For>` loop does not update the DOM at all. Is there something I am doing wrong here, or is this a bug?

```js
import { createSignal, For } from "solid-js"

export default function TablePage() {

  const [rows, setRows] = createSignal([
    {"id": 0, "name": "ed", age: 0},
    {"id": 1, "name": "steve", age: 0},
  ])

  function updateRow(row) {
    setRows(prev => {
      for (let r of prev) {
        if (r.id === row.id) r.age++
      }
      return [...prev]
    })
  }

  return (
    <div>
      <button onClick={() => updateRow(rows()[0])}>Update First Row</button>

      <h4>.map:</h4>
      {rows().map(r => {return <p>{r.name}: {r.age}</p>})}

      <h4>For each:</h4>
      <For each={rows()}>{r => {return <p>{r.name}: {r.age}</p>}}</For>

      <h4>JSON Dump</h4>
      {JSON.stringify(rows())}
    </div>
  );
}
```

### Your Example Website or App

https://izrite.com/solid-explore/example-issue

### Steps to Reproduce the Bug or Issue

Go to above link
Press Update First Row button
Notice that the `For each:` section does not update
The code it is using is pasted in the description

### Expected behavior

I would expect the `<For>` loop to behave the same as the `.map`, especially considering the ES lint rules tell me to convert my `.map` into a `<For>`

### Platform

All

**Comment by drum445** [comment]
Changing `upadteRow()` to the below "fixes" the issue, so it does seem to be an equality check issue
```js
  function updateRow(row) {
    setRows(prev => {
      for (let r of prev) {
        if (r.id === row.id) r.age++
      }
      return JSON.parse(JSON.stringify(prev))
    })
  }
```

**Comment by ryansolid** [comment]
You are deeply mutating data that isn't being tracked to change. You should view values in Signals as immutable. One way to do it is is like you did.. although generally more immutable patterns are cleaner:
```js
function updateRow(row) {
    setRows(prev =>
      prev.map((r) => {
        if (r.id !== row.id) return r;
        return {...r, age: r.age + 1}
      })
    )
  }
```

That being said what you are after are Stores and deep reactivity. I suggest checking out this and the next couple parts of the tutorial: https://www.solidjs.com/tutorial/stores_nested_reactivity

**Comment by drum445** [comment]
Perfect, thanks for the example, @ryansolid
