### ISSUE TITLE
Hydration fails randomly in Astro Project

### ISSUE THREAD

**Issue by Tanguy-Magnaudet** [solidjs/solid#1583]
### Describe the bug

Hydration randomly fails or succeed in Partial Hydration mode using Astro & Nanostores.
Console shows the following warning : 

`Unable to find DOM nodes for hydration key: s00-1-0`

I've seen other issues related to this one but not in a similar context.

### Your Example Website or App

https://stackblitz.com/edit/astro-solid?file=package.json

### Steps to Reproduce the Bug or Issue

1 - Click on Add to Cart 1 or 2 times -> it should updates.
2 - Refresh the page 50 times and check each times the subtotal. It randomly shows 0 (hydration failed), or show the right amount, some times it shows the right amount but the id: 1, quantity 2 is not hydrated on its side.

### Expected behavior

The states should be loaded at hydration time every single time and everywhere.

### Screenshots or Videos

https://www.loom.com/share/009bb446553a4e10af422be1cbfa1856

### Platform

- OS: Alpine Linux / Docker
- Browser: Chrome, Brave, Safari & Firefox
- Version: "solid-js": "^1.6.11"

**Comment by ryansolid** [comment]
Looking into it. It looks like the nodes are missing from the server render causing the mismatch.

**Comment by thetarnav** [comment]
We had a similar issue with solid-primitives a while ago. https://github.com/solidjs-community/solid-primitives/issues/310
Even though signals are great at sharing state between islands - Solid even supports using a Context API shared by multiple islands - changing the state on the client in one island before the rest are hydrated will lead to hydration mismatches.
So to prevent that in our primitives, which are designed to share a single signal instance between different consumers, we need to deopt from that behavior during hydration and create a fresh instance with its value matching the server value.

**Comment by Tanguy-Magnaudet** [comment]
I understand now, I thought Astro client:only was load before client:load components but it look likes its not the case.

I fixed it using a custom hook that use onMount to initialize the stores before returning the signals : 

```js
export const useCart = () => {

  onMount(() => {
    initCart()
  })

  return {
    items: useStore(items),
  }
}
```

client:only also worked.
Sorry for the useless issue, and thanks for the explanation.
