### ISSUE TITLE
Missing Git tags v1.6.11, v1.6.12

### ISSUE THREAD

**Issue by andersk** [solidjs/solid#1598]
https://github.com/solidjs/solid/tags is missing `v1.6.11` and `v1.6.12`. I assume these should be tagged at 50a955e4d2713754e56a019d4e0bac607342093c, 722830f91e15de932840ecbf089e3383ca337e3a, respectively.

**Comment by ryansolid** [comment]
Yes thanks not part of my new workflow and I missed doing it. Should be updated now.
