### ISSUE TITLE
Wrong error message

### ISSUE THREAD

**Issue by Mubasher-Skylinx** [solidjs/solid#1603]
### Describe the bug

if you make a signal like this

```js
    const [counter, setCounter] = createSignal(0);
```
and use it like this

```js
     <h2>Counter: {Counter()}</h2>
```

### Your Example Website or App

http://localhost:3000/

### Steps to Reproduce the Bug or Issue

just Capitalize signal variable name instead of lowercase

### Expected behavior

instead of lowercase counter you wrote capitalize Counter you will get error maximam callstack exceed. it should give Counter is not defined.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/116548357/223742897-fa39c58c-849b-446e-baec-3d250866a48c.png)

### Platform

Chrome

**Comment by kakserpom** [comment]
In the snippet you call recursively Counter() inside of Counter(). `Counter` is defined ;-)

**Comment by ryansolid** [comment]
Yeah it looks like you called your component recursively rather than the signal causing the infinite loop.
