### ISSUE TITLE
Branching on Effect value and a Selector can break reactivity when Effect value is checked first

### ISSUE THREAD

**Issue by L1Q** [solidjs/solid#1614]
### Describe the bug

It seems like the selector is completely ignored by an effect function if it's not evaluated on the first run.

In my real use case, I needed an effect that scrolls an item into view when it is selected. This does not make sense to do on the first render, only when menu items are clicked by the user.

### Your Example Website or App

https://stackblitz.com/edit/solidjs-templates-kcmqlk?file=src/App.tsx

### Steps to Reproduce the Bug or Issue

Click the buttons [A, B, C, D]

### Expected behavior

Additional log entries appear as the createEffect function runs again and again.

### Platform

- OS: Windows, Linux
- Browser: Chrome
- Version: 110.0.5481

**Comment by thetarnav** [comment]
If you don't read from a signal, you won't subscribe to it. This applies to selectors as well.
So even if you don't want to perform any action on the first run, you should subscribe to the sources you want to track, so they can trigger the effect next time they update.

**Comment by L1Q** [comment]
It is disappointing that the compiler is not able to track dependencies in such cases.
The ``on`` hint is pretty useful though, my use case benefits from the ``defer`` option as well. Thank you!

One thing that's still not clear at all is how to use ``on`` with a selector?
In the docs, signal ``a`` is passed to the ``on`` helper, it is just an accessor function, that will be evaluated and the results will go to the effect function as ``v``, but a selector is different, it needs an argument, right?

Can you provide a code sample of how my ``createEffect`` call can be rewritten to use ``on`` with the selector?

**Comment by thetarnav** [comment]
> It is disappointing that the compiler is not able to track dependencies in such cases.

reactivity is fully runtime, so it has to run at least once to track dependencies

> Can you provide a code sample of how my `createEffect` call can be rewritten to use `on` with the selector?

```ts
const [selectedId, setSelectedId] = createSignal(0)
const isIdSelected = createSelector(selectedId)

createEffect(on(
  () => isIdSelected(index),
  isSelected => {
    console.log(isSelected)
  },
  { defer: true }
))
```

**Comment by L1Q** [comment]
> reactivity is fully runtime

Disappointing, but good to know 👍

A code example like this from a contributor definitely helps relieve my anxiety about any more dependency tracking issues.

Thank you again for your very fast and helpful responses 🙏
