### ISSUE TITLE
onMount got executed server side

### ISSUE THREAD

**Issue by bwyx** [solidjs/solid#1616]
### Describe the bug

I use Astro SSR with Solid and got an `error   window is not defined` when using the `window` object inside `onMount` or `onCleanup`

I can't make sure if it's a bug in Astro SSR implementation or Solid itself, but I can make it work by wrapping `onMount` inside a `!isServer` check.

### Your Example Website or App

https://stackblitz.com/edit/github-9ahefq?file=src/components/Solid.tsx

### Steps to Reproduce the Bug or Issue

1. Open the [Stackblitz](https://stackblitz.com/edit/github-9ahefq?file=src/components/Solid.tsx)
2. `npm run dev` / `npm run build`
3. Got `window undefined`

### Expected behavior

able to use client-side code inside `onMount` on SSR

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/37757388/224541273-4a02a7ba-6d48-46b5-be6b-232aef8c9cad.png)

### Platform

- OS: linux arch 5.15.87-1-lts
- Browser: Chromium
- Version: 109.0.5414.74 (Official Build) Arch Linux (64-bit)

**Comment by ryansolid** [comment]
Took a quick look without running anything (I can try it out later). One thing I noticed;

`onCleanup` runs on the server. There were some bugs until recently that it didn't always do so. If you are cleaning up side effects created by an `onMount` call I suggest nesting the `onCleanup` inside the `onMount`.

**Comment by bwyx** [comment]
so it's the `onCleanup` that caused the error, not the `onMount`. my bad for not checking it first. thank you. closing this one
