### ISSUE TITLE
can you provide h function for customize renderer.

### ISSUE THREAD

**Issue by zsytssk** [solidjs/solid#1617]
### Discussed in https://github.com/solidjs/solid/discussions/1612

<div type='discussions-op-text'>

<sup>Originally posted by **zsytssk** March 10, 2023</sup>
I'm writing a solidjs customize renderer for weapp support. and I need `h` function in some scenarios. 

I have try use `hyper-dom-expressions.createHyperScript` but I get some errors, weapp environment don't support dom api like `Node`, and customize renderer don't export `assign,dynamicProperty,SVGElements` api.

can you provide a `h` function  or `createHyperScript` for  customize renderer.</div>

**Comment by ryansolid** [comment]
As this is already discussion. I'm going to leave this there.
