### ISSUE TITLE
Suspense Fallback disappears when interacting with counter

### ISSUE THREAD

**Issue by rtkaaho** [solidjs/solid#1624]
### Describe the bug

When using the default/base solid start template and implementing simple streaming with the `renderStream` server function in the `entry-server.tsx.` the Suspense fallbacks disappear when interacting with the counter component.

### Your Example Website or App

https://github.com/adamaho/suspense-fallback-bug

### Steps to Reproduce the Bug or Issue

1. Clone the repo
2. pnpm install
3. pnpm dev
4. Open `http://localhost:3000`
5. Observe the `loading p1...` and `loading p2...` fallbacks
6. While the one or more fallbacks are present, press the counter button
7. Observe the fallbacks disappear until the promises are resolved after the timeout, at which point the content of the promise appears

### Expected behavior

As a user, I expect the fallback to remain on the page while clicking the counter button until the stream has completed and the content from the promises is shown.

### Screenshots or Videos

https://user-images.githubusercontent.com/56700218/225392459-9abb890c-0a72-454b-ab7f-687d4e037383.mov

### Platform

- OS: macOS - M1 macbook air
- Browser: Chrome
- Version: 111.0.5563.64

**Comment by ryansolid** [comment]
Ok hah.. I found the bug. Not what I thought. Not some crazy hydration bug. Literally I removed all the placeholder when it realizes it needs to bail out. But that's the wrong timing. It shouldn't do that until the data comes in. Thanks for reporting.
