### ISSUE TITLE
Property 'checked' does not exist on type 'EventTarget & Element'

### ISSUE THREAD

**Issue by moshuchao** [solidjs/solid#1630]
### Describe the bug

**solidjs**: Property 'checked' does not exist on type 'EventTarget & Element'.
![image](https://user-images.githubusercontent.com/27390758/225858126-8f5c760a-8764-44df-9fcb-1e88f9fca511.png)

**react**: ok
![image](https://user-images.githubusercontent.com/27390758/225858773-418022fb-5a72-4fc7-b393-652fcd468eb3.png)

### Your Example Website or App

//#

### Steps to Reproduce the Bug or Issue

//#

### Expected behavior

//#

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by ryansolid** [comment]
Does anyone know how React does this? Is it something special to their change event as it is non-standard?

The tricky part of this is target in general is the originator of the event vs currentTarget which is the element the listener is attached to. Which conceivably some events could be narrowed to specific targets there is nothing to my knowledge that could allow TS predict which element triggers the event as that is up to the user at runtime.

Do they have specific events on certain element types? Do they incorrectly assume target === currentTarget?

**Comment by otonashixav** [comment]
Pretty much. `onChange` on input, select and textarea elements have a specific event type that has target set to the current element's type.

**Comment by elite174** [comment]
@ryansolid Seems like everybody have sticked to incorrect assumption that target is the same as currentTarget.
@moshuchao You should use currentTarget instead.

**Comment by ryansolid** [comment]
I did find a way to implement this in a smart enough way. it will be in 1.7.
