### ISSUE TITLE
Google map iframe typescript error

### ISSUE THREAD

**Issue by LuisCoderDev** [solidjs/solid#1639]
### Describe the bug

when i copy and paste a google map iframe in solid js i get a typescript error in one property.

Property 'loading' does not exist on type 'IframeHTMLAttributes<HTMLIFrameElement>.

this is a normal iframe and i dont have external libraries for nothing.

### Your Example Website or App

https://github.com/LuisSkyDev/solid_map

### Steps to Reproduce the Bug or Issue

```
const Map = () => (
  <div class='footer-map'>
    <iframe
      src='https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d59300.46446226757!2d-90.1990071630986!3d38.6351569191218!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sen!2sve!4v1679451144286!5m2!1sen!2sve'
      class='footer-map__map'
      loading='lazy'
      frameborder='0'
      referrerpolicy='no-referrer-when-downgrade'
    />
  </div>
);

export { Map };
```

### Expected behavior

the property loading should be available in typescript i dont kwon if this a ts error or is a error in the types definitions in solidjs

### Platform

- OS: Windows
- Browser: Chrome
- Version: 1.6.10

**Comment by arbassett** [comment]
The loading property of iframe is still considered experimental. Firefox doesn't support it and safari has a a technical preview.
more info here https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#browser_compatibility

the types for jsx are found here if you want to file a pr to get it added https://github.com/ryansolid/dom-expressions/blob/e1ab767e69b10edbd61dd63f18762d695fb246e0/packages/dom-expressions/src/jsx.d.ts#L766-L777
