### ISSUE TITLE
TypeScript: Event properties can be omitted but not set to undefined

### ISSUE THREAD

**Issue by WesSouza** [solidjs/solid#1640]
### Describe the bug

The types for events are optional, but require a valid value if set.

Optional properties should allow `undefined` in case we want to programmatically set the property, such as in the example below, as the effect is most likely the same.

```tsx
export function Test(props: {
  onClick?: () => void
}) {
  return (
    <>
      <button>No Errors</button>
      <button onClick={props.onClick}>Test</button>
      {/* ^ Type 'undefined' is not assignable to type 'EventHandlerUnion<HTMLDivElement, MouseEvent>'. ts(2375) */}
    </>
  );
}
```

_Edit: adjusted example._

**Comment by WesSouza** [comment]
Thanks for the note on `props`, I still need to get properly familiar with the reactive-gotchas-for-React-developers 😅.

I see all of the properties are described in the [jsx.d.ts](https://github.com/solidjs/solid/blob/main/packages/solid/h/jsx-runtime/src/jsx.d.ts#L110-L293) file using `EventHandlerUnion`.

I wonder if it would be acceptable to just change that type to:

```
type EventHandlerUnion<T, E extends Event> = EventHandler<T, E> | BoundEventHandler<T, E> | undefined;
```

**Comment by otonashixav** [comment]
The types are in [dom-expressions](https://github.com/ryansolid/dom-expressions/blob/main/packages/dom-expressions/src/jsx.d.ts).

**Comment by WesSouza** [comment]
I can’t find anywhere that brings that codebase into the solid package. How does that work?

**Comment by ryansolid** [comment]
It's because dom-expressions is sort of a framework builder. In order to get a treeshakeable output we need to basically bundle it into Solid's output.
