### ISSUE TITLE
InputHTMLAttributes does not have all native input attributes

### ISSUE THREAD

**Issue by jesseb34r** [solidjs/solid#1642]
### Describe the bug

The [InputHTMLAttributes interface](https://github.com/solidjs/solid/blob/main/packages/solid/h/jsx-runtime/src/jsx.d.ts#L787) does not have all of the attributes of the native `<input />` element. Specifically it doesn't handle the attributes that depend on the specified input `type`.

I initially ran into this bug when using a Kobalte text field input with `type="search"` and adding the `incremental` attribute that is specific to `<input type="search">`. It errors because the solidjs InputHTMLAttributes type does not include incremental. 

### Your Example Website or App

https://playground.solidjs.com/anonymous/67880890-0ca4-416b-a3a4-744398c71ff1

### Steps to Reproduce the Bug or Issue

add the `incremental` attribute to an `<input>` element with `type="search"` and it will type error.

### Expected behavior

I expected `<input type="search" incremental />` to be valid

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/61254589/227025289-cdd79fcf-abd5-4876-9391-ee5a759456f7.png)

### Platform

solid-js version 1.6.11

**Comment by jesseb34r** [comment]
The [HTML spec](https://html.spec.whatwg.org/multipage/input.html#the-input-element) for the input element describes the expected attributes for each `type`

**Comment by ryansolid** [comment]
Definitely open to PRs here. We got our types from other JSX libraries and some of those are older so we added them as we found them.

Our JSX types can be found in this package: https://github.com/ryansolid/dom-expressions/blob/main/packages/dom-expressions/src/jsx.d.ts

**Comment by jesseb34r** [comment]
Yeah I linked the types file in the issue above. I will see if I can make a PR for this in the next week. It will be my first PR to a major OSS project like this so I might need some help, I'll reach out on discord if I have questions.

**Comment by elite174** [comment]
@jesseb34r https://github.com/ryansolid/dom-expressions/pull/225 Could you check this?

**Comment by titoBouzout** [comment]
This issue can be closed, it already has been merged in dom-expressions.

**Comment by ryansolid** [comment]
Thanks.
