### ISSUE TITLE
Wrong typescript type on createStore when using generics

### ISSUE THREAD

**Issue by ChrisCoy** [solidjs/solid#1646]
### Describe the bug

The first argument of createStore which is store, is optional, so you can pass undefined, but when using a type in generics, it become requeried, even if you type is optinal. The follow code generates the type error:

`
interface AuthContextData {
  user?: IUser;
}

type IUser = {
  id: string;
  email?: string;
} | undefined;

const AuthContext = createContext({} as AuthContextData);

export function AuthProvider(props: { children: JSX.Element }) {
  const [user, setUser] = createStore<IUser>(undefined);

  return <AuthContext.Provider value={{user}}>{props.children}</AuthContext.Provider>;
}
`

### Your Example Website or App

https://github.com/ChrisCoy/videos-notes-solidjs

### Steps to Reproduce the Bug or Issue

Pass a optional type to createStore generics.

### Expected behavior

I exptected store to be optional when i pass an optional type.

### Platform

solid 1.6.10

### Additional context

I dont know pretty much about type script, but the follow code fixes the error:

`export declare function createStore<T extends object | undefined>(...[store, options]: {} extends T ? [store?: T | Store<T>, options?: {
    name?: string;
}] : [store: T | Store<T>, options?: {
    name?: string;
}]): [get: Store<T>, set: SetStoreFunction<T>];
export {};`

The file i edited is located in solid-js/store/types/store.d.ts. I only changed the generic type from `<T extends object = {}>` from `<T extends object | undefined>`.

Btw, loving solid-js💙, thank you for all your work.

**Comment by otonashixav** [comment]
I can't look at the repro now (could if it were in a playground) but the first argument is meant to only be optional if the actual type has no required properties. If this still errors with `id` being optional then this is a bug, otherwise it is expected behaviour. Another issue is that it seems like the return type can include `undefined` if `T` extends `undefined`, which is never the case, it is always a store.

**Comment by ChrisCoy** [comment]
I tested with id being optinal and its like you said, theres no bug. Thanks for you help! have a nice day :D
