### ISSUE TITLE
Undesired behaviour: Portal bypasses Suspense

### ISSUE THREAD

**Issue by petermakeswebsites** [solidjs/solid#1653]
### Describe the bug

As I understand it, Portal find a DOM element and attaches to it. What I'm seeing is that Portals don't really care which "branch" they are in in terms of Suspense states.

Is this desired behaviour? Shouldn't Portal, when its being computed in the suspense "ghost" state, *not* attach to the DOM element ?

### Your Example Website or App

https://www.solidjs.com/tutorial/async_suspense

### Steps to Reproduce the Bug or Issue

Note: For some reason the SolidJS playground isn't rendering Suspense properly, which seems to be another issue altogether, but this example is functional if you paste it in the online tutorial IDE which I set as the example website:

```tsx
import { render } from "solid-js/web";
import { Suspense, createResource, createEffect } from "solid-js";

const [fiveSecondResource] = createResource(async () => {
  await new Promise(res => setTimeout(res, 5000))
  return "hello after 5 seconds"
})


function App() {
  return (
    <>
    Hello and welcome to my app. Here's some content <br />
      <Suspense fallback={<>.... Loading some extra content</>}>
        <span>{fiveSecondResource()}</span>
        <div>And here's some other content now that we're loaded after 5 seconds</div>
        <Portal>This content doesn't care about Suspense. It just renders anyway.</Portal>
      </Suspense>
    </>
  );
}

render(() => <App />, document.getElementById("app"));

```

### Expected behavior

I expected the content inside the Portal to only show when the Suspense is complete

### Platform

- OS: MacOS Monterey
- Browser: Chrome
- Version: 111

**Comment by lxsmnsyc** [comment]
Suspense isn't non-blocking anyways, so everything inside it would render regardless if the fallback is rendered. But yes, Portal should be suspended as well both in UI and in effects. I would say this is a bug, but let's see what @ryansolid thinks

**Comment by petermakeswebsites** [comment]
Yes that's what I mean. I think I may have used the term "render" incorrectly. IMO It should behave just like the rest of everything else in Suspense. E.g., it should render but not attach to the DOM element until the resource is properly loaded and Suspense gives the go-ahead, as you said.
