### ISSUE TITLE
 isWrappable(new Class()) return false

### ISSUE THREAD

**Issue by Reinhard2019** [solidjs/solid#1661]
### Describe the bug

In this issue: https://github.com/solidjs/solid/issues/19
@ryansolid Decided to only wrap plain Objects and Arrays like MobX.

But i think a class object also should be wrap.

What do you think?

### Your Example Website or App

https://stackblitz.com/edit/typescript-mkiunp?file=index.ts

### Steps to Reproduce the Bug or Issue

class Obj {}
console.log('new Obj():', isWrappable(new Obj()))

### Expected behavior

return true

### Screenshots or Videos

<img width="1471" alt="image" src="https://user-images.githubusercontent.com/13881726/228853565-e8b95703-4c75-40c8-be7d-c536aced9c61.png">

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by ryansolid** [comment]
No this is by design. Is wrappable false means that it can only wrap it atomically instead of each property. We did this to avoid wrapping built in classes like Date, Regexp, HTMLElement. And things like Set and Map which could be wrapped differently depending on intent.

**Comment by Reinhard2019** [comment]
> No this is by design. Is wrappable false means that it can only wrap it atomically instead of each property. We did this to avoid wrapping built in classes like Date, Regexp, HTMLElement. And things like Set and Map which could be wrapped differently depending on intent. The original issue explains how this is a much easier identification model than trying to exempt specific classes.

But when i use createStore({ obj: new Obj() })，store.obj will not be monitored. 

Can you give me an escape window?

**Comment by Reinhard2019** [comment]
@ryansolid Do you think it is possible to add a symbol to solve this problem? Like this:
![image](https://user-images.githubusercontent.com/13881726/229263613-cf00b898-19cf-4f1c-bac2-27be1b9ad2c3.png)
If you think it's ok, i will commit a pr. thx!
