### ISSUE TITLE
Can't have a key named "toString" in a store

### ISSUE THREAD

**Issue by alex-dixon** [solidjs/solid#1668]
### Describe the bug

Hello!

A key named `toString` in a store returns `"[object Undefined]"` when it is accessed. 

Minimally-reproducible example:
https://codesandbox.io/s/elated-gates-4967yq?file=/index.js

### Your Example Website or App

https://codesandbox.io/s/elated-gates-4967yq?file=/index.js

### Steps to Reproduce the Bug or Issue

https://codesandbox.io/s/elated-gates-4967yq?file=/index.js

### Expected behavior

Should match Javascript behavior:

```
const myobj = {toString: {some:'data'}}
myobj.toString => {some: 'data'}
```

### Platform

- OS: macOS
- Browser: Chrome
- Version: 1.7.1

**Comment by thekrprince** [comment]
Hi Alex,
Can I work on this issue?

**Comment by atk** [comment]
Using Object.toString allows you to overwrite the Object.prototype.toString() method. If you add something other than a function in this property, you have to expect problems, as this is undefined behavior.
