### ISSUE TITLE
Having a context inside of a context of the same type

### ISSUE THREAD

**Issue by gabrielmfern** [solidjs/solid#1669]
### Describe the bug

I am not sure if this would be considered a bug, but what I am trying to do is have some kind of a Box component
over which it will have certain kinds of degrees of gray. I want for these degrees of gray to increase
depending on how many boxes are above that box.

To do this I created a context for the Box and a Box component as follows:

```typescript
type Depth = 0 | 1 | 2 | 3 | 4;

const BoxContext = createContext<Accessor<Depth>>();

const Box: Component<ParentProps> = ({ children }) => {
  const oldDepth = useContext(BoxContext);
  const depth = createMemo(() => {
    console.log(oldDepth);
    if (typeof oldDepth !== 'undefined') {
      return Math.max(oldDepth() + 1, 4);
    } else {
      return 0;
    }
  }) as Accessor<Depth>;

  return <BoxContext.Provider value={depth}>
    <div class='box' classList={{
      'gray-0': depth() === 0,
      'gray-1': depth() === 1,
      'gray-2': depth() === 2,
      'gray-3': depth() === 3,
      'gray-4': depth() === 4,
    }}>
      {children}
    </div>
  </BoxContext.Provider>;
};
```

But as it happens, inside of the createMemo, the console.log always logs `undefined` regardless of how many boxes are above the current box.

### Your Example Website or App

https://github.com/gabrielmfern/foxpox

### Steps to Reproduce the Bug or Issue

1. Install node_modules using `npm install`
2. Run the project using `npm start`
3. Open the website on localhost and the colors will be just white instead of a contrasting gray scale.

### Expected behavior

I expected for the context to be able to use its parent context, but instead it just gets undefined regardless of how many contexts are above it.

### Platform

- OS: Linux (Ubuntu 22.04)
- Browser: Chrome
- Version: 111.0.5563.146
- SolidJS Version: 1.6.10

**Comment by lxsmnsyc** [comment]
You're destructuring children which is a no-no

**Comment by gabrielmfern** [comment]
That was actually the solution, thanks, didn't actually think of that. 
Sorry for wasting your time with this. 
I am closing the question, thank you agian.
