### ISSUE TITLE
createRessource and astro: Cannot read properties of undefined (reading 'id')

### ISSUE THREAD

**Issue by millette** [solidjs/solid#1674]
### Describe the bug

Not sure if the problem is in astro or solidjs but I can't use createRessource() and astro ssr.

### Your Example Website or App

https://github.com/millette/microattestations-icea

### Steps to Reproduce the Bug or Issue

`pnpm build` breaks after

> prerendering static routes

### Expected behavior

No error is expected, build should finish.

### Platform

- OS: Linux
- Browser: irrelevant
- solidjs Version: 1.7.1 ann 1.6.15
- astro: 2.1.9

**Comment by lxsmnsyc** [comment]
This might be related: https://github.com/withastro/astro/issues/6709

**Comment by ryansolid** [comment]
Reproduction seems not to be there. Can we get a reproduction?

**Comment by millette** [comment]
Sorry, I was overwhelmed with work. I'll try and make a simple repro soon.

**Comment by ryansolid** [comment]
Closing as stale
