### ISSUE TITLE
Portals used inside a nested ErrorBoundary are not being cleaned up

### ISSUE THREAD

**Issue by emdede** [solidjs/solid#1676]
### Describe the bug

When a Portal is rendered inside a nested ErrorBoundary context, it will not be removed as it should be.

### Your Example Website or App

https://stackblitz.com/edit/solid-ssr-vite-pcbdkr?file=src/routes/(app).tsx

### Steps to Reproduce the Bug or Issue

For the Stackblitz repro:
1. Switch between `IndexWithPortal` and `NoPortal` and it is working fine.
2. Navigate to `Portal with ErrorBoundary` and switch to another page, the Portal will remain visible.
3. Switch back and forth and more Portals are added to the DOM tree.

### Expected behavior

Portals should always be removed when you leave a route regardless of whether or not an ErrorBoundary is being used.

### Platform

- OS: Windows
- Browser: Chrome

**Comment by emdede** [comment]
Interesting side note:
It works when the page is loaded via SSR. This issue is only present in CSR.

**Comment by emdede** [comment]
Closing as duplicate of #1677

**Comment by ryansolid** [comment]
It is a different issue. Actually the new `catchError` + Transitions are at fault.
