### ISSUE TITLE
Getting c.outlet is not a function error in 1.6.14,1.7 and in few other versions

### ISSUE THREAD

**Issue by PrashantSingh2618** [solidjs/solid#1678]
### Describe the bug

I have a web app that has `solidjs: 1.6.14` and `"solid-app-router": "^0.3.2"`.  On opening the website in a webview in a react-native application, i am getting the error 
`c.outlet is not a function` 

**How is this a solid-js issue ?**
This error i was getting in 1.7.0, 1.6.15. When i downgraded the version to 1.5.x the error was changing `ws is not a function`, `No is not a function`.
It is working fine in dev/build environment in web, but it shows error while opening in webview.

### Steps to Reproduce the Bug or Issue

1. Create a web app using solid-js: 1.6.15 
2. Try opening it in a webview
3. Inspect this page (chrome://inspect)
4. In console we get this error

### Expected behavior

The web app breaks and does not render. This should work fine irrespective where it is opened.

### Screenshots or Videos

![error](https://user-images.githubusercontent.com/38156926/230634246-658132d6-5d7b-46e9-86f5-9c4580850e74.jpeg)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

### Additional context

In version 1.4.8 it is not happening but in 1.7.0 it is definitely there.

**Comment by ryansolid** [comment]
Yeah the bug is with the router which is a much older version. I didn't find it because there was a bunch any typecasting until much later. `solid-app-router` has been deprecated and replaced with `@solidjs/router`. Update to the latest version of the router and you should be fine.
