### ISSUE TITLE
Babel plugin produces incorrect import of the `use` function when used with custom renderer (solid-three)

### ISSUE THREAD

**Issue by yohgen** [solidjs/solid#1680]
### Describe the bug

While setting up [`solid-three`](https://github.com/nksaraf/solid-three), a weird bug occurred during dev/build (with vite): ~`The requested module 'solid-three' does not provide an export named 'use'`. This error is thrown because after Babel transpiles the original code it mistakenly outputs ~`import { use } from 'solid-three';`, rather than ~`import { use } from 'solid-js/web';`.

After some digging, it appears the `use` function has been added only recently, since older publicly available `solid-three` projects that also use older versions of `solid-js` don't have this bug: I verified it by downgrading to older `solid-js` that doesn't have the `use` function, and it made the bug disappear.

This issue is far above my expertise, but after some digging I was able log some internal workings of `solid-js` Babel transform, and it appears that for a reason I wasn't able to track down on my own Babel incorrectly infers that the `use` function belongs to `solid-three` renderer, which causes the buggy import statement to be produced. Hope these meager bits will help to find the root cause.

### Your Example Website or App

https://stackblitz.com/edit/solidjs-templates-p1lnyy?file=src/App.tsx

### Steps to Reproduce the Bug or Issue

1. Set up a Vite project
2. Install latest `solid-js` Vite plugin, add latest `three` and `solid-three`
3. In Vite config, modify `solid` key in `solid-js` Vite plugin options to this:
```typescript
import { DOMElements, SVGElements } from 'solid-js/web/dist/dev.cjs';

// ... other options
solid: {
  moduleName: 'solid-js/web',
  // @ts-ignore
  generate: 'dynamic',
  renderers: [
    {
      name: 'dom',
      moduleName: 'solid-js/web',
      elements: [...DOMElements.values(), ...SVGElements.values()],
    },
    {
      name: 'universal',
      moduleName: 'solid-three',
      elements: [],
    },
  ],
}
// ... other options
```
5. Try to use `ref` with any custom `three` component, for example:
```typescript
const Box: Component = () => {
  let meshRef: Mesh;

  useFrame(() => (meshRef.rotation.y += 0.01));

  const [isHovered, setIsHovered] = createSignal(false);

  return (
    <mesh
      ref={meshRef}
      onPointerEnter={() => setIsHovered(true)}
      onPointerLeave={() => setIsHovered(false)}
    >
      <boxBufferGeometry />
      <meshStandardMaterial color={isHovered() ? 'blue' : 'green'} />
    </mesh>
  );
};
```

### Expected behavior

Babel was supposed to import the `use` function from regular `solid-js/web` package, but it failed to do so...

### Platform

- OS: Linux version 6.2.6-arch1-1 (linux@archlinux)
- Browser: Google Chrome
- Version: 109.0.5414.74 (Official Build) (64-bit)

**Comment by ryansolid** [comment]
This should actually come from the custom renderer because `solid-js/web` may not be present. I probably added it to the compiler and missed adding it to the runtime. Good catch I don't have enough universal renderer demos to actually see that miss in action. It's been broken for a few months most likely.

**Comment by ryansolid** [comment]
Actually I see the use function in our universal output. Maybe the version of the compiler and Solid are out of sync. And you need to update Solid?

**Comment by yohgen** [comment]
> Ahh the library inlined their own version of the renderer in the bundle that is out of date. So it built in the old version. It needs to be updated or you need to downgrade solid and babel back to 1.5. Or even better it can just keep the dependency and not bundle it in.

Oh, I see. It's kinda hard for me to follow, but I guess you are referring to `export * from 'solid-js'` declaration in `/src/renderer.tsx` in `solid-three` source code. I also saw noticed it, but I thought that it wasn't supposed to be used anyway, in a sense that it seems _hacky_ to me.

> As far as I'm concerned this is an issue with solid-three and you should open an issue there.

Thank you for the tip, I'll refile the issue there.

**Comment by ryansolid** [comment]
More it looks like it isn't externalized. I see the definition for createRenderer in that bundle. Instead of refering to the version being exported by solid bundle.

**Comment by ryansolid** [comment]
Since that is being tracked over there going to close this one here.

**Comment by yohgen** [comment]
@ryansolid Sorry, I was busy. I tried to tinker a bit on my own, but had little luck so far. I still am thankful that you took a gander, though!
