### ISSUE TITLE
Uncaught TypeError: Cannot read properties of null (reading 'nextSibling')

### ISSUE THREAD

**Issue by elite174** [solidjs/solid#1684]
### Describe the bug

The error is:

```
Uncaught TypeError: Cannot read properties of null (reading 'nextSibling')
    at 2d974b49-e6f9-4756-9a3b-355c5758ed5a:10:21
    at Counter (2d974b49-e6f9-4756-9a3b-355c5758ed5a:16:5)
    at jspm.dev/npm:solid-js@1.7.3:549:12
    at untrack (jspm.dev/npm:solid-js@1.7.3:434:12)
    at Object.fn (jspm.dev/npm:solid-js@1.7.3:545:37)
    at runComputation (jspm.dev/npm:solid-js@1.7.3:696:22)
    at updateComputation (jspm.dev/npm:solid-js@1.7.3:679:3)
    at devComponent (jspm.dev/npm:solid-js@1.7.3:556:3)
    at createComponent (jspm.dev/npm:solid-js@1.7.3:1232:10)
    at 2d974b49-e6f9-4756-9a3b-355c5758ed5a:18:31
```

The error appears during rendering simple markdown:

https://playground.solidjs.com/anonymous/cd306969-c2d8-4d59-97d3-1a46cd9fd86a

```tsx
import { render } from "solid-js/web";

function Counter() {
  const handleClick = () => console.log(123);

  return (
    <section>
      <form>
        <label>
          <span>Set input value</span>
          <input type="text" />
        </label>
        <fieldset>
          <legend>Time travel options</legend>
          <label>
            Keep same values
            <input type="check" />
          </label>
        </fieldset>
      </form>
      <span> text</span>
      <br />
      <span> text</span>
      <div>
        <button onClick={handleClick}>Undo</button>
        <button>Redo</button>
        <button>Clear history</button>
      </div>
    </section>
  );
}

render(() => <Counter />, document.getElementById("app")!);
```

### Your Example Website or App

https://playground.solidjs.com/anonymous/cd306969-c2d8-4d59-97d3-1a46cd9fd86a

### Steps to Reproduce the Bug or Issue

Go to the playground and insert the code.

### Expected behavior

The markdown should be rendered without any errors.

### Platform

- OS: [Windows,]
- Browser: [Edge]
- Version: [Latest]

**Comment by elite174** [comment]
Should it be possible to use random tags? AFAIK HTML spec allows to use any tag name.

**Comment by ryansolid** [comment]
I tested custom elements and they were fine.. it is just a few elements seem to have weird parsing exception cases.

**Comment by phungleson** [comment]
Hey peeps, I had the same issues and I narrow down to `babel-preset-solid`.

I used to have `babel-preset-solid@1.6.13` and when I upgraded to `babel-preset-solid@1.7.1` then all my tests broke with the same error.

**Comment by ryansolid** [comment]
Yeah... depends on your test runner environment. I found out recently that Happy DOMs parser isn't as sophisticated as the browser's which makes things a little bit tricky since it pretty much breaks on any sort of tag omission. In the browser we've narrowed it down to a few special fields. I'm still trying to decide what to do with this information since it'd be nice to apply this optimization but not all non-browser environments are going to have an HTML parser with perfect behavior.

**Comment by elite174** [comment]
An interesting behaviour: if you remove `onClick={handleClick}` from the button, everything will work.

**Comment by howagain** [comment]
Wanted to add on to this that we were finding this same error when we were spreading props on a button element and it contains 3 prop elements on the same level, one of them being children, with a no op create effect. I know super specific but when we narrowed it down it was this weird combination of conditions that caused the same error and getting rid of any one of these pieces made it work again. Note this is in Astro using Solid's plugin. Have absolutely no idea what's going on but wrapping the props.children in a span is our current solution for it.

https://stackblitz.com/edit/github-9aeck2?file=src/components/Button.tsx

**Comment by ryansolid** [comment]
@howagain that looks like a bug but it is a completely different issue. 

The error is generic for any sort of walk/DOM mismatch. I was going to close this one because I changed dom expressions to no longer aggressively omit closing tags.
