### ISSUE TITLE
Portal's children, can't get ref.clientHeight in onMount

### ISSUE THREAD

**Issue by Reinhard2019** [solidjs/solid#1687]
### Describe the bug

If a component is Portal's children, can't get ref.clientHeight in onMount

bug reason:
I'm guessing it might be caused by this update. https://github.com/solidjs/solid/commit/47d574a812c492efd0d3b59904f14b765560dd86

<img width="644" alt="image" src="https://user-images.githubusercontent.com/13881726/231643052-d8093ed0-cd55-4e54-9d35-087c81081933.png">

The subcomponent was executed ahead of time before portal mounting

### Your Example Website or App

https://stackblitz.com/edit/solidjs-templates-ejazx4?file=src/App.jsx

### Steps to Reproduce the Bug or Issue

<img width="1414" alt="image" src="https://user-images.githubusercontent.com/13881726/231641376-0d73fc0e-ec9c-4d9b-85eb-6b15b4e8fb9d.png">

### Expected behavior

normal acquisition clientHeight
like this:
<img width="201" alt="image" src="https://user-images.githubusercontent.com/13881726/231641806-f08324f4-d8e4-4c8c-95f5-21ff4b47244c.png">

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by ryansolid** [comment]
I believe this was already fixed. Your example is using Solid 1.7 but this was fixed in 1.7.3. Updating seems to have resolved the problem: https://stackblitz.com/edit/solidjs-templates-mrtzzr?file=package.json

**Comment by Reinhard2019** [comment]
> I believe this was already fixed. Your example is using Solid 1.7 but this was fixed in 1.7.3 (this commit: [8ce2c47](https://github.com/solidjs/solid/commit/8ce2c47b0bb05b4ec73eecf6b5139f9c55f79bec)). Updating seems to have resolved the problem: https://stackblitz.com/edit/solidjs-templates-mrtzzr?file=package.json

You are right! My fault, I forget check the latest version
