### ISSUE TITLE
Attributes inside custom-element deleted when it come from an object 

### ISSUE THREAD

**Issue by tufik2** [solidjs/solid#1689]
### Describe the bug

Hi Guys, Thanks, and excellent job developing this great framework. Making testing I note that Solid is removing attributes when I assign it to a custom element...developing

I am using vide+solid template to init the project

### Steps to Reproduce the Bug or Issue

You will note that name and checked attributes are no present in the output?

```
import ('https://cdn.jsdelivr.net/npm/cuppajs/libs/components/cuppa.switch.min.js')

export function App(){
	let switchData = {name:"SwitchName", checked:true};
	return (
		<div >
			<cuppa-switch
				name={switchData.name}
				checked={switchData.checked}
				onChange={(e)=>{ console.log(e.target.checked) }}
			></cuppa-switch>
		</div>
	)
}
```

### Expected behavior

<cuppa-switch name="SwitchName" checked="true" ></cuppa-switch>

### Platform

All browsers

**Comment by mdynnl** [comment]
For custom-elements, solid assigns to property for dynamic props (or unkown props for native elements) i.e `node.checked = dynamic.value` also handling kebab-case to camelCase, whereas static `checked="true"` stays unchanged as attributes in template and (final html output). Solid also supports explicit https://www.solidjs.com/docs/latest/api#attr___ or https://www.solidjs.com/docs/latest/api#prop___ respectively if that is neccesssary for some reason.
