### ISSUE TITLE
Solid-Start SSR 'v' Client Side

### ISSUE THREAD

**Issue by KpjComp** [solidjs/solid#1693]
### Describe the bug

Back to playing with SolidJS, and noticed Solid Start, nice!!,..  Looking very promising.

Not sure if this is a Solid or Vite bug or even `solid-icons`, but while browsing some Solid repo's I noticed  `solid-icons`, I thought could I make it so that I could see all the icons in a pack.  Nice simple project, not very reactive I know, but very useful to see what's in the pack..

So I did ->

```
import * as aiIcons from "solid-icons/ai";
```

And then to render them all I could do ->

```
<>
{
  Object.entries(aiIcons).map(r => {
    const [name, Icon] = r;
    return <><span style={{ "margin-right": '0.6em' }}>{name}<Icon /></span></>
  })
}
</>
```

And this works like a charm in client mode,  and seems to work at first in SSR.   But when in SSR if you do a page refresh you get this error ->

```
TypeError: Comp is not a function
    at Proxy.createComponent (file:///home/keith/node/lib/node_modules/.pnpm/solid-js@1.7.3/node_modules/solid-js/dist/server.js:310:15)
    at eval (/src/routes/index.tsx:194:34)
    at Array.map (<anonymous>)
```

If your comment out the code save, the app will work again without icons of course, and then if you un-comment it works during partial update, but if you refresh the page again it would fail.

Also tried using `For`, and the same error.

### Your Example Website or App

Just local dev.

### Steps to Reproduce the Bug or Issue

Explained above.

### Expected behavior

SSR version to work the same as Client rendering.

### Platform

- OS: Line
- Browser: Chrome

**Comment by ryansolid** [comment]
I'd love to have a quick reproduction so I can see what's going on. Otherwise I need to try and remake this example myself. Comp is not a Function means precisely that. Still it is happening on a Proxy which suggests to me this might be HMR related. You can try turning HMR off and see if that changes anything.

Honestly, I probably won't get to this without a reproduction.

**Comment by KpjComp** [comment]
@ryansolid  

Ok, I've looked into this a bit further, and have found out what was causing it.

If you do -> `import * as ii from "solid-icons/ai";`

If you console log   `ii`   normally you will get all the functions as follows.

```
[Function: AiFillAccountBook],
[Function: AiFillAccountBook],
...
```

As you would expect.

But while in SSR `ii` contains ->

```
[Function: AiFillAccountBook],
[Function: AiFillAccountBook],
...
{
   AiFillAccountBook: [Function: AiFillAccountBook],
   AiFillAlert: [Function: AiFillAlert],
   ....
}
```

IOW:  You get an extra object exported that has all the exports again.

So what was happening, it was getting to this Object and try to render that, and of course an Object is not a function.

So a simple fix is ->

```
{
   Object.entries(ii).map(r => {
      const Icon = r[1];
      if (typeof Icon === 'function') {
         return <Icon />
      } 
   })
}
```

This extra Object on import only seems to happen in SSR, I assume it's there for CommonJS backwards compatibility, and the reason it wasn't doing this in Client mode is that it's always using ES modules.

**Comment by ryansolid** [comment]
Ah I see. And that is probably related to the bundler or the package and isn't something Solid specific. Why it is behaving differently is odd. The only thing I can think of is if the client build is using prebuilt and SSR is using application build or something like that. You'd think it would be the same on both sides. Unless `solid-icons` is doing something.

Is this Vite? Esbuild? I guess I'd be looking how this is being introduced. We might need to open an issue against `solid-icons` otherwise we might need to look at the bundler defaults.

**Comment by KpjComp** [comment]
It looks like it's Vite, it was your SSR starter for todo app that I modified.

Looks like I was unlucky to try out solid again, and then hit this.  In both cases I was doing `npm run dev`

To be fair, I assume its very rare to enumerate from an `import *`,  but for a quick and easy way to view all icons seemed a logical way to do it.

I don't believe it's `solid-icons`, as the icons are just a series of
```
export function AiFillAccountBook (props) {
```

Bit more digging, it's maybe obvious what's happening.  :-)


```
import * as ii from "solid-icons/ai";

console.log(Object.entries(ii).slice(-2));
```

You get ->
```
[
  [ 'AiTwotoneWarning', [Function: AiTwotoneWarning] ],
  [
    'default',
    {
      AiFillAccountBook: [Function: AiFillAccountBook],
      AiFillAlert: [Function: AiFillAlert],
....
```

Even though `solid-icons` has no `export default` something in the vite build is adding it,  that in itself might not be a problem if they had marked it as none enumerable, as for a `default` check it's not required to enumerate.

**Comment by ryansolid** [comment]
Yeah not really sure what to do with this one as it looks like a mismatch between like maybe CJS bundling and ESM. Or something weird like that. This issue has gone stale and it seems unlikely without a reproduction I will ever get to it. So cleaning this up and closing. If you are still experiencing the issue and have a reproduction please resubmit.
