### ISSUE TITLE
Strange Hydration bug

### ISSUE THREAD

**Issue by KevinBLT** [solidjs/solid#1697]
### Describe the bug

Hi,

I am sorry in advance, I can not build a nice reproduction, but maybe someone has an idea.

I updated to the newest solid-js version `1.5.7` -> `1.7.3`.

Testing the code, hydration suddenly failed with `Cannot read properties of null (reading 'nextSibling')`. 

This is the error:  
```
p.js:1 Uncaught TypeError: Cannot read properties of null (reading 'nextSibling')
    at get children [as children] (app.js:1:50283)
    at Object.fn (app.js:1:10267)
    at Da (app.js:1:4751)
    at Rn (app.js:1:4692)
    at Q (app.js:1:1284)
    at Wa (app.js:1:10208)
    at app.js:1:8367
    at _e (app.js:1:2879)
    at w (app.js:1:8360)
    at be (app.js:1:47956)
```
<img width="586" alt="image" src="https://user-images.githubusercontent.com/12692409/233800633-01227288-ca23-4311-9ab1-723c93284f1f.png">

So okay, I managed to find the underlaying codes:

```javascript
<label {...props} class="flag">
  <i class="icon camera-slash-solid"></i>

  <Show when={typeof count() == 'number'}><span>{ count() }</span></Show>
  <Show when={props.value}><span>{ props.value }</span></Show>

  {props.children}

</label>
```

So this somehow failed after uggrading. I compared the hydrations:

Before, this label was like this:

```html
<label data-hk="0-0-0-2-1-0-0-0-0-0-0-0-0-3-1-8-0-0-17">
  <i class="icon camera-slash-solid"></i><!--#--><span
              data-hk="0-0-0-2-1-0-0-0-0-0-0-0-0-3-1-8-0-0-18-0">0</span><!--/--><!--#--><!--/--><!--#--><!--/--></label>
```

After the upgrade, it was like this:
```html
<label data-hk="0-0-0-2-1-0-0-0-0-0-0-0-0-3-1-8-0-0-17">
  <i class="icon camera-slash-solid"></i><!--#--><span data-hk="0-0-0-2-1-0-0-0-0-0-0-0-0-3-1-8-0-0-18-0">0</span><!--/--><!--!$--><!--#--><!--!$--><!--!$--><!--/--><!--!$--><!--#--><!--!$--><!--!$--><!--/--></label>
```

So I created new functions and was just testing around, since it worked when I removed one show OR the children.

I ended with this:

```javascript
  const renderCount = () => <Show when={typeof count() == 'number'}><span>{ count() }</span></Show>;
  const renderKey   = () => <Show when={key()}><span>{ translate[key()] ?? key() }</span></Show>;
  const renderValue = () => <Show when={props.value}><span>{ props.value }</span></Show>;

  const renderCountAndValue = () => (
    <>
      {renderCount()}
      {renderValue()}
    </>
  )
```

NOW this works:
```javascript
<label {...props} class="flag">
  <i class="icon camera-slash-solid"></i>

  {renderCountAndValue()}

  {props.children}

</label>
```

For clarification this WILL NOT WORK:
```javascript
<label {...props} class="flag">
  <i class="icon camera-slash-solid"></i>

  {renderCount()}
  {renderValue()}

  {props.children}

</label>
```

So I was just moving lines around and this somehow fixed it, but it felt really just like a hack
and I have no idea what went wrong after upgrading.

### Your Example Website or App

#Private

### Steps to Reproduce the Bug or Issue

Please see above.

### Expected behavior

No error.

### Platform

- OS: macOS
- Browser: Chrome 112
- Version: 1.7.3

**Comment by ryansolid** [comment]
Yeah I think I know what this is. I'm overlabelling on spreads. I have a fix that I will release soon. I hope it fixes your issue as well.
