### ISSUE TITLE
Error when using Show with more than one direct child element

### ISSUE THREAD

**Issue by trfx351** [solidjs/solid#1707]
### Describe the bug

In my app I have a list of items and a few toggles to customize the displayed output of each item. Solid will sometimes remove/hide incorrect parts of the displayed output text, compared to what is intended, and eventually crash with a DOM exception. I think I have narrowed it down to using a ````<Show>```` component with more than one direct child.

### Your Example Website or App

https://playground.solidjs.com/anonymous/2a8653d0-8524-4a21-8c70-4c68f6e9024a

### Steps to Reproduce the Bug or Issue

1. Go to the playground link
2. The app shows a list of 3 items, with 3 toggles (signals) to customize the printed display of the items: show/hide ID, show/hide Name, show/hide number of Related items. The initial state of the display toggles is to show only Name.
3. Click "ID off" button to turn on the ID display. Then click "Related IDs off" to turn on the Related ID display.
4. Observer that wrong parts of the output are hidden (incorrect DOM nodes are removed)
5. If you play around with toggling the buttons on/off, it will eventually cause a DOM operation exception. I have not fully looked into the generated Solid output to see what exactly is happening.

### Expected behavior

Expected display after following the 3 steps:

````
M-1: Model 1 (2)
M-2: Model 2 (1)
M-3: Model 3 (0)
````

Actual display:
````
M-1: (2)
: M-2 (1)
M-3: Model 3 (0)
````

### Platform

- OS: Windows 10
- Browser: Chrome & Firefox
- Version: Latest

### Additional context

If you change the ````<Show>```` component on lines 66-69 from

````
<Show when={showId()}>
      {model.ID ?? "-"}
      <Show when={showName() || showRelatedId()}>: </Show>
 </Show>
````

to 

````
<Show when={showId()}>
<span>
      {model.ID ?? "-"}
      <Show when={showName() || showRelatedId()}>: </Show>
</span>
 </Show>
````

That is, if you wrap the contents in a ````<span>````, the behavior works as expected. I am not sure if the root cause here is that ````<Show>```` does not work correctly with more than one child element, but that seems to have fixed the issue in this case.

**Comment by ryansolid** [comment]
Yeah this is a regression in 1.7.x. My bad. I was trying to optimize something for hydration around textNodes and it seems to have broken this case.
