### ISSUE TITLE
Starting from version 1.6.7, webstorm code hints appear abnormal

### ISSUE THREAD

**Issue by GitOfJason** [solidjs/solid#1727]
### Describe the bug

When using version 1.7.0, I found that editing tsx files in webstrom could not trigger code hinting function for html tags, as shown in the figure below. Finally, I rolled back to version 1.6.6, and the code hinting function of html tags was available. Finally, it was confirmed that the code hinting function of html tags in tsx files was unavailable after version 1.6.7. The problem should have occurred on the `types/jsx.d.ts` file of solid.

#### version: 1.6.7
<img width="803" alt="image" src="https://github.com/solidjs/solid/assets/124339951/a339f9f0-2c9b-48bb-a307-e036cbb451fe">

<img width="972" alt="image" src="https://github.com/solidjs/solid/assets/124339951/0a863b76-343b-4a0c-9f4a-a78179655c15">

_____

#### vsrsion: 1.6.6
<img width="842" alt="image" src="https://github.com/solidjs/solid/assets/124339951/fbe9ea70-4c89-4283-a9c1-e939338c74b7">

<img width="981" alt="image" src="https://github.com/solidjs/solid/assets/124339951/bfd18c24-7983-4d1c-9df4-701f91564e8d">

### Platform

- OS: macOS
- Browser: Chrome
- Version: 113.0.5672.92

**Comment by ryansolid** [comment]
Is this related? https://github.com/ryansolid/dom-expressions/pull/242

**Comment by GitOfJason** [comment]
> Is this related? [ryansolid/dom-expressions#242](https://github.com/ryansolid/dom-expressions/pull/242)

Yes, I think it’s a relevant issue. Is there currently a solution to this problem? Or do we need to let WebStorm solve it?

**Comment by NoDocCat** [comment]
@GitOfJason I use [patch-package](https://github.com/ds300/patch-package) temporarily solved it.

**Comment by ryansolid** [comment]
Well it is an interesting one, in that we could change our types back to work better with Webstorm if we remove some of the nice organization that was contributed. If Webstorm isn't going to prioritize fixing it we might as well do that because I don't really care how nice the JSX types file looks compared to the usability of completions for a portion of users. It is unfortunate but I'm also ok with it.

**Comment by ChristianIvicevic** [comment]
Hey everyone, I'm from the WebStorm team at JetBrains and Ryan mentioned this issue last week when we met. I'll be relaying the information about it to raise awareness and we'll take a look at it once we find some time. Can't make any promises yet, but we'll keep you up to date.

**Comment by ChristianIvicevic** [comment]
Hey there, in our latest EAP 5 (232.7754.72) there have been several fixes to JSX-related issues within Solid, Preact and Co.
Would you mind checking whether your previously reverted changes of the types still cause false positives in our latest WebStorm EAP version?

**Comment by GitOfJason** [comment]
@ChristianIvicevic 
Thank you very much for your prompt response. I have verified in WebStorm 2023.2 EAP version, and the conclusion is that the issue has been fixed.

**Comment by ryansolid** [comment]
Thank you. Happy to close this one.
