### ISSUE TITLE
Resource can be `ready` but also return `undefined`

### ISSUE THREAD

**Issue by deluksic** [solidjs/solid#1739]
### Describe the bug

Please take a look at this example: https://playground.solidjs.com/anonymous/1c0baf1f-20e7-4bc8-a878-6afe824ce4c1

### Your Example Website or App

https://playground.solidjs.com/anonymous/1c0baf1f-20e7-4bc8-a878-6afe824ce4c1

### Steps to Reproduce the Bug or Issue

In the `createEffect`, the type of `shouldBeUndefinedButItsNot` is `number`, but console writes `undefined` on first run.
You might need to refresh for the console to capture the initial `undefined`.

### Expected behavior

I'm expecting the resource to not be `ready` unless there is a `number` ready.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by deluksic** [comment]
Could be related to #1725

**Comment by ryansolid** [comment]
Yeah not completely related. But it is interesting. When a resource has a false source it is considered waiting. Mostly it has no guarentees if that state will ever change. So it considers itself ready. But I suppose if it has never been resolved we should keep state that way. Everything mechanically works as expected but we aren't reflecting the expected state properly. Let me see if there is an easy way to special case this.
