### ISSUE TITLE
createResource swallows error

### ISSUE THREAD

**Issue by mathieuprog** [solidjs/solid#1744]
### Describe the bug

Errors happening in the fetcher of the `createResource` seem to be swallowed:

```ts
window.addEventListener('unhandledrejection', (e) => console.error(e));
window.addEventListener('error', (e) => console.error(e));

function getCurrentUserResource() {
  const [currentUser] =
    createResource<any>(
      async () => {
        console.log('hello!') // logs
        throw 'error'; // swallowed
      }
    );

  return currentUser;
}

getCurrentUserResource();
```

### Your Example Website or App

-

### Steps to Reproduce the Bug or Issue

-

### Expected behavior

Expected to see the error in the console

### Platform

- OS: Windows
- Browser: Chrome 113
- Solid: 1.7.5

**Comment by atk** [comment]
Yes, errors are handled by either the error property of the resource or solid's error boundaries or onError/catchError.

**Comment by ryansolid** [comment]
Yeah this by design. Resources work off reads, and error in the UI where they are read. I think ultimately error boundaries should have a better design that doesn't immediately unmount. More like:
```js
<ErrorBoundary>{
  (err) => /*... do stuff */
}</ErrorBoundary>
```
That way you always have the error where you can manage it. This is one of the 2.0 component changes we're evaluating.

Anyway. Current resolution is this is by design.

**Comment by mathieuprog** [comment]
I want all errors to be handled by my global listeners on error events and on promise rejection events, as they will send any error to an error reporting tool.

As you have mentioned, one option is to check the "error" property of the resource, so I created an effect.

This is my code simplified:
```ts
const [userResource, { refetch }] = // ...

createEffect(() => {
  if (userResource.state === 'errored') {
    // allows the event to reach the global listener on unhandledrejection events
    setTimeout(() => { throw userResource.error }, 0);
  }
});
````

Note that I need to use `setTimeout` here because if I don't, I noticed that throwing directly from an effet will break the other `createEffect`, i.e. they will not run. (https://discord.com/channels/722131463138705510/1115173423652540437/1115173423652540437).

This seems to work fine but I noticed an issue:

The `unhandledrejection` listener (`window.addEventListener('unhandledrejection', (e) => handleErrorEvent(e))`) sometimes run twice, sometimes only once.

It seems that even if I don't rethrow the error as shown above, sometimes the promise rejection event will reach the global listener, sometimes not.

On my machine, the event listener will be called about 1 out of 3 times twice.

**Comment by mathieuprog** [comment]
@snnsnn **Without** writing any `setTimeout`, the listener on `unhandledrejection` is called about 1 time on 3 on my machine when a `GET http://localhost:4001 net::ERR_CONNECTION_REFUSED` error occurs, as the server is purposely not running to test the error handling on the client).
I do not understand why I have an inconsistent behavior.
