### ISSUE TITLE
Delete store array item by setting `undefined` causes rendering error

### ISSUE THREAD

**Issue by leaysgur** [solidjs/solid#1748]
### Describe the bug

Docs says

> Set values to undefined to delete them from the Store.
> https://www.solidjs.com/docs/latest/api#updating-stores

But this code does not work.

```tsx
function Repro() {
  const [state, setState] = createStore({ items: [{ id: Date.now() }] });
  const addItem = () => setState("items", state.items.length, { id: Date.now() });

  const deleteItemNG = (idx: number) => setState("items", idx, undefined!); // 👈🏻
  const deleteItemOK = (idx: number) => setState("items", (items) => [...items.filter((_, i) => i !== idx)]);

  return (
    <ErrorBoundary fallback={(err) => <pre>{err.message}</pre>}>
      <button onClick={addItem}>ADD</button>
      <hr />
      <For each={state.items}>
        {(item, idx) => (
          <div>
            {item.id}
            <button onClick={() => deleteItemNG(idx())}>DEL(NG)</button>
            <button onClick={() => deleteItemOK(idx())}>DEL(OK)</button>
          </div>
        )}
      </For>
    </ErrorBoundary>
  );
}
```

It ends up with `Cannot read properties of undefined (reading 'id')` error.

Am I missing something?

### Your Example Website or App

https://playground.solidjs.com/anonymous/7cafb3a2-7dc3-44f5-9cd2-75f35aef92ec

### Steps to Reproduce the Bug or Issue

1. Open repro by playground url
2. Click `DEL(OK)` button works
3. Click `DEL(NG)` button does not work

### Expected behavior

Deleting can be done by `DEL(NG)` button too.

### Platform

- OS: macOS
- Browser: Firefox, Chrome
- Version: 113, 114

**Comment by snnsnn** [comment]
You are using the api incorrectly. Try `setState("items", undefined!)`.

**Comment by snnsnn** [comment]
If you are going to remove an item, filter the item and set the resulting array as the new value.

If you are going to update, you can map over the items and set the resulting array as the naxt value. Alternatively you can use path pattern: https://www.solidjs.com/docs/latest/api#updating-stores

**Comment by ryansolid** [comment]
The answer is above is correct.. deleting a key in an array leaves a hole. The actual operation is should be a filter, slice etc... I'm going to move this to discussions so we can track this as a Q&A.
