### ISSUE TITLE
Portal's children are not reactive

### ISSUE THREAD

**Issue by thetarnav** [solidjs/solid#1767]
### Describe the bug

The `<Portal>` component doesn't react to changes made to `props.children`.
Not sure if that was always the case, but it seems like a bug.

```tsx
<Portal><div>{reactive()}</div></Portal> // works
<Portal>{reactive()}</Portal> // doesn't work
```

### Your Example Website or App

https://playground.solidjs.com/anonymous/3e137d98-99eb-47db-92fa-e13ae7b4bc95

**Comment by Brendan-csel** [comment]
Workaround using a fragment...
```js
<Portal>{<>{reactive()}</>}</Portal>
```

**Comment by wjq990112** [comment]
Maybe this bug is caused by this line code:
https://github.com/solidjs/solid/blob/main/packages/solid/web/src/index.ts#L79
Because `props.children` will be executed immediately and return the value of `reactive`, we should wrap `props.children` into a function;
I would like to fix it.

**Comment by ryansolid** [comment]
Yeah this just looks like an oversight on refactoring. We just need to make sure the timing is still right.
