### ISSUE TITLE
SSR fails to run

### ISSUE THREAD

**Issue by pankajmyt** [solidjs/solid#1768]
### Describe the bug

I started with templated project 

`npx degit solidjs/templates/ts my-app` and able to run the project locally. In the next step I wanted to return rendered component via express-js.

I followed up vite's  documentation on ssr.
https://github.com/vitejs/vite-plugin-react/blob/main/playground/ssr-react/server.js
https://vitejs.dev/guide/ssr.html#building-for-production

```
"build:client": "vite build --outDir dist/client --ssrManifest",
"build:server": "vite build --outDir dist/server --ssr src/entry-server.tsx",
"serve": "NODE_ENV=production node server"
```

`entry-server.tsx` is as

```
import { renderToStringAsync } from 'solid-js/web';

import App from './App';

export function render(url: string, context: any) {
    return renderToStringAsync(() => <App />);
}
```

However, while serving route 
```
app.use('*', async (req, res, next) => {
  const url = req.originalUrl

  let template = indexProd
  // @ts-ignore

  let render = (await import('./dist/server/entry-server.js')).render

  const context = {}
  const appHtml = render(url, context)

  if (context.url) {
    // Somewhere a `<Redirect>` was rendered
    return res.redirect(301, context.url)
  }

  const html = template.replace(`<!--app-html-->`, appHtml)

  res.status(200).set({ 'Content-Type': 'text/html' }).end(html)
})
```

```
import { isServer, createComponent, spread, setAttribute, template, delegateEvents, insert } from 'solid-js/web';
                                            ^^^^^^^^^^^^
SyntaxError: The requested module 'solid-js/web' does not provide an export named 'setAttribute'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:190:5)
```

one after another it keeps saying `does not provide an export named 'xxx...`

### Your Example Website or App

https://github.com/pankajmyt/solid-vite-ssr

### Steps to Reproduce the Bug or Issue

1. Clone repo
2. npm install
3. npm run "build:client"
4. npm run "build:server"
5. npm run serve

### Expected behavior

some html should come

### Platform

MacOS Ventura 13.4 M2
Node v18.15.0

**Comment by ryansolid** [comment]
Here I fixed it up on stackblitz: https://stackblitz.com/edit/github-xgypdg

Key changes:

1. `ssr: true` in the plugin options is required to do SSR. By default the plugin doesn't have SSR enable so you were getting the wrong build.
2. `await` the render call in `server.js` as it was just serializing the promise into the page
3.  Add the `<!--app-html-->` into the index.html so that it would do the replacement.
