### ISSUE TITLE
'solid-js/h' is client-only, yet attempts to import 'solid-js/web/dist/server.js' at build.

### ISSUE THREAD

**Issue by shareable-vision** [solidjs/solid#1777]
### Describe the bug

As discussed in [previous issues](https://github.com/solidjs/solid/issues/1480), `solid-js/h` is intended to be client-only.

Importing `solid-js/h/jsx-runtime` on the client:
```ts
  createMemo(async () => {
      if (source() && !isServer) {
          const runtime = await import('solid-js/h/jsx-runtime')
          setContent((await evaluate(source() as string, runtime)).default as MDXContent)
      }
  })
```

This works during development but will not build, fails with:
`[RollupError]: "assign" is not exported by "node_modules/solid-js/web/dist/server.js", imported by "node_modules/solid-js/h/dist/h.js".`

Because `solid-js/h` is client-only, it should not be importing from `solid-js/web/dist/server.js`.

Instead, the first line of `solid-js/h` should explicitly import from `solid-js/web/dist/web.js`.

In practice, this also requires declaring as a module:
`declare module "solid-js/web/dist/web.js"`

### Your Example Website or App

https://stackblitz.com/edit/issue-solidjs-h

### Steps to Reproduce the Bug or Issue

1. Import `solid-js/h/jsx-runtime` into client environment.
2. Run `solid-start build`

### Expected behavior

Rollup should successfully build SolidJS runtime into client bundle.

### Platform

- OS: Linux
- Browser: Brave ([Version 1.52.117 Chromium](https://brave.com/latest/))
- Version: solid-start v0.2.26

**Comment by ryansolid** [comment]
Hmm.. So the scenario is you want to include `solid-js/h` in a server rendered app? Because setting `ssr: false` in your example works. There are a few other ways to lazy load it for client only but the problem right now as I can see in your example is you are trying to include it in a server build which will not work.
