### ISSUE TITLE
Calling `props.ref` multiple times with a function when using magic refs calls the function

### ISSUE THREAD

**Issue by otonashixav** [solidjs/solid#1783]
### Describe the bug

`props.ref` is transformed to:
```ts
let magicRef;
_$createComponent(Counter, {
  ref(r$) {
    const _ref$ = magicRef;
    typeof _ref$ === "function" ? _ref$(r$) : magicRef = r$;
  }
})
```
Which is problematic if `r$` is a function, and `props.ref` is called again after calling it with a function.

### Your Example Website or App

https://playground.solidjs.com/anonymous/9ea41eca-8dd8-40fc-a659-c5929b60af3b

### Steps to Reproduce the Bug or Issue

Click the button more than once.

### Expected behavior

Nothing should be logged since we never call `logCount` -- we only expect it to be set when the button is clicked. Instead it's called on subsequent clicks of the button.

### Platform

N/A

### Additional context

Saving the initial value of the magic ref could work, though that's only feasible if it is static (i.e. not `ref={refs[i]}`). This seems pretty hard to run into, so maybe not worth fixing?

**Comment by lxsmnsyc** [comment]
heh, that's a weird scenario, and honestly it's a bit weird on how should we approach this.

**Comment by ryansolid** [comment]
Hmm.. It does assume that the ref value can't be a function to support the callback form. And we want to support the callback form so I suggest boxing the value in an object if you need to pass the function around. I think this is one of those by-design things.

I suppose the approach is to set a flag when it first runs to decide what type of ref it is.. but I think that is probably tricky especially with runtime mechanisms like spreads that won't maintain that context.  This feels like a won't fix.
