### ISSUE TITLE
`createMemo` gets works only two times when lazily used

### ISSUE THREAD

**Issue by AFatNiBBa** [solidjs/solid#1793]
### Describe the bug

I'm trying to create a proxy handler that will lazily create a memo for each getter the first time it is called, this code is pretty lengthy so, when you'll see the peculiar things I'm about to do, keep in mind that this is a very minimal example of what I'm trying to do.
Let's start without the memo:
```tsx

import { createSignal, createMemo } from "solid-js";
import { render } from "solid-js/web";

export default function Index() {
  const [g, s] = createSignal(1);
  var f: () => number;
  
  function getter() {
    return () => {
      console.log("Updated getter");
      return g() * 98;
    };
  }

  console.log("Before returning");

  return (
    <>
      <button onClick={() => s((x) => x + 1)}>
        {(() => {
          f ??= getter(); // Lazily created
          return f();
        })()}
      </button>
      
      <button onClick={() => console.log("Getter value is", f())}>GET</button>
    </>
  );
  
}

render(Index, document.getElementById("app")!);
```
The expected result are two buttons: The first updates the signal and triggers the execution of `f`, which prints "Updated getter" on the console and changes the content of the button; The second buttons prints the result of `f` to the console, since it is not a memo "Updated getter"  gets printed too.
Now lets wrap the function with a memo:
```tsx
function getter() {
  return createMemo(() => {
    console.log("Updated getter");
    return g() * 98;
  });
}
```
Now if I click the first button everything will work like before, but if I click the second I will not get "Updated getter" on the console, as expected. The problem is that if I click the first button again it just doesn't work, the memo doesn't get updated.
But if I slightly change the place where I use the signal from this
```tsx
{(() => {
  f ??= getter(); // Lazily created
  return f();
})()}
```
To this
```tsx
{(f ??= getter())()}
```
Then it works as expected, this is because in the compiled output `f` is not lazily assigned because the solid compiler is clever enough to understand that there is no need to wrap the expression in a function since it can just remove the "()" at the end, so it does this
```js
_$insert(_el$, f ??= getter());
```
Instead of this
```js
_$insert(_el$, () => {
  f ??= getter(); // Lazily created
  return f();
});
```
This doesn't work for me since `f` not being lazy defeats the whole purpose.
Why can't I lazily create a memo? 

### Your Example Website or App

You can use the solid playground, but use the real console to see the output, because the fake one shows the wrong result

### Steps to Reproduce the Bug or Issue

Paste the code on the solid playground and then click the generated button (The one with the number) more than once

### Expected behavior

The value should increase at each click

### Platform

- OS: Windows
- Browser: Edge with chromium
- Version: 114.0.1823.58

**Comment by thetarnav** [comment]
If you're doing something like this
```tsx
<>
{(() => { // <- this scope will be wrapped in an effect
	memo ??= createMemo(() => /* ... */) // <- memo created in an effect will be disposed when it reruns
	return memo() // <- you're subscribing to the memo in the effect
})()}
</>
```
you are creating a loop of
'run effect' -> 'create memo' -> 'subscribe to memo' -> 'update the signal' -> 'rerun the memo' -> 'rerun the effect' -> 'dispose old memo' -> 'read from the old memo?' -> ...

The compiler may be doing something weird, but I think the logic is wrong too

**Comment by AFatNiBBa** [comment]
Thank you, didn't know that the lifecycle of an effect was this tiny.
Additionally `createLazyMemo` has been quite helpful
