### ISSUE TITLE
SSR Context with store not displaying reactive value

### ISSUE THREAD

**Issue by ryoid** [solidjs/solid#1795]
### Describe the bug

I have a context that uses a store with an object and retrieve by keys, with the value updated on mount. The displayed values are not updated when this is the first page loaded. Using `console.log` in the effects show the correct state. 

Navigating from another page to this page works.
Doing the same without context works and `ssr: false` works.

```tsx
// context
type Data = {
  [k: string]: {
    email: string;
  } | null;
};
const [data, setData] = createStore<Data>({
  jeff: null,
});
onMount(() => {
  setData('jeff', {
    email: 'jeff@mail.com',
  });
});
```
```tsx
const { data } = useData();
const state = createMemo(() => {
  if (!data['jeff']?.email) {
    return 'No email';
  }
  return 'Has email';
});
return <>
  <div>State: {state()}</div> // Does not update to "Has email"
  <div>email: {data['jeff']?.email}</div> // Does not update to show email
</>
```

### Your Example Website or App

https://stackblitz.com/edit/github-afuq7e?file=src%2Froutes%2Findex.tsx

### Steps to Reproduce the Bug or Issue

1. Go to `/` path
2. No data would be displayed
3. console logs in `createEffects` display the state correctly
4. Go to `/links`, then navigate to the problem route - it works

### Expected behavior

HTML is updated to reflect state 

### Platform

- OS: macOS
- Browser: Chrome
- Version: 114.0.5735.198

### Additional context

This issue occured in my project when using returning enums in `state` memo, no issues with normal variables. However, when making the reproduction I could not make it this far.
```tsx
const state = createMemo(() => {
    if (!data['jeff']?.email) {
      return State.NO_EMAIL; // returning a string worked
    }
    return 'Has email';
});
// simply having the above also affected reading the store value, even when `state` was not being used:
return <div>{data['jeff']?.email}</div>
```

**Comment by ryansolid** [comment]
Yeah it seems to be some sort of race condition. When I put a breakpoint in the onMount call it works. I will explore further.
