### ISSUE TITLE
JS Class Props fail in Solid

### ISSUE THREAD

**Issue by Guergeiro** [solidjs/solid#1808]
### Describe the bug

I initially filed a bug report in Astro's repository (https://github.com/withastro/astro/issues/7652) since I have a working code with this in Solid 1.5.2, so I assumed it was an issue with Astro, but I just spawned a stackblitz project with a newer version of Solid and it failed just as well.

### Your Example Website or App

https://stackblitz.com/edit/github-bzkd2c-gkrvsm

### Steps to Reproduce the Bug or Issue

1. Create a JS Class with some prop.
2. Add an async method that tries to access said prop.
3. Instantiate said class in Solid Component.
4. Call the method with `createResource`

*Note:* I haven't tested if it's a problem with the fact that the method is an async one, or a problem with `createResource`, but the stackblitz is minimal enough.

### Expected behavior

We should be able to use instantiated class properties normally.

### Platform

- OS: Linux
- Browser: Edge

**Comment by Debbl** [comment]
You can try writing like this.
`const [foo] = createResource(async() => await service.get())`
I guess it directly obtained this function without binding this.
https://stackblitz.com/edit/github-bzkd2c-ryyng3?file=src%2FTestComponent.tsx

**Comment by Guergeiro** [comment]
Although that works @Debbl , I may have simplified the problem. Say you have a pagination to that get service and take the page as param. Example:

```ts
const [page, setPage] = createSignal(1);

const [response] = createResource(async () => {
  return await service.get({
    page: page(),
  });
});
```
That example successfully works having with 

Now, unless I'm doing something wrong, it seems I never get a "refreshed" content when `page` changes. But if I do it like this, it works:
```ts
const [page, setPage] = createSignal(1);

const [response] = createResource(() => {
  return {
    page: page(),
  };
}, service.get);
```

**Comment by Debbl** [comment]
@Guergeiro You can see this API `createRource` on the document. if you want to refresh when the page change. You can try writing like this. Pass a signal that needs to be monitored in the first parameter.
```js
const [page, setPage] = createSignal(1);

const [response] = createResource(() => page(), async () => {
  return await service.get({
    page: page(),
  });
});
```
```js
const TestComponent: Component = () => {
  const [page, setPage] = createSignal(0)

  const [foo] = createResource(() => page(), async() => await service.get())

  setInterval(() => {
    setPage(page() + 1);
    console.log("page", page())
  }, 3000)

  return <Suspense fallback={<p>Error</p>}>
    <For each={foo()}>
      {(item) => {
        return <p>{item.title}</p>
      }}
    </For>
  </Suspense>
}
```

<img width="1044" alt="image" src="https://github.com/solidjs/solid/assets/61053131/9fbbc497-adc2-48c8-9b20-fb9966f9e28e">

**Comment by Guergeiro** [comment]
This does seem to work. Although it is kinda "hidden" between words in docs. I guess it would be productive to have multiple examples in the docs.

**Comment by ryansolid** [comment]
Yeah the bug posted here is simply that JavaScript doesn't have the right `this` when you just pass a reference to a function instead of calling. Binding or calling it directly fixes the posted issue. The tutorial for resources has an ok example: https://www.solidjs.com/tutorial/async_resources

But I agree reference docs could be better. Luckily the new docs have done a lot better here I think: https://docs.solidjs.com/references/api-reference/basic-reactivity/createResource

Anyway glad this issue has been resolved.
