### ISSUE TITLE
Please let's avoid in-range breaking changes

### ISSUE THREAD

**Issue by trusktr** [solidjs/solid#1810]
### Describe the bug

The following demo is now broken because something in Solid changed.

### Your Example Website or App

https://codepen.io/trusktr/pen/NWNaMZa

### Steps to Reproduce the Bug or Issue

Click on the box. The number does not increment.

### Expected behavior

As a user, I expect use of SemVer to mean that I will prevent breaking changes in my previous creations.

### Platform

- OS: any
- Browser: any

### Additional context

The given example is using standard SemVer versioning, but Solid released an in-range breaking change, so the example no longer works.

There is no code bug here. It is known that Solid releases in-range breaking changes intentionally. This is considered a bad practice by many!

**Comment by yume-chan** [comment]
Isn't it because `https://esm.sh/@lume/element@^0.7.0/dist/variable.js` is importing from `/stable/solid-js@1.7.7/es2022/solid-js.mjs` so there are two Solid instances?

It works after replacing 

```js
import { variable } from "https://esm.sh/@lume/element@^0.7.0/dist/variable.js";
```

with

```js
import { variable } from "https://esm.sh/@lume/variable@0.8.0?deps=solid-js@^1.0.0";
```

**Comment by ryansolid** [comment]
@yume-chan Thank you. You are correct. I see two versions of Solid and when we get around to updating the Signals there are no observers which is pretty surefire sign of this. Looks like the templating is on 1.7.8 and the application is on 1.7.7.

**Comment by trusktr** [comment]
Hmmm, I still wonder, even if it was my fault (sorry about that if it was), could Solid at least try to pull its internals from a global cache to attempt to still work even if there are duplicates?
