### ISSUE TITLE
Allow initializing undefined objects in store setter path

### ISSUE THREAD

**Issue by quasaray** [solidjs/solid#1813]
### Describe the bug

Currently when setting a nested value under undefined objects, trying to set a nested value will throw an error and fail to update. (demonstration https://stackblitz.com/edit/solidjs-templates-ga3sxz?file=src%2FApp.tsx)

I know a workaround is to pass the complete object and let solid merge everything, but that loses the granularity of the path syntax.

### Your Example Website or App

https://stackblitz.com/edit/solidjs-templates-ga3sxz?file=src%2FApp.tsx

### Steps to Reproduce the Bug or Issue

1. Create a store with an empty object
2. Use updater to set nested value e.g. setStore('nested', 'path', 1)
3. An error is logged to the console `Uncaught TypeError: Cannot read properties of undefined`

### Expected behavior

It would be nice if the store setter checks intermediate objects if they are null, and creates empty objects to prevent this kind of undefined error.

### Platform

- OS: Windows
- Browser: Chrome
- Version: [e.g. 91.1]

**Comment by ryansolid** [comment]
And use the fact it is a string to determine whether it is an object or an array? I avoided this because I didn't want to make that assumption.

**Comment by quasaray** [comment]
Oh I forgot that arrays also can use a single index
In that case it is not worth changing the default, it is definitely safer to assume everything is defined than to assume everything should be an object.
I guess the best way is what I was already doing, which is to write a custom updater and call it with `produce`.
That is simpler to implement outside of solid, so there isn't anything else which needs to change.
