### ISSUE TITLE
Typescript erros in button tag an frame

### ISSUE THREAD

**Issue by AesthetiCoder** [solidjs/solid#1822]
i am getting this typescrip error in a normal button

`Property 'forwardRef' does not exist on type 'ButtonHTMLAttributes<HTMLButtonElement>'.`

```jsx
      <button
        forwardRef={slider}
        onMouseMove={handleMove}
        onMouseUp={handleStopDragging}
        onMouseDown={handleStartDragging}
        onMouseLeave={handleStopDragging}
        class='scroll-horizontal rating__container'
      >
        <For each={homeLocale.rating.data}>
          { (ratingData) => <CardRating rating={ratingData} /> }
        </For>
      </button>
```

also in a frame i get this typescript error

`Property 'frameborder' does not exist on type 'IframeHTMLAttributes<HTMLIFrameElement>'.`

```jsx
  <iframe
    {...props}
    src={source}
    frameborder='0'
    allowfullscreen
    class='modal-video'
    title='YouTube video player'
    allow='autoplay; encrypted-media'
  />
```

there is a lot of typescript issues in solid also i want to mention another issue not relevant to solid but relevant to solid-meta more than 2 mounths and no update

[solid-meta/#31](https://github.com/solidjs/solid/issues/1824)

if the forwardRef issye is not solved i cant compile the project

**Comment by Debbl** [comment]
This issue https://github.com/solidjs/solid/issues/1639 seems to mention.

**Comment by mosheduminer** [comment]
You're getting a typescript error for `forwardRef` because there is no such property on buttons (or any other element). Perhaps you meant to use the special `ref` property?

**Comment by ryansolid** [comment]
Yeah there is no `forwardRef` prop in Solid. Maybe you meant `ref`.

It's also possible that some deprecated properties never made it into our JSX types. `frameborder` for example is deprecated and no longer supported in all user agents(https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe). We've been a bit loose here to be fair, so its omission was probably simply because it wasn't in the non-deprecated list when we set up the types.

The Solid Meta issue is legit. I missed that one. I've moved it to the Solid repo so it is in the right place.

**Comment by AesthetiCoder** [comment]
Let me explain what i want to do, i dont kwon how wto do a hook with ref i see this in the docs of ["ref"](https://www.solidjs.com/tutorial/bindings_forward_refs)

i have a hook let`s called useRating.tsx

```tsx
const useRating = () =>
{
  let slider: undefined | HTMLButtonElement;

  const handleMove = (event: MouseEvent) =>
  {
      // Change the slider informaion ref
  };

  return {
    handleMove,
    slider
  };
};
```

when i try tu use this ref in a component i get an error, how can i separate the ref outside the component ?

button.tsx

```tsx
      const { slider, handleMove } = useRating();
   
      <button
        ref={slider}
        onMouseMove={handleMove}
      >

      </button>
```

**Comment by mosheduminer** [comment]
Assigning a variable through ref only works due to a compiler trick, and only works when the variable was defined (with `let`) in the same component. In your case, you should use a signal for slider in useRating, return the setter, and pass that setter to `ref`.

**Comment by AesthetiCoder** [comment]
you are right using a signal works fine, but it is the only method to do it ? i think it is better to not use a signal, a variable is good just for a ref, for now i accept that as a answer

**Comment by mosheduminer** [comment]
Yes, using a signal is the only way to have define a ref not in the same function as the element it is a ref for.

**Comment by ryansolid** [comment]
Yeah that is the answer.. if the value can change it should be a Signal.
