### ISSUE TITLE
Typescrip link properties not supported

### ISSUE THREAD

**Issue by AesthetiCoder** [solidjs/solid#1824]
I have a normal solidjs app whit solid meta and i am getting an error with typescript, i can put the sizes and the srcset of the image for a responsive image.

```jsx
<Link
  rel='preload'
  as='image'
  href='/logo.png'
  imagesrcset="/logo.png?width=223w ..........."
  imagesizes='100vw'
/>
```

```bash
Property 'imagesrcset' does not exist on type 'IntrinsicAttributes & LinkHTMLAttributes'
Property 'imagesizes' does not exist on type 'IntrinsicAttributes & LinkHTMLAttributes<HTMLLinkElement>
```

**Comment by ryansolid** [comment]
I've added them to the types here. They will be in the next version of Solid. https://github.com/ryansolid/dom-expressions/commit/b63993dea6ff4d715763fc1f3f5d23980fafbe1c
