### ISSUE TITLE
lazy bahave strangely with vite-plugin-dynamic-import

### ISSUE THREAD

**Issue by qchenqchen** [solidjs/solid#1830]
### Describe the bug

I have the following plugin enabled for vite: vite-plugin-dynamic-import, vite-plugin-solid, and vite-plugin-solid-svg. Also, I have devicon added as program dependency. When I attempts to dynamic load svg as component from devicons, the loaded component did not appear to be rendered in the DOM tree.

### Your Example Website or App

https://stackblitz.com/edit/solidjs-templates-3zkr4x?file=src%2FApp.tsx

### Steps to Reproduce the Bug or Issue

1. Run the app and wait for it to load. Nothing should appear in the `<header>` element.
2. Open console, the dynamic import result should have been logged.
3. Store the result as a global var, call it with no parameters. An `<svg>` element should be logged to the console. If instead, the call result is appended to an element, the SVG would appear.

### Expected behavior

As a user, I would expect the SVG component to be rendered onto the screen properly.

### Screenshots or Videos

After Step 1 & 2:
![image](https://github.com/solidjs/solid/assets/112787240/696753b0-60dc-449d-ab29-690c5a74a250)
After Step 3:
![image](https://github.com/solidjs/solid/assets/112787240/d1f467c1-b3da-42e8-9707-989b8e35993a)

### Platform

- OS: server running in WSL2, browser running in Windows
- Browser: Firefox
- Version: 115.0.3

**Comment by qchenqchen** [comment]
current working workaround: wrap dynamic import with `createSignal`, i.e.,

```
const DynamicIcon: Component<{ name: string } & JSX.SvgSVGAttributes<SVGSVGElement>> = (props) => {
  const name = props.name
  delete props.name
  const [comp, setComp] = createSignal<JSX.SvgSVGAttributes<SVGSVGElement>>(null)
  import(`devicon/icons/${name}/${name}-plain.svg`).then((c) => setComp(c.default(props)))
  return <>{comp}</>
}
```

**Comment by ryansolid** [comment]
It's because lazy only works on default imports.. or rather expects `.default` to be returned on it.

So deleting accessing the `.default` fixes your problem:

```jsx
const Icon = lazy<Component<JSX.SvgSVGAttributes<SVGSVGElement>>>(() => import(`devicon/icons/${name}/${name}-plain.svg`))
```

**Comment by qchenqchen** [comment]
Indeed, its on my fault. Thank you so much!
