### ISSUE TITLE
A resource created with a signal is unresolved when the signal's initialValue is falsy

### ISSUE THREAD

**Issue by ii41** [solidjs/solid#1853]
### Describe the bug

When `createResource` is called with a signal, and the signal has an `initialValue`, the resource's state behaves differently depending on the `initialValue`. From my experimentation, `null`, `undefined`, and `false` will cause the resource's state to keep being "unresolved" until the set function of the signal is called with another value, while other values will make the resource's state go towards "ready".

### Your Example Website or App

https://playground.solidjs.com/anonymous/223b4e99-a382-41d6-a43f-f6e1bf063337

### Steps to Reproduce the Bug or Issue

Follow the solidjs playground link and see how the states of resources are different based on the initial value of the signal.

### Expected behavior

The resource behaves consistently whatever the `initialValue` of the signal is.

### Platform

- OS: Linux
- Browser: Chromium
- Version: 87.0.4280.144

### Additional context

Thank you very much for this great framework!

**Comment by emdede** [comment]
This is mentioned in [the docs](https://www.solidjs.com/docs/latest/api#createresource), albeit rather innocuous, pretty much verbatim `fetchData will be called as soon as sourceSignal has any value other than false, null, or undefined.`

Not saying that your point is moot, but it's not a bug in that it is known and documented behavior.

**Comment by ii41** [comment]
I see... Thank you for pointing me there. I somehow missed it and this does look like a bug.
