### ISSUE TITLE
Unable to find DOM nodes for hydration key

### ISSUE THREAD

**Issue by MariuzM** [solidjs/solid#1855]
### Describe the bug

When passing SVG component as prop to another component I'm getting `Unable to find DOM nodes for hydration key` issue, ive seen post here some solved `const c = children(() => <span>{props.children}</span>);` but I'm really confused is this the best approach. 

<img width="1146" alt="image" src="https://github.com/solidjs/solid/assets/36937039/6c346740-4917-4c48-a2e1-50f57fec8e63">

```tsx
import { type JSXElement } from 'solid-js';

export default function Test() {
  return (
    <main>
      <TextInput iconLeft={<Profile />} />
    </main>
  );
}

export const TextInput = (p: { iconLeft?: JSXElement }) => {
  return <div>{p.iconLeft ? p.iconLeft : 'No Icon'}</div>;
};

export const Profile = () => {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      stroke-width={1.5}
      stroke="currentColor"
      class="w-6 h-6"
    >
      <path
        stroke-linecap="round"
        stroke-linejoin="round"
        d="M15.75 6a3.75 3.75 0 11-7.5 0 3.75 3.75 0 017.5 0zM4.501 20.118a7.5 7.5 0 0114.998 0A17.933 17.933 0 0112 21.75c-2.676 0-5.216-.584-7.499-1.632z"
      />
    </svg>
  );
};
```

Please remove also `Your Example Website or App` not all issues need example when here is a code that shows 

### Your Example Website or App

No repo

### Steps to Reproduce the Bug or Issue

Just passing the file via prop

### Expected behavior

Not get the message 

### Platform

Version: 1.81.1
Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
Date: 2023-08-09T22:40:25.698Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.6.0

**Comment by MariuzM** [comment]
It does work now with children function but just feels odd writing it and confusing, wish there was a better way

<img width="663" alt="image" src="https://github.com/solidjs/solid/assets/36937039/4aa5adac-eb22-4ef1-865a-60f1f2db3a3b">

**Comment by thetarnav** [comment]
would `"iconLeft" in props ? props.isonLeft : <Fallback/>` or `props.iconLeft || <Fallback/>` work?

**Comment by MariuzM** [comment]
both worked, i'm confused :D 
what is diff between props.iconLeft || <Fallback/> and children()?

**Comment by thetarnav** [comment]
```ts
let last_hk = 0
function getUniqueHydrationKey() {
	return ++last_hk
}

const props = {
	get children() {
		const hk = getUniqueHydrationKey()
		return `<div data-hk="${hk}"/>`
	}
}

// children getter is called twice:
return props.children ? props.children : "fallback"

// children getter is called once:
return props.children || "fallback"

// same with children():
const resolved = children(() => props.children) // created a memoized signal like createMemo
return resolved() ? resolved() : "fallback"
```
