### ISSUE TITLE
onCleanup gets latest value of tracked signal instead of previous value

### ISSUE THREAD

**Issue by delph123** [solidjs/solid#1856]
### Describe the bug

When accessing a tracked signal during onCleanup, the value received is the latest value of the signal (the new value that the developer sent to the signal setter and that triggered the reactive loop).

I don't know if it makes sense, but I imagine the developers will expect the value of the signal to be the previous value when accessed during clean-up step (for example if the signal is the resource to clean-up).

Take this small code example:

```javascript
  const [target, setTarget] = createSignal(/* some thing target to be install at each value change */);

  createEffect(() => {
    onCleanup(() => uninstall(target()));
    install(target());
  })
```

I would expect that the target() represents the previous value before the change when accessed during cleanup, so that the proper target gets uninstalled, while the new target gets installed.

This is not critical as there are other ways to make it work (by hoisting the access to target() at the beginning of the effect for example), but, unless I'm misunderstanding it, the current behavior may not align with what could be expected by developers.

### Your Example Website or App

https://playground.solidjs.com/anonymous/3494f16f-1f3c-4a92-b696-d3fa0ff92740

### Steps to Reproduce the Bug or Issue

1. Go to example site (solid playground)
2. Click on the counter button
3. In the console, the values received by effect, cleanup & mount functions are logged
4. We can see that the value received during cleanup is the same as the one received by the effect & mount handler

### Expected behavior

I would expect that when accessing a signal in a cleanup function, the value of the signal has not yet changed. Or in other words, the signals accessed during cleanup returns their previous values.

### Platform

- OS: macOS
- Browser: Chrome
- Version: 115.0

**Comment by thetarnav** [comment]
Changing the value caused the effect to rerun, so it makes sense that you won't get an outdated value if you read from the signal again. Because signal is a function that will always give you the latest underlying value.

So you expect `onCleanup` to be special-cased somehow to stay in the past? Or the signal to not actually be updated until the effect runs?

What about a scenario like this:
```ts
const [count, setCount] = createSignal(1)

createEffect(() => {
  console.log("effect", count())
  onCleanup(() => {
    console.log("cleanup", count())
  })
})

// later
batch(() => {
  setCount(2)
  console.log("before effect", count())
})

/* currently:
  effect 1
  before effect 2
  cleanup 2
  effect 2
*/

/* with cleanups in the past:
  effect 1
  before effect 2  (should this also stay in the past?)
  cleanup 1
  effect 2
*/
```
https://playground.solidjs.com/anonymous/1edc86de-5942-4bce-892b-7e7fb919f2ce

**Comment by delph123** [comment]
First of all, thanks for your very quick feedback and sorry for my late response. It allowed me to further investigate on the topic and gain a few more insights.

So, I know that's the way I wrote it but, I'm not expected the signal to be "in the past" during onCleanup, it was only my way of trying to explain the problem clearly and succinctly. However, my mental model of how the onCleanup works is that it is an effect that is triggered right _before_ the new state is changed, in order to clean-up the previous state.

In plain javascript, here is a oversimplified version of how setSignal seem to work:

```javascript
function setSignal(newState) {
    signalState = newState;
    observers.forEach((obs) => {
        obs.cleanup();
        obs.rerun();
    });
}
```

I would argue that this implementation could be seen as flawed with regard to the principle of least astonishment, considering that the developer using the setSignal / onCleanup version may think of onCleanup being called before the signalState is changed.

```javascript
function setSignal(newState) {
    observers.forEach((obs) => {
        obs.cleanup();
    });

    signalState = newState;

    observers.forEach((obs) => {
        obs.rerun();
    });
}
```

With that in mind, your example log would turn into something more logical:

```javascript
  effect 1
  cleanup 1
  before effect 2 (after the cleanup, the signal's value is set)
  effect 2
```

That being said, I tend to think such a change could also be seen as problematic for at least two reasons:

1. The change would probably be a breaking change, seing that it affects the way and order of the effects in Solid
2. Your example showcase another problematic think with my second implementation, the cleanup part as it must be done before the state change will need to be synchronous, while the re-run part can be asynchronous (performed during next microtask in an Effect I guess) -> this asymmetry does trouble me...

**Comment by delph123** [comment]
One last thing: I compared the cleanup behavior of React for reference.

```javascript
  const [count, setCount] = useState(0);

  useEffect(() => {
    console.log("effect:", count);
    return () => console.log("cleaning:", count);
  });
```

For sure, due to the closure, the state value during cleanup the the value from the previous state. This is consistent with my mental model but mainly as a result of the way reactivity works in React.

More interesting:
* If we have multiple effects, React schedules all cleanups before all effects.
* On the other hand, when the cleanups are run, the state has already been changed (and reflected in the DOM)

Doing something like that in Solid (batching all cleanups before all re-runs, instead of running the cleanup/re-run cycles in sequence) seem a little bit far fetched and probably inconsistent as you demonstrated.

**Comment by ryansolid** [comment]
To be fair it is trickier than that for us because even if we schedule an effect we don't know if it will run because it still depends on the value being pulled out of upstream derived values. It's possible an upstream equality check stops the effect from running. In so it is pretty hard for us to run the cleanups at any other time than immediately before an effect runs.

The closure trick works here as well luckily and that is what I suggest being done to "solve" this as I think different scheduling will not work.

**Comment by delph123** [comment]
Fair enough.

After looking up the way react work on the topic, I was pretty much convinced that it would be irrealistically complex to solve this "issue". And that was before even considering all the algorithm around graph resolution and the possibility an effect may not re-run if value is changed back... Anyway, I wanted to let you take the opportunity to consider this issue before closing it.

I guess I will close it now, and try to change my mental model. Thanks anyway :)
