### ISSUE TITLE
Issue with form DOM

### ISSUE THREAD

**Issue by qlaffont** [solidjs/solid#1870]
### Describe the bug

I am unable to add a div  when I have a form  who is parent. 

Uncaught TypeError: can't access property "firstChild", _el$4 is null
    Settings index.tsx:14
    Settings index.tsx:40
    HMRComp @solid-refresh:25
    untrack dev.js:435
    HMRComp @solid-refresh:25
    runComputation dev.js:691
    updateComputation dev.js:674
    createMemo dev.js:251
    HMRComp @solid-refresh:22
    c dev.js:545
    untrack dev.js:435
    c dev.js:541
    runComputation dev.js:691
    updateComputation dev.js:674
    devComponent dev.js:552
    createComponent dev.js:1263
    App App.tsx:8
    HMRComp @solid-refresh:25
    untrack dev.js:435
    HMRComp @solid-refresh:25
    runComputation dev.js:691
    updateComputation dev.js:674
    createMemo dev.js:251
    HMRComp @solid-refresh:22
    c dev.js:545
    untrack dev.js:435
    c dev.js:541
    runComputation dev.js:691
    updateComputation dev.js:674
    devComponent dev.js:552
    createComponent dev.js:1263
    _cleanup index.tsx:35
    render dev.js:114
    updateFn dev.js:181
    runUpdates dev.js:795
    createRoot dev.js:186
    render dev.js:112
    <anonymous> index.tsx:35

### Your Example Website or App

https://github.com/qlaffont/lestudio-app

### Steps to Reproduce the Bug or Issue

1.  Use this template : https://github.com/AR10Dev/tauri-solid-ts-tailwind-vite
2. Add form with a div inside
3. pnpm dev
4. Render

### Expected behavior

As a user, it should render the page.

### Platform

- OS: Linux
- Browser: Firefox Browser Developer & Chrome
- Version: 118.0b2 / 116.0.5845.140

**Comment by qlaffont** [comment]
After some checks it seems to be related to : https://github.com/qlaffont/lestudio-app/blob/master/src/pages/settings/index.tsx#L40

I try to to convert it in a memo (createMemo) doesn't work too ...

**Comment by qlaffont** [comment]
@ryansolid any clue ?

**Comment by qlaffont** [comment]
@elite174 try what i say on my comments it seems to be related with date display

**Comment by elite174** [comment]
@qlaffont This is a bug in the compiler. So the error appears because of wrong compilation of the template. Probably dom-expressions should be fixed.

**Comment by qlaffont** [comment]
So how i can fix that ?

**Comment by ryansolid** [comment]
I haven't had a chance to look at this one yet. It does look like a compiler mismatch. I imagine the reproduction is already probably pretty minimal. But putting a simple example in the playground is often the quickest way to look at it as it shows the compiled output side by side.

**Comment by qlaffont** [comment]
The strange things is I don't reproduce the issue with the playground 0-o. Maybe due to vite plugin ?

**Comment by mosheduminer** [comment]
`babel-preset-solid` (the compiler) [seems to be](https://github.com/qlaffont/lestudio-app/blob/294815c38da7f606f553b2c6b09e43115f2c2e4a/pnpm-lock.yaml#L1269) out of date. Try running `pnpm update`, and if that fails, deleting `node_modules` and `pnpm-lock.yaml` and `pnpm install` should do the trick.

**Comment by qlaffont** [comment]
Thanks I will try ! I forgot to do it ^^"

**Comment by qlaffont** [comment]
@mosheduminer unfortunately it doesn't work. I have updated the repository -> https://github.com/qlaffont/lestudio-app

**Comment by qlaffont** [comment]
@mosheduminer it's working ( I deleted my previous comment, I was needed to delete pnpm cache too) !
