### ISSUE TITLE
mergeProps fails with SSR

### ISSUE THREAD

**Issue by juanrgm** [solidjs/solid#1875]
### Describe the bug

This code throws an exception only with SSR enabled:

```ts
import { render } from "solid-js/web";

function Div(props: any) {
  return <div {...props} />;
}

function App() {
  // `data-firstprop` and `undefined` together cause the error
  const props = () => undefined as any;
  return (
    <Div data-firstprop {...props()}>
      test
    </Div>
  );
}

render(() => <App />, document.getElementById("app")!);
```

### Your Example Website or App

https://playground.solidjs.com/anonymous/d1fa8058-4207-41c8-98fe-591be0d25909

### Steps to Reproduce the Bug or Issue

1. Execute the code with SSR enabled.

### Expected behavior

No error.

### Platform

- SolidJS: 1.7.11

**Comment by ryansolid** [comment]
What's the error? The reproduction just shows code but no error message. If I can get a working reproduction, maybe Stackblitz or at least a posting of what the error message is.

**Comment by juanrgm** [comment]
I tried to create an example on Stackblitz, but NodeJS 18 is not supported yet (https://github.com/stackblitz/webcontainer-core/issues/560).

You can download it (https://stackblitz.com/edit/solid-ssr-vite-c8xxyw?file=src%2FApp.tsx) and run it locally.

The error is:

> An unhandled error occured: TypeError: Cannot read properties of undefined (reading 'data-firstprop')

And the problem is [here](https://github.com/solidjs/solid/blob/f79ba4d9087d74ef7e55fd0dc336c98ce2ec8526/packages/solid/src/server/rendering.ts#L105C16-L105C16).

**Comment by ryansolid** [comment]
I see the server side merge props is much "simpler" and isn't handling undefined case properly. It must try to read it through undefined..
