### ISSUE TITLE
Bug: JSX types for `contentEditable`/`contenteditable` do not allow `plaintext-only`

### ISSUE THREAD

**Issue by sno2** [solidjs/solid#1908]
## Reproduction

The `contentEditable`/`contenteditable` attributes do not include `plaintext-only` as valid value:

```tsx
import { render } from "solid-js/web";

function App() {
  return (
    <>
      <span contentEditable="plaintext-only" />
      <span contenteditable="plaintext-only" />
    </>
  );
}

render(() => <App />, document.getElementById("app")!);
```

```sh
Type '"plaintext-only"' is not assignable to type 'boolean | "inherit" | undefined'.(2322)
Type '"plaintext-only"' is not assignable to type 'boolean | "inherit" | undefined'.(2322)
```

Solid Playground: https://playground.solidjs.com/anonymous/375732d5-3837-4992-b999-ac318f96cd9e

See the specification: https://html.spec.whatwg.org/multipage/interaction.html#attr-contenteditable

> The contenteditable content attribute is an [enumerated attribute](https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#enumerated-attribute) whose keywords are the empty string, true, plaintext-only and false. The empty string and the true keyword map to the true state. The plaintext-only keyword maps to the plaintext-only state. The false keyword maps to the false state. In addition, there is a fourth state, the inherit state, which is the [missing value default](https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#missing-value-default) and the [invalid value default](https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#invalid-value-default).
> 
> The true state indicates that the element is editable. The plaintext-only state indicates that only the element's raw text content is editable, but rich text formatting is disabled. The inherit state indicates that the element is the same kind of editable (or not editable) as the parent element. The false state indicates that the element is not editable.

## Fix

The types need to be adjusted to include `"plaintext-only"` as a valid value.

**Comment by sno2** [comment]
I tried to fix this, but I cannot figure out where the types are located. Can anyone refer me to this file?

**Comment by ryansolid** [comment]
It's in [dom-expressions](https://github.com/ryansolid/dom-expressions) package. We use this framework agnostic core for fine-grained rendering in Solid.

But it's okay I was literally in the middle of fixing JSX types. It will be in the 1.8 release that should come out today or tomorrow.

**Comment by sno2** [comment]
Ah ok, thanks.
