### ISSUE TITLE
<svg /> and <path /> elements malformed or removed in v1.8

### ISSUE THREAD

**Issue by rpivo** [solidjs/solid#1911]
### Describe the bug

When upgrading to v1.8, I am seeing that attributes of an `<svg />` element are getting removed, and a contained `<path />` element is also removed.

Here is the resulting dom html using 1.7:

```html
<div id="nav-middle">
  <div data-hk="0-0-0-0-0-0-0-0-0-1-0-0-0-0-1-4-0" class="form-container">
    <form class="search">
      <input
        class="search-text"
        placeholder="Search People, Places, or Topics"
        value=""
      /><button type="submit">
        <svg
          stroke-width="0"
          height="22"
          width="22"
          xmlns="http://www.w3.org/2000/svg"
          size="22"
          viewBox="0 0 1024 1024"
          color="currentColor"
          fill="currentColor"
          style="overflow: visible"
        >
          <path
            d="M909.6 854.5 649.9 594.8C690.2 542.7 712 479 712 412c0-80.2-31.3-155.4-87.9-212.1-56.6-56.7-132-87.9-212.1-87.9s-155.5 31.3-212.1 87.9C143.2 256.5 112 331.8 112 412c0 80.1 31.3 155.5 87.9 212.1C256.5 680.8 331.8 712 412 712c67 0 130.6-21.8 182.7-62l259.7 259.6a8.2 8.2 0 0 0 11.6 0l43.6-43.5a8.2 8.2 0 0 0 0-11.6zM570.4 570.4C528 612.7 471.8 636 412 636s-116-23.3-158.4-65.6C211.3 528 188 471.8 188 412s23.3-116.1 65.6-158.4C296 211.3 352.2 188 412 188s116.1 23.2 158.4 65.6S636 352.2 636 412s-23.3 116.1-65.6 158.4z"
          ></path>
        </svg>
      </button>
    </form>
    <div class="legend">
      Try searching for:
      <ul data-hk="0-0-0-0-0-0-0-0-0-1-0-0-0-0-1-4-2-3">
        <li>People: "chuck grassley"</li>
        <li>Topics: "medicare"</li>
        <li>States: "kansas" (coming soon)</li>
        <li>Cities: "kalamazoo" (coming soon)</li>
        <li>Zip Codes: "90210" (coming soon)</li>
      </ul>
    </div>
  </div>
</div>
```

And here is the dom html when using 1.8

```html
<div id="nav-middle">
  <div data-hk="0-0-0-0-0-0-0-0-0-1-0-0-0-0-1-4-0" class="form-container">
    <form class="search">
      <input
        class="search-text"
        placeholder="Search People, Places, or Topics"
        value=""
      /><button type="submit">
        <svg stroke-width="0" style="overflow: visible"></svg>
      </button>
    </form>
    <div class="legend">
      Try searching for:
      <ul data-hk="0-0-0-0-0-0-0-0-0-1-0-0-0-0-1-4-2-3">
        <li>People: "chuck grassley"</li>
        <li>Topics: "medicare"</li>
        <li>States: "kansas" (coming soon)</li>
        <li>Cities: "kalamazoo" (coming soon)</li>
        <li>Zip Codes: "90210" (coming soon)</li>
      </ul>
    </div>
  </div>
</div>
```

### Your Example Website or App

https://stackblitz.com/edit/solidjs-templates-1lvbyq?file=package.json

### Steps to Reproduce the Bug or Issue

- Run `npm ci`
- Run `npm run dev`
- Right-click on the search icon in the input form button and inspect the DOM. Notice the attributes on the containing `<svg />` as well as the `<path />` element.
- stop the server
- run `npm i solid-js@1.8`
- Run `npm run dev`
- Right-click the same location and inspect the DOM. Notice that the `<svg />` has fewer attributes, and the `<path />` is now missing.

### Expected behavior

The `<svg />` and `<path />` elements should not be malformed.

### Platform

- OS: macOS
- Browser: Chrome
- Version: 1.8

**Comment by ryansolid** [comment]
Oh this is fun. The problem is solid-icons is using the client precompiled version not the hydratable version. Which suggests to me the client only precompiled version is getting pulled in. 

In fact looking at it, it isn't packaged properly for SSR. There is no `solid` export condition. While they make a server build, there is no way to make a client hydratable build. So this library has always been doing destructive hydration.

I think there is a way I can warn about this in the runtime. I will make a patch release with a dev warning that will make it clear something is wrong.

**Comment by ryansolid** [comment]
Ok done. In 1.8.1 forward the moment you add a library that doesn't hydrate to your SSR project without putting it behind a createEffect/onMount/clientOnly type thing it is going to error.
