### ISSUE TITLE
Boolean attributes sometimes are not generated properly

### ISSUE THREAD

**Issue by GiyoMoon** [solidjs/solid#1912]
### Describe the bug

Boolean attributes after a non-boolean attribute are not generated correctly:
jsx:
```html
<p one two three four="with value" five six seven>Check the attributes of this element</p>
```
generated html:
```html
<p one="" two="" three="" four="with value" fivesixseven="">Check the attributes of this element</p>
```

### Your Example Website or App

https://github.com/GiyoMoon/solid-attributes

### Steps to Reproduce the Bug or Issue

1. git clone https://github.com/GiyoMoon/solid-attributes.git
2. cd solid-attributes
3. pnpm install
4. pnpm dev
5. Navigate to http://localhost:5174/
6. Have a look at the centered `p` element. Compare it with its jsx equivalent (https://github.com/GiyoMoon/solid-attributes/blob/main/src/App.jsx#L6)

### Expected behavior

Every boolean attribute should have a space appended after/before it.

### Platform

- OS: macOS
- Browser: Chrome
- Version: 117

**Comment by ryansolid** [comment]
Thanks for reporting. This is fixed in babel-plugin-jsx-dom-expressions 0.37.2. Since the preset is set to match range this should be fixed in any new install and will be bumped in the next release of Solid.
