### ISSUE TITLE
No resource.loading defined when using hyper dom expressions

### ISSUE THREAD

**Issue by wrnrlr** [solidjs/solid#1914]
### Describe the bug

When I try to use a `Resource` with hyper dom expressions the `loading` attribute is missing when I pass this resource to another component.

### Your Example Website or App

https://jsbin.com/febodeyenu/edit?html,output

### Steps to Reproduce the Bug or Issue

The simpelest example I could think off

```js
import {createSignal,createEffect,createResource} from 'https://esm.sh/solid-js@1.8.1'
import {render} from 'https://esm.sh/solid-js@1.8.1/web'
import h from 'https://esm.sh/solid-js@1.8.1/h'

function A() {
  const [a,setA] = createSignal('hello'),
    [r] = createResource(a,()=>a())
  setTimeout(()=>setA('goodbye'),1000)
  createEffect(()=>console.log({r:r.loading}))
  console.log({a,r})
  return ()=>[
    h('div',[()=>''+r.loading,' ',r]),
    h(B,{r})
  ]
}

function B(props) {
  return h('div', [
    ()=>''+props.r.loading,
    ' ',
    ()=>props.r
  ])
}

render(A, document.getElementById('app'));
```

### Expected behavior

I would expect the loading property to be present on the resource, like it does when using JSX.

### Platform

* SolidJS: 1.8.1

**Comment by ryansolid** [comment]
It's because `r` is a function so it has no choice but to wrap its access in a getter to have that prop syntax. As it can't tell the difference between passing a function and passing a resource. It has to treat them all as something that will be lazy evaluated. In so you can think of props.r as:
```js
props = {
  get r() { r() }
}
```
In so you are getting the value of the resource rather than it being passed straight through.

**Comment by wrnrlr** [comment]
Ok, that makes sense in the context of JSX, I've been using this workaround with HDE:

```js
function createWrappedResource(source,fetchData) {
  const [data,util] = createResource(source,fetchData)
  return [{value:data,loading:()=>data.loading},util]
}
```

I think that this behaviour is a bit confusing, even when using JSX I was surprised that something like `r()` and `r.loading` works, but then again I didn't know you could do something like this in js:

```js
var object = { foo: 42 },
    callable = Object.assign(function () {}, object);

console.log(callable)
console.log(callable())
console.log(Object.keys(callable));
```

**Comment by ryansolid** [comment]
Yeah this is an old pattern we used in Knockout called "sub-observables". I really dislike it, and `createResource` is definitely getting another look at in the future. 

Yeah if you have to box it, do so.. I know it is a bit clunky but it is what it is. While it is completely possible to use hyperscript/tagged template literals with reactivity, it compromises on [Locality of Thinking](https://dev.to/this-is-learning/thinking-locally-with-signals-3b7h) which I think is really important. I can't compromise the rest of the system to make those work better.
