### ISSUE TITLE
[SSR] Hydration mismatch when createResource throws an error

### ISSUE THREAD

**Issue by mattersj** [solidjs/solid#1918]
### Describe the bug

When `createResource` throws an error (e.g. rejects a promise), the hydration mismatch error is thrown.

Another thing to notice here: there's no hydration mismatch if `createResource` throws an error without a promise (e.g. without `async`). It feels like the behavior should be unified no matter whether it returns a promise or not.

### Your Example Website or App

https://stackblitz.com/edit/solid-ssr-vite-81jsyh?file=src/routes/index.tsx

### Steps to Reproduce the Bug or Issue

0. This bugs can only be reproduced when using SSR.
1. Go to the console and observe the hydration mismatch error.

### Expected behavior

There should be no error during hydration.

### Platform

- OS: macOS 12.6.8
- Browser: Chrome
- Version: 118

**Comment by ryansolid** [comment]
Thank you for reporting. Synchronous resolution of values work but errors from serialization. Which means that loading states are breaking hydration. Will get this fixed up.
