### ISSUE TITLE
When using the result of `<Index>` or `indexArray` in a `createComputed`, cleanups aren't run

### ISSUE THREAD

**Issue by danieltroger** [solidjs/solid#1923]
### Describe the bug

When using indexArray and lengthening the array from within the looping function the function for certain items is re-executed without the previous one being cleaned up.

### Your Example Website or App

https://playground.solidjs.com/anonymous/dbf19f7d-3c19-4981-a8d3-5a45860c1939

### Steps to Reproduce the Bug or Issue

1. Go to https://playground.solidjs.com/anonymous/dbf19f7d-3c19-4981-a8d3-5a45860c1939
2. Make the code execute (click refresh)
3. Check console
4. Note how indexes 1-3 are repeated and <b>no cleanups are ran</b>

```
We mapped over 0
We mapped over 1
We mapped over 2
We mapped over 3
We mapped over 0
We mapped over 1
We mapped over 2
We mapped over 3
```

### Expected behavior

1. Items aren't repeated
2. If they have to, cleanups should be ran

BTW am I understanding it correctly that indexArray only does stuff if the function it returns is used? Why that?

### Platform

- OS: macOS 14.0 (23A344)
- Browser: Firefox
- Version: 119.0b9

**Comment by danieltroger** [comment]
Also seems to happen when using `<Index>` and createEffect I think, due to the createMemo inside of `<Index>` using createComputed internally.

This coupled with https://github.com/solidjs/solid/commit/b632dfd5621a367bdf7e88a014c1ad88e98b784d not being released yet means I can't work around my SSR builds breaking by using <Index> instead of indexArray and therefore can't ship my stuff to customers 😢

**Comment by ryansolid** [comment]
Honestly, I'd love to find a way to make what you did here illegal. Changing the length of the list synchronously while rendering has no defined behavior that doesn't compromise consistency one way or the other. While I agree there is an issue here from the perspective we shouldn't be running the inner loop update before the outer has finished, I don't think trying to fix it in the current system is particularly feasible especially as this will be actually illegal in the future (no synchronous writes during pure computation). It works fine with `createEffect`. This is a large part why `createComputed` will be getting deprecated in 2.0, but these sort of edge cases are what `createComputed` invites currently.

So I think this is a won't fix. And we get back to fixing the 1.8 related issues to get a release out.

**Comment by danieltroger** [comment]
Here's an example with `createEffect` which also runs into the issue: https://playground.solidjs.com/anonymous/e424d483-41a0-4415-98bc-ce57f06d9ceb

I'm trying right now to delay the writing with a microtask to see if that works - I have a tricky issue and getting this weird writing in the loop thing working is my big hope lol. Basically while I process input my input it changes until there's equilibrium at some point.

I hope 2.0 won't be too restrictive, I really enjoy the power that current solid-js offers to do things. But I agree it would be better if this wasn't possible than having the weird behavior.

**Comment by danieltroger** [comment]
FYI I gave up on my fancy interface, it was too hard to find equilibrium and I didn't want to restructure all my code to not use IndexArray and do a more manual approach. So no pressure to fix this or release https://github.com/solidjs/solid/commit/b632dfd5621a367bdf7e88a014c1ad88e98b784d anymore :)

**Comment by ryansolid** [comment]
> Here's an example with `createEffect` which also runs into the issue: https://playground.solidjs.com/anonymous/e424d483-41a0-4415-98bc-ce57f06d9ceb

I see. I would not expected Effects to run there. They are already in a batch call. It's seems that inside the root in the loop it doesn't see the existing run and starts it mid cycle. Probably because it is initial run itself and not part of a computation update. Like looking at it I get it and I know why I've never seen this.

> I'm trying right now to delay the writing with a microtask to see if that works - I have a tricky issue and getting this weird writing in the loop thing working is my big hope lol. Basically while I process input my input it changes until there's equilibrium at some point.

Writing delayed should work. I didn't try queueMicrotask, but setTimeout definitely did.

> I hope 2.0 won't be too restrictive, I really enjoy the power that current solid-js offers to do things. But I agree it would be better if this wasn't possible than having the weird behavior.

Yeah synchronous writes are big no during creation. Too easy to send off other reactive updates out of cycle. Well anywhere createComputed is involved.. Our loops aren't 100% sound which is something we've been looking at. In general avoid the write during creation and don't hit this.

> FYI I gave up on my fancy interface, it was too hard to find equilibrium and I didn't want to restructure all my code to not use IndexArray and do a more manual approach. So no pressure to fix this or release https://github.com/solidjs/solid/commit/b632dfd5621a367bdf7e88a014c1ad88e98b784d anymore :)

I'm glad you got somewhere with this. I admit I've never seen anyone try to do that so it was interesting.
