### ISSUE TITLE
Static SSR (async) inserting hyrdation script when using lazy and Suspense

### ISSUE THREAD

**Issue by Enideo** [solidjs/solid#1931]
### Describe the bug

When using `renderToStringAsync()` with `lazy` and `<Suspense>`, since version 1.8.x a `<script>` tag is injected at the end of the html string which looks like it's for hydration. `hydratable` is not set to true in babel config and this is a change since 1.7.12.

### Your Example Website or App

https://stackblitz.com/edit/solid-nollup-epm7fs?file=package.json

### Steps to Reproduce the Bug or Issue

1. from the stackblitz link, run `npm run start` (should happen automatically)
2. the console should log the html string, containing a script tag
4. to see how it used to be: change `package.json` version for solid-js "^1.712" to "1.7.12" and save.
5. then run `npm install && npm run start`
6. the console should log a html string without a script tag

### Expected behavior

I do not expect any `<script>` to be inserted into the html for hydration, just static html rendered from the Solid JSX components.

### Platform

- OS: Linux
- Browser: N/A: node
- Version: 18.18.2

**Comment by ryansolid** [comment]
Hmm.. interesting. The runtime and the compiler don't really know each other. I'm a little surprised there wasn't anything here before. What is being serialized is the completion of the Suspense boundary. I guess the difference was that anything registered before first flush would be cancelled before, and then it would never call the actual serializer. Where as now it is serializing the Suspense boundary. I will think if there is anything we can do here.

**Comment by ryansolid** [comment]
I've added a `noScripts` option to renderAsync available in 1.8.4.

**Comment by patdx** [comment]
FYI I ran into something similar when doing:

```

**Comment by patdx** [comment]
FYI I ran into a similar issue with some tests in this PR I have been working on (https://github.com/withastro/astro/pull/6791 after Solid was updated from 1.7.x to 1.8.3

```jsx
renderToStringAsync(() => (
  <NoHydration>
    <Suspense>
      <Component />
    </Suspense>
  </NoHydration>
));
```

I ended up fixing the failing tests by updating to Solid 1.8.5 and adding the `noScripts: true`  option.

**Comment by patdx** [comment]
FYI I ran into a similar issue with some tests in this PR I have been working on (https://github.com/withastro/astro/pull/6791 after Solid was updated from 1.7.x to 1.8.3

```jsx
renderToStringAsync(() => (
  <NoHydration>
    <Suspense>
      <Component />
    </Suspense>
  </NoHydration>
));
```

I ended up fixing the failing tests by updating to Solid 1.8.5 and adding the `noScripts: true`  option.
