### ISSUE TITLE
Using component props values inside noscript template crashes in Firefox

### ISSUE THREAD

**Issue by aquaductape** [solidjs/solid#1937]
### Describe the bug

When creating noscript tag, if child elements use component props values, then it crashes. In this case, the `noscript` element has an anchor tag where it's aria attribute is being set by component prop `label` and it results in error `node.setAttribute is not a function`.

```jsx
const Comp = (props: {label: string}) => {
  return (
    <div>
      <noscript>
        <a href="#foo" 
        // Uncaught TypeError: node.setAttribute is not a function
        aria-label={props.label}
        >
          hi
        </a>
      </noscript>
      nooooo
    </div>
  );
};

function App() {
  return (
    <>
      <Comp label="hi"/>
    </>
  );
}
```

This maybe a silly useless issue to report, since this occurs in client side rendering, which doesn't make sense since creating a noscript jsx template will never be created and fired in a disabled javascript page. I'm reporting due to browser inconsistency where Chrome and Safari renders the noscript tag with children while Firefox fails. However I haven't tested this in SolidStart.

### Your Example Website or App

https://playground.solidjs.com/anonymous/3876e2a9-a538-45ec-afc0-f4ab745bebd7

### Steps to Reproduce the Bug or Issue

1. Create component with props and have noscript element with child elements.
2. Make noscript child element attribute use a component prop.

### Expected behavior

It should render the noscript element in the DOM, with the aria-label set to the value of the component label prop.
```html
<div>
  <noscript>
    <a href="foo" aria-label="world">
      hi
    </a>
  </noscript>
  nooooo
</div>
```

### Platform

- OS: macOS
- Browser: Firefox
- Version: 119.0

**Comment by ryansolid** [comment]
This is probably relared https://github.com/solidjs/solid/issues/1601#issuecomment-1463314273
