### ISSUE TITLE
Multiple For from the same array that contains a JSXElement will only render the last For.

### ISSUE THREAD

**Issue by AlbertSabate** [solidjs/solid#1986]
### Describe the bug

When creating an array of JSXElement and using For more than once on the same page. It only renders the last For, ignoring the previous one.
In the following example, you can see that only the last For is rendered (you can only see 2 <hr />).

### Your Example Website or App

https://playground.solidjs.com/anonymous/e7d409ec-036a-480d-b6dd-0b918edc4b12

### Steps to Reproduce the Bug or Issue

Use the following minimal code:

```
import { For } from "solid-js";

const ComponentA = (props) => (<For each={props.array}>
    {(a) => (<div>{a}</div>)}
  </For>);
const ComponentB = (props) => (<For each={props.array}>
    {(a) => (<div>{a}</div>)}
  </For>);

const LoopComponent = () => {
  const array = [<hr />, <hr />];

  return (
    <>
      <ComponentA array={array} />
      <ComponentB array={array} />
    </>
  );
};

export const App = () => (<LoopComponent />);
```

### Expected behavior

I would expect to see 4 <hr />.

### Platform

- Any
- Can be tested on https://playground.solidjs.com/

**Comment by titoBouzout** [comment]
That's how the DOM works. If you create a DIV you can use it only once, any other use of it, will remove the previous div and insert it in the new place.  Check https://developer.mozilla.org/en-US/docs/Web/API/Node/appendChild

Has note:

> Note: If the given child is a reference to an existing node in the document, appendChild() moves it from its current position to the new position.

In this case you create 2 HRs, and then use them 4 times, so these will be added to the first FOR, and then removed from the first FOR and moved to the last one.

**Comment by titoBouzout** [comment]
For the sake of completness, you may do something like this, which will return new instances of HRs on each function call

```js
const LoopComponent = () => {
  const array = ()=> [<hr />, <hr />];

  return (
    <>
      <ComponentA array={array()} />
      <ComponentB array={array()} />
    </>
  );
};
```

**Comment by AlbertSabate** [comment]
I solved using <Dynamic component={} /> and having an object map with the components.

> In this case you create 2 HRs, and then use them 4 times, so these will be added to the first FOR, and then removed from the first FOR and moved to the last one.

Got it. So, it is expected to work this way.

> const LoopComponent = () => {
  const array = ()=> [<hr />, <hr />];

  return (
    <>
      <ComponentA array={array()} />
      <ComponentB array={array()} />
    </>
  );
};

This is super clear. I think this is my way to go! Thank you so much :)

**Comment by AlbertSabate** [comment]
See @titoBouzout answer. I am closing the issue as it is not an issue.

**Comment by AlbertSabate** [comment]
See @titoBouzout answer. I am closing the issue as it is not an issue.
