### ISSUE TITLE
`insert` function changes rendering order

### ISSUE THREAD

**Issue by snnsnn** [solidjs/solid#1997]
### Describe the bug

The bug is about the insert function which is implemented in the `dom-expressions` library but its impact is most obvious when using the context  API.

```typescript
// https://github.com/ryansolid/dom-expressions/blob/main/packages/dom-expressions/src/client.js#L198
function insert(parent, accessor, marker, initial) {
  if (marker !== undefined && !initial) initial = [];
  if (typeof accessor !== "function") return insertExpression(parent, accessor, initial, marker);
  effect(current => insertExpression(parent, accessor(), current, marker), initial);
}
```

The `props` destructuring changes the execution order, making children run before the parent component. Here is an example demonstrating the issue:

```typescript
import { render } from "solid-js/web";
import { createContext, useContext } from "solid-js";

const Context = createContext(0);

const Title = () => {
  const value = useContext(Context);
  return <div>Value: {value}</div>
}

const Card = (props) => {
  return (
    <Context.Provider value={30}>
      {props.children}
    </Context.Provider>
  );
}

const DestructuredCard = ({ children }) => {
  return (
    <Context.Provider value={20}>
      {children}
    </Context.Provider>
  );
}

const App = () => {
  return (
    <>
      <Card>
        <Title />
      </Card>
      <DestructuredCard>
        <Title />
      </DestructuredCard>
    </>
  );
}

render(App, document.body);
```

Live Demo: https://playground.solidjs.com/anonymous/5f1fe27f-24a3-4ebb-80f9-ab0fa2516d1e

When destructured, child components are executed before the parent component, before the context values are set, hence children uses the default value.

Why children is executed before the parent is that `insert` calls the `insertExpression` function immediately if `children` is not of `function` type. Otherwise it wraps the function call it in an effect, having children executed after their parent.

Initially I thought is was a feature, but now thinking about it is clearly a bug because it reverses rendering order unexpectedly and in a very subtle way. Also it serves no purpose because children should be executed after the parent component at all times.

There is a SO question about it:

https://stackoverflow.com/questions/76947570/solidjs-context-not-passing-down-to-children

### Your Example Website or App

https://playground.solidjs.com/anonymous/5f1fe27f-24a3-4ebb-80f9-ab0fa2516d1e

### Steps to Reproduce the Bug or Issue

Please check the example above.

### Expected behavior

Please check the example above.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by Brendonovich** [comment]
Is this a bug when destructuring props in Solid isn't allowed? Seems like a side-effect of not following Solid's rules rather than a bug.

**Comment by snnsnn** [comment]
> Is this a bug when destructuring props in Solid isn't allowed? Seems like a side-effect of not following Solid's rules rather than a bug.

I believe it is. There is nothing wrong with destructuring.

**Comment by snnsnn** [comment]
I am sorry, I accidentally touch the screen and closed the issue. So, i reopened.

**Comment by ryansolid** [comment]
> > Is this a bug when destructuring props in Solid isn't allowed? Seems like a side-effect of not following Solid's rules rather than a bug.
> 
> I believe it is. There is nothing wrong with destructuring and there is no such rule.
> 
> If you do not destructure props, solid will add a getter method for every reactive value so that they are transmitted to the child components reactively. If you use destructuring, you need pass the signal, not the value, and run the invocation yourself. So, there is no such rule as not using props destructuring. It is just a convenience offered by Solid. People may advice not to use destructuring so that they don't have to go through lengthy explanation like I did here.

But if you destructure the getter it will run on the spot if you aren't passing a Signal. And here you are not. So children are running before you even get to inserting them. I don't believe this has anything to do with the insert call.

**Comment by Brendonovich** [comment]
> I believe it is. There is nothing wrong with destructuring and there is no such rule.

Yes there is, it's in the [Props/Default Props](https://www.solidjs.com/tutorial/props_defaults) section of the tutorial

**Comment by snnsnn** [comment]
> But if you destructure the getter it will run on the spot if you aren't passing a Signal. And here you are not. So children are running before you even get to inserting them. Like literally where you are destructuring. I don't believe this has anything to do with the insert call.

I thought it was the insert function that changes the execution order by inserting  expression immediately for the variables that are not of function type (since they are not signals) and wrapping them in a render effect if they are of function type. It was the following example that gave me that impression:

```typescript
import { render } from "solid-js/web";

const Child = () => {
  console.log('Rendering Child...')
  return <div>Greetings</div>
}

const Parent = (props) => {
  console.log('Rendering Parent..');
  return (
    <div>
      {props.children}
    </div>
  );
}

const App = () => {
  console.log('Rendering App..');

  return (
      <Parent>
        <Child />
      </Parent>
  );
}

render(App, document.body);
```

Live: https://playground.solidjs.com/anonymous/422a2f4b-142d-4bdb-9c17-69899f673fcb

This executes as expected, outputting:

```
Rendering App..
Rendering Parent..
Rendering Child..
```

But when we destructure, children get to run first:

```typescript
import { render } from "solid-js/web";

const Child = () => {
  console.log('Rendering Child...')
  return <div>Greetings</div>
}

const Parent = (props) => {
  console.log('Rendering Parent..');
  return (
    <div>
      {props.children}
    </div>
  );
}

const App = () => {
  console.log('Rendering App..');

  return (
      <Parent>
        <Child />
      </Parent>
  );
}

render(App, document.body);
```

Live Demo: https://playground.solidjs.com/anonymous/200efac4-44cc-4fcd-b3df-842f7d64649f

Producing this output:

```
Rendering App..
Rendering Child..
Rendering Parent..
```

The only difference between these two examples is the parameters of the insert function:

```ts
// Without destructuring
_$insert(_el$2, () => props.children);

// With destructuring
_$insert(_el$2, children);
```

**Comment by snnsnn** [comment]
> > I believe it is. There is nothing wrong with destructuring and there is no such rule.
> 
> Yes there is, it's in the [Props/Default Props](https://www.solidjs.com/tutorial/props_defaults) section of the tutorial

It is not a rule, what you post is just an example and I don't know why you are being defensive here. I have been using Solid for quite a long time, I know what I am saying.

**Comment by Brendonovich** [comment]
> It is not a rule, what you post is just an example and I don't know why you are being defensive here. I have been using Solid for quite a long time, I know what I am saying.

Maybe I came off as defensive, but it is a rule - it's even enforced by `eslint-plugin-solid`. The difference in the code you provided doesn't really lie in the insert call, but in the fact that `children` is being destructured in the first place.

`children` in this case is implemented as a getter, and evaluating that getter is what causes the children to render and log to the console. Using `props.children` delays evaluating the getter to inside `insert`, but destructuring evaluates the getter early, leading to the child logging to the console before the parent.

**Comment by snnsnn** [comment]
> children in this case is implemented as a getter, and evaluating that getter is what causes the children to render and log to the console. Using props.children delays evaluating the getter to inside insert, but destructuring evaluates the getter early, leading to the child logging to the console before the parent.

I agree with you and that is what I've been believing all along (see my SO answer) but the examples I posted above really confused me because there is no change in the compiled output besides the insert parameter and the Parent component receives children via getter function in both example.

```typescript
import { template as _$template } from "solid-js/web";
import { createComponent as _$createComponent } from "solid-js/web";
import { insert as _$insert } from "solid-js/web";
const _tmpl$ = /*#__PURE__*/_$template(`<div>Greetings`),
  _tmpl$2 = /*#__PURE__*/_$template(`<div>`);
import { render } from "solid-js/web";

const Child = () => {
  console.log('Rendering Child...');
  return _tmpl$();
};

const Parent = props => {
  console.log('Rendering Parent..');
  return (() => {
    const _el$2 = _tmpl$2();
    _$insert(_el$2, () => props.children);
    return _el$2;
  })();
};

const App = () => {
  console.log('Rendering App..');
  return _$createComponent(Parent, {
    get children() {
      return _$createComponent(Child, {});
    }
  });
};

render(App, document.body);
```

```typescript
import { template as _$template } from "solid-js/web";
import { createComponent as _$createComponent } from "solid-js/web";
import { insert as _$insert } from "solid-js/web";
const _tmpl$ = /*#__PURE__*/_$template(`<div>Greetings`),
  _tmpl$2 = /*#__PURE__*/_$template(`<div>`);
import { render } from "solid-js/web";

const Child = () => {
  console.log('Rendering Child...');
  return _tmpl$();
};

const Parent = ({
  children
}) => {
  console.log('Rendering Parent..');
  return (() => {
    const _el$2 = _tmpl$2();
    _$insert(_el$2, children);
    return _el$2;
  })();
};

const App = () => {
  console.log('Rendering App..');
  return _$createComponent(Parent, {
    get children() {
      return _$createComponent(Child, {});
    }
  });
};

render(App, document.body);
```

Anyway, it would be ideal if we had a rendering paradigm that was free from quirks but it seems impossible with all these compiler tricks. However, it is not something we can not live without.

Thanks you all.

**Comment by titoBouzout** [comment]
> the examples I posted above really confused me because there is no change in the compiled output

Consider that if the children components modify `props.children` in any way or in case you use Context or something like that, then triggering `props.children` evaluation earlier may change the output
