### ISSUE TITLE
Missing attribute `popover` in HTMLAttributes

### ISSUE THREAD

**Issue by benlesh** [solidjs/solid#2002]
### Describe the bug

I'm getting type errors when trying to use `<div popover>`. [popover](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/popover) is supported in pretty much everything but Firefox, which I'm not targeting. In fact, there are a number of things that aren't supported in the JSX, which _are_ supported in the DOM lib for TypeScript.

### Your Example Website or App

https://stackblitz.com/edit/solidjs-templates-k5yisa?file=src%2FApp.tsx

### Steps to Reproduce the Bug or Issue

The following code will result in TypeScript type checking errors:

```tsx
import type { Component } from 'solid-js';

const App: Component = () => {
  return (
    <>
      <div
        id="my-popover"
        popover="manual"
        onToggle={(e) => {
          console.log({
            oldState: e.oldState,
            newState: e.newState,
          });
        }}
        onBeforeToggle={(e) => {
          console.log({
            oldState: e.oldState,
            newState: e.newState,
          });
        }}
      >
        This is a popover
      </div>
      <button popovertarget="my-popover">Toggle Popover</button>
    </>
  );
};

export default App;

```

### Expected behavior

It should compile in TypeScript and be type safe during development.

### Platform

- OS: n/a
- Browser: n/a
- Version: n/a

#### Workaround

The workaround is to just add a `solid-js-extensions.d.ts` file with the following:

```ts
import "solid-js";

declare module "solid-js" {
  export namespace JSX {
    interface HTMLAttributes<T> {
      popover?: "auto" | "manual" | true;
    }

    // Note this doesn't cover <input type="button"/>
    interface ButtonHTMLAttributes {
      popovertarget?: string;
    }

    interface CustomEventHandlersCamelCase {
      onBeforeToggle?: (event: ToggleEvent) => void;
      onToggle?: (event: ToggleEvent) => void;
    }
  }
}


```

#### Contribution Difficulty

Contributing to types in this area is harder than it probably should be? I was happy to try to make a PR to attempt to resolve this, but after a bit of surfing, I couldn't quite figure out where the JSX types were coming from. It seems like maybe they're generated from some third party? Not sure. In any case, some documentation about how to upstream stuff like this might be helpful.

**EDIT: Added more detail and related attributes and events**

**Comment by lxsmnsyc** [comment]
> I couldn't quite figure out where the JSX types were coming from

The entirety of JSX-related types is declared [here](https://github.com/ryansolid/dom-expressions/blob/main/packages/dom-expressions/src/jsx.d.ts)

It's a bit surprising for new contributors that Solid is structured this way, but I feel like in the future, the compiler and the reactivity core will be united.

**Comment by benlesh** [comment]
Thanks y'all! ❤️

**Comment by LexSwed** [comment]
Seems like [beforetoggle](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/beforetoggle_event) and [toggle](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/toggle_event) events are still missing (`onBeforeToggle` and `onToggle` JSX versions) 👀
