### ISSUE TITLE
Invalid JSX <tr> not allowed as child of <table>

### ISSUE THREAD

**Issue by jmurphyct** [solidjs/solid#2003]
### Describe the bug

An HTML table with a <tr> row throws an invalid jsx error. <tr> cannot be child of <table>

### Your Example Website or App

https://playground.solidjs.com/anonymous/048a77b8-f213-44a9-b2f4-939d387d1aac

### Steps to Reproduce the Bug or Issue

Create a .jsx file with the contents 
```
  function HTMLTable() {
    return (
        <table>
          <tr>
            <th>Company</th>
            <th>Contact</th>
            <th>Country</th>
          </tr>
          <tr>
            <td>Alfreds Futterkiste</td>
            <td>Maria Anders</td>
            <td>Germany</td>
          </tr>
          <tr>
            <td>Centro comercial Moctezuma</td>
            <td>Francisco Chang</td>
            <td>Mexico</td>
          </tr>
        </table> 
    );
  }
```
Then, use HTMLTable as a component,

### Expected behavior

As a user, I expected for valid HTML markup returned by a component to render as that html, or that there is a very obvious workaround, such as the attribute className instead of class. 

### Platform

- OS: Windows (though should be same on any)
- Browser: Firefox/Edge
- Version: 1.8.7 and 1.7.12

**Comment by DrogeanuNicu** [comment]
You don't have <thead> and <tbody>.

import { render } from "solid-js/web";

function HTMLTable() {
  return (
    <table>
      <thead>
        <tr>
          <th>Company</th>
          <th>Contact</th>
          <th>Country</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>Alfreds Futterkiste</td>
          <td>Maria Anders</td>
          <td>Germany</td>
        </tr>
        <tr>
          <td>Centro comercial Moctezuma</td>
          <td>Francisco Chang</td>
          <td>Mexico</td>
        </tr>
      </tbody>
    </table>
  );
}

render(() => <HTMLTable />, document.getElementById("app")!);

**Comment by jmurphyct** [comment]
Thanks!
I figured since it was valid html it would still work. https://www.w3schools.com/html/html_tables.asp
