### ISSUE TITLE
Data binding between signal and <input /> breaks unexpectedly

### ISSUE THREAD

**Issue by fabian-hiller** [solidjs/solid#2006]
### Describe the bug

When the value of an `<input />` is transformed, the data binding between the signal and the element breaks at a specific point. Put simply, the element no longer shows the value of the signal. However, I am not sure if this is a bug in SolidJS.

### Your Example Website or App

https://playground.solidjs.com/anonymous/b220dd2c-fe24-42d8-ad4a-0c22a31e8f31

### Steps to Reproduce the Bug or Issue

1. Open playground link
2. Enter 1234 into the form field
3. Input should be transformed to 999
4. Enter more numbers

You expect the input to stay at 999. Instead, the data binding breaks and more numbers are displayed.

### Expected behavior

The same implementation works with vanilla JavaScript: https://playground.solidjs.com/anonymous/5b399010-fcb1-4fee-8850-c986f67c13b0

### Platform

- OS: macOS
- Browser: Chrome
- Version: 120

**Comment by mdynnl** [comment]
https://github.com/solidjs/solid/discussions/416
