### ISSUE TITLE
el.clientWidth returns 0 in ref function.

### ISSUE THREAD

**Issue by u1in** [solidjs/solid#2013]
### Describe the bug

There is a [code snippets.](https://codesandbox.io/p/devbox/u1in-issue-demo-hnj7r6?file=%2Fsrc%2Findex.tsx)

When I try to get dom clientWidth in ref function. I found it always return 0. 
Is the ref function called in a wrong time or I use it in a wrong way?

Thanks for help.

### Your Example Website or App

https://codesandbox.io/p/devbox/u1in-issue-demo-hnj7r6?file=%2Fsrc%2Findex.tsx

### Steps to Reproduce the Bug or Issue

1. Waiting for the log called in ref function. It shows 0.

### Expected behavior

I expected el.clientWidth return the div's clientWidth as it shows but i got 0.

### Platform

OS: Windows11
Browser: Chrome 120.0.6099.130
SolidJS Version: 1.8.8

**Comment by titoBouzout** [comment]
From the docs  https://github.com/solidjs/solid-docs/blob/main/langs/en/api/api.md#ref

> Refs are assigned at render time but before the elements are connected to the DOM. 

So `element.isConnected` is false and doesn't have a clientWidth yet.

**Comment by u1in** [comment]
> From the docs https://github.com/solidjs/solid-docs/blob/main/langs/en/api/api.md#ref
> 
> > Refs are assigned at render time but before the elements are connected to the DOM.
> 
> So `element.isConnected` is false and doesn't have a clientWidth yet.

Thanks for your reply. Seems I do use the ref functions in a wrong way.

**Comment by u1in** [comment]
> The `ref` function is called as soon as the actual element is created, you need to wait for it to be mounted using `onMount`
> 
> ```tsx
> <div
>     ref={(el: HTMLDivElement) => {
>         onMount(() => {
>             console.log(el.clientWidth);
>         });
>     }}
> />
> ```

Thanks for your reply. It helps me a lot.

**Comment by step135** [comment]
Is there any other way to detect when element is in DOM? `onMount` calls the function before the component is inserted.

**Comment by titoBouzout** [comment]
```js

const [element, setElement] = createSignal()

createEffect(()=>{
    if(element() && element().isConnected){
        console.log('element is in the Document')
    }
})

<div ref={setElement}/>
```

**Comment by ryansolid** [comment]
> Is there any other way to detect when element is in DOM? `onMount` calls the function before the component is inserted.

It shouldn't. Only if you are holding on to it and not inserting it. `onMount` doesn't fire until all rendering is done which means unless you are waiting to insert it to some later point it will be inserted at that point. If that isn't the case, this might be an indicator of different possibly more serious issue with your code. (like double rendering things that aren't being inserted etc).
