### ISSUE TITLE
`reconcile` fails to replace nested array with object

### ISSUE THREAD

**Issue by Bubz43** [solidjs/solid#2017]
### Describe the bug

Basically the reverse of [this issue](https://github.com/solidjs/solid/issues/1973). Using reconcile to replace a nested value that is an array with an object still leaves it as an array.

### Your Example Website or App

https://playground.solidjs.com/anonymous/d43decad-3911-4beb-99e0-6a166b6655c6

### Steps to Reproduce the Bug or Issue

```ts
  const [store, setStore] = createStore<{ value: [] | {} }>({ value: [] });
  setStore(reconcile({ value: {} }));
  expect(Array.isArray(store.value)).toBe(false);
```

### Expected behavior

Expect the array to be replaced with an object, works without reconcile.

### Platform

- OS: Linux
- Browser: Vivaldi
- Version: 6.5

### Additional context

I don't think the playground version of solid has been updated to use the latest version so obj -> array bug exists there, but this bug exists both on older and latest (1.8.8) version.

**Comment by takeramagan** [comment]
I have a example here:
`const state = {
  value: []
}
Object.assign(state.value, {})
console.log(Array.isArray(state.value)); // true`
We are doing something similar in reconcile, so this bug happens

**Comment by ryansolid** [comment]
Hmm.. ok. I need to think about this one a moment because this one is innately trickier. I think you are right that reconcile should update. What comes to mind is that like:
```js
setStore("value", {0: something });
```
Shouldn't turn it into an object if value was an array. But this will:
```js
setStore({value: {0: something }});
```
But yeah `reconcile` doesn't care about any of that. It should just swap.
