### ISSUE TITLE
Breaking change between v1.8.9 and v1.8.10

### ISSUE THREAD

**Issue by samualtnorman** [solidjs/solid#2028]
### Describe the bug

Here's a route:
```jsx
import { createSignal } from "solid-js"

export default () => <TextInput/>

function TextInput(props) {
	const [ getFocused, setFocused ] = createSignal(false)

	return <input
		{...props}
		value={props.value || ""}
		onFocusOut={() => setFocused(foo => !foo)}
		classList={{ "border-red-500": getFocused() }}
	/>
}
```
In `solid-js@1.8.9` entering text into the input box and then losing focus just alternates the border colour.
In `solid-js@1.8.10` entering text into the input box and then losing focus alternates the border colour and then resets the `.value` of the input box to an empty string.

The `props.value || ""` expression appears to be re-evaluated even though `props.value` did not change.

### Your Example Website or App

https://playground.solidjs.com/anonymous/f790b17d-ecec-494a-961e-2475ea09d1ad

### Steps to Reproduce the Bug or Issue

1. Visit the playground link.
2. Enter text into the input and click away.
	- Playground appears to be still on v1.8.9.

### Expected behavior

Behaviour to not beak between a patch version.

### Platform

- OS: Linux
- Browser: Firefox
- Version: 121.0.1

**Comment by ryansolid** [comment]
I see so this is probably related to the bug fix for: https://github.com/solidjs/solid/issues/2016. The idea was that value would just propagate through. I don't see how that would clear it.

To be fair props.value would be evaluated again regardless to do the equality check, but it would not have been set on the input. Are you clearing `props.value` field in your app at some point.
