### ISSUE TITLE
Typo found in signal.ts?

### ISSUE THREAD

**Issue by only-cliches** [solidjs/solid#2055]
### Describe the bug

First off, huge fan of of solid and all the work Ryan and the team has done.  Can't thank you guys enough!

I think I found a typo on the source code.  I was running `tsc` commands and they were failing with error reports from inside solid's source code:

```sh
node_modules/solid-js/types/reactive/signal.d.ts:103:20 - error TS1139: Type parameter declaration expected.

103 export type Setter<in out T> = {
                       ~~

node_modules/solid-js/types/reactive/signal.d.ts:103:23 - error TS1005: ';' expected.

103 export type Setter<in out T> = {
```

I wen to the file and sure enough, there appears to be a typo in this file:
https://github.com/solidjs/solid/blob/099a22b13890e31aa2945a64a573bf5666a8ae6d/packages/solid/src/reactive/signal.ts#L180

A small fix took care of it for my install, but figured other folks might want the fix in place.
```ts
// old code 
export type Setter<in out T>

// typo fixed
export type Setter<T>
```

### Your Example Website or App

https://github.com/solidjs/solid

### Steps to Reproduce the Bug or Issue

N/A

### Expected behavior

Typescript should compile without an errors from with SolidJS

### Platform

- OS: MacOS
- Browser: NodeJS
- Version: 20.7

**Comment by ryansolid** [comment]
This was changed in this commit: https://github.com/solidjs/solid/commit/6cd10c736bf1c1aeccb73d93ab5bc4a35e677edd

Seems very specific commit to add this. @otonashixav I have to admit I haven't seen this syntax. Is it a typo?

**Comment by otonashixav** [comment]
It requires at least typescript version 4.7; see https://github.com/solidjs/solid/pull/1826#issuecomment-1652455663

**Comment by only-cliches** [comment]
Wow, I didn't know about that syntax!  Thanks for the clarification, will update TS.
