### ISSUE TITLE
ReferenceError: XXX is not defined when using createResource

### ISSUE THREAD

**Issue by oliverpool** [solidjs/solid#2073]
### Describe the bug

I created a new project using `npx degit solidjs/templates/js my-app` (without typescript).

I want to fetch some data and followed the [new docs](https://docs.solidjs.com/guides/fetching-data#using-createresource) accordingly.

When I try it in the sandbox it works, however locally it yields `ReferenceError: counter is not defined`.

### Your Example Website or App

https://codeberg.org/oliverpool/ics-yearly-planner/src/branch/solidjs

### Steps to Reproduce the Bug or Issue

1. Clone the project https://codeberg.org/oliverpool/ics-yearly-planner and switch to the `solidjs` branch.
2. Run `npm install` and `npm run dev`
3. Visit http://localhost:3000/ and check that everything looks fine
4. Go to the `src/Counter.jsx` file and uncomment the `{/* <Show when={counter.loading}>LOADING</Show> */}` line.
5. Go back to the browser and see the console log.
6. Reload the page: nothing is rendered.

### Expected behavior

As a user I would expected no `ReferenceError`.

### Platform

- OS: Linux
- Browser: Firefox 122.0.1
- Version: 1.8.14

**Comment by oliverpool** [comment]
Seems to have been fixed with 1.8.15 which was released yesterday!

Sorry for the noise.

**Comment by birkskyum** [comment]
thanks for reporting!

**Comment by ryansolid** [comment]
This was probably related to that issue with vite-plugin-solid we had yesterday. Thanks for reporting anyway.
