### ISSUE TITLE
Trying to access fields of data from `createResource` throws error

### ISSUE THREAD

**Issue by matronator** [solidjs/solid#2096]
### Describe the bug

When I try to access a property of an object from a resource, I get the following error in the console:

```
Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'data().date')
```

Here's my code:

```ts
// data fetcher

export async function fetchDay(date: string) {
    const response = await fetch(`${API_URL}/days?date=${date}`);

    console.log(`${API_URL}/days?date=${date}`);

    return response.json();
}
```

```tsx
// the component

const params = useParams();
const [data] = createResource(params.day, fetchDay);

return (
    <div>
        <Card>
            <CardHeader>
                <h1>{data().date}</h1>
            </CardHeader>
            <CardContent>
                {props.children}
            </CardContent>
        </Card>
    </div>
)
```

Now if I try to render just `data()` it works and renders `[object Object]`. However if I try to log it in the console, it outputs `undefined`.

The code is the same as in the docs on Solid's website here: https://docs.solidjs.com/guides/routing-and-navigation#accessing-parameters

### Your Example Website or App

https://github.com/matronator/dochazka

### Steps to Reproduce the Bug or Issue

Run the app.

### Expected behavior

Be able to access the properties returned from `data()`.

### Platform

- OS: [e.g. macOS]
- Browser: [Safari]
- Version: [1.8.15]

**Comment by atk** [comment]
Without an options.initial value, the resource's value will initially be undefined, so either use `data()?.date` or use an iniital value that defines date with a placeholder.

**Comment by matronator** [comment]
Sorry, yeah, my problem was that the response was an array, but it didn't report anything in the console, just failed silently when I tried accessing a property on an array.
