### ISSUE TITLE
'reconcile' mutates array items

### ISSUE THREAD

**Issue by DrevaSergii** [solidjs/solid#2099]
### Describe the bug

I want to develop something like [Combobox](https://mantine.dev/core/combobox/#search-input) component - input field with a list of suggestions.
These suggestions are stored on the server, so I have to use `createStore` and `reconcile` to optimise the rendering of the new items.
I managed to add search field and display suggestions by field value, but I noticed that `reconcile` mutates array items and after a while the list displays the same suggestion multiple times.

### Your Example Website or App

https://playground.solidjs.com/anonymous/e7f8746a-97f3-4edb-8fcf-041905c5660d

### Steps to Reproduce the Bug or Issue

1. Go to the [example](https://playground.solidjs.com/anonymous/e7f8746a-97f3-4edb-8fcf-041905c5660d)
2. Click on the input
3. Press `3`, press `Delete` few times.

### Expected behavior

As a user, I expected to get the same suggestions while typing, but after some time the list displays the same suggestion multiple times.

### Screenshots or Videos

https://github.com/solidjs/solid/assets/27158929/ea9b28cb-6def-47ed-9f97-72ac6994fbcc

**Comment by sdreva** [comment]
@phy-lei I solved the problem by adding `key` option to [reconcile](https://www.solidjs.com/docs/latest#reconcile).

**Comment by phy-lei** [comment]
Thanks, I tried it and the problem was resolved.
