### ISSUE TITLE
[Bug?]: hydration mismatch on ssr, and nested ternaries in jsx with objects or signals

### ISSUE THREAD

**Issue by birkskyum** [solidjs/solid#2100]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

With SSR, this gives a hydration error:

```tsx
export default function App() {
  const obj1 = {
    prop: true,
  };

  const obj2 = {
    prop: true,
  };

  return <>{obj1.prop ? obj2.prop ? <div>Output</div> : <></> : <></>}</>;
}
```

The error also exist with signals instead of plain objects

```tsx
import { createSignal } from 'solid-js';

export default function App() {
  const [signal1, setSignal1] = createSignal(true);
  const [signal2, setSignal2] = createSignal(true);

  return <>{signal1() ? signal2() ? <div>Output</div> : <></> : <></>}</>;
}
```

The error is:

```sh
Uncaught Error: Hydration Mismatch. Unable to find DOM nodes for hydration key: 1
    at getNextElement (chunk-7APIXOX5.js?v=fd41909e:275:37)
    at app.tsx:12:25
    at normalizeIncomingArray (chunk-7APIXOX5.js?v=fd41909e:486:51)
    at insertExpression (chunk-7APIXOX5.js?v=fd41909e:438:9)
```

### Expected behavior 🤔

I expected this to work, like it does with `ssr:false`.

The code also runs fine if I replace this:

```tsx
return <>{obj1.prop ? obj2.prop ? <div>Output</div> : <></> : <></>}</>;
```

With anything else really..  

```tsx
return <div>{obj1.prop ? obj2.prop ? <div>Success</div> : <></> : <></>}</div>;
return <>{true ? obj2.prop ? <div>Success</div> : <></> : <></>}</>;
return <>{obj1.prop ? true ? <div>Success</div> : <></> : <></>}</>;
return <>{obj1 ? obj2 ? <div>Success</div> : <></> : <></>}</>;
return <>{obj1.prop && obj2.prop && <div>Success</div>}
```

### Steps to reproduce 🕹

Steps:

1. Take the Bare example, and update the App component
2. Look in console.

Here is a stackblitz:
- SolidStart bare: https://stackblitz.com/edit/github-7dcnxd?file=src%2Fapp.tsx
- Astro: https://stackblitz.com/edit/github-taemjc-gceveu?file=src%2Fcomponents%2FApp.jsx
- Vinxi (solid, ssr, basic): https://stackblitz.com/edit/github-q2byll?file=app%2Fserver.tsx

**Comment by birkskyum** [comment]
> I'm going to move this to Solid.. I'm about 99% sure this is a compilation mismatch error.

Fair enough. I tried, but didn't manage to, reproduce the error with the ssr examples in the solid repo [here](https://github.com/solidjs/solid/tree/main/packages/solid-ssr/examples). I can repro in vinxi ssr example / astro / start... is there any chance it could come from vite-plugin-solid ?

**Comment by birkskyum** [comment]
I think I've figured why the error doesn't repro in the solid-ssr examples as i expected: It only shows up in dev mode, and they only have build/start.

For both astro, vinxi, solid-start I don't see the error when previewing a build.

**Comment by birkskyum** [comment]
Since it's only in dev mode, can this be esbuild related? what is the pipeline there?

**Comment by lxsmnsyc** [comment]
@birkskyum I can't seem to repro it in the vite demo: 
![image](https://github.com/solidjs/solid/assets/4783372/d030c9ab-1847-4e29-86f8-bb597b29cf5b)

**Comment by lxsmnsyc** [comment]
@birkskyum the only common thing between the three is that they are in SSR and they use the Vite plugin.

**Comment by birkskyum** [comment]
@lxsmnsyc exactly, but can we somehow narrow down further with the information that the error only appear in dev mode, or is it just silence in prod?

**Comment by birkskyum** [comment]
I'm actually a bit confused why it's trying to hydrate in the first place - this component should just return <div>Output</div> which doesn't require any js on the client

**Comment by birkskyum** [comment]
Alright, if I remove the dev-only flag in dom-expressions for the Hydration Mismatch error, then I can repro with the solid-ssr example as well - without the vite-plugin-solid etc.

**Comment by birkskyum** [comment]
This is an error in babel-plugin-jsx-dom-expressions

**Comment by birkskyum** [comment]
```ts
function Comp (){
  const obj1 = {
    prop: true,
  };

  const obj2 = {
    prop: true,
  };

  return <>{obj1.prop ? obj2.prop ? <span>4</span> : <></> : <></>}</>;
}
```

Compiles to

```diff
function App() {
  const obj1 = {
    prop: true
  };
  const obj2 = {
    prop: true
  };
  return _$memo((() => {
    const _c$ = _$memo(() => !!obj1.prop);
    return () => _c$() ? (() => {
      const _c$2 = _$memo(() => !!obj2.prop);
      
--    // Current / Wrong
--    return () => _c$2() ? _$getNextElement(_tmpl$) : [];
      
+     // Correct
+     return (() => _c$2() ? _$getNextElement(_tmpl$) : [])();
      
    })() : [];
  })());
}
```

**Comment by birkskyum** [comment]
Seems like the wrapping memo is lacking a "() =>", and every memo inside has an extra.

Therefore

### 0 x obj1.prop - this works

```ts
<>{_$getNextElement(_tmpl$)}</>
```

Result

```ts
return getNextElement(_tmpl$);
```

### 1 x obj.prop - this works, accidentally


```ts
<>{ obj1.prop ? _$getNextElement(_tmpl$) : [] }</>
```

Result

```ts
return createMemo( // Missing "() =>" from the wrapper

    () => (createMemo(() => !!obj1.prop)() ? getNextElement(_tmpl$) : [])  // inserted per obj1.prop

);
```

here we see the wrapper as an IIFE, but because the function inside has an extra `() =>` it's being countered, and the result is this which does work:

```ts
return createMemo(() => // Steals the "() =>" from below line

 (createMemo(() => !!obj1.prop)() ? getNextElement(_tmpl$) : []) 

);
```

### 2 x obj.prop

```ts
<>{ obj1.prop ? obj1.prop ? _$getNextElement(_tmpl$) : [] : [] }</>
```

Result

```ts
return createMemo( // Missing "() =>" from the wrapper

    () => (createMemo(() => !!obj1.prop)() ? 

       () => (createMemo(() => !!obj1.prop)() ? getNextElement(_tmpl$) : [])  // inserted per obj1.prop
//      ^ this "()=>" should not be here, and does so "getNextElement" never get's called

   : [])  // inserted per obj1.prop

);
```

this is where things start to go sideways. The wrapper still pairs with the outermost `() =>`, but there is an extra one added within.

It ofc. only get's worse if i make the example with 3 x obj.prop, because then there're two extra `() =>` that doesn't get called.

### Solution

an extra `() =>` should be added to the outermost wrapper, and no `() =>` should wrap each memo inside.

Result

```diff
-- return createMemo(
++ return createMemo(() =>

--       () => (createMemo(() => !!obj1.prop)() ? getNextElement(_tmpl$) : [])  // inserted per obj1.prop
++      (createMemo(() => !!obj1.prop)() ? getNextElement(_tmpl$) : [])  // inserted per obj1.prop


);
```

**Comment by ryansolid** [comment]
Hmm.. I wonder if I did this for a reason. But didn't reflect it in SSR. The one thing that returning the function does is isolate the execution.. however returning a non-memoized function seems weird. So this is probably my mistake. There was a compilation issue where we were hoisting up the memo outside of the prop getter. I changed the behavior then. I'd love to track that down.
