### ISSUE TITLE
SVG attribute stdDeviation changes to lowercase when used with a reactive variable

### ISSUE THREAD

**Issue by mthh** [solidjs/solid#2110]
### Describe the bug

When I create an SVG element of type `feDropShadow` in JSX and its `stdDeviation` attribute is linked to a signal or a store, the property is generated entirely in lowercase (`stddeviation`) instead of keeping its initial case, making this property inactive.

For example with the following code :

```jsx
export default function ExampleSvg() {
  const [stdDev, setStdDev] = createSignal(0);

  return (
    <div>
      <svg width="200" height="200">
        <defs>
          <filter id="shadow-2">
            <feDropShadow dx="4" dy="8" stdDeviation={stdDev()} />
          </filter>
        </defs>
        <circle cx="50%" cy="50%" r="80" style="fill:blue; filter:url(#shadow-2);" />
      </svg>
    </div>
  );
}
```

Note that this doesn't happen if the same element is written in JSX but the `stdDeviation` attribute isn't linked to a signal or to a store.

### Your Example Website or App

https://stackblitz.com/edit/solidjs-templates-cvdvm1?file=src%2Findex.jsx,src%2FSvgWorksFine.jsx,src%2FSvgDontWorkFine.jsx

### Steps to Reproduce the Bug or Issue

1. Go to https://stackblitz.com/edit/solidjs-templates-cvdvm1
2. Take a look at the HTML code generated for the `feDropShadow` filter in the first circle, no problem, it works fine.
3. Take a look at the HTML code generated for the `feDropShadow` filter in the second circle, the stdDeviation property is written entirely in lowercase which is not what is expected.

### Expected behavior

As a user, I expect the svg attributes to retain the case in which they were written.

### Screenshots or Videos

Current behavior (the second circle in the stackblitz demo):

![Capture du 2024-03-25 17-00-57](https://github.com/solidjs/solid/assets/12172162/da33891c-17c9-4395-bd03-0f3b45ca3812)

Expected behavior (as for the first circle in the stackblitz demo):

![Capture du 2024-03-25 17-00-28](https://github.com/solidjs/solid/assets/12172162/1792ca75-c1ff-4a3b-aeec-ec1999692fb9)

### Platform

- OS: Linux
- Browser: Chromium
- Version: 123.0.6312.58

### Additional context

Please let me know if this problem is not directly related to solid-js / to this repo, so that I can open an issue in the appropriate place.

**Comment by maciek50322** [comment]
Unfortunately that's what happens with html attributes in Solid jsx after transform. Mainly because html attributes are case insensitive, this is xml though - case sensitive. So that's valid issue, maybe there should be someting alongside `prop:` and `attr:` (`svg:` / `case:`)?
Or reconsider how attribute names are handled?

Workarounds for now:
- ```tsx
  <feDropShadow dx="4" dy="8" {...{stdDeviation: stdDev()}} />
  ```

- ```tsx
  let dropShadow;
  createEffect(() => {
    dropShadow.setAttribute("stdDeviation", stdDev())
  });
  
  ...
  
  <feDropShadow dx="4" dy="8" ref={dropShadow} />
  ```

**Comment by ryansolid** [comment]
Added it. This will be part of the next Solid release. This appears to be the only one that is missing cross-checking with: https://developer.mozilla.org/en-US/docs/Web/SVG/Element
