### ISSUE TITLE
[Bug] Repeated call syntax in JSX breaks reactivity

### ISSUE THREAD

**Issue by deluksic** [solidjs/solid#2134]
### Describe the bug

Having `someSignal()()` inside JSX breaks reactivity.

### Your Example Website or App

https://playground.solidjs.com/anonymous/a27d79e6-d87f-4361-ad2b-512cd32c6d18

### Steps to Reproduce the Bug or Issue

1. Click the first counter a few times to make it different than the second counter
2. Toggle between the counters using the third button

### Expected behavior

I expect `Result (broken)` to match `Result (works)`.

### Platform

All

### Additional context

Discussion on discord https://discord.com/channels/722131463138705510/751355413701591120/1229427809173377144

**Comment by ryansolid** [comment]
Yeah this is a compiler error.. when it detects it can avoid the wrapper and pass in the signal directly there is no new wrapper made. It turns out that we prematurely remove the wrapper when there are double function calls.
