### ISSUE TITLE
[Astro] resource and signal rendering is mixed up on the client

### ISSUE THREAD

**Issue by PeterDraex** [solidjs/solid#2135]
### Describe the bug

I'm rendering a resource and a signal:

```ts
  return (
    <>
      resource: {data()}
      <br />
      signal: {isMounted() ? 'yes' : 'no'}
    </>
  );
```

But [in Astro](https://stackblitz.com/edit/github-pqy8j7-3kzkkj?file=src%2Fcomponents%2FPage.tsx), the resource gets render output is:
```
resource: nopesignal: nonope
signal: yes
```

### Your Example Website or App

https://stackblitz.com/edit/github-pqy8j7-3kzkkj?file=src%2Fcomponents%2FPage.tsx

### Steps to Reproduce the Bug or Issue

-

### Expected behavior

In [pure SolidJS](https://stackblitz.com/edit/solidjs-templates-un3rgb?file=src%2FApp.tsx), the output is correct:
```
resource: nope
signal: yes
```

### Platform

Windows, Chrome 123

**Comment by elite174** [comment]
One solution is: wrap `data` with `span`

```tsx
    resource: <span>{data()}</span>
    <br />
    signal: {isMounted() ? 'yes' : 'no'}
 ```

**Comment by ryansolid** [comment]
I swore I fixed this top level fragment issue. And I had but I missed a case where it resolves for the first time under a Suspense boundary.
