### ISSUE TITLE
Is security@solidjs.com active now?

### ISSUE THREAD

**Issue by arkark** [solidjs/solid#2149]
### Describe the bug

I sent an email to `security@solidjs.com` according to [Security.md](https://github.com/solidjs/solid/security/policy) about a month ago, but I have not received a reply.

May I ask you to check the mailbox?
My email title starts with `[Security Report]` and the date is 4/8.

I'm sorry for opening this issue.

### Your Example Website or App

-

### Steps to Reproduce the Bug or Issue

-

### Expected behavior

-

### Platform

-

**Comment by ryansolid** [comment]
Hey thanks. I was away from work for a few weekd with some personal stuff. I will try to look into it shortly.

**Comment by arkark** [comment]
Thank you. I'll close this issue.
