### ISSUE TITLE
Attempted import error

### ISSUE THREAD

**Issue by IsaccoSordo** [solidjs/solid#2175]
### Describe the bug

Hello,

We are receiving reports from users that importing our [SDK](https://github.com/airgap-it/beacon-sdk) into their SSR applications results in the following errors:

```bash
Attempted import error: 'effect' is not exported from 'solid-js/web'
Attempted import error: 'memo' is not exported from 'solid-js/web' (imported as 'memo')
Attempted import error: 'template' is not exported from 'solid-js/web' (imported as 'template')
Error: export 'style' (imported as 'style') was not found in 'solid-js/web'
```

We attempted to resolve these issues by updating our rollup configuration file from [this version](https://github.com/airgap-it/beacon-sdk/blob/master/packages/beacon-ui/rollup.config.mjs) to [this version](https://github.com/airgap-it/beacon-sdk/blob/fix/solid_build/packages/beacon-ui/rollup.config.mjs), explicitly excluding Solid dependencies from the bundle. 
Despite this, we continue to encounter the same errors when importing our module into a NextJS app.

I've linked a StackBlitz repository to this issue, which hosts a NextJS app attempting to import a SolidJS component, where one of the errors occurs.

For instance from our observations, directly calling `createEffect` in the example app does not trigger the error, but it seems that when it gets transpiled the error appears.
If `createEffect` is called through the `html` property from `import html from "solid-js/html";`, we encounter the "Attempted import" error.

Thank you for your attention to this matter.

### Your Example Website or App

https://stackblitz.com/edit/stackblitz-starters-dttbwm?file=app%2Fpage.tsx,packages%2Fmy-ui-lib%2Fsrc%2FApp.tsx

### Steps to Reproduce the Bug or Issue

One way we found to consistently reproduce the issue is as follows:

1. Set up a NextJS application.
2. In the NextJS app, import `html` from `solid-js` using the statement: `import html from "solid-js/html";`.
3. Attempt to use a SolidJS component within the NextJS application.

This should trigger the error mentioned above.

### Expected behavior

The "Attempted import" errors should not appear in the console.

### Platform

Versions tested: 1.7.6, 1.7.11

**Comment by ryansolid** [comment]
In 1.9 instead of erroring on import we will error on calling the function.

This is fixed by this commit: https://github.com/solidjs/solid/commit/4f8597dc0e04f1cdb5c5502f6f82499ccb9c7b97
