### ISSUE TITLE
Using enableScheduling in a simple solidjs-router project throws errors on transitions

### ISSUE THREAD

**Issue by QWu4xYV** [solidjs/solid#2176]
### Describe the bug

Using enableScheduling in a simple solidjs-router project throws errors when changing pages, saying that the results of createMemo are `undefined`. 

(To be clear, this isn't a blocker or even an issue for me, I had just run enableScheduling in the hopes that it would help with some perf issues due to bad design on my part. Reporting it just in case it wasn't a known issue and there were plans to make enableScheduling less experimental)

### Your Example Website or App

https://stackblitz.com/edit/solidjs-templates-gttqb3?file=src%2FApp.tsx

### Steps to Reproduce the Bug or Issue

1. Open the devtools console drawer
2. Click "Other", which navigates to the second page that's set up
3. See the error

(comment out line 8 and observe that no error is thrown)

### Expected behavior

As a user, I expected to be able to navigate between pages with a Link component and enableScheduling on.

### Platform

- OS:  macOS
- Browser: Chrome
- Version: 124.0.6367.203

**Comment by ryansolid** [comment]
Yeah and truthfully we are redesigning this whole piece. I'm going to close this to keep issues relevant as it as we won't be updating the current version. But appreciate the information.
