### ISSUE TITLE
[ssr]: Spreading `readOnly: false` on input applies `readonly`

### ISSUE THREAD

**Issue by segunadebayo** [solidjs/solid#2192]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

During SSR, spreading `<input {...{ readOnly: false }} />` results in the underlying input getting the `readonly` property. Here's what it looks like:

```html
<input readonly="false">
```

### Expected behavior 🤔

I expect it to be the same as applying `<input readOnly={false} />` which completely skips add `readonly` property

### Steps to reproduce 🕹

Steps:

1. Visit https://stackblitz.com/edit/github-xfcetd?file=src%2Froutes%2Findex.tsx
2. Notice the use of spread `readOnly: false`
3. Try to edit the input that says "Not working"
4. See it's not editable

**Comment by Klerith** [comment]
I had to do this in order to work

```html
readOnly={isNewCourse ? undefined : true}
```

**Comment by tats-u** [comment]
Is the fix going to be shipped only to v2?
The type must be changed from boolean to string in v1 if the fix is applied only to v2.
