### ISSUE TITLE
Unexpected values in For loop when nullish coalescing operator used with additonal ternary check

### ISSUE THREAD

**Issue by martinpengellyphillips** [solidjs/solid#2215]
### Describe the bug

When a nullish coalescing operator is used with an additional ternary check within a `<For>` loop, Solid appears to render a duplicate and incorrect value for every item. 

### Your Example Website or App

https://playground.solidjs.com/anonymous/8888fdd6-3c51-43ad-a7c8-18f26f57574c

### Steps to Reproduce the Bug or Issue

1. Use the toggle button in the shared reproducible test case to see the effect.
2. Note that when nullish coalescing operator used _with_ additional ternary, the output is incorrect.

### Expected behavior

List should output the same with nullish coalescing operator as with using multiple ternary operators.

### Screenshots or Videos

![Kapture 2024-07-07 at 20 37 42](https://github.com/solidjs/solid/assets/214338/8f80d5a3-4074-44f2-a53f-d9fd4be93d48)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by maciek50322** [comment]
I think it has to do with order of operations, the `??` is higher than `? ... : ...`, and so the line
```tsx
return <>{meta.highlight ?? item.id === 2 ? 'PEAR' : item.name}</>;
```
is same as
```tsx
return <>{(meta.highlight ?? item.id === 2) ? 'PEAR' : item.name}</>;
```
and because `meta.highlight` is always truthy, it immediately jumps to `'PEAR'`

to fix this, try using parenthesis different way
```tsx
return <>{meta.highlight ?? (item.id === 2 ? 'PEAR' : item.name)}</>;
```

**Comment by martinpengellyphillips** [comment]
Indeed! Thanks for the hint. Closing this as user error :)
