### ISSUE TITLE
Vite HMR causes SSR Hydration Mismatch

### ISSUE THREAD

**Issue by QuentinDutot** [solidjs/solid#2219]
### Describe the bug

A Vite HMR update followed by a hard page refresh causes an hydration mismatch error.

On the same page the next renderToString call returns an empty string.

### Your Example Website or App

https://stackblitz.com/edit/stackblitz-starters-n1n7zh?file=src%2Fcomponents%2FHome.tsx

### Steps to Reproduce the Bug or Issue

1. Make a change in Home.tsx component
2. Browser receive the hmr update (works as expected)
3. Refresh the page (Ctrl+R)
4. Get the hydration mismatch error in the console

### Expected behavior

I expected no hydration mismatch error.

### Platform

- OS: macOS
- Browser: Edge
- Version: -

**Comment by mdynnl** [comment]
As `lazy` helper is built on `createResource`, `Suspense` is necessary to wait for them to finish loading.
```tsx
<Router root={props => <Suspense>{props.children}</Suspense>}>
	...
</Router>
```

_hono vite server seems neat though_

**Comment by QuentinDutot** [comment]
You're right `Suspense` was missing, thanks!
