### ISSUE TITLE
Export types mismatch

### ISSUE THREAD

**Issue by illiaChaban** [solidjs/solid#2224]
### Describe the bug

I'm using typescript and able to import "effect" from "solid-js/web"
```
import { effect } from "solid-js/web";

effect;
```
If I use it in any way I get "The requested module 'solid-js/web' does not provide an export named 'effect'" error. Seems like types specify this export, but it doesn't actually exist

Types:
<img width="553" alt="image" src="https://github.com/user-attachments/assets/bdda4018-5c51-42af-8662-20107c6322de">

### Your Example Website or App

https://stackblitz.com/edit/github-f45fb5-pkhx6p?file=src%2Froutes%2Findex.tsx

### Steps to Reproduce the Bug or Issue

```
import { effect } from "solid-js/web";

effect;
```

### Expected behavior

No error or no available export 

### Screenshots or Videos

<img width="553" alt="image" src="https://github.com/user-attachments/assets/71fadad2-da33-4004-8852-2d34decd325a">

### Platform

- OS: [e.g. macOS]]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by Brendan-csel** [comment]
Perhaps you want `createEffect`?

or maybe `import { type effect } from 'solid-js/web';` if you just want the type?

**Comment by illiaChaban** [comment]
No, I just like the shorter name vs createEffect and noticed that it was available.

**Comment by Brendan-csel** [comment]
Yeah - a different (internal use) thing I think.  Probably best to stick with `createEffect` :)

**Comment by ryansolid** [comment]
Yeah this is internal used by the compiler and not intended for outside use. Under the hood it actually doesn't use `createEffect` and uses `createRenderEffect`. We need to export these helpers for the compiled output but the signature could be different and have different behavior.
