### ISSUE TITLE
createAsync stuck on initialValue via ssr navigation

### ISSUE THREAD

**Issue by katywings** [solidjs/solid#2228]
### Describe the bug

`createAsync` that depends on other `createAsync` is not properly rendered during full ssr navigations since Solid v1.8.18.

### Your Example Website or App

https://stackblitz.com/edit/github-pvkuw1?file=src%2Froutes%2Findex.tsx

### Steps to Reproduce the Bug or Issue

1. Access the result of a `createAsync` call in a second `createAsync` call
2. Output the data of the second createAsync call in the jsx
3. Open the website in the browser (via full ssr navigation)
4. Result: The second createAsync call will be stuck on the initialValue of the first createAsync

### Expected behavior

The second `createAsync` call should either properly render during ssr, or the client should atleast replace the initialValue with the proper value during hydration.

### Screenshots or Videos

SSR + Hydration Result in 1.8.17 (right):
![Bildschirmfoto vom 2024-07-19 23-12-20](https://github.com/user-attachments/assets/254adea3-8116-4497-9de3-f4eaac3305e4)

SSR + Hydration Result in 1.8.18 (wrong):
![Bildschirmfoto vom 2024-07-19 23-12-47](https://github.com/user-attachments/assets/1a378266-9cc7-47e3-a877-210080a99380)

### Platform

- Solid: 1.8.18
- Firefox & Chrome

**Comment by ryansolid** [comment]
Ok.. I thought there might be a chance of this but I use this cascading example in Solid's repo to test this case specific. The original approach for this had some really buggy side effects for hydration. I guess we still need something like that though. I will look into this.

**Comment by katywings** [comment]
Thank you, I am looking forward to what you will come up with! My workaround for now is to drill the loaded data from the parent to the child with the nested `createAsync`s (https://codeberg.org/nitropage/nitropage/src/commit/9fbcfa1d4b2d75237337d9180040ba20149307a9/packages/nitropage/src/components/admin/router.tsx#L74)

**Comment by katywings** [comment]
Thank you for the fix 🥳!
