### ISSUE TITLE
Solidjs cannot update a dom correctly in the Chrome for iOS browser

### ISSUE THREAD

**Issue by Lam9090** [solidjs/solid#2235]
### Describe the bug

I found that in the Chrome for iOS browser, this browser can automatically add some html(**_chrome_annotation_**) tag to some specific texts. it causing some part of the DOM structure changed. 

when solid try to update the content inside this tag, it won't 
work, but work correctly in other browser and the Chrome for PC.

![image](https://github.com/user-attachments/assets/c107f06f-724b-466d-903c-b5f9de928bc9)

### Your Example Website or App

https://codesandbox.io/p/devbox/cocky-waterfall-94mrl7?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clyxriv1b00073p6k0jv23saw%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clyxriv1b00023p6k9dvteep0%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clyxriv1b00043p6k601x80o4%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clyxriv1b00063p6ktzpq5dgt%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clyxriv1b00023p6k9dvteep0%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clyxriv1a00013p6kg78zo4jf%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%257D%255D%252C%2522id%2522%253A%2522clyxriv1b00023p6k9dvteep0%2522%252C%2522activeTabId%2522%253A%2522clyxriv1a00013p6kg78zo4jf%2522%257D%252C%2522clyxriv1b00063p6ktzpq5dgt%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clyxriv1b00053p6kkerp6gen%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clyxriv1b00063p6ktzpq5dgt%2522%252C%2522activeTabId%2522%253A%2522clyxriv1b00053p6kkerp6gen%2522%257D%252C%2522clyxriv1b00043p6k601x80o4%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clyxriv1b00033p6kxezvlyrf%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522id%2522%253A%2522clyxriv1b00043p6k601x80o4%2522%252C%2522activeTabId%2522%253A%2522clyxriv1b00033p6kxezvlyrf%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### Steps to Reproduce the Bug or Issue

1. Open the code sandbox in the Chrome for IOS browser.
2. Click the button to "Open in the new Tab" .
    <img width="884" alt="image" src="https://github.com/user-attachments/assets/fe482526-4eec-4777-93b9-6128c8150873">
3. You will see the content("11m") automatically added an underline
4. clicking the "update text" button
5. expected the "11m" to be updated to "22m", but in the Chrome for iOS, it won't work correctly.

### Expected behavior

Expected the "11m" to be updated to "22m", but in the Chrome for iOS, it won't work correctly.

### Platform

- OS: iOS 18
- Browser: Chrome for IOS
- Version: 126.0.6478.153 (Official Build) stable (64-bit)

**Comment by ryansolid** [comment]
I made a playground version too.. hopefully to help people test this: https://playground.solidjs.com/anonymous/f162b22c-1c40-4189-b0fd-d3d575b1806a

I don't have an iOS device to test offhand but in general things messing with the structure of HTML will break our ability to update. It will break any cloning based framework like Lit, Vue Vapor, Svelte 5, but it will probably break almost any JS framework to be fair. We expect the DOM to be in a certain place and if it changes without our knowledge things will go wrong. Similar to built in browser translators etc which also have this problem.

I was trying to search for this issue in other frameworks and only saw an unanswered question on Stackoverflow for Lit. https://stackoverflow.com/questions/78207646/how-do-i-disable-chrome-annotation-tags

In any case thanks for reporting hopefully we can bring more visibility to this issue.

**Comment by gtm-nayan** [comment]
Somewhat related: https://issues.chromium.org/issues/353650041

**Comment by Lam9090** [comment]
> I made a playground version too.. hopefully to help people test this: https://playground.solidjs.com/anonymous/f162b22c-1c40-4189-b0fd-d3d575b1806a
> 
> I don't have an iOS device to test offhand but in general things messing with the structure of HTML will break our ability to update. It will break any cloning based framework like Lit, Vue Vapor, Svelte 5, but it will probably break almost any JS framework to be fair. We expect the DOM to be in a certain place and if it changes without our knowledge things will go wrong. Similar to built in browser translators etc which also have this problem.
> 
> I was trying to search for this issue in other frameworks and only saw an unanswered question on Stackoverflow for Lit. https://stackoverflow.com/questions/78207646/how-do-i-disable-chrome-annotation-tags
> 
> In any case thanks for reporting hopefully we can bring more visibility to this issue.

Thank you so much for your detailed response and for taking the time to look into this issue. I really appreciate the effort.

For anyone facing this issue, my current temporary workaround is to add an invisible character like '\u200B' between the "11" and "m". I hope this helps others who might encounter the same problem.

**Comment by wootra** [comment]
is it still valid issue? I followed the scenario and cannot reproduce it. I am on Chrome on IOS (version 126.0.6478.153)

**Comment by Lam9090** [comment]
> I followed the scenario and cannot reproduce it. I am on
> 
> * Chrome on IOS (version 126.0.6478.153) - iPhone 13 mini
> * IOS version 17.5.1
> 
> I see the chrome version is the same with the reported one, but maybe different result on different IOS version?

I can't reproduce the issue either; it seems they may have turned off this feature recently. I'm going to close this issue for now.
