### ISSUE TITLE
Best way to have dynamic component in Solidjs?

### ISSUE THREAD

**Issue by geohuz** [solidjs/solid#2242]
### Discussed in https://github.com/solidjs/solid/discussions/2240

<div type='discussions-op-text'>

<sup>Originally posted by **geohuz** July 30, 2024</sup>
I have a component which loads and displays svg file as component, I can't find a decent way to do this, currently I'm coding like this:

```jsx
import {  createEffect } from "solid-js";
import { render } from 'solid-js/web'

export const BaseLayer = (props) => {
  let baseLayerImg
  let gRef
  let dispose = () => {}      // a dispose function for the first run

  createEffect(async()=> {
    let file = props.file                     // have to access props.file to make reactive
    dispose()                                   // run dispose to remove the rendered component
    baseLayerImg = await import(`./${file}.svg?component-solid`)  // load my svg file 
    dispose = render(baseLayerImg.default, gRef)                             // render into a node
  })


  return (
      <svg>
        <g ref={gRef}/>
      </svg>
  )
}
```

so end user can choose file and a parent component like `<BaseLayer file="base" />` or `<BaseLayer file="other" />` can render different svg image dynamically. But the implementation looks awkward. Would somebody suggest an elegant way to do it?</div>

**Comment by onx2** [comment]
I have a min repro of dynamic svg imports posted here, using this plugin & `lazy`.
https://github.com/jfgodoy/vite-plugin-solid-svg/issues/47#issuecomment-2266370301

**Comment by onx2** [comment]
I was only able to get this working correctly (for my use-case of lazy dynamic svg components) with this approach. Vite will handle dynamic imports so we can remove `lazy` which simplifies things... After that we need to use `createResource` to create a reactive scope for importing the file. Then, instead of using `Suspense`, `Show` can be used to wait for the resource to be ready.


```tsx
export function Icon(props: IconProps): JSX.Element {
  const mergedProps = mergeProps({ size: "md", callout: false }, props);

  const [lazyIcon] = createResource(
    () => mergedProps.icon,
    async (iconName) => {
      try {
        const lazyFile = await import(
          `./icons/icon-${iconName}.svg?component-solid`
        );
        return lazyFile.default;
      } catch {
        return null;
      }
    }
  );

  return (
    <Show when={lazyIcon()} fallback={<div class={css[mergedProps.size]} />}>
      {(LoadedIcon) => (
        <div
          classList={{
            [css.callout]: mergedProps.callout,
            [css.icon]: true,
            [css[mergedProps.size]]: true,
            ...(mergedProps.color ? { [css[mergedProps.color]]: true } : {}),
          }}
        >
          {LoadedIcon()}
        </div>
      )}
    </Show>
  );
}
```

**Comment by ryansolid** [comment]
Honestly the discussion (or on our discord is probably the best place to ask the question). Looking there I think there is an answer so I'm going to close this. Continue the discussion there.
