### ISSUE TITLE
Hydration Mismatch Fallback Render

### ISSUE THREAD

**Issue by joeyczz** [solidjs/solid#2250]
### Describe the bug

When I use SSG to generate HTML code, with the code update, the HTML code generated by SSG cannot match CSR. At this point, using hydrate will get an error _Hydration Mismatch_ , which I think is correct. However, when I want to use render to re-render after catch the error, I get the same error again.

<img width="469" alt="image" src="https://github.com/user-attachments/assets/b631ec3d-2f32-4603-9ae8-95448f901945">

<img width="665" alt="image" src="https://github.com/user-attachments/assets/b6bf8dce-0b2e-4028-a9ae-175c5b79bf78">

### Your Example Website or App

https://codesandbox.io/p/devbox/solid-ssg-ssr-lvqs4w

### Steps to Reproduce the Bug or Issue

<img width="1907" alt="image" src="https://github.com/user-attachments/assets/dbf28ac1-d7ab-4327-b96f-1a3615442d7a">

### Expected behavior

When `hydrate(() => <App />, root);` got an error, and use `render(() => <App />, root)` to Re-render, no error and render success

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]
Mac OS Chrome 127

**Comment by ryansolid** [comment]
Gotcha.. we are missing a try catch.. something to reset hydration. Hydrate on completion clears its state but we should do that even if it errors. Thanks for the report.
