### ISSUE TITLE
`onclick="alert(1)"` works on `<button>` but not on `<Dynamic component="button">`

### ISSUE THREAD

**Issue by gersomvg** [solidjs/solid#2258]
### Describe the bug

`onclick="alert(1)"` works on `<button>` but not on `<Dynamic component="button">`

### Your Example Website or App

https://playground.solidjs.com/anonymous/bb6ad441-95f0-4f7a-b8d8-267d13d1bd4f

### Steps to Reproduce the Bug or Issue

One of the two buttons doesn't show an alert.

### Expected behavior

I would expect both buttons to have the same behaviour.

### Platform

macOS, chrome, solid 1.8.21

**Comment by ryansolid** [comment]
I'm surprised that would work from types perspective. The reason the first works is incidental because of an optimization not intentionally. We hijack dom events so I wouldn't expect this to work. But it does bring up an interesting question of whether we could let it work since technically we know the value isn't an array or a function. 

In any case any luck with `attr:onclick`?

**Comment by mdynnl** [comment]
I guess this can be closed https://discord.com/channels/722131463138705510/1275467267865444434

**Comment by gersomvg** [comment]
@ryansolid thanks for the quick reply and @mdynnl thanks for the help on discord. The types perspective is probably just a setup issue on my side. It does show red squiggly lines in the playground indeed.

I was thrown off because I'm using solid in astro and the `attr:` syntax seems to be broken there. So in combination with `onclick` not working on `<Dynamic>`, which is exactly what I'm trying to achieve, it's a bit of a painful combination of events 😅

**Comment by gersomvg** [comment]
> @ryansolid: But it does bring up an interesting question of whether we could let it work since technically we know the value isn't an array or a function.

When mixing islands of different nature in Astro, its actually quite nice if this would be possible. An example usecase:

```
<SolidButton onclick="document.getElementById('foo').showModal()" />
<AstroModalWebComponent id="foo" />
```

"Why would you have that button be written in solid to begin with" I hear you ask... that is because in astro you can't have a solid component that internally renders an astro component, so if there is only one solid component anywhere in your app where you want to use that reusable button, you have to convert it into a solid component.

**Comment by ryansolid** [comment]
Ok since we've opened #2259 I will close this one since there is nothing to fix here I believe except fixing that other issue.
