### ISSUE TITLE
`attr:` syntax doesn't work in server-side rendering

### ISSUE THREAD

**Issue by gersomvg** [solidjs/solid#2259]
### Describe the bug

Solid's attr: syntax broken is broken in astro:
https://stackblitz.com/edit/github-vunq7y?file=src%2Fcomponents%2FSolidComponent.tsx

The funny thing is that locally after triggering HMR by updating a file it does work. It just doesn't work on first render.

It works outside of astro:
https://playground.solidjs.com/anonymous/3fc352bc-7d8d-4031-b510-4ae5ceca35c0

@ryansolid [already identified](https://discord.com/channels/722131463138705510/1275467267865444434/1275478781179596893) this as a general bug in the server-side rendering of solid.

Just opening an issue here to keep track, so it doesn't get lost in the middle of all the `2.0` work.

**Comment by gersomvg** [comment]
Initially opened it on astro's side, but that one is already closed.

https://github.com/withastro/astro/issues/11792

**Comment by gersomvg** [comment]
Thank you so much for spending time on this. From the commit history it looks like this landed in `1.8.22`?

Unfortunately it still doesn't seem to work: https://stackblitz.com/edit/github-vunq7y?file=package.json

**Comment by ryansolid** [comment]
Make sure that the babel plugin is the latest version. Like is babel-preset-solid also 1.8.22. This is a compiler bug I believe. It appears in that project you like you have 1.8.19 installed. Blow out your lockfile, remove and re-install node modules.

**Comment by gersomvg** [comment]
You're right :) With an override it works:

`package.json`
```
{
  ...
  "overrides": {
    "babel-preset-solid": "1.8.22"
  },
  ...
}
```
