### ISSUE TITLE
React is not defined for ESbuild

### ISSUE THREAD

**Issue by kortirso** [solidjs/solid#2261]
### Describe the bug

I try to migrate from react to solid my Ruby on Rails application with bundling js with ESbuild

I made simpliest component

```
import { render } from "solid-js/web";

function HelloWorld() {
  return <div>Hello World!</div>;
}

render(
  () => <HelloWorld />,
  document.getElementById('app')
);
```

I added babel-preset-solid package with configuration in 3 ways, then esbuild runs `esbuild app/javascript/application.jsx --bundle --minify --sourcemap --outdir=app/assets/builds`

and in output file there is `React.createElement("div",null,"Hello World!")` and inside browser console I got `Uncaught ReferenceError: React is not defined`

### Your Example Website or App

https://github.com/kortirso/pullmetry/pull/337

### Steps to Reproduce the Bug or Issue

1) Application can be prepared with (but maybe it's not required)
bundle install
rails db:create
rails db:schema:load
yarn install

2) For bundling
yarn build --watch
check `app/assets/builds/application.js`

### Expected behavior

Output application.js does not have React.createElement

### Platform

- OS: [e.g. macOS]
- Browser: [Firefox]
- Version: [Firefox 129.0.2]

**Comment by ryansolid** [comment]
I admit I have no experience using esbuild directly so I'm unclear if what I'm suggesting is correct, but since the wrong transform is happening I have to imagine the babel preset is not being picked up. This could mean that a babel plugin for esbuild may be required as well.

Looking it up I also see we have an esbuild plugin https://github.com/amoutonbrady/esbuild-plugin-solid. It appears to be a wrapper over the esbuild babel plugin, which atleast aligns with my expectations.

I hope that helps.

**Comment by kortirso** [comment]
@ryansolid yes, looks like adding configuration for esbuild works

```
const path = require('path');
const { context } = require('esbuild');
const { solidPlugin } = require('esbuild-plugin-solid');

async function build() {
  let ctx = await context({
    entryPoints: [path.join(process.cwd(), 'app/javascript/application.jsx')],
    bundle: true,
    minify: true,
    sourcemap: true,
    outdir: path.join(process.cwd(), 'app/assets/builds'),
    absWorkingDir: path.join(process.cwd(), 'app/javascript'),
    plugins: [solidPlugin()],
  }).catch(() => process.exit(1))

  await ctx.watch()
  console.log('watching...')
}

build();
```

and running it with `node esbuild.config.js`,
thank you
