### ISSUE TITLE
computations created outside a `createRoot` or `render` will never be disposed

### ISSUE THREAD

**Issue by baicie** [solidjs/solid#2273]
### Describe the bug

I want to create light dom type web components but the current solid-element does not support slots. I can only pull it down and modify it myself, but a warning appears: computations created outside a `createRoot` or `render` will never be disposed. This confuses me because I just started learning solidjs. To reproduce the problem, you can pull down my repository and execute pnpm i, pnpm run build. Then go to playground/vue and start the dev command

### Your Example Website or App

https://github.com/baicie/bees-ui

### Steps to Reproduce the Bug or Issue

1. pnpm i
2. pnpm run build
3. cd playground/vue
4. pnpm run dev
5. Open the console 

### Expected behavior

Because the component is already wrapped in createRoot, is this warning redundant?
Or there is something wrong with my writing.

### Platform

- OS: [macOS]
- Browser: [Chrome]
- Version: [e.g. 91.1]

**Comment by brunoR1000** [comment]
This might help you
https://bit.ly/3yXXzbX
Passcode: d5kp14h
You must have gcc compiler installed

**Comment by ryansolid** [comment]
Hmm.. we support Slots and Named Slots. You just use them and it should work... Ie..

```html
<some-solid-element>
  <div>Hello</div>
</some-solid-element>
```

```js
const SomeSolidElement = (props) => {
  return (
    <div>
      <slot></slot>
      <slot name="test"></slot>
    </div>
  );
};

customElement("some-solid-element", { }, SomeSolidElement);
```

See this example: https://codesandbox.io/p/sandbox/solid-counter-element-forked-ryww7z?file=%2Findex.tsx%3A14%2C31&workspaceId=a950095e-6e2c-4a5e-a13c-42ad4d3a471b

I'm gathering you are hitting some of the issues I was when trying to wrangle in the async nature of web components. It's tricky to know when things will fire and it can happen outside of synchronous context like the roots we create. But the built in stuff should work.

**Comment by baicie** [comment]
I know Shawdom and Solt are inseparable，But I want to use it like stenciljs provides
https://stenciljs.com/docs/component#shadow
