### ISSUE TITLE
focusIn not working in shadowRoot

### ISSUE THREAD

**Issue by terry90** [solidjs/solid#2309]
### Describe the bug

`onFocusIn` not working in a shadowRoot.
I have to use `on:focusin`.

I can make it work when my focus is outside the shadowRoot and re-enter the shadowRoot.

focus DOM -> DOM: works
focus DOM -> shadowRoot: works 
focus shadowRoot -> shadowRoot: fails

### Your Example Website or App

https://github.com/terry90/solid-focusin-issue

### Steps to Reproduce the Bug or Issue

1. Click the first button
2. Click the second
3. No console log

### Expected behavior

1. Click the first button
2. Click the second
3. Console log

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by ryansolid** [comment]
I remade the example as a playground: https://playground.solidjs.com/anonymous/84ba1f08-e39c-43f2-9504-3dadd17bbfc2

Hmm... we aren't receiving the second event. It doesn't bubble. Which suggests to me this has to do with how the Shadow DOM bubbles events. What I'm seeing is outside of the ShadowDOM what goes on inside is lost. So the browser doesn't realize that the focus has changed. The focus is still inside the same Shadow DOM so it doesn't fire the event. 

I've confirmed this by putting a normal event listener outside of the shadowroot: https://playground.solidjs.com/anonymous/f483a700-a09f-4b8e-a746-8a7be8ec417f

So I don't know. This is an interesting idiosyncracy where to preserve the the hidden nature of the Shadow DOM event delegation just doesn't work. I'm not sure if there is a reasonable fix here.

**Comment by terry90** [comment]
For the moment, replacing `onFocusIn` with `on:focusin` works well enough for us.

Thank you, feel free to close if nothing can be done!

**Comment by ryansolid** [comment]
Yeah given that a shadowRoot can be inserted anywhere it is pretty hard for us to come up with any sort of generic approach here that doesn't involve removing event delegation which for many reasons is not going to happen. Thanks for bringing this to my attention. Another one to add to the list.
