### ISSUE TITLE
Broken video link in README

### ISSUE THREAD

**Issue by timneedham** [solidjs/solid#2315]
### Describe the bug

[SolidJS README](https://github.com/solidjs/solid/blob/main/packages/solid/README.md) points to a missing YouTube video...

* https://www.youtube.com/watch?v=J70HXl1KhWE

### Your Example Website or App

https://www.npmjs.com/package/solid-js

### Steps to Reproduce the Bug or Issue

Click the **"intro video"** link at the top of the [README](https://www.youtube.com/watch?v=J70HXl1KhWE&ab_channel=SolidJS).

### Expected behavior

As a user I expected to "check out an intro video" but instead i am seeing YouTube being sad. 

### Platform

N/A

**Comment by atilafassina** [comment]
oh, that video moved places, @timneedham .

Thanks for pointing that out, I'll make a PR to fix it.

[This is the video](https://www.youtube.com/watch?v=hw3Bx5vxKl0)

**Comment by timneedham** [comment]
Great, thanks @atilafassina ! 🙏
