### ISSUE TITLE
Warning about malformed HTML when using `scope` attribute on `th` tag

### ISSUE THREAD

**Issue by epatters** [solidjs/solid#2326]
### Describe the bug

When Vite builds a Solidjs app that uses the `scope` attribute on `th` tags, a warning about malformed HTML is emitted.

I believe this started happening when I upgraded from the Solidjs v1.8 series to v1.9.1.

### Your Example Website or App

https://stackblitz.com/edit/solidjs-templates-o3v2hy?file=src%2FApp.tsx

### Steps to Reproduce the Bug or Issue

Build the app using Vite and observe the console.

### Expected behavior

I expect to get no warning because the emitted HTML is valid, as confirmed by the w3 validation utility.

However, the following warning is emitted:

```text
The HTML provided is malformed and will yield unexpected output when evaluated by a browser.

- Expected
+ Received

- <th></th>
Original HTML:
 <th scope=col></th>
```

Note that, despite the warning, the generated HTML is as expected and the app appears to work fine.

### Platform

- OS: Linux
- Browser: N/A (but using Firefox)
- Version: Solid v1.9.1

**Comment by titoBouzout** [comment]
There's a PR to solve this and other table related validation issues 
https://github.com/ryansolid/dom-expressions/pull/360

**Comment by epatters** [comment]
Ah, thank you! I didn't know where to look.

**Comment by epatters** [comment]
Resolved by upstream changes. Thanks!
