### ISSUE TITLE
bug: some exposed types/interfaces are not exported by `solid-js`

### ISSUE THREAD

**Issue by jorroll** [solidjs/solid#444]
**Describe the bug**

Currently, `solid-js` does not export all of the type definitions / interfaces used by exported functions. This forces the end user to manually recreate the type/interface (by reviewing source code) if they need access to the type. The most egregious example of this is `PropsWithChildren`, but there are others.

**To Reproduce**

Some of the types/interfaces which are not exported but which are exposed by exported functions are:

- `PropsWithChildren`
- `GraphRecord`
- `SuspenseContextType`
- `ResourceReturn`
- `MatchProps`
- `HydrationContext`
- `SharedConfig`

**Expected behavior**

In general, if a function/object is exported by a package, all types exposed by that function should also be exported, unless there are specific reasons to do otherwise. I've noticed that many packages owned by the `solidui` org fail to do this. I'm prepared to help submit PRs, but sometimes an opinionated decision needs to be made on where the "canonical" version of the type should live. For example, `PropsWithChildren` is currently defined in multiple places. Additionally, there might be specific reasons why some of the types are not exported. For these reasons, a maintainer might be in the best position to make these changes.

**Comment by jorroll** [comment]
> What's the best practice?

I believe that, in general, exporting all types exposed by a package is a best practice (though sometimes there are specific reasons why doing this is undesirable). But as to "what is the best practice for organizing typescript declarations", that I haven't seen and am not aware of. I think it varies by the project (in the same way that javascript file structure is largely a matter of opinion). I actually took a stab at making a PR to accompany this issue a week ago, but it was unclear where `PropsWithChildren` should be declared because it is currently defined in two files that don't seem to have much in the way of common dependencies. While oftentimes a type or interface can find a natural home in a specific file, there will probably always be cases where a type/interface doesn't have a natural home so it's sorta a judgement call on whether you shoehorn it into an existing file or create a new file for that type. 

> I do have some concerns with types giving the perspective of things being more narrow than they are in terms of Signal vs Thunk

This is difficult. In practice, I find one of the primary uses for types are as a form of required jsDoc, so your concern is very valid. 

For this case, the best solution might be something like the following:

```ts
export type Signal<T> = () => T;
export type Thunk<T> = () => T;
export function myFunc<T>(value: Signal<T> | Thunk<T>);
```

Historically, I think you would have needed to instead do `export type Signal<T> = () => T` and `export type SignalOrThunk<T> = () => T` and then use one alias vs the other to make the intent clear. This was because, historically, the typescript compiler would automatically normalize type unions and so something like `function myFunc<T>(value: Signal<T> | Thunk<T>)` would have been condensed to `function myFunc<T>(value: () => T)`. But recently I've noticed typescript has gotten a lot better about honoring aliases and, [in testing just now](https://www.typescriptlang.org/play?#code/PTAEHUFMBsGMHsC2lQBd5oBYoCoE8AHSAZVgCcBLA1UABWgEM8BzM+AVwDsATAGiwoBnUENANQAd0gAjQRVSQAUCEmYKsTKGYUAbpGF4OY0BoadYKdJMoL+gzAzIoz3UNEiPOofEVKVqAHSKymAAmkYI7NCuqGqcANag8ABmIjQUXrFOKBJMggBcISGgoAC0oACCoASMFmgY7p7ehCTkVOle4jUMdRLYTqCc8LEZzCZmoNJODPHFZZXVtZYYkAAeRJTInDQS8po+rf40gnjbDKv8LqD2jpbYoACqAEoAMsK7sUmxkGSCc+VVQQuaTwVb1UBrDYULY7PagbgUZLJH6QbYmJAECjuMigZEMVDsJzCFLNXxtajBVAtUDECjMTgMaAAHhwAD5QABeUAACgAlJz2TgANyKKlEbyYLjxFnsrl8gXeEWKZJcWCoCjwLyIPAAMVVMu5OkZ7Eg+RpdIZzLZoAAPhKpTL+QBvRQlEpOAlkLxG6AmkUAX2C2r15m58o57IAjLygA), `function myFunc<T>(value: Signal<T> | Thunk<T>)` seems to be displayed as desired.

> I'd also recommend any PRs be made against `next` since I'm trying to finalize Docs/APIs there for 1.0 release and this seems like the perfect candidate for this sort of thing.

Sounds good.

**Comment by rturnq** [comment]
I agree that if the type is exposed publicly the type should also be exported - the public API surface should be available to users. That being said, many of the types listed I would consider internal types which are getting exposed due to exported methods which expose the underlying workings.

For example:

```ts
function resumeEffects(e: Computation<any>[]): void;
```
and
```ts
function getListener(): Computation<any> | null;
```
both expose `Computation` which in turn ends up exposing `Owner`, `Signal` and `SuspenseContextType`. This would obviously be an issue if you wanted to create an explicit `Signal` type like
```ts
type Signal<T> = () => T
```
since the underlying one already exists and should really be exported since it is accessible
```ts
interface Signal<T> {
  value?: T;
  observers: Computation<any>[] | null;
  observerSlots: number[] | null;
  pending: T | {};
  tValue?: T;
  comparator?: (prev: T, next: T) => boolean;
  name?: string;
}
```
These functions are exported for a reason and necessary for certain advanced use cases like creating dev tools for Solid. I think this requires us to answer the question how do we separate the common public interface from the more advanced and internal interface while balancing strict encapsulation with ease off access? I think it is important people understand they should not rely on some of these functions and types.

`PropsWithChildren` and `MatchProps` are clearly part of the common API and should be exported. The others listed (I know there are more) should probably be evaluated. As for the duplicate definitions, I would probably pull them out into a types file if they don't have a single home.

**Comment by trusktr** [comment]
This is still not fixed, f.e. with latest Solid:

```
7:15:10 PM [vite] Error when evaluating SSR module /src/elements/Scroller.ts: failed to import "solid-js/html"
|- file:///Users/trusktr/src/showcase/node_modules/solid-js/html/dist/html.js:1
import { effect, style, insert, untrack, spread, createComponent, delegateEvents, classList, mergeProps, dynamicProperty, setAttribute, setAttributeNS, addEventListener, Aliases, getPropAlias, Properties, ChildProperties, DelegatedEvents, SVGElements, SVGNamespace } from 'solid-js/web';
                                                                                                                                                                          ^^^^^^^
SyntaxError: The requested module 'solid-js/web' does not provide an export named 'Aliases'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:131:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:213:5)
    at async ModuleLoader.import (node:internal/modules/esm/loader:308:24)
    at async nodeImport (file:///Users/trusktr/src/showcase/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:52954:15)
    at async ssrImport (file:///Users/trusktr/src/showcase/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:52812:16)
    at async eval (/Users/trusktr/src/showcase/src/elements/Scroller.ts:4:31)
    at async instantiateModule (file:///Users/trusktr/src/showcase/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:52870:5)
```

`Aliases` is defined as something that is exported from `solid-js/web`, for example:

https://playground.solidjs.com/anonymous/414e76e7-dc7e-4736-9d43-7f26fbb365bc
