### ISSUE TITLE
Hyperscript Todos example does not render if fragment is changed to `h` element

### ISSUE THREAD

**Issue by dgllghr** [solidjs/solid#458]
**IMPORTANT: If you have a question or an idea for a new feature use Github Discussions instead**

**Describe the bug**

The [Hyperscript Todos example](https://codesandbox.io/s/0vmjlmq94v?file=/index.js) does not render when the root fragment is changed to an element

**To Reproduce**
Provide a code snippet and steps to reproduce the behavior:
1. Go to the [Hyperscript Todos example](https://codesandbox.io/s/0vmjlmq94v?file=/index.js)
2. Change line 18 to wrap in a div element: `h("div",` (and change line 82 from `];` to `);` )
3. The example no longer renders

**Expected behavior**
The example still renders and is functional

**Reproduction**
Make changes described to https://codesandbox.io/s/0vmjlmq94v?file=/index.js

**Additional context**
Thank you for Solid! Please let me know if I am just misunderstanding the API or not using it correctly

**Comment by ryansolid** [comment]
Yep it's a bug. A stupid bug that never should have made it this far. Basically the arguments for an internal function got reversed a while back and it didn't get caught. Simple fix but unfortunate that no one noticed this until now.

**Comment by dgllghr** [comment]
Thanks for the quick fix!
