### ISSUE TITLE
image element inside svg "Template html does not match input"

### ISSUE THREAD

**Issue by clinuxrulz** [solidjs/solid#474]
This is impossible to do:
```
const SomeUI = (props) => {
    return (
        <>
            <svg style="display: flex; flex-grow: 1; background: white;">
                <image src="some.svg"/>
            </svg>
        </>
    );
};
```

The error:
```
Template html does not match input:
<svg style="display: flex; flex-grow: 1; background: white;"><image src="some.svg"></image></svg>
<svg style="display: flex; flex-grow: 1; background: white;"><image src="some.svg"></svg>
```

**Expected behavior**
The generated html would have the closing tag for the "image" element when inside the "svg" element so it matches what the web-browser changes the html to when it goes in.

**Additional context**
Tested on Google Chrome Version 90.0.4430.212.

If the closing tag of the image element inside the jsx/tsx file is left out, then the code will not compile. jsx/tsx always expect closing tags, but how it is rendered would depend on the tag itself.

The reason for wanting to embed an external svg in an svg element is to give the end-user pan/zoom controls on the view of the svg.

**Comment by ryansolid** [comment]
Aha. `<img>` is a void element, `<image>` is not. I was just looking and the void element list I'm using is ancient full of elements that haven't existed in HTML for almost a decade and I had `image` on the list too. This looks like it is from my earliest prototypes 5 years ago. In any case, I've cleaned this up and will get it out in the next release.
