### ISSUE TITLE
SolidStart - The new Solid Starter

### ISSUE THREAD

**Issue by ryansolid** [solidjs/solid#477]
This issue is a placeholder for the work being done over at https://github.com/solidjs/solid-start for Github projects.

The idea is this will be a Vite-powered opinionated Isomorphic Starter that incorporates all Solid's best practices.

Key Features:
* Support all Solid's Async SSR modes including streaming
* Static Site Generation
* Adapters for deploy to common Cloud Providers (Cloudflare, Vercel, Netlify, Begin)
* File-based Nested Routing with Parallel data fetching
* Cache based query system with Data/Server Components
* Universal Action Functions for mutation

**Comment by ilyaryabchinski** [comment]
What options are going to be prompted from the user to choose? (e.g. ts/js, ssg/ssr/csr, deploy adapters)

**Comment by ryansolid** [comment]
Yeah I have TS/JS. I haven't bootstrapped adapters yet so it's manual but that seems reasonable.

The SSG/SSR/CSR question I haven't quite figured out what makes the most sense here. I'm gathering it probably makes sense as an upfront question but SSG is always a little messier than the other 2. CSR vs SSR is just a switch of the same app. SSG always has the routes that can be determined statically and those that cannot, and even in SSR or CSR you might want some SSG. Right now the pure one is an adapter but that might not be quite right. 

Right now those are the core decisions I believe. I have also think we will be doing SPA/MPA. The way I'm designing the program entry and routing I believe should work for both. Just right now there isn't much incentive to do MPA architecture with Solid. But this seems that once there is(things like partial hydration) this should all be the same. That way the end user basically decides client vs server-side routing but develop their apps the same way.

**Comment by ryansolid** [comment]
SolidStart is Beta now. No need to track this here. Discussions should happen over at: https://github.com/solidjs/solid-start
