### ISSUE TITLE
HTML Streaming

### ISSUE THREAD

**Issue by ryansolid** [solidjs/solid#478]
Solid's streaming solution right now only streams data. This has the majority of the benefits of a full HTML streaming solution except the need to wait for JavaScript for the async content to load in. Technically TTI is the same but on slower networks the visual difference can be anywhere from couple hundred milliseconds to a second.

This is also key technology if we want to consider Partial Hydration seriously outside of SSG. Otherwise waiting for the server to render can be really painful for First Paint. Only through this method can we send Async HTML and not ship the JavaScript to Hydrate it. So I consider this a precursor to any Partial Hydration effort.

**Comment by aalpgiray** [comment]
How/Where to start ?

**Comment by ryansolid** [comment]
This has been added to the upcoming Solid 1.3 release and merged in main.
