### ISSUE TITLE
Question: the "ref" attributes

### ISSUE THREAD

**Issue by clinuxrulz** [solidjs/solid#488]
Just a quick question was the "ref" attribute found in version 0.23 replaced with something else in the newer version? Or just removed?

I get the following when upgrading and using "ref":
```[!] Error: 'currentContext' is not exported by node_modules/solid-js/web/dist/web.js```

I can learn to manage without it if it was removed, so no biggy.

**Comment by ryansolid** [comment]
Looks like a mismatch between solid version and babel preset solid version. Refs are definitely still there.

**Comment by clinuxrulz** [comment]
Thanks, thats all I needed to know.
