### ISSUE TITLE
Add to docs request for createState

### ISSUE THREAD

**Issue by clinuxrulz** [solidjs/solid#489]
Hi again, this library is amazing!

Just a trap that caught me off guard that might be worth mentioning in the createState doc.

Do not use TypeScript class objects in createState as their reactivity will not be tracked. Even if it is a plain data object TypeScript class.

I switched from a TypeScript class instance to a JavaScript object ```{a: 1, ...}``` and everything worked fine again. (I actually had the TypeScript class instance embedded deep in the plain JavaScript object)

Its alright if this note is not added to the docs. It just took me a couple of days to work that out, and might save some pain for someone else.

**Comment by ryansolid** [comment]
Thanks it was in the old docs. I probably missed it during the rewrite.

**Comment by ryansolid** [comment]
I've added to the API docs now. Thank you for bringing this to my attention. (I have been moving a lot of stuff around).
