### ISSUE TITLE
solid-js/store is missing?

### ISSUE THREAD

**Issue by erganmedia** [solidjs/solid#502]
Hi.

In the API documentation it sayst that createStore is available at solid-js/store. But I couldn't find a package named "solid-js/store". Am I missing something, or did you guys move createStore somewhere else?

thank you in advance

**Comment by ryansolid** [comment]
Sorry this is an example of things getting ahead of ourselves. The docs reflect the latest 1.0 release candidate as I mention. If you are using the current published version of Solid look here: https://github.com/solidjs/solid/tree/0.x/#documentation

`createStore` used to be called `createState`

1.0 is coming really soon.

**Comment by erganmedia** [comment]
thank you for the fast response. I may should consider using the 1.0 release candidate then :)
