### ISSUE TITLE
use solid-scripts with solid-js 1.0.0-rc.9

### ISSUE THREAD

**Issue by erganmedia** [solidjs/solid#503]
Hi,

I created my solidjs project using the create-solid script
`> npm init solid app-ts my-app`

I would like to use the 1.0 release candidate, so I just updated the version of solid-js in package.json. My package.json looks like this:
```
{
  "name": "project-name",
  "version": "0.1.0",
  "private": true,
  "devDependencies": {
    "@types/jest": "26.0.23",
    "@types/node": "15.12.4",
    "prettier": "^2.3.1",
    "solid-js": "^1.0.0-rc.9",
    "solid-scripts": "^0.0.56",
    "typescript": "4.3.4"
  },
  "dependencies": {},
  "scripts": {
    "start": "solid-scripts start",
    "build": "solid-scripts build",
    "test": "solid-scripts test"
  },
  "browserslist": [
    "Chrome 74",
    "Firefox 63",
    "Safari 11",
    "Edge 17",
    "Node 10"
  ]
}
```

after some time I realized, that npm start doesn't work properly and I get following error when I try to start my project.

```
Failed to compile.

./node_modules/solid-js/store/dist/store.js
Module not found: Can't resolve 'solid-js' in '/Users/oe/projects/private/em-builder-v2/node_modules/solid-js/store/dist'

```

I am not sure if that is a bug in the create-solid project, or if changing the version in the package.json is not the proper way of trying to update to 1.0

`npm run build` works though

**Comment by ryansolid** [comment]
For sure.. I will be updating this shortly. The long term plan is to slowly move away from this project which so it hasn't been the top of my list but I will be sure to get a version working with 1.0 in the next day or so.

**Comment by erganmedia** [comment]
Thank you. I love solid js so far, and I appreciate the work you are putting into it. keep going. I'll do my best to contribute wherever I can :)

**Comment by ryansolid** [comment]
Ok Fixed.. use solid-scripts `0.0.57-rc.0` with Solid 1.0 rc candidates
