### ISSUE TITLE
Export a type for createSignal's setter

### ISSUE THREAD

**Issue by otonashixav** [solidjs/solid#507]
**IMPORTANT: If you have a question or an idea for a new feature use Github Discussions instead**

**Describe the bug**
The type of createSignal's setter is not exported anywhere. This was recently made more problematic due to [https://github.com/solidjs/solid/commit/2f5311dc90f25b8a68de536d7a095112235d385b](https://github.com/solidjs/solid/commit/2f5311dc90f25b8a68de536d7a095112235d385b) which changed the setter's type from a simple setter to one that also accepted a function form, making writing types, for example when passing a setter as a prop, more tedious. 

**To Reproduce**
N/A

**Expected behavior**
Export a setter equivalent of `Accessor<T>`.

**Reproduction**
N/A

**Additional context**
N/A

**Comment by ryansolid** [comment]
Trying to get this work reminds me why I am no good at TypeScript. I'm very much open to PRs.

**Comment by atk** [comment]
https://github.com/solidjs/solid/pull/575
