### ISSUE TITLE
Multiple logical conditions fail to compile.

### ISSUE THREAD

**Issue by minht11** [solidjs/solid#509]
**Describe the bug**
Multiple inline logical conditions fail to compile.
```tsx
<Show when={props.first || props.second || props.third}>
  Render
</Show>
```
**To Reproduce**
Provide a code snippet and steps to reproduce the behavior:
1. Go to https://playground.solidjs.com/?hash=-1206259292&version=1.0.0
2. See error

**Expected behavior**
No error.

**Comment by ryansolid** [comment]
Confirmed. It appears the nested traversal goes too far and ends up with a null. Thanks for reporting.

**Comment by ryansolid** [comment]
Ok I've updated the underlying package babel plugin package `babel-plugin-jsx-dom-expressions` to 0.29.1. This contains the fix and should install from a clean lock I imagine with the latest `babel-preset-solid`. I will release a update preset when I make the next Solid patch release but you should be able to use it now.

**Comment by Salemsa89** [comment]
Multiple logical conditions fail to compile.

**Comment by Salemsa89** [comment]
Ok I've updated the underlying package babel plugin package babel-plugin-jsx-dom-expressions to 0.29.1. This contains the fix and should install from a clean lock I imagine with the latest babel-preset-solid. I will release a update preset when I make the next Solid patch release but you should be able to use it now.
