### ISSUE TITLE
createEffect seems to execute before node are actually inserted into the DOM in Storybook

### ISSUE THREAD

**Issue by grenierdev** [solidjs/solid#553]
**Describe the bug**
`createEffect` seems to execute before nodes are actually inserted into the DOM. **This happens only in Storybook.**

**To Reproduce**
Minimal repo to reproduce the behaviour https://github.com/grenierdev/solidjs-storybook-bug

**Expected behaviour**
When executing similar code through the [playground](https://playground.solidjs.com/?hash=1192562140&version=1.0.0), nodes referenced in the `createEffect` are in the DOM (`document.body.contains(node) === true`). When ran in Storybook, `document.body.contains(node)` returns `false`.

**Reproduction**
https://github.com/grenierdev/solidjs-storybook-bug

**Additional context**
I found an old [pull request](https://github.com/solidjs/solid/pull/81/files) that described the configuration to make Solidjs works inside Storybook.

**Comment by grenierdev** [comment]
As described in the repo's [README](https://github.com/grenierdev/solidjs-storybook-bug#readme), if I wrap the `console.log` inside a `setTimeout(..., 0)`, the nodes are now part of the DOM.

**Comment by ryansolid** [comment]
I see why this happening. Im not sure if there are better suggestions in #430. But basically effects are scheduled synchronously at the end of any render. However the storybook setup seems to use `createRoot` to render which has no guarantees the nodes are ever attached. I assume they are but only after Solid's full render cycle occurs.

**Comment by grenierdev** [comment]
@ryansolid Thanks for the quick response. I'll close this issue for now and follow along on #430. Might even dig in to create a plugin for Storybook as I'm a big advocate for _Test Driven Development_ and loves Storybook and Solidjs.
