### ISSUE TITLE
Context.Provider typescript error: error TS2741: Property 'children' is missing in type ... but required in type '{ value: unknown; children: any; }'

### ISSUE THREAD

**Issue by btakita** [solidjs/solid#559]
If the https://github.com/solidjs/solid/blob/main/packages/solid-ssr/examples/shared/src/router.js example were applied to a tsx file, `error TS2741: Property 'children' is missing in type` occurs.

In router.tsx:
```tsx
      <RouterContext.Provider
        value={[location, pending, { setLocation: v=>start(()=>setLocation(v)), matches }]}
      >
        <Comp/>
      </RouterContext.Provider>

```

**Comment by ryansolid** [comment]
Hah weird. TypeScript confuses me. Doesn't it understand semantically it has children?

I will leave this to greater minds.

**Comment by btakita** [comment]
I wouldn't say my mind is greater, but I do have a fix.

https://github.com/solidjs/solid/pull/560

**Comment by ryansolid** [comment]
I'm going to put this out in the discord and hopefully get some more discussion and solutions. I'd love if we could keep children mandatory here or to even understand better what is going on. From the linked issue while people suggested those solutions it looks like the OP, who much like myself wanted it to be required, did not go with them.

**Comment by btakita** [comment]
Sounds good. Looking forward to the discussion & the solution.

**Comment by rturnq** [comment]
@btakita, Can you check to see if your are telling TypeScript to use Solid's JSX types? You should have `"jsxImportSource": "solid-js"` in your tsconfig.json (https://www.typescriptlang.org/tsconfig#jsxImportSource). I was unable to reproduce the error using the code you pasted above unless I omitted that setting.

**Comment by btakita** [comment]
Adding `"jsxImportSource": "solid-js"` fixes the issue. Thank you!
