### ISSUE TITLE
How to bind custom method or property with component's ref?

### ISSUE THREAD

**Issue by Sioxas** [solidjs/solid#563]
I want to customize the ref of the component. 
In React we can use `useImperativeHandle` to customizes the instance value that is exposed to parent components.
How to achieve the same feature in Solid?

**Comment by ryansolid** [comment]
Oh sure. We don't have a hook for it. All you need to do is call props.ref as a function. The only caveat is it may not exist, which could be hidden behind a hook of sorts I suppose but you can also just check that it exists.

Converting the example from the linked docs I think it's just this?
```js
function FancyInput(props, ref) {
  const inputRef = (el) => {
    props.ref?.({
      focus() { el.focus(); }
    })
  }
  return <input ref={inputRef} ... />;
}
```
