### ISSUE TITLE
npm run test not pass

### ISSUE THREAD

**Issue by athlan20** [solidjs/solid#565]
when i run the command: npm run test, got a lot of error like this:
![image](https://user-images.githubusercontent.com/2987056/125911220-65964bfa-df7f-463a-8c25-af3a68a14cd2.png)
how should i fix this,or maybe some problem in my config?

**Comment by ryansolid** [comment]
I've never seen this one. But worth mentioning you should run `npm run build` before `npm test` since it generates some things. See if that helps.

It's almost like it doesn't recognize TypeScript.

**Comment by athlan20** [comment]
Ok.....the error deps which node version you use...
node v12.16.1 will meet these errors,but when I use node v14.15.1 that's ok.
