### ISSUE TITLE
QoL `children` helper should be generic over it's accessor

### ISSUE THREAD

**Issue by grenierdev** [solidjs/solid#570]
I'm encountering an issue with the `children` helper.

https://github.com/solidjs/solid/blob/c4b31d8cae5f7c5fc46c2eea411bec1959b0a247/packages/solid/src/reactive/signal.ts#L658

It returns `Accessor<unknown>`, which is not a valid `JSX.Element`. Is it possible to change the signature to be generic over the accessor's type?

```ts
export declare function children<T>(fn: Accessor<T>): Accessor<T>;
```

**Comment by otonashixav** [comment]
I think it shouldn't be possible unless we know the resolved type of the input function, which could be anything; there's no guarantee that passing in a `JSX.Element` will give you a type that passes as a `JSX.Element`:
https://playground.solidjs.com/?hash=905545203&version=1.0.0

**Comment by ryansolid** [comment]
I was thinking that but I think I'm ok casting in those cases. JSX.Element handles all usual things. Except returning non-thunk functions and objects. And you have to cast in those cases already anyway if you use them as children. But yes the input doesn't equal the output so a generic isn't right. I tried 2 generics but it just led to manual casting more or less anyway. So I will just make this all `Accessor<JSX.Element>`.

**Comment by giubatt** [comment]
> I was thinking that but I think I'm ok casting in those cases. JSX.Element handles all usual things. Except returning non-thunk functions and objects. And you have to cast in those cases already anyway if you use them as children. But yes the input doesn't equal the output so a generic isn't right. I tried 2 generics but it just led to manual casting more or less anyway. So I will just make this all `Accessor<JSX.Element>`.

It seems like this change broke the children tutorial example: https://www.solidjs.com/tutorial/props_children?solved

**Comment by ryansolid** [comment]
I see thanks. Yeah since it is always the array version of it. I guess it should be an array of JSX.Element
