### ISSUE TITLE
Newline in a static string causes elements to appear out of order

### ISSUE THREAD

**Issue by whatisaphone** [solidjs/solid#571]
**Describe the bug**

Newline in a static string causes elements to appear out of order

**To Reproduce**

```js
import { createSignal } from "solid-js";
import { render } from "solid-js/web";

function App() {
  const [first] = createSignal('first');

  return (
    <pre>
      {first}
      {'\n'}
      {'second'}
    </pre>
  );
}

render(() => <App />, document.getElementById("app"));
```

This outputs "secondfirst".

**Expected behavior**

I expect the browser to normalize the newline to a space, and see "first second".

**Reproduction**

https://playground.solidjs.com/?hash=1226199451&version=1.0.0

**Comment by atk** [comment]
The issue is actually in the trimWhitespace-function of babel-plugin-jsx-dom-expressions; I already created a PR to fix it.
