### ISSUE TITLE
Variable components (experiments)

### ISSUE THREAD

**Issue by aleksanderd** [solidjs/solid#579]
Hi!

It is not a critical issue at all - just experiments about creating UI components with unified interface, so the realization can be replaced w/o changing client code.

I created a context with example components, like this:
```jsx
export interface UIContextValue<C extends Components = Components> {
  components: C;
  setComponents: SetStoreFunction<C>;
}

...

export const UIProvider: Component<UIProviderProps> = (props) => {
  const [components, setComponents] = createStore<Components>(
    props.components ?? defaultComponents,
  );
  const value = createMemo<UIContextValue>(() => ({ components, setComponents }));
  return <UiContext.Provider value={value()}>{props.children}</UiContext.Provider>;
};

```
then use it like this:
```jsx
  const { setComponents, components } = useContext(UiContext);
  return  <components.Button>click me!</components.Button>;
```

But when I try to change components at runtime with setComponents, some strange things happens...
Firstly, the button not updated to new component. It works only if use this:
```js
      {() => {
        return components.Button({ children: 'click me!' });
      }}
```
but even in this case the updates happens only on first change - changing back to first/initial components not changing anything... even an createEffect on the component.Button triggering only on init and on first change...

Is it possible at all to todo such hacks with solid?

Thank you!

**Comment by ryansolid** [comment]
Are you trying to remake the `<Dynamic>` component https://www.solidjs.com/docs/latest/api#%3Cdynamic%3E

2 things. Since we run once you can't use the component syntax and have it update. It's expecting a function it calls once and isn't wired to ever re-run. You need to wrap the call like you are doing at the end. But you probably also want to call it like a Component so the internals aren't tracking top level.

The other is that the value passed to a Context provider is inert. Otherwise we'd need to always have a signal wrapper the consuming side. Since the intention is to have what you pass in is what you get out.. don't call the `value()` memo just pass it through and then the consumer can call it where it uses it. Right now it is only resolving it once and no updates would be tracked.

**Comment by aleksanderd** [comment]
Thank you!

> trying to remake the <Dynamic>   

not sure) I need not defer loading of a component or so. I trying to create a mechanism to substitute some components(consider interfaces of cos) if I need later w/o changing consumer code. 
In other words, I wish write consumer code using one UI interface and change look-n-feel by substitute the ui-lib. 
It is ok to do it at build time(not runtime).

May be you have an idea about better way to do it in solidjs?

**Comment by ryansolid** [comment]
At build time (ie.. not changeable at runtime) you could just alias the imports. At runtime though you'd need to use Dynamic.

**Comment by aleksanderd** [comment]
> just alias the imports

I as know, it is app-level abstraction, what about different packages/libs using one interface + app using these packages with ability to change ui-lib at _app_ build time... the packages are prebuilded...

I still able to use context, but read only for now, without any setters provided... 
No store at all - just pass components from props to the context value.
So packages can use components from contexts(instead of direct/aliased import) and able to substitute them at app level.
Some kind of static context) 

What you think about it? Is it not too bad idea?)

**Comment by ryansolid** [comment]
If that works for you. If it is static you should be able to use it the way you describe. The function provided as the component constructor should run a single time on each creation and that should work. Changing after the fact would require using `<Dynamic>`.

**Comment by ryansolid** [comment]
Are we good? Are there any further realizations or any other questions?

**Comment by aleksanderd** [comment]
currently I playing with 'static context' variant... other variant is to use some Dependency Injection lib... I not sure what better... 

anyway, there is not any needs from solidjs side I think, or I have not any idea... may be an ability to re-run this "the single run" if it possible and not too complicated...

**Comment by ryansolid** [comment]
Ok makes sense. Yeah a Force update type thing to like re-run everything isn't really easy to do. You'd basically need to just wrap everything from the root of the change and toggle it. I think I will just consider this answered.
