### ISSUE TITLE
Error within ErrorBoundary fallback causes endless loop.

### ISSUE THREAD

**Issue by andrewgreenh** [solidjs/solid#585]
Hello everyone :)

Have been playing around with solid a lot lately and encountered a "weird" behavior. I'm not sure if it is according to spec or a bug:

**Describe the bug**
When the fallback render function throws an error, the playground gets stuck. My guess is, that an error in an error boundaries fallback ends up in that very same error boundary and not its parent ErrorBoundary, causing some sort of endless loop.

**To Reproduce**
```tsx
import { render } from "solid-js/web";
import { ErrorBoundary, For } from "solid-js";

function App() {
  return (
    <>
      <h1>Welcome</h1>
      <ErrorBoundary fallback={<span>Outer error</span>}>
        <ErrorBoundary
          fallback={(err, reset) => {
            // Change this to err2 to cause an error
            console.log(err);
            return <button onClick={reset}>Retry</button>;
          }}
        >
          {(() => {
            throw new Error("BOOM");
          })()}
        </ErrorBoundary>
      </ErrorBoundary>
    </>
  );
}

render(() => <App />, document.getElementById("app"));
```

Reproduction in [playground](https://playground.solidjs.com/?version=1.0.0#NobwRAdghgtgpmAXGGUCWEwBowBcCeADgsrgM4Ae2YZA9gK4BOAxiWGjIbY7gAQi9GcCABM4jXgF9eAM0a0YvADo1aAGzQiAtACsyAegDucAEYqA3EogcuPfrwCijeYwBCDUVEb4svAGLcUrLyiip0Gtp6FlZWMvQQzLhotBC8AIKEhAAUAJT8VryCcLhMqVkFhbwAPAB8FZXVABYAjDUA6nBqzApwVfotdakN1U4u7vEiXviyUGpqJlDMANYAvCBVZIRQEDUA8vS44rziLn2b2zWSg8OVVaPc457e9TczcwvLa1knvkJkxXkVjV8kNXpV9PpeABhRrbADmcF4uFox2cACYXmDuhBwnAAHRqWhw77OHKWUFgoolRipKomA7I1IpKEaT4gP7FK4AJWK3j69NwjJq5MpUkkmMq10pICyuV4QJBosKuEa8kMvAgcHV90Y5TArl2uwAsioyRKGpIcrlxRSGn0dY9Jt4pXb9A6PE78C7qvopWaIDarEJROJZYDgVUMoReL7fCJaMx6PAILg8QjcA41HBk7hXPgAJIiPVQTKmslgSQAXSAA):
1. Open the playground
2. Change the err variable in the inner ErrorBoundary to err2
3. Page gets stuck.

**Expected behavior**
Intuitively, I guessed that the outer error boundary would catch the error and act as another fallback layer.

**Comment by ryansolid** [comment]
Yeah that is probably right assumption. Hadn't hit this case yet but sounds like we need to change the behavior a bit to get this working right.

**Comment by andrewgreenh** [comment]
Wow, that was quick...
Thanks a lot :)
