### ISSUE TITLE
Typescript error with Windicss attributify

### ISSUE THREAD

**Issue by HriBB** [solidjs/solid#586]
I am trying out solid + solid-start + typescript + WindiCSS [attributify mode](https://windicss.org/posts/attributify.html), all latest versions.

Attributify mode lets you define tailwind classes as html attributes
```tsx
const HeaderMenuButton = (props: Props) => {
  return (
    <div flex="~" align="items-center" lg:display="hidden" p="r-4">
      <button
        p="1"
        flex="~ items-center"
        hover:text="gray-900"
        focus:outline="none"
        focus:shadow="outline"
        transform="~"
        transition="scale duration-300 ease-in-out"
        hover="scale-105"
        text={props.raised() ? 'gray-800' : 'white'}
        onClick={props.onClick}
      >
        <Icon class="fill-current h-6 w-6" />
      </button>
    </div>
  )
}
```

There is a "conflict" between Solid's `JSX.HTMLAttributes.align` and WindiCSS [align](https://windicss.org/posts/attributify.html#align) attribute (and possible others).

![solid-windicss](https://user-images.githubusercontent.com/4412324/127580264-9e1cce74-943b-47ae-90a9-1cd5535c2100.png)

Is there a way to override solid typescript definitions for JSX? Or any other way to tell typescript to allow a simple `string`.

![solid-windicss2](https://user-images.githubusercontent.com/4412324/127580292-73eaa121-7cb1-438d-9ae1-92d28ae0139d.png)

I guess I can avoid this problem by using a `prefix` for windicss attributes, but that's kinda ugly. There's gotta be a better way!

**Comment by ryansolid** [comment]
On the positive it looks like `align` has been deprecated a long time ago. It is supported in Microsoft Edge though but nothing else.

I wasn't able to find it in types of other JSX libraries so I can likely just remove it. I don't know what other conflicts there would be. Although I imagine other libraries would hit the exact same problem if Windi chose to use other existing DOM attributes.
