### ISSUE TITLE
Error trying to use Typescript compilator for generating types.

### ISSUE THREAD

**Issue by xstevenyung** [solidjs/solid#587]
**IMPORTANT: If you have a question or an idea for a new feature use Github Discussions instead**

**Describe the bug**
While working on a Solid library using Typescript and Vite lib mode, I was trying to generate the `.d.ts` files to include the type definition, but I realize that `<For />` will always throw an error while compiling types, I'm probably doing something wrong.

Edit: It seems to work when using `children` directly as a prop. But it also seems to affect all component  (similar issue w/ `<Show/>`)

<details>
<summary>Stacktrace</summary>

src/App.tsx:9:8 - error TS2741: Property 'children' is missing in type '{ each: number[]; }' but required in type '{ each: readonly number[]; fallback?: Element; children: (item: number, index: Accessor<number>) => Element; }'.

9       <For each={numbers()}>
         ~~~

  node_modules/.pnpm/solid-js@1.0.2/node_modules/solid-js/types/render/flow.d.ts:6:5
    6     children: (item: T, index: Accessor<number>) => U;
          ~~~~~~~~
    'children' is declared here.

Found 1 error.

 ERROR  Command failed with exit code 2.

</details>

**To Reproduce**
I made a quick repo to represent the issue:

1. clone https://github.com/xstevenyung/solid-type-generation-issue
2. Run installation with PNPM, NPM or Yarn
3. Run type generation script `pnpm build:types`

**Expected behavior**
It should generate types without any issue 

**Reproduction**
Reproduction repo: https://github.com/xstevenyung/solid-type-generation-issue

**Additional context**

**Comment by mattjennings** [comment]
Out of curiosity I did some poking around on this and it seems to happen when `jsxImportSource` is not set to `solid-js` in tsconfig. So for your build script, if you add `--jsxImportSource solid-js` it should work.

**Comment by ryansolid** [comment]
Yeah that worked for me. @mattjennings thanks for the help.

**Comment by xstevenyung** [comment]
Yeap, that solve my issue. Thanks a lot @mattjennings !
