### ISSUE TITLE
{ ...rest } spread in <Dynamic/> results in props being undefined in v1.1.0

### ISSUE THREAD

**Issue by areknawo** [solidjs/solid#597]
**Describe the bug**
When using props spread with `<Dynamic/>`, the spread props are `undefined` in used component.
The bug happens in v1.x.x, but not in v0.x.x.
Check out the demo here:
https://playground.solidjs.com/?hash=-1806763644&version=1.1.0

**To Reproduce**
[Link to playground](https://playground.solidjs.com/?hash=-1806763644&version=1.1.0)
**Expected behavior**
Spreading props in `<Dynamic/>` should simply pass them to the used component.

**Reproduction**
https://playground.solidjs.com/?hash=-1806763644&version=1.1.0

**Comment by ryansolid** [comment]
Yeah it's a compilation error. I'm pretty sure I broke this super recently. Like with the 1.1.0 release can't test older version of the playground as it will bring in the latest compiler. I will look at it.

**Comment by areknawo** [comment]
Thanks! Though it seems like when selecting the latest v0.x.x in the playground something does change, as the props are properly spread.

**Comment by ryansolid** [comment]
Yeah it was a fix where I was merging things unnecessarily but in the process broke all trailing spreads. I've fixed the issue with the latest babel plugin 0.29.14 so a fresh install with the locks removed should do it but it might be a few days before this fix makes it to the playground.

**Comment by areknawo** [comment]
Good to hear that r.e. playground. To be precise, the bug also happened in my local Vite project (_vite-plugin-solid_ 2.0.1, _solid-js_ 1.1.0) initialized from the _templates_ repo, so this will also need an update.

**Comment by ryansolid** [comment]
Your own projects will update if you do what I said above. And any new installs shouldn't hit it. It's just the playground that will need a manual update. The fix is in a semver compatible range.
