### ISSUE TITLE
Cannot import <Portal> from 'solid-js'

### ISSUE THREAD

**Issue by pheianox** [solidjs/solid#602]
**Describe the bug**
When I import `<Portal>` it throws a massive error.

**Error**
> Uncaught SyntaxError: The requested module '/node_modules/.vite/solid-js.js?v=e574e228' does not provide an export named 'Portal'

**Component**
```jsx
import styles from "./index.module.scss";
import { Portal } from "solid-js";

export const Modal = props => {
    return (
        <Portal mount={document.getElementById("face")}>
            <div class={styles.self}>Modal</div>
        </Portal>
    );
};
```

**Expected behavior**
No error in the console and fully loaded page

**Additional context**
Building a modal using portals described here https://www.solidjs.com/docs/latest/api#%3Cportal%3E)

**Comment by ryansolid** [comment]
Portal is only in `solid-js/web`. It's DOM specific in implementation. Might consider how to generalize in the future but for the time being it is only available there.
