### ISSUE TITLE
Custom event names with periods in them

### ISSUE THREAD

**Issue by clinuxrulz** [solidjs/solid#606]
I can see that we have ```on:MyCustomEvent``` which is really nice. However some frameworks like bootstrap use event names with periods in them E.g. ```hidden.bs.modal``` and when you try ```on:hidden.bs.modal``` then the JSX/TSX compiler doesn't like it.

Its actually not a big deal, we can just make use of ```onMount``` / ```onCleanup``` to do it, just thought I'd bring it to your attension.

**Comment by ryansolid** [comment]
I see I wasn't aware of frameworks using periods. But yeah that's invalid JSX. So wouldn't work in React or any JSX library. I guess that's beyond what we can do something about. As you said manual registration will work.

**Comment by clinuxrulz** [comment]
Manual registration did not work for me either. Must not be a standard event listener.
```addEventListener("hidden.bs.modal", handleColumnNameDialogHidden);``` <-- failed

The bootstrap website wants me to do it like this using JQuery:
```
$('#myModal').on('hidden.bs.modal', function (e) {
  // do something...
})
```
So I'd probably not expect it to work by default in any JSX libraries anyway.
