### ISSUE TITLE
Declare web component in solid typescript

### ISSUE THREAD

**Issue by nemixe** [solidjs/solid#616]
have been tried implement web component in solid typescript but i dont really know how to declare the component name, it show an error like this.

<img width="829" alt="CleanShot 2021-08-23 at 08 36 54@2x" src="https://user-images.githubusercontent.com/33045816/130378531-f65dc3e7-70a7-4fbc-9b5c-b997b09c079c.png">

i have tried to declare it on file declaration.d.ts like this.

<img width="613" alt="CleanShot 2021-08-23 at 08 37 56@2x" src="https://user-images.githubusercontent.com/33045816/130378575-baef23a1-8b61-4f0f-8939-84f4a6bb146a.png">

is there any way to declare web component name in solid typescript ?, thanks!.

**Comment by ryansolid** [comment]
I think the problem is that works on the global namespace and it needs to work on Solid's. I've done it the way posted above in the past but that was back when we were too polluting the global namespace like React. 

So perhaps:

```ts
declare module "solid-js" {
  namespace JSX {
    interface IntrinsicElements {
      "component1-component": any
    }
  }
}
```

**Comment by nemixe** [comment]
thanks for your reply. so i've implement it and now it shows different error like this.

<img width="833" alt="CleanShot 2021-08-23 at 11 36 35@2x" src="https://user-images.githubusercontent.com/33045816/130390729-f7351104-2e86-489e-bc9d-403d76c5d4f5.png">

this is my declaration.d.ts file look like.
<img width="358" alt="CleanShot 2021-08-23 at 11 38 49@2x" src="https://user-images.githubusercontent.com/33045816/130390801-8d162478-868e-4305-914c-84bb3f299c2f.png">

**Comment by nemixe** [comment]
but i found out if i declare it on component file like this.

<img width="642" alt="CleanShot 2021-08-23 at 16 09 12@2x" src="https://user-images.githubusercontent.com/33045816/130421455-b22b9039-b677-4a16-818c-ec03426b90ad.png">

this works, but i dont know if this is a good practice or not.

**Comment by ryansolid** [comment]
Honestly, TypeScript differentiating between this confuses me. Anyone with TS experience with custom elements can chime in. @trusktr maybe.

**Comment by rturnq** [comment]
You should be able to perform this module augmentation in a declaration file (.d.ts) which will make it available everywhere in your app. The trick is to also import 'solid-js' in that declaration file. Without the import, the new module declaration clobbers the existing one instead of extending it. Here is an example: https://codesandbox.io/s/solid-counter-forked-ulhhj?file=/my-web-components.d.ts

Please also note codesandbox falls down sometimes dealing with this stuff - reloading usually fixes it.

**Comment by nemixe** [comment]
works perfectly, thanks!.

**Comment by hawkticehurst** [comment]
Chiming in with a potential improvement on the ideas/code snippets in this thread:

There was a [discussion/thread](https://github.com/shoelace-style/shoelace/discussions/770) in a WC library called Shoelace on how to use the components in Solid.

As part of that discussion, @justinfagnani (a member of the Lit team at Google) offered the below declaration file snippet as a way to get even better type annotations on web components used in Solid.

> I figured out how to get good typings for all custom elements that are added to `HTMLElementTagNameMap` without having to add each individually to `'solid-js'.JSX.IntrinsicElements` and without using `any` for the type.
> 
> ```ts
> declare module 'solid-js' {
>   namespace JSX {
>     type ElementProps<T> = {
>       // Add both the element's prefixed properties and the attributes
>       [K in keyof T]: Props<T[K]> & HTMLAttributes<T[K]>;
>     }
>     // Prefixes all properties with `prop:` to match Solid's property setting syntax
>     type Props<T> = {
>       [K in keyof T as `prop:${string & K}`]?: T[K];
>     }
>     interface IntrinsicElements extends ElementProps<HTMLElementTagNameMap> {
>     }
>   }
> }
> ```
> 
> You can see in the Solid playground that an element with `foo: number` causes an error with a binding of `prop:foo={'hello'}`, which is what we want:
> 
> [Solid Playground Link](https://playground.solidjs.com/?version=1.4.1#NobwRAdghgtgpmAXGGUCWEwBowBcCeADgsrgM4Ae2YZA9gK4BOAxiWGjIbY7gAQi9GcCABM4jXgF9eAM0a0YvAOR0ANmhEBaAFZkA9AHc4AIyUBuADoQrM+hGa40tCLwAqcMrgAUASn5XeQThcJhcvAMDeAB4APgjI6Jh8TThVOHgIPkJ5QkQZWloAXhAlAAtU1VolSRiovSSUtIzcOJdIutbAn0sISSsrIVFxL19eQpjo909ePRisXhFaZnpmgDoAc2CAUSbhXAAhfABJES8lKEJCJR8AQh9++1UoMjJeAFl8HfS93jgKXGEIleAAlXG8ADJfZr+NrZNAANygAN4AH18rRELwICtjOIxrwACwAJh6EU2fHRowEQhCjBcuFKaDIqzRBTMUgiZGCsgKXnhmOxMFxjD8IHivAZTJZ6Px8J6CUlzMGYkYvnlHOsbWYzk8jHoDm4VPFZHoxFV3XFitWSNwUGYpQAyqUoIsDF4QDBaGJMUpaMQINULW1AlblcMg4E+prAmHzTCFYzmWRna6AEoFXA3VYYCDiUEQ-EAAyipQAjDFgRVaLwACQgK3oyQl8uF9VRqPLTwKKF7ZliGQYOBnBqpb6ZJTzD49zJBqxiZhPIS8daVYxQVTx3gYAGMGR2uC8fOQ3aZVxQdYAOVgcDeF03gQsKGSo+aj8xU5PuDbVijc7gC6gJdPREeg0mUNQNB0MglE3aB4DIQh914AApB0AA17wlIgD2nXAAAUcjIKJXAmQpMMCPQ9F4ABBEQRF4YxaAZCVyl+T8VF4bI4AHCg4Ho7I-XERwPF4KBRBYg8bUYNBjHoAEyHFQJgAAaS3FwAGs4HwWgZDcABdTECL9IjXBUvSJgAMkPMFwWo3BcGk2T5OIsyYnVSNxUo3gCO4tBeNedcNwEs1hNeAw0GYwtgsQQsJWrVBcHtXgHVodQRA44KhPwXguXsjB1hy-BMigChLWw7zCOI0jyN4FS1N4TTtN01xRNeKKckQOtdXy3grOUyRCz0gB+TFTOUvT3I1BJt3EPdWF4I5MmkiAyDQZhcNeP4AVEV5cKMwgiKPXCz0va9b0ICYxWDKaNSjMBJD0oA)

^([Link to Justin's comment for more context](https://github.com/shoelace-style/shoelace/discussions/770#discussioncomment-2852125))

_It's also worth noting, that this will only work for web component libraries that add their components to the global `HTMLElementTagNameMap` interface as demonstrated in the above Solid playground link, however. This is something that [Shoelace does for its components](https://github.com/shoelace-style/shoelace/blob/next/src/components/button/button.ts#L237-L241), but you'll want to check your desired component library for this addition._

Hope it helps anyone still passing by on this thread!

**Comment by AlexErrant** [comment]
If you extend `'solid-js'.Component` (instead of `HTMLElement` as above), here's some half-working code:

```ts
declare module "solid-js" {
  namespace JSX {
    type ElementProps<T> = {
      [K in keyof T]: T[K] extends Component<infer P> ? P : never
    }

    interface IntrinsicElements extends ElementProps<HTMLElementTagNameMap> {}
  }
}
```

Unfortunately this code does **_not_** error if you pass props to a component that has no props, like `function MyComp(): JSX.Element { ... }`. Unfortunately I'm not good enough at TypeScript to figure out the solution. Some thoughts on where I gave up:

The default generic on Component is `{}`, which I can't differentiate from a populated prop using conditional types. In other words:

```ts
    type ElementProps<T> = {
      [K in keyof T]: T[K] extends Component<infer P>
        ? P extends Record<string, never>
          ? boolean // this is never hit
          : P
        : never // though this is hit, which correctly yields errors if, say, you pass a string to an number prop
    }
```

For now I think I'll just have two `HTMLElementTagNameMap`s - one for Components with props, and one for Components without props. I haven't tried it yet though.

**Comment by nilshelmig** [comment]
@ryansolid Any plans or information to support this in solidjs? Or at least a documentation note, that using web components with typescript requires this?

**Comment by ryansolid** [comment]
There was a documentation note at one point about what I posted above. But, looking now it doesn't seem to have made it to the new Docs. So I think there could be a note about how to declare web components in the TS section.

Opened an issue: https://github.com/solidjs/solid-docs-next/issues/823
