### ISSUE TITLE
No reactivity with electron-forge

### ISSUE THREAD

**Issue by tadeaspetak** [solidjs/solid#622]
I am trying to include `solid` in an `electron-forge` project. The app is rendered without an issue, but I get zero reactivity.

At first, I thought this might be similar to #196, but I don't think there's a problem with `externals` here, or at least I could not find anything of that sort in the transpiled code (at https://github.com/tadeaspetak/electron-forge-solid-issue/blob/master/.webpack/renderer/main_window/index.js).

**To Reproduce**
1. `git clone https://github.com/tadeaspetak/electron-forge-solid-issue.git`
2. `cd electron-forge-solid-issue && npm i`
3. `npm start`
4. You should see a window with the app rendered. Press `ctrl+shift+i` to open the dev tools. You should see a periodic message in the console verifying the interval is running, but the counter never changes.

**Expected behavior**
The counter should be increased by 1 each second.

**Additional context**
I have included all the transpiled code within the repo at https://github.com/tadeaspetak/electron-forge-solid-issue/tree/master/.webpack.

I would **love** to use `solid` in our `electron-forge` project as it would speed it up massively, but this is, obviously, problematic.

**Comment by ryansolid** [comment]
Multiple versions of Solid are getting pulled into the build. Why not sure as not familiar with this setup. But that's the problem. Compiler is creating effects with different Solid instance than the signals being created.

**Comment by tadeaspetak** [comment]
Wonderful! Thanks for the explanation, the following webpack rule loads all typescript and fixes this issue:

```
{
      test: /\.tsx?$/,
      exclude: [/(node_modules|\.webpack)/],
      use: [
        {
          loader: "babel-loader",
          options: {
            presets: ["solid", "@babel/preset-typescript"],
          },
        },
      ],
    },
```

Cheers for digging in!
