### ISSUE TITLE
about understand of solid

### ISSUE THREAD

**Issue by wwmmzz** [solidjs/solid#623]
```html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <button id='btn'></button>

    <script>
        let queue = []

        setInterval(() => {
            if (queue.length) {
                for (let i of queue) {
                    setTimeout(() => {
                        i()
                    }, 0);
                }
                queue = []
            }
        }, 100);

        const createSignal = (value) => {
            let currentValue = value
            const getValue = () => {
                return currentValue
            }
            const setValue = (el, nextValue) => {
                currentValue = nextValue
                if (el) {
                    queue.push(() => el.innerText = currentValue)
                }
            }

            return [getValue, setValue]
        }

        const [getCount, setCount] = createSignal(0)

        const btn = document.getElementById('btn')
        btn.innerText = getCount()
        btn.onclick = () => setCount(btn, getCount() + 1)
    </script>
</body>

</html>
```
I just started using solid，
I read part of the source code，
I wonder if the above code can briefly describe the working principle of solid

**Comment by ryansolid** [comment]
I've seen reactivity introduced this way before. It's interesting since it's polling. On one hand, this functions roughly the same as an approximation. This might help some people understand the most basic idea here. But it also only shows half the equation as it doesn't really show dependency tracking/subscriptions. That being said it's much less code to convey the idea than any attempt using the actual model. I got it down to about ~50 lines of code in my introduction to reactivity article and this comes in considerably less.

**Comment by pheianox** [comment]
Is the idea of queue that important? Can't we just update directory like this?

```js

function createSignal(initalValue) {
    let currentValue = initalValue;

    function getter() {
        return currentValue;
    }

    function setter(element, nextValue) {
        if (!element) return;
        currentValue = nextValue;
        element.innerText = currentValue;
    }

    return [getter, setter];
}

const btn = window.btn;
const label = window.label;

const [getCount, setCount] = createSignal(0);

btn.onclick = () => setCount(label, getCount() + 1);

```

**Comment by wwmmzz** [comment]
@pheianox 
In fact, I just don’t know how to update the view without virtual dom, so I added this queue。
 I read more source code, tried to build the source code myself, and found that dom was bound when compiling jsx(maybe not correct).
I will try more on solid,maybe i will understand better

**Comment by ryansolid** [comment]
This article is my best reference (and the part 1 article) https://dev.to/ryansolid/building-a-reactive-library-from-scratch-1i0p

**Comment by pheianox** [comment]
> This article is my best reference (and the part 1 article) https://dev.to/ryansolid/building-a-reactive-library-from-scratch-1i0p

Thx, that's what I was looking for
