### ISSUE TITLE
Looking for Solid logo Svg

### ISSUE THREAD

**Issue by aFuzzyBear** [solidjs/solid#634]
Hey guys,

I am finding it difficult to get a svg copy of your logo, if it is possible to for you's to share one, it would be greatly appreciated. 

Many thanks

**Comment by ryansolid** [comment]
Are the logos on https://www.solidjs.com/media sufficient?

**Comment by aFuzzyBear** [comment]
Legend thank you for the link man,

Im currently setting up the thumbnail for the Solid Astro Template, hopefully this should look good and be live in the next day or two...
