### ISSUE TITLE
directive support in vs code

### ISSUE THREAD

**Issue by tanekim77** [solidjs/solid#642]
What editor would you recommend for us to use for Solid js?
I am currently using vs code, but I am getting syntax error for directive:
![image](https://user-images.githubusercontent.com/20119808/132099884-2c1da8a1-0b9d-4946-8193-a4b9a7edbe57.png)

And this is my tsconfig.json, which is generated by solid js template
![image](https://user-images.githubusercontent.com/20119808/132099858-126de081-aaa1-48ce-aed9-efc4a2bddb49.png)

**Comment by FlatMapIO** [comment]
I have the same problem. I don't know if it's the typescript itself.

**Comment by atk** [comment]
Did you add your directive to the module "solid-js" / namespace JSX / interface Directives like described in the docs? https://www.solidjs.com/docs/latest/api#use%3A___

**Comment by tanekim77** [comment]
@atk  Thanks for that link. That solved the issue!
