### ISSUE TITLE
Syntax improvements

### ISSUE THREAD

**Issue by tanekim77** [solidjs/solid#645]
Suppose I create a store like this in typescript:
![image](https://user-images.githubusercontent.com/20119808/132123244-177aad37-1645-45e0-a002-62f64a34df34.png)

Currently, the only way to use setFields would be to pass in a string as a first argument.
setFields("fromInput", "A value");

Wouldn't it be better if we could also allow the following syntax as well?
setFields( e=> e.fromInput, "A value");
The latter version allows vs code to change the property name "fromInput" into something else with F2 key. This renaming does not work on the formal version that usese the string argument.
Imagine I have a lot of fields I would like to rename, but all setFields used string as first arguments. It would be a lot of rework to rename fields.

Implementation wise, the e in setFields( e=> e.fromInput, "A value") should be { fromInput : 'fromInput' }

**Comment by atk** [comment]
That's exactly what `produce` is meant for: https://www.solidjs.com/docs/latest/api#produce

**Comment by tanekim77** [comment]
@atk 
Thanks! That solved the issue.
