### ISSUE TITLE
Duplicate lines when translating the documentation to Portuguese

### ISSUE THREAD

**Issue by jvzaniolo** [solidjs/solid#650]
**Describe the bug**
Hey guys, awesome work! Solid looks amazing. I hope we'll be using it in the future.
I was reading the documentation and I saw there were duplicate lines (highlighted below) when translating to Portuguese.

![image](https://user-images.githubusercontent.com/54036572/132533981-c7d39980-e9a0-4ac6-af0b-5b4d61f7d109.png)

**To Reproduce**
Provide a code snippet and steps to reproduce the behavior:
1. Go to 'https://www.solidjs.com/guide?lang=br#introduzindo-primitivos'
2. The first two lines are duplicates in English from the last two in Portuguese.

**Expected behavior**
Show only the lines in Portuguese.

**Comment by davedbase** [comment]
Oh interesting, thanks for reporting this! We maintain the docs in `solid-docs`. I've gone ahead and pruned the sentences: https://github.com/solidjs/solid-docs/commit/d00ade76d300d2f7771326a7c4e438016123f66a. The update will go live on the next push.

Thanks for the report!
