### ISSUE TITLE
Inconsistent style prop behaviour with regards to null value

### ISSUE THREAD

**Issue by sickill** [solidjs/solid#651]
**Describe the bug**

There seems to be something funky with batching the updates for the `style` prop when you flip it from `false` to `{...}`.

**To Reproduce**

1. Open this playground snippet:

https://playground.solidjs.com/?version=1.1.1#NobwRAdghgtgpmAXGGUCWEwBowBcCeADgsrgM4Ae2YZA9gK4BOAxiWGjIbY7gAQi9GcCABM4jXgF9eAM0a0YvADo1aAGzQiAtACsyAegDucAEYqA3EogcuPfr2ZCouOAGU0Ac2hqps+YpU6DW09CysrGXoIZlw0WgheABU4MlwACgBKfiteB3jU3mBU-DU4LF4yOFxXAlKAXV4AXgcnF3cvKDU0iHo1NQzLCBy8iAL4gGENZgBrJt5MpoA+bITciqqakrhu3v7BtfXq2u2BAHITKBmPeSjtZnVuU8ReU6ERU6kB4clw1aFcJgJNLDXIAHhM9FwuHivAIxEaKghUPiKl4Eym00aIHRaBm0mKpSxBO2GUkixBa0muNm8ApoP0SOhEHJqy+EB+QwgQlE4jSC0ay1ByQK+kW5REtGY9HgEFwADoPFUAKKlGW4ABC+AAkiJgWAoIRCCoMmywJI6kA

2. Inspect the button - observe the initial `style` value of `null` produced a button element with no style prop (👍) and no crash (👍)
3. Click the button - observe the `style` has been set to desired background color (👍), no crash (👍)
4. Click the button again - observe the `Uncaught TypeError: Cannot read property 'background-color' of null` in JS console (👎)

**Expected behavior**

I'd expect the usage of `false` value for `style` prop either:
- was not supported at all and crashed on any usage including initial render, or
- it worked on subsequent value changes as it does today on the initial render

**Additional context**

solid-js 1.1.2

**Comment by sickill** [comment]
Posting the reproduce snippet here as well in case playground is unavailable:

```js
import { render } from "solid-js/web";
import { createSignal } from "solid-js";

function Test() {
  const [style, setStyle] = createSignal(null);

  const onClick = () => {
    setStyle(null);
    setStyle({ 'background-color': 'red' });
  }

  return (
    <button type="button" onClick={onClick} style={style()}>
      Click me
    </button>
  );
}

render(() => <Test />, document.getElementById("app"));
```

**Comment by sickill** [comment]
Note that the above example is contrived, but I encountered this in my app where I'm driving signal updates with `setTimeout/requestAnimationFrame` combo and it happens that setter is called with `null` (to clear the style) and then with `{...}` to set it back, and I'm `batch` there explicitly, which it seems it's similar in effect to calling the setter twice in the same event handler.

**Comment by ryansolid** [comment]
Yeah it doesn't support null the way it's written currently. You should be able to set it to an empty object or empty string "" to clear the styles. Adding check for null seems reasonable but just to get you immediately unblocked.
