### ISSUE TITLE
createMemo computed value always fires even though it didn't change, when wrapped in suspense.

### ISSUE THREAD

**Issue by minht11** [solidjs/solid#652]
**Describe the bug**
Create memo value is observed inside createEffect on every change even though computed value itself did not change. That only happens when `<Routes />` is wrapped in `<Suspense />`

**To Reproduce**
Provide a code snippet and steps to reproduce the behavior:
1. Go to https://codesandbox.io/s/flamboyant-sea-9y52b?file=/index.js:978-1031
2. Click on different links 
3. See that `createEffect` fires on every page change, even though computed boolean value is the same.
```tsx
const usersMatch = useMatch(() => "/users/*");
const isUsersRoute = createMemo(() => Boolean(usersMatch()));
createEffect(() => {
  // Should only fire when boolean value changes,
  // but now it fires on every page change.
  console.log("is Users route", isUsersRoute());
});
<Suspense>
  <Routes />
</Suspense>
```

**Expected behavior**
`createEffect` only fires boolean value actually changes.
**Reproduction**
[Reproduction](https://codesandbox.io/s/flamboyant-sea-9y52b?file=/index.js:978-1031)

**Additional context**
The last working Solid version was 1.1.0, all other newer versions have this bug.

**Comment by ryansolid** [comment]
Ok should be fixed in 1.1.4. This one was tricky to notice at first and trickier to track down. But it was just an omission made to a more comprehensive bug fix I did in 1.1.1. Thanks for reporting.
