### ISSUE TITLE
createSource: `source` is not reactive when use props

### ISSUE THREAD

**Issue by weijarz** [solidjs/solid#659]
**Describe the bug**

Resources are not updated when use props as source.

**To Reproduce**

[Playground](https://playground.solidjs.com/?version=1.1.1#NobwRAdghgtgpmAXGGUCWEwBowBcCeADgsrgM4Ae2YZA9gK4BOAxiWGjIbY7gAQi9mjOFFxwAymgDm0ADZZe4+mWIQycBUJFiASnDpNWm4aLgBRAGYW4zPgF9eFxrRi8A5HVloAJgFoAVmRuADoQHFw8-LzCEN5wjLwOTi7unj4BZAD0AO5wAEYhEKHMtGp81rjMABYAqoTEjABysHC8ALy8UGT4EMy8ABTQ8Ii8ZLiMGFIAlO0AfPyhvIKlnnAAdLK0Uv1uFdWTbgpDcFOLndnofBBw2bwACs4waOr9CW3z6rgAKhxwDLivBQARgADGCpqcIEthLgmFDjmtcLQ6g0AMJdOD9SF2UKhCz0Xq4NClXgo+LNeD9QjOQhkEYCY4jMYTCBSRIzEBnEplXjAej1cktAC67UEJl0+gYLEx1NotLWxwUe1qAqaLUhSy0pks1ls-SxcwWUKWyzUtFk6022zcx0OvFl8sVvH5DQpmIhZzsGuicFhjChAB4qkDZgAJOCyTYKEAOsgKloODogF2C+B2AOZYOzUI4orXCgRPhxCxQeiycoE2zEqEAQXqBs5xu5Y15Ts+bpFHS1YkkMigsh2EFKLTc3ubfH53lMbtFgxaTPGkxm7wGy4+vrdc-gkLOMLhAzOSwD2eNJt4Aby9FwSKhpVRXmYAGs2snCFOxJu3I0-qO7LNv7QGaXtepQnmeR7ATevB3g+z6vu+cCfqiVQTEEUx-shqFAVeN5geBAaEP+878McWLppkhGHiaAZKCocBqK0JaRnkUBPi+BGzAAMrQUDeJMGaEX+VFngGZJqvAvDHC+pHobwmR4SJmS0ao6gKee8lnNiuIQDEcSMPqa7nnWhBybMCjeLQzD0PAEC4GsUi+mYFo2bgABC+AAJLeP0wRgFA9S+R6mB2EKQA)

```typescript
import { createSignal, Suspense, createResource, createEffect } from 'solid-js'
import { render } from 'solid-js/web'

const fetchUpperName = async (name: string) => {
  console.log('fetching', name)
  await new Promise(r => setTimeout(r, 1000))
  return name.toUpperCase()
}

function UpperName(props: { name: string }) {
  const [upperName] = createResource(props.name, fetchUpperName)
  createEffect(() => {
    console.log('name', props.name, upperName())
  })
  return <h1>Hello, {props.name} = {upperName}</h1>
}

export default function App() {
  const [name, setName] = createSignal('noname')
  const updateName = (name: string) => () => setName(name)

  return (
    <>
      <button onClick={updateName('Neo')}>Neo</button>
      <button onClick={updateName('Chris')}>Chris</button>
      <p>Name: {name()}</p>
      <Suspense fallback={<p>Loading</p>}>
        <UpperName name={name()} />
      </Suspense>
    </>
  )
}

render(() => <App />, document.getElementById("app"))
```

**Expected behavior**

When click top buttons, resources are not refetch.

**Comment by LXSMNSYC** [comment]
You need to wrap it into a function, otherwise `createResource` wouldn't know that there's something to track with.

```js
const [upperName] = createResource(() => props.name, fetchUpperName)
```
