### ISSUE TITLE
Memoed store getter is undefined

### ISSUE THREAD

**Issue by mhyfritz** [solidjs/solid#662]
**Describe the bug**
The [memoed store getter pattern from the official docs](https://www.solidjs.com/docs/latest/api#getters) throws an error (`fullName is not a function`). It seems the getter is immediately invoked when the store is created (i.e. before actually explicitly accessing it). At that point in time the memoed function isn't defined yet, hence the error.

**To Reproduce**
Provide a code snippet and steps to reproduce the behavior:
1. Clone the [repro repo](https://github.com/mhyfritz/solid-store-memoed-getter-issue)
2. Run `npm install` and `npm run dev`
3. Open the app in a web browser
4. See error in console: `Uncaught TypeError: fullName is not a function`

**Expected behavior**
The app should render without an error.

**Reproduction**
[GitHub repo](https://github.com/mhyfritz/solid-store-memoed-getter-issue)

**Additional context**
The repro is literally just the [official JS template](https://github.com/solidjs/templates/tree/master/js) with the [code from the docs](https://www.solidjs.com/docs/latest/api#getters) added to `<App>`.

**Comment by LXSMNSYC** [comment]
CMIIW but I think this is issue should be flagged on https://github.com/solidjs/solid-docs

**Comment by mhyfritz** [comment]
Hmm, not sure. The docs/example per se are fine. It's unexpected to me though that the getter is immediately executed by `createStore` and was wondering whether that's a bug... I am happy to move the issue though if that makes more sense.

**Comment by high1** [comment]
@mhyfritz you are calling the function inside the getter. This is an issue of you not examining your code, unfortunately.
```
let fullName;
  const [state, setState] = createStore({
    user: {
      firstName: "John",
      lastName: "Smith",
      get fullName() {
        return fullName();
      },
    },
  });
  ```

**Comment by ryansolid** [comment]
What is in the docs should work. The idea is the getter is just a simple getter. So what you put in is what you get out. It shouldn't run immediately.

**Comment by high1** [comment]
It should not, @ryansolid. There is a mistake. 
```
get fullName() {
  return fullName()
}
```
is written in the docs, and this calls fullName immediately. This is a mistake, it should be:
```
get fullName() {
  return fullName
}
```

**Comment by LXSMNSYC** [comment]
Getters only run when accessed, in this case, `fullName` should not even evaluate given that the property wasn't accessed even before `createMemo`.

**Comment by high1** [comment]
You are calling the function inside the getter, doesn't matter if you didn't call the getter itself.

**Comment by cynecx** [comment]
The problem is:

https://github.com/solidjs/solid/blob/670f4f3db98b5a9eeb07623ab5fff6beb32fe08e/packages/solid/store/src/store.ts#L368-L371

The demo is running in dev mode (`_SOLID_DEV_`) and since `options.name` hasn't been set invokes `DEV.hashValue` on the initial store which further down `JSON.stringifies` the initial store, which tries to evaluate the getter method.

**Comment by ryansolid** [comment]
That makes a lot of sense. Thank you.. some of the Dev mode stuff less tested in conjunction. Ok, well looks like we have a direction. I should have made a test for nesting Memos too.. I think I just disliked how it looked and hoped to do something differently at some point and just never added them. That's a mistake.
