### ISSUE TITLE
Missing link on articles page: The Deep Dive Ep#4 Reactive Frontend Frameworks

### ISSUE THREAD

**Issue by tforward** [solidjs/solid#663]
https://github.com/solidjs/solid/blob/main/documentation/resources/articles.md

https://thedeepdive.simplecast.com/episodes/reactive-frontend-frameworks 

returns error 404

**Comment by ryansolid** [comment]
Yeah it looks like it's been taken down. We aren't really maintaining this here any more and is part of the website/docs. I'm just going to remove the link off the home page. And eventually remove those sections from the repo. Thanks for reporting.
