### ISSUE TITLE
Question: why does none of the effects trigger in this case?

### ISSUE THREAD

**Issue by isaacHagoel** [solidjs/solid#669]
Sorry if this is not the best place for such a question. In the code snippet below none of the effects run (I expect it to resolve to 0,0,0,0) and I don't understand why. 
Thanks
```
import { render } from 'solid-js/web';
import { createSignal, createEffect } from 'solid-js';

function Calc() {
  const [a, setA] = createSignal(1);
  const [b, setB] = createSignal(8);
  const [c, setC] = createSignal(3);
  const [d, setD] = createSignal(4);
  createEffect(() => {
    setA(b() + c());
  });
  createEffect(() => {
    setD(a() * 2);
  });
   createEffect(() => {
    if (a() > 10) {
	console.log('resetting');
	setB(0);
         setC(0);
    }
  });
   createEffect(() => {
    console.log({ a:a(), b:b(), c:c(), d:d() })
  });

  return <>a: {a()}, b:{b()}, c: {c()} d: {d()}</>;
}

render(() => <Calc />, document.getElementById('app'));
```

**Comment by orenelbaum** [comment]
I think that signals must be independent of each other otherwise you break the reactive system. Instead of writing to signals inside of effects you need to use memo for every value that is dependent on a signal or another memo. Also you are constructing a cyclic graph which I don't know if it's something you can do with Solid and I'm not sure why you would need.

**Comment by otonashixav** [comment]
It seems to resolve as you expect? https://playground.solidjs.com/?hash=-1684461603&version=1.1.1

The output tab shows `a: 0, b:0, c: 0 d: 0` and I get this in the console:
```js
Object { a: 1, b: 8, c: 3, d: 4 }
resetting
Object { a: 11, b: 8, c: 3, d: 2 }
Object { a: 11, b: 0, c: 0, d: 22 }
Object { a: 0, b: 0, c: 0, d: 22 }
Object { a: 0, b: 0, c: 0, d: 0 }
```

**Comment by isaacHagoel** [comment]
@otonashixav lol. my bad. I saw things refreshing as i was typing but it wasn't really executing until I clicked the small "refresh" icon. When I do it does work as expected. 
thanks!
