### ISSUE TITLE
DIrective runs before its entire subtree gets rendered 

### ISSUE THREAD

**Issue by isaacHagoel** [solidjs/solid#673]
**IMPORTANT: If you have a question or an idea for a new feature use Github Discussions instead**

**Describe the bug**
It seems like a directive can run before the entire subtree of the node it's referencing gets rendered. Specifically it happens to children added with a `<For>` loop. 

**To Reproduce**
1. Go to [sandbox](https://codesandbox.io/s/basic-example-m64mx?file=/src/App.jsx)
2. The container has 6 children (items). 3 without a `<For>` and 3 with. It also has a directive that iterates over the children.
3. It is only able to iterate over the children that were added without `<For>` 
4. Look at the console, try to click the two types of children. Only the children without `<For>` have click handlers
5. Uncomment the `setTimeout` (lines 15 and 21) to see everything working as expected.

**Expected behavior**
The directive should be run after all the children were mounted. All of them should get click handlers.

**Reproduction**
https://codesandbox.io/s/basic-example-m64mx?file=/src/App.jsx

**Additional context**
I know this example is not how one should add click handlers. it is just in order to show the issue.

**Comment by ryansolid** [comment]
I recommend using `createEffect` or `onMount` in the directive here. Generally speaking refs happen as they render. This allows passing them around easier as you know that they are present to be passed to Components that occur after. Directives are sugar over that. There is an argument to autowrap these in an `onMount` hook I suppose but this does give more versatility. Changing this behavior is breaking as well. So this needs careful consideration.

**Comment by isaacHagoel** [comment]
Thanks Ryan. I tried wrapping with onMount but then other effects and
renderEffects inside the directive started misbehaving (as in behaving
differently to when they weren't wrapped). I will experiment some more. If
this is expected behaviour feel free to close this.

**Comment by ryansolid** [comment]
This isn't the first time this question came up. Although it was still after 1.0. Ultimately I decided to keep ref behavior as it was. Although I wasn't thinking about directives. I will close this but I think it is worth further discussion but further down the line. Anything already in an Effects should have access to the children. `renderEffects` might not though.
