### ISSUE TITLE
{ ...rest } spread in <Dynamic /> reactivity issue

### ISSUE THREAD

**Issue by azuwey** [solidjs/solid#681]
**Describe the bug**
When using props spread with `<Dynamic />` it keeps the initial props

**To Reproduce**
Provide a code snippet and steps to reproduce the behavior:
1. Go to this [playground link](https://playground.solidjs.com/?version=1.1.5#NobwRAdghgtgpmAXGGUCWEwBowBcCeADgsrgM4Ae2YZA9gK4BOAxiWGjIbY7gAQHFeIXgGFanWhDgRcWXgCkAygA1eAX14AzRuN4ByOgBs0AEwC0AKzJ6AOhA5ceQ3o2km4jOQBF80GGmZ1LR0YXhsaWmNzKwB6AHc4ACNwgG47B24+YWZXKFw4RVxuOCDtXXCjU0syGLIi11S7O016CGZcNElRcS4pGQB5KV4ACkIdQjJEBRUAOgBJCEJ6XAAJABUAWQAZAEFcXEY0ROW4MgAede2FpdwAUUM4eBkAPgBKITteFzhcJgheM4YG5CGagsa0CYaGLPOxqJoQFptDpdMQSPq4NZxWgjYSgmbgibqKZKZQzS67faHY75c7kxSEKAQe6PaS4N4ff7fX6Mf5nMgM-4gPEEshqZ74WhnWoCmEQOEQdIyDyaKCsXgABVRvVZHK+zB6klZUy1hpkn14IqmACU4PrGCY+QcMABzOStADWEFocQgsvldn1EDqvH1aNZWzQdSmmoN6OAAF1eABeXjAc3ZWNG7phmSY2hyS3OOr4B5TPT6wzcRCJQz0OApPRBNRYdMhzMyY3t3CDOAF8aTZwANygtbgZYAFnBDJXGxp5fG0gqEa12p1-ib0Yo4mhcMxJ4xhu8QObA8HgHU8r3eGQfoVL4mUzk4JfCsVhsIbw92nATBuswAGdRXhPSRg0kRQp1tXA-xkZMRgwdwKCmCB6BgRIPFeKZB1oUxk2ea9b1wS93wIr98l-LspgQuAKCA+Evlcbl-mGc0vjOEw0EHWUvh4gEOK41jeIBHw-ACQShJ40NtRkJMQCk01cAjOpzyI-IZk-KCfxg3B4xmeT0XlCSJKFUF9PDSNcBUy91Mg78KJzHT8X7QyjK+aFxIBGJ+O4oT2M4nyJLOakin+AQ4CTcJgskcJeEkERjGYd1ZMPPDYogCCyO04Z-1eMUPN4jT2jbBy0rgfLPKi31yqC5YQv4Ihwsi2rorANL4oCJKQBSpN8PA2zoK7YYAEZcoCozCr4MzYNwLFqpiSqxrYrz-MEqVvPNV5F39CBXAgdwD26-Czm0rcdz3DxeGhOQTFoZhUNZGZnR+ZknlwAAhfA5hMFiwCgQhCHCV5NrsMA1HjIA)
2. Click on 'select component one'
3. Scroll down to 'select component two'

**Expected behavior**
The value in the input box change from 'test' to 'hello'

**Reproduction**
[Playground link](https://playground.solidjs.com/?version=1.1.5#NobwRAdghgtgpmAXGGUCWEwBowBcCeADgsrgM4Ae2YZA9gK4BOAxiWGjIbY7gAQHFeIXgGFanWhDgRcWXgCkAygA1eAX14AzRuN4ByOgBs0AEwC0AKzJ6AOhA5ceQ3o2km4jOQBF80GGmZ1LR0YXhsaWmNzKwB6AHc4ACNwgG47B24+YWZXKFw4RVxuOCDtXXCjU0syGLIi11S7O016CGZcNElRcS4pGQB5KV4ACkIdQjJEBRUAOgBJCEJ6XAAJABUAWQAZAEFcXEY0ROW4MgAede2FpdwAUUM4eBkAPgBKITteFzhcJgheM4YG5CGagsa0CYaGLPOxqJr2GQeTRQVi8AAKYgkfSyn14zB6kmkuCmmN6RNx4ImUwASnB8YwTGc6ocIABzOStADWEFocQgMIgcIgdnxEDqeIJ2K2aDqUwxkqJwAAurwALy8YC47IKmQknW4QZwOSUybOABuUEM9DgUz0+TqeiCaiwWolWKJevdAykxvGpuEFqtNv0AAs4IZDLRHRohUq0sKIC02h0uqTCTJFHE0LhmGHGMN3iBcaLxcA6nkjbwyD9ChWVeqcnAK4VisNhNWHu04CY09ipgAGdSvYuScWSRThum4XtEtUjDDuChTCD0GCJDyvKZm2imNXPKs13AVtsHzv5Hv6qYLuAUIfwr6uX6Mf7DXFfM4mNBmgVfX8Az-fm+f4Aj4fgBEBwG-viXq4KqIDQWSMjSnUZZHvkMwdlO3YzjISozAh6a4EKkGQSAoL4fqyG4KhFYYZOXYXjBeEmsRJFfNCEEAjEAE-sBH5frxkFnMc+xdAIcCquEIlFMKYC8JIIjGMwnJwQWe7yRAE5njhuDDP2rxqIJJGYe0bqIXwhKce+MTSZIRl-sJywyfwRASVJTmSOEGmKQEKkgGpqr7uO9HTvqwwAIwGfZwEmXwBHYvwcS0FZXG2fynFnNxAlAZlPG4q88ZCnYrgQO4+YBfuZw6Zm2a5h4vDQnIJi0Mwq5EjMrI-PcjxEgAQvgcwmK+YBQIQhDhK8BV2GAahKkAA)

**Comment by LXSMNSYC** [comment]
It's a design choice, although there has been some discussion: https://github.com/ryansolid/dom-expressions/issues/91

The motivation was that since props are only created once, it is assumed to be static. However, there are use cases that we needed to patch it reactively (See the linked discussion).

**Comment by azuwey** [comment]
Oh I see, didn't know that was a design choice, maybe the documentation should mention it. I close this ticket then.
