### ISSUE TITLE
The HMR bug with using webpack

### ISSUE THREAD

**Issue by eveningwater** [solidjs/solid#694]
Describe the bug
When using webpack, the root node is duplicated upon saving a file, rather than replacing it. For example, when using the webpack, you'll see the following after saving a file.

Download code from https://github.com/eveningwater/solidjs-web-demo
npm i and npm run start
Make a change to App.tsx and observe that the root node is duplicated rather than replaced
Expected behavior
Upon saving a file the page content should be replaced rather than duplicated.

Additional context

I try to add the solid-refresh library and  on a per file basis, use comments at top of file to force reload,but it still not working:

```js
/* @refresh reload */
```

**Comment by ryansolid** [comment]
I haven't checked this specifically yet, but you need the babel plugin `solid-refresh/babel` in your babel config. That's what does all the transformations that make any of this work. We need to have better instructions in the readme.

**Comment by eveningwater** [comment]
I get it, thanks!
