### ISSUE TITLE
Using Context with injected children - Context reactivity not applied to any child

### ISSUE THREAD

**Issue by kristianmandrup** [solidjs/solid#707]
**Describe the bug**

Not clear how to use Context with dynamic children

This works as per the documentation

```tsx
export const CounterContext = createContext([{ count: 0 } as {count: number}, {} as any]);

export default function CounterProvider(props: any) {
  const [state, setState] = createStore({ count: props.count || 0 } as {count: number});
  const store = [
    state,
    {
      increment() {
        setState("count", (c: number) => c + 1);
      },
      decrement() {
        setState("count", (c: number) => c - 1);
      },
    },
  ];

  return (
    <div>
      <h2>Counter</h2>
      <CounterContext.Provider value={store}>
        <CounterDisplayer />
      </CounterContext.Provider>
    </div>
  );
}
```

But this doesn't work

```tsx
  return (
    <div>
      <h2>Counter</h2>
      <CounterContext.Provider value={store}>
       {children}
      </CounterContext.Provider>
    </div>
  );
```

How do I make it work when injecting one or more children that reference and use the context?

```tsx
<CounterProvider>
  <CounterDisplayer />
</CounterProvider>
```

I've tried to use the special [children](https://www.solidjs.com/docs/latest/api#children) helper (to add reactivity to children) but to no avail. What am I missing? Please improve the docs to make this limitation and way around it more clear. Perhaps I'm not using `children` helper correctly, but there are no examples for correct use, except in an effect.

I tried doing:

```tsx
const reactiveChildren = children(() => props.children)
// ...

      <CounterContext.Provider value={store} children={reactiveChildren}>
      </CounterContext.Provider>
```

I also tried using `For`

```tsx
      <For each={reactiveChildren() as any[]}>
        {(item) => <Dynamic component={tag} class={classes}/>}
      </For>
```

Produces the same error. I expect this is because it should be used in a render effect somehow? That the children are not subscribing to the state/store and are thus not re-rendered when the state is changed?

I was finally able to "solve it" by wrapping with a `Show` conditional element, but feels very awkward. Surely there must be a better way.

```tsx
      <Show when={state.open} fallback={() => <span>...</span>}>
        {props.children}
      </Show>
```

**Expected behavior**

I would have expected the children to gain access to the populated Context automatically

**Comment by ryansolid** [comment]
Make sure you aren't destructuring the children outside of a reactive context. Basic case works. https://playground.solidjs.com/?hash=1178248814&version=1.2.0

Children helper won't help if outside of the provider because it will be executing immediately outside of the context. If you need to introspect them you could do it inline (or in a function you call), but make sure to access props.children only once. Or if you need to deeply resolve children for introspection(ie. use the `children` helper) it might be easier to extract that into a component.

**Comment by trusktr** [comment]
Do the docs say this? Might be worth copy/pasting.

**Comment by kristianmandrup** [comment]
Very cool! Thanks @ryansolid. I even got it working with `createStore`.

```js
import { render,  } from "solid-js/web";
import { createStore } from "solid-js/store";
import { onCleanup, createContext, useContext } from "solid-js";

const CounterContext = createContext([{}, {}]);
function CounterProvider(props) {
  const [state, setState] = createStore({count: 0});
  const id = setInterval(() => {
    setState({count: state.count + 1});
  }, 1000);
  onCleanup(() => clearInterval(id));
  const store = [
    state,
    {
      setState      
    }
  ]

  return (
    <CounterContext.Provider value={store}>
      {props.children}
    </CounterContext.Provider>
  );
}

function Header() {
  const [store] = useContext(CounterContext);
  return <h2>{store.count}</h2>;
}

function Div() {
  const [store] = useContext(CounterContext);
  return <div>{store.count}</div>;
}

function App() {

  return (
    <>
      <CounterProvider><Header /><Div /></CounterProvider>
    </>
  );
}

render(() => <App />, document.getElementById("app"));
```

So the key was this part "Make sure you aren't destructuring the children outside of a reactive context.".
In other words avoid doing `const { children } = props;` and then trying to use the children from there, but instead reference props.children just once per functional component. Would be great with some updated docs with an example to cover this. 

I hit this issue while trying port reactstrap (for Bootstrap 5) to  SolidJS. We are using reactstrap at my workplace (with lots of legacy code to migrate/maintain) and would like to experiment with solidjs going forward (using micro frontends with SingleSPA).

**Comment by kristianmandrup** [comment]
Aha, this starts to look promising https://playground.solidjs.com/?hash=1605046603&version=1.2.0

**Comment by floric** [comment]
I had exactly the same problem, destructuring my props for the children with `({children})` and couldn't find the solution until I found this issue. I think this is pretty difficult to find as I always assumed destructuring was safe to do.
