### ISSUE TITLE
When strict mode is false in TypeScript, createSignal<Foo>() returns type `any`

### ISSUE THREAD

**Issue by trusktr** [solidjs/solid#710]
I discovered this while working on https://github.com/solidjs/solid/pull/706. More details starting here: https://github.com/solidjs/solid/pull/706#issuecomment-957268798

I will open a new PR that attempts to fix that issue, while preserving the return type splitting mentioned there.

**Comment by otonashixav** [comment]
I think this issue can be closed. If anything it's caused by `undefined` (and `null`) being weird with `strict: false`, as seen in the playground (which has `strict: false`):

https://playground.solidjs.com/?hash=-1038877944&version=1.3.3
