### ISSUE TITLE
CreateResource and Uncaught (in promise)

### ISSUE THREAD

**Issue by timojuonoja** [solidjs/solid#714]
**Describe the bug**
When using `createResource` and fetching from non-working url, like for example `localhost` and there isn't any server handling the request, the `Uncaught (in promise)`error occurs. 

**Expected behavior**
Should it gracefully handle the error?

**To reproduce**
```
import { createSignal, createResource, ErrorBoundary } from "solid-js";
import { render } from "solid-js/web";

const fetchUser = async (id) =>
  (await fetch(`https://localhost:6000/api/people/${id}/`)).json();

const App = () => {
  const [userId, setUserId] = createSignal();
  const [user] = createResource(userId, fetchUser);

  return (
    <ErrorBoundary fallback={<div>OUCH!</div>}>
      <input
        type="number"
        min="1"
        placeholder="Enter Numeric Id"
        onInput={(e) => setUserId(e.currentTarget.value)}
      />
      <span>{user.loading && "Loading..."}</span>
      <span>{user.error && "Error..."}</span>
      <div>
        <pre>{JSON.stringify(user(), null, 2)}</pre>
      </div>
    </ErrorBoundary>
  );
};

render(App, document.getElementById("app"));
```
**Reproduction**
[Playground link](https://playground.solidjs.com/?version=1.2.2#NobwRAdghgtgpmAXGGUCWEwBowBcCeADgsrgM4Ae2YZA9gK4BOAxiWGjIbY7gAQi9mjOFFxwAymgDm0ADZZBw0XABKcOk1YKAoo0bcAQgwgATKI3y8AvrwBm+mLwA6NWrLQmAtACsyLgNxOEBxcPPy8wqZwjNZ2Ds6u7l6+APQA7nAARgFBQcy0EGR8tnC4zAAWAKpk0bwAvLxQZPgQzLwAFB4AlPUAfEG8HVBp6MWlFe0ABuW4uIRkiCkpsrTMULLltEWIAGwADAcpUIRoKcS0hLJwKQAkIB5WKZNdXQB0vgXtXYEQeQVFvAAgoRCPUOj06r1+ANBP8+MB6DVGABJEwKGq4arRVEAXTBQhEYkkMnWXx+g3yhXhiOieIaBOUag0LDg7RpKLRdnGVSR31yEEGwlwTAF7RhgwAPLp9IwjPRTOZLLZ1rJMlBmABrOogCUmNAAN16AHlKgBhAASAEIJSk9YarP0BYNnRKMIR6Lhxc7BgRiHUXBB6DBMtEXF7vTAMP6wABGMNO72DS7quCbWQmaLR7QQMQxAByQeiaDaqPjiedBWREHduG17TgEKhGKxHPrr2YTEiuAAKuYpKVXvr1vQG1Zw7wUo7yxKyIQoBBeiB2a8VlA9RApLwAGRbhIAGVoa4wUlep5cVhts-nU8TM7nC6XSNe0Rl293Lml3FPr3Pl-vN+9XUDQA29CGERcAClxCNPNXiKRhjzQWx8DZJEvgUQNZHkXgACYugvM5wPHG07RAm1P1lYwzAsG8+QgKwfiCSIM0YdpgUIBQTFWQsc1eftcG0K54BzAx8FRMUwGOQgXBeH4wCsHEgA).

**Comment by rturnq** [comment]
As far as I can tell the linked example is working as expected; however, I'm not seeing an uncaught error, the ErrorBoundary you have seems to be handling it.

We should add a note about this to the docs but for resources, errors which occur in the fetcher are delegated to the resource read. So in this case, the error will be thrown where you read `user()` in the JSX. This design lets authors determine how and where to handle errors through the strategic use of ErrorBoundaries like you have done here. If you add another one just around your `user` read, you should see that rest of the UI will remain intact.

**Comment by timojuonoja** [comment]
Thanks for your response, @rturnq. Ok, that clarifies the case and I was just expecting things handled differently. Closing..
