### ISSUE TITLE
Issues using ref with splitProps

### ISSUE THREAD

**Issue by kristianmandrup** [solidjs/solid#720]
```bash
Uncaught (in promise) TypeError: Cannot set property ref of #<Object> which has only a getter
    at ref (Input.tsx?t=1636616602126:76)
    at assign (dev.js:216)
    at Object.fn (dev.js:343)
    at runComputation (dev.js:633)
    at updateComputation (dev.js:618)
    at createRenderEffect (dev.js:197)
    at spreadExpression (dev.js:343)
    at spread (dev.js:185)
    at Object.fn (dev.js:526)
    at runComputation (dev.js:633)
```

Unable to assign to `local.ref` for some reason!? Proxy object?

```bash
return _$createComponent(Dynamic, _$mergeProps({
    get component() {
      return tag();
    }

  }, setAttribs() && attributes, {
    ref(r$) {
      const _ref$ = local.ref;
      typeof _ref$ === "function" ? _ref$(r$) : local.ref = r$; <=== unable to assign
    },
```

Full code here: https://github.com/kristianmandrup/solid-bootstrap/blob/main/src/components/Input.tsx
Snapshot of the essential parts causing the error

```tsx
export const Input = (props: PropTypes) => {
  const [local, attributes] = splitProps(mergeProps(props, defaultProps),
  ["className", "tag", "type", "bsSize", "valid",
  "invalid", "addon", "plaintext", "ref"]);

  // ....

  return <Dynamic 
    component={tag()} 
    {...(setAttribs() && attributes)} 
    ref={local.ref} 
    type={type}
    class={classes()} 
    aria-invalid={local.invalid}>
  </Dynamic>
```

**Comment by otonashixav** [comment]
Minimal reproduction: https://playground.solidjs.com/?hash=-472019162&version=1.2.3

Seems to be because `ref` always gets compiled assuming it is a valid ref, so either assignable or callable, which is not the case with `splitProps` which always creates a getter for the split props regardless of whether the original props object had a getter or not. You can work around this by using `props.ref` directly instead of `local.ref`. 

This pattern of splitting attributes and using local props directly from the props object is maybe common, which might explain why this bug wasn't reported earlier.

**Comment by kristianmandrup** [comment]
Ah, makes sense. I was previously advised by Ryan to use `splitProps` and avoid dereferencing props (as it screws with the reactivity mechanics). I guess `ref` and such variables that are assignable go into the special case category. Thanks!

Would be great if these kinds of patterns and special cases could be better documented. Not entirely clear from the docs or tutorial. Cheers :)

**Comment by ryansolid** [comment]
I wasn't aware of this. We should see if we can fix this. In this case assignment actually doesn't make sense. If its there call or we don't care what happens. Unfortunately that isn't easy to detect. I think if these proxies compiled with a no op setter we'd be fine here and there would be no issue.

**Comment by ptrckhjnl** [comment]
I also found something related, the order of the `props` in relation to the `ref` seems to matter.

I have created a few cases: https://playground.solidjs.com/?hash=-1481069100&version=1.2.2

**Comment by ryansolid** [comment]
Yeah that is interesting.. because in a spread it just runs them in order. If you really want to get a settled ref I recommend using `createEffect` or `onMount`.
