### ISSUE TITLE
Property is not deleted

### ISSUE THREAD

**Issue by juanrgm** [solidjs/solid#723]
**Describe the bug**
I don't know if this behaviour is documented, but when you apply a spread conditional property never is unsetted.

**To Reproduce**

```ts
<div {...(align() && { align: "center" })}>Text</div>
```
**Expected behavior**
The property should be deleted when `align` is false.

**Reproduction**
https://playground.solidjs.com/?hash=1441382847&version=1.2.2

**Comment by ryansolid** [comment]
Ah.. because it returns null instead of an object it never iterates. Ok yeah there is a bug here. Thanks for reporting.

**Comment by juanrgm** [comment]
It also fails with this case: 

```ts
<div {...(align() && { align: "center" })}>Text</div>
```

https://playground.solidjs.com/?hash=1052253120&version=1.2.2

Seems that the problem is in [assign](https://github.com/ryansolid/dom-expressions/blob/41e356571808b2c331783a406312a05977ab316c/packages/dom-expressions/src/client.js#L159) function, I don't see any control over deleted properties.

**Comment by ryansolid** [comment]
Yes you are correct. I do have the prevProps so this should be achievable with a small change.
