### ISSUE TITLE
`produce` doesn't work correctly

### ISSUE THREAD

**Issue by elite174** [solidjs/solid#726]
**IMPORTANT: If you have a question or an idea for a new feature use Github Discussions instead**

**Describe the bug**
Internal `produce` function doesn't work correctly. In the example component below nothing happens, however if I change to immer `produce` everything works well.

**To Reproduce**
```
export const Component = () => {
  const [stats, setStats] = createSignal<[string, number][]>([
    ['Luck', 5],
    ['Morality', 5],
    ['Strength', 5],
  ]);

  const inc = (index: number) => {
    setStats(
      produce((s) => {
        s[index][1] += 1;
      })
    );
  };

  return (
    <div>
      <For each={stats()}>
        {([text, value], index) => {
          return (
            <div>
              <span>
                {text}: {value}
              </span>
              <button onClick={() => inc(index())}>+</button>
            </div>
          );
        }}
      </For>
    </div>
  );
};```

**Expected behavior**
The list should be updated on button click.

**Reproduction**
If applicable, add a link to a simple reproduction on a site like https://codesandbox.io or https://playground.solidjs.com.

**Additional context**
Add any other context about the problem here.

**Comment by ryansolid** [comment]
This is happening because you are destructuring in the function in `<For>`

This line: `([text, value], index) =>`

What's happening is Immer is replacing the whole top level object and in so triggering everything to re-render again. If you did not destructure there, Solid would be able to update just that text without re-running the whole `<For>`.

**Comment by elite174** [comment]
@ryansolid Thank you for your answer!
Just a question then: for instance, I want to iterate through object entries:

```
 const [store, setStore] = createStore({Luck: 5, Strength: 5, Morality: 5});

const entries = createMemo(() => Object.entries(store));

return (
 <For each={entries}>
...
</For>
)
```

In this case when I change the store (update `Luck` value), the entire list will be rendered again. How to update only one item in a list?

**Comment by ryansolid** [comment]
I'd probably use Object.keys. Entries produces new arrays each time. Then Id use the key to access the value in the object. This should be able to update independently.

**Comment by elite174** [comment]
Thank you!

**Comment by myWsq** [comment]
It may be simpler to use `immer` produce function in this case. I have written a helper function for this: https://github.com/myWsq/solid-immer
