### ISSUE TITLE
JSX spread doesn't apply style changes (within store)

### ISSUE THREAD

**Issue by Brendan-csel** [solidjs/solid#728]
**Describe the bug**
Spreading a store containing a `style` property on a JSX element doesn't update with any changes within `style` (unless the style reference itself changes.

This was picked up when using a store and `reconcile` to update the store with new style properties (among other things).  It seems `style` retains the same reference and the spread doesn't apply the changes within that.

**To Reproduce**
This [playground example](https://playground.solidjs.com/?hash=-789351390&version=1.2.2) demonstrates the issue.  After 1 second the store gets updated and the `ul` should move.

Possible workarounds:
- removing `reconcile`.  But that results in the whole store content being replaced.
- specifically spreading the style like `<ul {...menuProps} style={{...menuProps.style}}>`.  But that is no good if the JSX is being written by someone else consuming the store object from a library.

**Expected behavior**
The spread should apply the changes within `style`.

**Comment by trusktr** [comment]
It seems that using `reconcile` shouldn't cause it to break; reactivity should still be triggered.

**Comment by ryansolid** [comment]
reconcile is working correctly, its just the equality check happens at the wrong place for nested objects in spreads. Style and classList are both affected.

**Comment by trusktr** [comment]
How is it working correctly? When someone updates data (with reconcile or not) they expect the template to update.

**Comment by Brendan-csel** [comment]
The only reason it is working without reconcile is the whole store content is changing - including a new `style` object.

The issue seems to be more with spread not digging into the style object (or classList) to look for changes (so not reactive within the style object).

The only way reconcile could help with that would be to replace the style object with a new one if any of its properties changed.

If everything was super-fine grained then I guess each prop within the style object would independently update - but I think style is applied atomically instead of property-by-property (as least by spread).

**Comment by trusktr** [comment]
I get that this is "how it works" currently, but it is something that definitely feels unexpected.

A question is, what is the intent when a user spreads?

In that example, ultimately the template _does_ read the individual style properties in order to apply them to the DOM, so it might also be an easy assumption that the Proxy path reactivity will pick up the change to each style value regardless if the style object ref changed or not.

**Comment by ryansolid** [comment]
Yes. It is s bug with `spread`. I just wanted to note `reconcile` is working as expected.

**Comment by Brendan-csel** [comment]
Thanks @ryansolid.  Unfortunately 1.2.4 doesn't seem to have resolved this issue.

I am now seeing console warnings `Cannot mutate a Store directly.` which seem to be coming from within a Solid function called `style()` on a line that does `delete prev[s];`

**Comment by ryansolid** [comment]
Interesting. I wasn't expecting previous to become a store. It is created from a non-proxy and I thought it was only ever mutated directly. DOM Expressions where I did the fix has no knowledge of proxies so I didnt see this. Im going to need to find where that happens.

**Comment by Brendan-csel** [comment]
It looks like this line `prevProps[prop] = value` at the bottom of `assign()` is saving `style` (which is a prop of the top-level store being spread across the component).

The screenshot below is actually 2nd time through but the proxy for style was definitely assigned by the bottom line first time through.

![ad9Me5I76B](https://user-images.githubusercontent.com/1744490/142488049-9fd033e6-fe77-48bf-8253-7da2234b376a.png)

**Comment by ryansolid** [comment]
Yeah that's it.. I was thinking I fixed this with the early exit.. but when I refactored for the other bug fix I pulled the function out.

**Comment by leeoniya** [comment]
![jrMwlkO](https://user-images.githubusercontent.com/43234/142493926-87f9835a-c7da-4e70-90e8-ecac4a27e471.gif)

**Comment by Brendan-csel** [comment]
Just confirming 1.2.5 has fixed this issue for me.  Thanks @ryansolid!
