### ISSUE TITLE
Directives don't work through spreads

### ISSUE THREAD

**Issue by otonashixav** [solidjs/solid#729]
**Describe the bug**
Directives assigned through spreads instead become an attribute on the element that they are spread on. 

**Expected behavior**
Directives should work through spreads. 

**Reproduction**
https://playground.solidjs.com/?hash=-1587864117&version=1.2.3

**Comment by ryansolid** [comment]
They can't. Like components there is no guarantee of being in scope. Like the spread helper could only get a string and have no where to get the directive from.
