### ISSUE TITLE
produce causes TS error

### ISSUE THREAD

**Issue by bgoscinski** [solidjs/solid#732]
**Describe the bug**
Valid usage of `produce` causes TS error. 

**To Reproduce**
Provide a code snippet and steps to reproduce the behavior:
1. Go to [playground](https://playground.solidjs.com/?version=1.2.2#NobwRAdghgtgpmAXGGUCWEwBowBcCeADgsrgM4Ae2YZA9gK4BOAxiWGjIbY7gAQi9GcCABM4jXgF9eAM0a0YvADo1aAGzQiAtACsyAegDucAEYqA3EogcuPfr2ZCouOAGVc3OFl6F5I+qxSsvKKKnQa2nr6ZB5CFlZWMvQQzLhotBC8AMIMEC6MABQAlPxWvA4ZMbzAMZ7eZHC47p4AurwAvA5OLs1CBSDMubiIvAAMkkWWmRUQVRiOcPB5HbzFHQB8pdPlDU2xcAW+tP6sBWQbW+VXvGQAdIPJuADUT2VXE5Nvkm9CuEyZBTe5QAPCZ6LgPJkCMR2iowRCMipeBkshpmABrdogeZCJa4STrIFXEC1IT3Ibfba8YH6eGQwnTT4QSlWISicQFNbtTbAnKPcS8fTrbwiWjMeh424Ac0aAFE1IthLgAEL4ACSIkBYCghEIKiKTLAkhaQA)
2. Wait for code to be type checked 
3. See the error

**Expected behavior**
No error

**Reproduction**
See above

**Additional context**
The error is silenced in the tutorial by `// @ts-nocheck` directive: https://www.solidjs.com/tutorial/stores_mutation?solved

**Comment by mackignacio** [comment]
It's not actually an error. You are just missing some interface for `produce`. Add a `Count` interface and provide it as a generic type for `produce` like the code below.

```ts
interface Count {
  count: number;
}

function Counter() {
  const [store, setStore] = createStore({ count: 0 });

  const increment = () => {
    setStore(
      produce<Count>((s) => {
        s.count++;
      })
    );
  };
  return (
    <button type="button" onClick={increment}>
      {store.count}
    </button>
  );
}
```

**Comment by bgoscinski** [comment]
Thanks @mackignacio! 
While your solution works I assumed that the original intent was that explicit interface should not be necessary because TS should be able to infer the types. This would greatly improve the ergonomics of produce.

@ryansolid is my assumption correct?
In any case please treat this ticket as a request for making the generic optional :)

I tried to dig into the types of produce and setStore and fix it myself but oh boy they're complex lol

**Comment by davedbase** [comment]
@trusktr has been reviewing our TS, maybe he has an opinion on this.

**Comment by mackignacio** [comment]
@trusktr I can help with the types if needed. Just show me where to start.

**Comment by trusktr** [comment]
Indeed there are more places to take a stab at improving inference, plus making the source code itself more type safe. Just run `Go To Definition` in VS Code on `produce` and that'll take you right to it.
