### ISSUE TITLE
can solidjs support render canvas animation?

### ISSUE THREAD

**Issue by zsytssk** [solidjs/solid#747]
React can render canvas animation. eg: [react-pixi-fiber](https://github.com/pmndrs/react-three-fiber). React can do such thing but the performance is so bad. Solidjs just like react but with better performance and small bundle size. If Solidjs can support this,
I think this could be a big use scenario for Solidjs.

**Comment by LXSMNSYC** [comment]
Yes, it requires a Pixi renderer for Solid's universal renderer.

**Comment by zsytssk** [comment]
add some demo:
https://codesandbox.io/s/solid-gl-boxes-lmpei
https://codesandbox.io/s/custom-dom-renderer-yu2pj
