### ISSUE TITLE
Using a store with a list, a selected element among this list cause elements from the list to be overriden

### ISSUE THREAD

**Issue by neckaros** [solidjs/solid#758]
**IMPORTANT: If you have a question or an idea for a new feature use Github Discussions instead**

**Describe the bug**
Code is better than a thousand word: https://codesandbox.io/s/counter-context-issue-with-select-wh0v9?file=/index.tsx (sometimes the browser view fail and you have to refresh the embedded browser window 1-2 times. Not sure why it has a hard time finding the solid dep. I used one of the examples )
i have a store with:
-elments (array of basic element with a unique id property)
-selectedId used to set which element you wand to select
-selectedElement set with an effect when selectedId change to the matching element in the elements array.

i select an element the first time no issue, as soon as i select a second element it will correctly set it as selected element but it will also replace the previous selected element in the elements array

**To Reproduce**
Provide a code snippet and steps to reproduce the behavior:
1. Go to ['Sandbox'](https://codesandbox.io/s/counter-context-issue-with-select-wh0v9?file=/index.tsx)
2. Click on 'name1' => it will set the selectedId in the store to "1" and the effect will set the selected element to the first element (matching by id)
3. Click on 'name2' => it will set the selectedId in the store to "2" and the effect will set the selected element to the first element (matching by id)
4. the first element of the array is replaced by the second.

**Expected behavior**
it should not change the elements array

Store code:
```typescript
import { createContext, useContext, Component, createEffect } from "solid-js";
import { createStore } from "solid-js/store";
type Element = { id: string; name: string };
type CounterStore = [
  { elements?: Element; selectedId?: string; selectedElement?: Element },
  { select?: (id: string) => void }
];

const CounterContext = createContext<CounterStore>([{}, {}]);
const el1 = { id: "1", name: "name1" };
const el2 = { id: "2", name: "name2" };
const elements = [el1, el2];
export const CounterProvider: Component = (props) => {
  const [state, setState] = createStore({
      elements: elements,
      selectedId: undefined,
      selectedElement: undefined
    }),
    store: CounterStore = [
      state,
      {
        select(id) {
          setState("selectedId", (c) => id);
        }
      }
    ];
  console.log(state);
  createEffect(() => {
    console.log(state.selectedId);
    if (state.selectedId) {
      setState("selectedElement", (_) =>
        state.elements.find((l) => l.id === state.selectedId)
      );
    }
  });
  return (
    <CounterContext.Provider value={store}>
      {props.children}
    </CounterContext.Provider>
  );
};

export function useCounter() {
  return useContext(CounterContext);
}
```

**Comment by ryansolid** [comment]
Yeah it's because objects merge rather than replace even on nested paths. (https://www.solidjs.com/docs/latest/api#updating-stores)

If you change it to this it works:
```
if (state.selectedId) {
   setState((_) => ({
      selectedElement: _.elements.find((l) => l.id === state.selectedId)
   }));
}
```

**Comment by neckaros** [comment]
I read the tutorials but not this doc, my bad. I will have a read and try to understand why :)
Thanks for the very quick reply, and of course the awesome framework!!!

**Comment by ryansolid** [comment]
It isn't the most intuitive but it's consistent. I did struggle with this one a bit. Not my happiest decision but it is reasonable I think. Without it causes much more verbose things for relatively common cases, where being aware of this it's about the same amount of code.

**Comment by neckaros** [comment]
okay i read the doc and after a bit of thinking i now i understand.
By doing 
```typescript
setState((_) => ({
        selectedElement: _.elements.find((l) => l.id === state.selectedId)
      }));
````
i was basically replacing the fields of the element 1 with the fields of element 2 because you merge the properties instead of replacing the object.
Your version works because you are one level higher and the store get shallow merged, thus not impacting element 1 but only top level "selectedElement".
```typescript
setState((_) => ({
        selectedElement: _.elements.find((l) => l.id === state.selectedId)
      }));
```

Not most intuitive but by reading the doc i see why. The store is very very powerful!
Maybe a little warning in the tutorial pointing to the doc? I'm just afraid i won't be the only noob to bother you.

i'm happy to do a PR if it can help you
