### ISSUE TITLE
"computations created outside a `createRoot` or `render`" in vite-plugin-ssr example

### ISSUE THREAD

**Issue by makoven** [solidjs/solid#759]
**Describe the bug**

When you run the solid example for the [vite-plugin-ssr](https://github.com/brillout/vite-plugin-ssr) plugin, a warning:
_"computations created outside a `createRoot` or `render` will never be disposed"_
appears in the console, but everything seems to work.

Link to example: https://github.com/brillout/vite-plugin-ssr/tree/master/examples/solid

**To Reproduce**

1. git clone https://github.com/brillout/vite-plugin-ssr.git
2. cd vite-plugin-ssr/examples/solid/
3. npm install
4. npm run dev
5. Follow the localhost:3000 in the browser 

**The file in which the `render` function is used:**

https://github.com/brillout/vite-plugin-ssr/blob/master/examples/solid/renderer/_default.page.client.tsx
or
https://github.com/brillout/vite-plugin-ssr/blob/master/examples/solid/renderer/_default.page.server.tsx

**Comment by ryansolid** [comment]
The warning is basically warning against possible memory leaks. It means that something is being rendered not under the synchronous execution of the reactive graph. I don't see anything on the surface so this will probably take debugging the vite-plugin-ssr internals to see if there is timing concerns with our how either routing or HMR works etc.. Thanks for bringing this to our attention.

**Comment by ryansolid** [comment]
Oh this is on the server.. Something is being imported from the client build on the server. I think this is related to recent changes in Vite resolutions of export conditions. I've been battling similar issues. This isn't specific to this plugin but Solid-Vite integrations.

**Comment by pheianox** [comment]
Also using 
```ts
const navigate = useNavigate() 
```
outside of component created this issue
Just to have more options to look at. Spent 3h to resolve..
