### ISSUE TITLE
Test files do not have `strict: true` applied in editor

### ISSUE THREAD

**Issue by otonashixav** [solidjs/solid#767]
The tsconfigs aren't applied to tests, which can cause issues during development. I'm not sure how to fix the issue in a monorepo, but including tests in `tsconfig.json` and having a `tsconfig.build.json` extending it and excluding tests should be the way to go.

**Comment by ryansolid** [comment]
I tried to do it the other way where there is a tsconfig for tests. I saw that pattern on another mono repo and copied it.

**Comment by ryansolid** [comment]
Fixed with https://github.com/solidjs/solid/pull/784
