### ISSUE TITLE
Create a SignalPair<T> type?

### ISSUE THREAD

**Issue by muscache** [solidjs/solid#777]
It's common to pass signals around (such as with [nested reactivity](https://www.solidjs.com/tutorial/stores_nested_reactivity?solved)) and I usually create a type:

```typescript
/**
 * A convenience type to represent the return value of `createSignal`
 */
export type SignalPair<T> = [get: Accessor<T>, set: Setter<T>];
```

...to type the return value of `createSignal`. It would be very useful to have a library-provided type for this.

Thanks for a *solid* library :1st_place_medal:

**Comment by orenelbaum** [comment]
I agree that we need a type for this. I'm not sure about the name though.

**Comment by mdynnl** [comment]
I thought I saw that in the recent ts refactor and yep. There it is.
<https://github.com/solidjs/solid/blob/main/packages/solid/src/reactive/signal.ts#L133>
