### ISSUE TITLE
Add type for PropsWithRef to define components that accept refs

### ISSUE THREAD

**Issue by nksaraf** [solidjs/solid#778]
This type will be helpful and will the serve the purpose that forwardRef in react did. It allows us to easily define the ref type. The ref prop should be a function should that people don't use it by mistake and know that they either have to pass it or call it with the reference.

eg.
```typescript
type PropsWithRef<T, Props> = Props & { ref: (val: T) => void 

function Box(props: PropsWithRef<HTML.DivElement, { color: string }) {
	return <div ref={props.ref} />
}
```

**Comment by LXSMNSYC** [comment]
How does that work for:

```js

let ref;

<Box ref={ref} />
```

Take note that Solid supports this.

**Comment by nksaraf** [comment]
Yeah I know this works.. but when the ref comes from a parent.. its typed as a function, and annoying to type ourselves.. and more like an implementation detail

**Comment by LXSMNSYC** [comment]
Not exactly. Even though it is typed as a function after compilation, we lose support to the feature I mentioned which is like the most common way to capture refs. We should be consistent. In solid-headless, a union type for ref works:

```js
type Ref<T> = T | (val: T) => void;
```

But normally, you only have to do this in the component:

```js
if (typeof props.ref === 'function') {
  props.ref(el);
}
```

of course, this is seamless:

```js
<div ref={props.ref} />
```

**Comment by nksaraf** [comment]
Ohh I thought passing a function in to ref is acceptable.. is that typed as an error? And is this Ref type exported from solid-js?

**Comment by LXSMNSYC** [comment]
passing a ref as a function is acceptable. My point was doing  `let ref` with your proposed type doesn't work and so users are forced to write a ref callback, even though the Solid compiler supports the expression.

**Comment by nksaraf** [comment]
I don't thing the type should be used with let ref.. its only for props with ref that needs to be forwarded.. that has the awkward type.. so
```
let ref: Ref<T>;
```

but
```
type PropsWithRef<T, Props> = Props & { ref: T | (val: T) => void }

function Box(props: PropsWithRef<HTML.DivElement, { color: string }) {
	return <div ref={props.ref} />
}
```

ohh yeah maybe ur right in that those props need to include `T | (val: T) => void`

but I adding that makes sure that the user checks the function before trying to assign to it or something

**Comment by LXSMNSYC** [comment]
Surely, that's the downside, however usage of the ref feels more natural.

**Comment by nksaraf** [comment]
Yeah no I agree being more explicit is better about the ref, but do we have the base Ref type in Solid?

**Comment by LXSMNSYC** [comment]
We don't. It's just an impromptu type I wrote 😂

**Comment by trusktr** [comment]
The problem here is that we're assigning to `someRef` in `ref={someRef}` (f.e. `<div ref={someRef}>` assigns an `HTMLDivElement` instance (at runtime) to `someRef`, but TypeScript considers the operation (type-wise) to be the opposite: TS sees the type of the `ref={someRef}` expression as assigning `someRef` to the `ref` prop.

I'm not sure how to improve this, because we can't make TypeScript think in the other direction here.

**Comment by LXSMNSYC** [comment]
@trusktr wouldn't really matter since we'll use it extend our props from anyway

**Comment by atk** [comment]
I fail to see how this has added value over `Component<{ ref: … }>`?

**Comment by LXSMNSYC** [comment]
@atk I rarely use `Component<T>` because you can't really use generics on it.

```ts
declare function SomeComp<T>(props: SomeProps<T>): JSX.Element
```

**Comment by atk** [comment]
Thanks for the clarification.

I think we should make the component/props types composable. There was also a discussion to add VoidComponents for components that do not allow children (because those would never be rendered).

If we touch the types to define components, we should aim for a more complete version.
