### ISSUE TITLE
Rendering errors when omitting tbody from table

### ISSUE THREAD

**Issue by trfx351** [solidjs/solid#782]
If the tbody element is omitted when using the table element, it will still be added to the final DOM by some (all?) browsers (tested in Firefox and Edge). This creates an inconsistency between SolidJS JSX/DOM structure and the actual DOM created by the browser, and can results in rendering errors in the app.

Example:

```
function App() {
  return (
     <table>
        <tr>
          <td>Cell 1</td>
          <td style={{ color:'red' }}>Cell 2</td>
        </tr>
    </table>
  );
}
```

The app crashes with error "Uncaught (in promise) TypeError: _el$4 is null". The generated code is:
```
const _Hot$$App = function App() {
  return (() => {
    const _el$ = _tmpl$.cloneNode(true),
          _el$2 = _el$.firstChild,
          _el$3 = _el$2.firstChild,
          _el$4 = _el$3.nextSibling;

    _el$4.style.setProperty("color", "red");

    return _el$;
  })();
};
```

Here, _el$ is the table element, and el$2 is the tbody element generated by the browser but missing from SolidJS structure. SolidJS expects el$2 to be the tr. In the browser DOM the el$3 is the tr element, and el$4 is null instead of the expected td element. And results in the null reference error when attempting to set the style property.

If you set the style on the first td element (Cell 1), the following code is generated:

```
const _Hot$$App = function App() {
  return (() => {
    const _el$ = _tmpl$.cloneNode(true),
          _el$2 = _el$.firstChild,
          _el$3 = _el$2.firstChild;

    _el$3.style.setProperty("color", "red");

    return _el$;
  })();
};
```

In this case, in the browser DOM the el$3 is the tr node. The app renders in this case but the style is applied to the tr node, not the td as specified in the SolidJS JSX.

In both cases, adding a tbody as a child of the table results in correct rendering behavior.

One workaround in SolidJS could be to enforce that a tbody is always used, through a compilation check. Or add it "behind the scenes" automatically, to match the browser behavior. The question is also if there could possibly be more cases like this other than for the table/tbody, where browsers may add extra DOM elements that are not present in the HTML that is given to them for rendering.

**Comment by ryansolid** [comment]
There are other cases like when people put certain elements in ones that can't accept them. We warn about to matching templates in dev builds.

**Comment by trfx351** [comment]
Hi Ryan

Thanks for the answer, good to know that this is something that you are aware of. For now some kind of warnings during dev time are probably sufficient. A compile time solution would indeed be ideal, but that is probably difficult with a lot of dynamic nested content. If this kind of browser/SolidJS DOM mismatch can be detected during runtime, in prod or dev, throwing an error with a clear message might be preferable since this can lead to hidden and hard to track down bugs.

**Comment by ryansolid** [comment]
I had it in Prod at one point. But some people were sensitive to having the additional check. Removing the check was the main thing that spawned creating Dev build for the rendering portion.

**Comment by trfx351** [comment]
Perhaps a flag could be added in the future to include the checks in the production build. Is there any documentation on the current checks/validation templates that are used?

I also want to say that so far my experience of SolidJS has been fantastic, I am really enjoying developing with it having previously used mostly React and Vue. I hope it will gain more popularity soon, SolidJS deserves much more attention in my opinion. So thanks for all of your/the teams hard work on this.

**Comment by ryansolid** [comment]
Yeah the builds are created at build time for Solid as in to not introduce flag mechanisms for the end user outside of the compiler. When we make a prod build the dev code is completely dead code eliminated. There were talks of doing more but it is a little tricky as the renderer is framework agnostic. Right now the check is really simple anyway and can miss stuff. I just count tags. This isn't fullproof. Trying to exactly match strings was problematic too. Most of the dev stuff is just suppressing warnings. Things like where people create reactivity that isn't part of autodisposal etc.. 

Ideally there would be a server package that just fed html into and would identify problems. But I've never found it.

Thanks for the kind words.

**Comment by ryansolid** [comment]
I'm going to close this here since nothin on the Solid side..Open an issue in DOM Expressions: https://github.com/ryansolid/dom-expressions/issues/105
