### ISSUE TITLE
Context issues with solid-element

### ISSUE THREAD

**Issue by coreymcg** [solidjs/solid#785]
I have 2 custom elements created with solid-element. One is a context provider and the other is a consumer.

```jsx
<sld-component-a message="hello world"> // message gets added to a provider
  <sld-component-b></sld-component-b> // hello world gets rendered in here
</sld-component-a>
```

It works fine if the consuming element is a direct child of the provider. However, when the child is further down in the DOM the consumer will instead get the default value of the context instead.

```jsx
<sld-component-a message="hello world">
  <div>
    <sld-component-b></sld-component-b> // renders the default context value instead of the updated value from the message
  </div>
</sld-component-a>
```

Working example:

https://stackblitz.com/edit/solid-vite-se4fzw?file=src/index.tsx

**Comment by ryansolid** [comment]
I see.. hmm.. interesting and tricky since it suggests that connectedCallback happens earlier than I'm expecting. Basically at clone time rather than when element.isConnected time. Stackblitz isn't really letting me debug (it hangs with the debugger open) but I will see if I can pull this project somewhere else and confirm this.

Thanks for reporting.

**Comment by ryansolid** [comment]
It isn't what I thought thankfully. It's simpler. Just need to fix the lookup.

**Comment by coreymcg** [comment]
Thank you so much! I've been really stoked with solid so far. I love what you're doing.

**Comment by ryansolid** [comment]
Yeah it isn't released yet but I will release it in the next patch version in the next day or so. So look out for 1.3.3.

**Comment by coreymcg** [comment]
I've already built the latest solid-element locally and can confirm that the problem is solved on my end. 🙏
