### ISSUE TITLE
Outdated types for generateHydrationScript

### ISSUE THREAD

**Issue by chrstntdd** [solidjs/solid#788]
**Describe the bug**
The type signature for `generateHydrationScript` declares no parameters, when the latest v1.3.X requires a configuration object. Calling this function now produces this runtime error:

```shell
TypeError: Cannot read properties of undefined (reading 'eventNames')
```

**To Reproduce**
Directly call `generateHydrationScript` from `"solid-js/web"` without parameters, as the types suggest.

**Expected behavior**
`generateHydrationScript`'s types should be updated to reflect the new signature.

**Additional context**
I might not have run into this issue if I used the `<HydrationScript/>` component with `renderToStringAsync`. Admittedly,  none of the examples show using `generateHydrationScript` directly, but I used it since it resulted in less noise in the simple vite SSG pipeline I have set up. 

Documentation would go far in clarifying which API is more appropriate. 

Diffing the two implementations across versions highlights the breaking change:

solid@1.2.6:
```js
// node_modules/solid-js/web/dist/server.js
function generateHydrationScript() {
  const {
    nonce,
    streaming,
    resources,
    eventNames = ["click", "input"]
  } = sharedConfig.context;
  return '...';
}
```

solid@1.3.1:
```js
// node_modules/solid-js/web/dist/server.js
function generateHydrationScript({
  eventNames = ["click", "input"],
  nonce
}) {
  return `...`;
}
```

**Fix**

```diff
-import { renderToStringAsync, generateHydrationScript } from "solid-js/web"
+import { renderToStringAsync, HydrationScript } from "solid-js/web"
import { App } from "./app"

async function render(url: string) {
  let html = await renderToStringAsync(() => <App url={url} />)
- let hydrationScript = generateHydrationScript()
+ let hydrationScript = await renderToStringAsync(() => <HydrationScript />)

 // or possibly... (causes a type error)
+ let hydrationScript = generateHydrationScript({})

  return { html, hydrationScript }
}

export { render }
```

I would be willing to contribute this fix, but would really value some guidance on the best solution.

**Comment by ryansolid** [comment]
Yeah this is my bad. The parameter will be optional in the next release. I already fixed the downstream dependency. Just need to update here.

**Comment by chrstntdd** [comment]
Gotcha. Is the preferred approach using the component? When I tried that approach, the generation ran fine, but it seems the hydration that ran in the browser didn't run correctly (events didn't work). Will have to investigate further, but I didn't encounter any error message I can share.
