### ISSUE TITLE
Rehydration: Component built by createGlobalStyles not included in template

### ISSUE THREAD

**Issue by btakita** [solidjs/solid#792]
Select "Client side rendering with hydration" in playground. Discussed in `solid-start` discord channel.

https://playground.solidjs.com/?version=1.3.3#NobwRAdghgtgpmAXGGUCWEwBowBcCeADgsrgM4Ae2YZA9gK4BOAxiWGjIbY7gAQi8AwrU60IcCLiy9mjOFFxwAymgDm0ADa8AvrwBmjEbwDkdDWgAmAWgBWZYwB0IHLj34y5CuAHENtAEZQGkoEGnBkOvqGMCZmllZkoXDWzCJc4pL2TnAUrnypEIm8AGK0tIqMAPoaUPgMuIjCohl8ALy8ABQAlK0AfCBODrgFRcCpnFAQ+JVk8iwAFpVMGgAkALq87bLyiirqQR3GiAD0x+OEk-gJc8zzVsvGXYPDYqNm9Lhor0uMqxtbnl2ak0hxOx3en1e91+j2eIz4wDCUEYEB+f02Hh2ymBByOpyRKOhGlhECGclwTAgvAAPL1nkNqSF8GFjnTSbgGXoyhUZDUyGRWg4wKVynAqjU6h8hWyhrLcNSLGgAG4yjlqhnQFX09Vq6nzeQWMW8qD8wV4fXwKwYJVi3BWOQ2xizaUABUMFnozHIvEmFl4SjFSrQrDI1OO+qghsYqrlcup9A0MZ1cfMvWpUF48zkelaIHOlxmN0WyxW3W0vSaFym-qLYagaeOqe1sd1qfTmezuYhX0KaNLXXLSloGg+PdDx3rYab7JbKbQaYzWbgOZABNRJbLvQAMnNnBBVEIJBU6w3p7PdccE0m48dNdf5cdFVqZw+uaLo88w2ztE54f6khi2xeL4ARBEyYRkAABk4AB0IoVNUtT1PwTg-hA0GYNoaxAA

**Comment by btakita** [comment]
Results in errors:

```
Uncaught (in promise) TypeError: node is null
    setAttribute dev.js:130
    Footer_layout Footer_layout.tsx:24
    runComputation dev.js:697
    updateComputation dev.js:682
    createRenderEffect dev.js:200
    Footer_layout Footer_layout.tsx:24
    Footer_layout Footer_layout.tsx:24
    c dev.js:524
    untrack dev.js:430
```
Uncaught (in promise) TypeError: _el$4 is null
Footer_layout Footer_layout.tsx:24
    _Hot$$Footer_layout Footer_layout.tsx:24
    hmrCompWrapper @solid-refresh:10
    untrack dev.js:430
    hmrCompWrapper @solid-refresh:10
    runComputation dev.js:697
    updateComputation dev.js:682
    createMemo dev.js:234
    hmrCompWrapper @solid-refresh:7
```

```

**Comment by ryansolid** [comment]
I'm going to need a reproduction. I copied this right into one of my rollup setups and one of the solid-start examples and had no issue. Must be more to it.

**Comment by ryansolid** [comment]
Been 2 months. Closing as stale.
