### ISSUE TITLE
Errors lose a lot of data when being serialized and hydrated

### ISSUE THREAD

**Issue by nksaraf** [solidjs/solid#831]
Currently this is how we serialize errors on the server:
```
function serializeError(error) {
  return error.message ? `new Error(${devalue(error.message)})` : devalue(error);
}
```
I think this looses some important data, i.e.other properties on the error object, eg. stack, code and custom properties. I think we can do better and more thorough serialization of the error to get almost the same error object on the client (with the stack preserved).

https://github.com/sindresorhus/serialize-error Might be a good starting point for this.

**Comment by Brendan-csel** [comment]
Perhaps dev mode only though so as not to over-expose details to the client.

**Comment by nksaraf** [comment]
yeah that's reasonable

**Comment by ryansolid** [comment]
I see.. Hmm... it would require custom deserialization in the browser which isn't great. `stack` and `name` seem at least reasonable for dev.

**Comment by Aslemammad** [comment]
How can I work on this issue? Are there any hints in the code so I can follow up?
