### ISSUE TITLE
`traversed` in `setStore` duplicates traversed keys when passed an array, function or object

### ISSUE THREAD

**Issue by otonashixav** [solidjs/solid#840]
**Describe the bug**
When passing arguments to `setStore`, passing an array of keys, or function/object to filter an array, the traversed key is added twice: once on initial pass, and a second time by the recursive call of `updatePath`. 

The traversed array is also in reverse order from what I expected, but I'm not sure if that's intentional. 

**To Reproduce**
[Playground Link](https://playground.solidjs.com/?version=1.3.5#NobwRAdghgtgpmAXGGUCWEwBowBcCeADgsrgM4Ae2YZA9gK4BOAxiWGjIbY7gAQi9mjOFFxwAyrm5xeAX14AzRrRi8AOjVoAbNABMAtACsyAejJThGgNxqIt5rQjnewLLzJxck6QF1eAXkFhUQkLOAAKAR1zRBcABjcARh83WgAjQzhmXFiBKFjEtzTYgCY5OQBKGwgTE156MgwAc14oRkYofF5aBV4Aazh8MlsPLzDwjWjcDTdgOJTecIB9N1wKgIA+QUc6LTgAOi1aJvC1qpHPb2EJsHTM7JmXDSgNBeXV9f8thydtA6OTmdqrV6o0IC1mFAtFo0lBmH0LmNpBMILx1GApjNbGj3rw0J8tmgAv5AglsYsVrw1pttr89odjqcKrZzjU6g1moplDB9FJ9Gl8IirhFJmhzI8BEoVLEElTaDK5G5cdSvrTdv9GUDbGBZD4gA)

**Expected behavior**
Each traversed key is only added once.

**Comment by ryansolid** [comment]
The path is intentionally backward. The thinking it would be easier for composing these patterns at unknown depth. But as for the other behavior seems like a bug.

**Comment by otonashixav** [comment]
Is `{ from, to }` including the item at index `to` instead of excluding it (matching `Array.slice` etc.) also intentional?
