### ISSUE TITLE
Elements inserted in the wrong location with <For>

### ISSUE THREAD

**Issue by pfgithub** [solidjs/solid#844]
**Describe the bug**  
Elements are inserted in the wrong location when using a \<For> with zero items where the next child is a function component

**To Reproduce**  
```jsx
import { render, For } from "solid-js/web";
import { createSignal } from "solid-js";

function Counter() {
  const [items, setItems] = createSignal([]);
  return <div>
    <For each={items()}>{() => <Button>Hi</Button>}</For>
    <Button onClick={() => setItems(it => [...it, 0])}>+</Button>
  </div>;
}
function Button(props) {
  return <button onClick={props.onClick}>{props.children}</button>;
}
render(() => {
  return <Counter />;
}, document.getElementById("app"));
```

Click the plus button

Notice that elements are inserted to the right of the plus button, rather than to the left.

**Expected behavior**  
Elements should be inserted to the left as that is the order in the code

**Reproduction**  
https://playground.solidjs.com/?version=1.3.5#NobwRAdghgtgpmAXGGUCWEwBowBcCeADgsrgM4Ae2YZA9gK4BOAxiWGjIbY7gAQi9GcCABM4jLLwBi3SQGUAFrQDuvAL68AZo1oxeAHRq0ANmhEBaAFZkA9MrgAjQwG59EDlx79ezIVFxwcmgA5tDGkr5w-nAAopqacMx8Gtq6BkamFtYubm7GcHxovAC8vAAMrhBumvQQSWi0ELwAwgwQAYwAFIQ6hGQAlPxuvIIFTE0APCJoAG4AfMMjvBMyjLxRzArFID20fQB0aAEwZJ39anMgnUeSaIPFc8sAQvS4uI2LS7yNzabMANbbM4lR67A5kAoASWOpyOcBBvDh+00aGMHU6nRmt1EcAo90eGDEFF4AEJiqU0Gd+udPrw5gAJIogI5qCY2F5vRpzVk2VYLJpLCYc95NAjEYqGByvEWGb4QX5oAFA-G8MFkfYQ3DQuAna58B68YD7Y03XgAajNaAAuud+V8RmbaWzhVzFmzpvNKmpchAanVcA0mi6IN1egMhgKhLhxsspZymj8-oCdmH9onFf8Lim9urNqiREIIDy4yK5l6fYWxF1gQaQItmI0yHxgGQlMpJJrFCorSUfH4AkFQlBjJ1cIx6HB+pURg2IE3DXCTh2oTCe6VItFB2FOsAbdPRtHGJMPXbBSfaSMJiXGnKFUqrirO23MQiSTNbe9gsF8kMwLKzbwrYqGcxbSq6AqXjY54QcsXaqMoCjCNsQHKCBp5fBMrS1B0iIwtsi5kBomraicyErjqhG8DY6HLDYcGnu6sxlm4aiSCItDMPQ8DtPswQFDE+TcbgTz4JCIidIYUCEIQhjUpUYBqFaQA

- Press the plus button to add items. They add in the wrong place
- Toggle off and back on. The items now show up in the right place
- Click all the items to delete them
- Press the plus button again. The items once again show up in the wrong place.

**Comment by ryansolid** [comment]
Oh my bad I just broke this recently(1.3.5) trying to cleanup some seemingly extraneous code. That'll teach me. Thanks for reporting this.
