### ISSUE TITLE
Property 'forEach' does not exist on type 'Element'

### ISSUE THREAD

**Issue by 6643** [solidjs/solid#856]
### Describe the bug

children(fn: Accessor<JSX.Element>): Accessor<JSX.Element>;
Property 'forEach' does not exist on type 'Element'

### Your Example Website or App

https://www.solidjs.com/tutorial/props_children

### Steps to Reproduce the Bug or Issue

createEffect(() => c().forEach(item => item.style.color = props.color));

### Expected behavior

no error

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by LXSMNSYC** [comment]
the type `JSX.Element` is as union of other types, you cannot safely assume that it is just an "array". This error you are experiencing is TS only. To perform type elimination, you can do

```js
const children = c();
if (Array.isArray(children)) {
  children.forEach(item => item.style.color = props.color);
} else {
  // cover the other types
}
```

**Comment by 6643** [comment]
@LXSMNSYC

thank you

**Comment by 6643** [comment]
cannot execute else
