### ISSUE TITLE
Switch statement does not match more than once when a selector is referenced more than once in a classList

### ISSUE THREAD

**Issue by GodBleak** [solidjs/solid#862]
### Describe the bug

When a selector is referenced more than once in a classList, Switch statements that match it, only do so once.

### Your Example Website or App

https://playground.solidjs.com/?hash=941788124&version=1.3.7

### Steps to Reproduce the Bug or Issue

1. Define some classes

```css
button {
  display: block;
}

.red {
  background-color: #ff3e00;
  color: white;
}
.bold {
  font-weight: 700;
}
```

2.  create a selector and toggle those classes in a classList referencing the selector more than once

```tsx
const buttons = ["Foo", "Bar", "Baz"]
const [current, setCurrent] = createSignal(1);
const isCurrent = createSelector(current)

...

<For each={buttons}>
    {(button, index) =>
        <button
            classList={{
                red: isCurrent(index() + 1),
                bold: isCurrent(index() + 1)
            }}
            onClick={() => setCurrent(index() + 1)}
        >
            {button}
        </button>
    }
</For>
```
3. match the selctor in a switch statemnt
```tsx
<Switch>
    <For each={buttons}>
        {(button, index) => <Match when={isCurrent(index() + 1)}>selected:{button}</Match>}
    </For>
</Switch>
```

### Expected behavior

The switch statement should continue to match every time the selector updates, as it does when the classList references the selector once.

### Platform

- OS: Manjaro
- Browser: Firefox
- SolidJS Version: 1.2.6

**Comment by LXSMNSYC** [comment]
I'm not sure what the problem is, the demo playground seems to be working correctly as intended. Have you tried upgrading your SolidJS version?

**Comment by mdynnl** [comment]
The switch updates only the first time if the commented line is un-commented. I've never thought using `For` or `Index` inside `Switch` though 😆.

**Comment by LXSMNSYC** [comment]
You're right, I tested it again. What's also weird is that there is some case where the first or the last item cannot be selected by any means.

**Comment by mdynnl** [comment]
https://playground.solidjs.com/?hash=-719259676&version=1.3.7

**Comment by GodBleak** [comment]
Yeah the more a played with it the weirder it got. 
Forgot to add, this is what Ryan had to say about it 

> yah the bug is in createSelector
we use a set to dedupe and onCleanup runs at the wrong time

that may be helpful.
