### ISSUE TITLE
Potential benchmark slowdown

### ISSUE THREAD

**Issue by Exelord** [solidjs/solid#875]
I think this might be a bug. It looks like garbage collection time is calculated into the benchmarked function. And as Garbage collection performance depends on system free resources this might very depending on workload.

https://github.com/solidjs/solid/blob/95969d0b67dbad306f7b18736d88356d5e678532/packages/solid/bench/bench.cjs#L71-L75

The solution would be changing the order of when the GC is run.

```suggestion
    end = now();

    // end GC clean
    sources = null;
    %CollectGarbage(null);
```

**Comment by leeoniya** [comment]
imo, GC costs should be part of any benchmark. under stress, the amount of mem alloc and garbage created (and must be tracked & collected) directly impacts performance.

**Comment by ryansolid** [comment]
This benchmark was a direct port from [S.js](https://github.com/adamhaile/S). I've been using it but haven't modified beyond using Solid's syntax. I think this was intentional. Adam was particularly concerned around overhead for creation/teardown. He did say the benchmark results were as stable as he'd like but it was instrumental in how he tuned reactive performance. I've been using it ever since.

**Comment by Exelord** [comment]
From what Im aware GC is async and happening during processor idle time. That means that even consuming large amount of memory for "garbage" it will have no impact on the performance unless we run out of it and it's needed again. As allocation can be quite high from 4-16gb I cannot see any reason why the process of "cleaning" should be included as performance measure as it's performance will never impact the benchmarked code in real life.

**Comment by leeoniya** [comment]
The GC is fully implementation-dependent. Chrome's GC is not fully concurrent as of last writing [1], and does delay the JS thread from running this script:

```html
<!doctype html>
<html>
  <head>
    <title>test</title>
  </head>
  <body>
    <div id="out1"></div>
    <div id="out2"></div>
    <div id="out3"></div>
    <script>
      let len = 1e6;

      let arr = Array(len);

      for (let i = 0; i < len; i++)
        arr[i] = Math.random() * 100;

      let out1 = document.getElementById("out1");
      let out2 = document.getElementById("out2");
      let out3 = document.getElementById("out3");

      let i = 0;

      let it = setInterval(() => {
        if (i+3 == len)
          clearInterval(it);

        out1.textContent = arr[i];
        out2.textContent = arr[i+1];
        out3.textContent = arr[i+2];

        i++;
      }, 20);
    </script>
  </body>
</html>
```

![image](https://user-images.githubusercontent.com/43234/156936890-df6a9e05-3b37-4e10-b6d3-03c01d8a8793.png)

[1] https://v8.dev/blog/trash-talk#state
