### ISSUE TITLE
Running into issues with Parcel looking for a jsx-dev-runtime

### ISSUE THREAD

**Issue by alexrhogue** [solidjs/solid#876]
### Describe the bug

Hey all.  I'm seeing this error when trying to build a solidJS project with Parcel:
```
@parcel/core: Failed to resolve 'solid-js/jsx-dev-runtime' from './src/writer/app.tsx'
```
tsconfig:
```
{
  "compilerOptions": {
    "module": "commonjs",
    "moduleResolution": "node",
    "jsx": "preserve",
    "jsxImportSource": "react"
  },
  "include": [
    "src/**/*"
  ]
}
```

I am **not** using babel as Parcel supports TS compilation natively.   

I may be over simplifying here, but is solidJS just missing a dev runtime export?  In the Preact library I see an [explicit export for the dev runtime](https://github.com/preactjs/preact/blob/d4a301391c21632828a1a9c19e08486a18075974/package.json#L55).

Any insights on this issue?  

I was torn on whether to put this issue here or in the parcel repo.  

### Your Example Website or App

https://github.com/alexrhogue/parcel-solid-build

### Steps to Reproduce the Bug or Issue

Clone that repo
```
npm i
npm start
```

Note, I made a branch with React that works as expected.

```
git checkout react
npm i
npm start
```

### Expected behavior

As a user, I expect parcel to be able to build a SolidJS package when the tsconfig is configured correctly

### Platform

- OS: osx
- Browser: n/a

**Comment by ryansolid** [comment]
Solid needs babel since we have a custom JSX transformation. Even with TS we need babel to transform the JSX. Part of what makes Solid special is that it does not use the default JSX transform. We have a babel preset.. `babel-preset-solid` that should be used.

**Comment by alexrhogue** [comment]
Oh I see.  That makes sense to me.  Thanks for the info!
