### ISSUE TITLE
Throw error when SSR rendering the app in the browser

### ISSUE THREAD

**Issue by ConsoleTVs** [solidjs/solid#878]
### Describe the bug

If possible, when using the `render*` functions that are aimed for SSR / SSG in the browser context, we should thow an error to indicate they should not be used on it. Instead, the current behaviour is to return undefined. This is misleading because typescript expects a string as well (and it should always be a string on the server anyway).

### Your Example Website or App

No need

### Steps to Reproduce the Bug or Issue

```tsx
import { renderToString } from "solid-js/web";

import App from "./App";

const result = renderToString(() => <App />);
console.log(result);
```

### Expected behavior

To throw an error when used in a browser context.

### Platform

- OS: macOS
- Browser: Chrome
- Version: 99.0.4844.51 (Official Build) (x86_64)

### Additional context

![Screenshot 2022-03-07 at 19 29 24](https://user-images.githubusercontent.com/6124435/157095539-7ecc4a4f-b759-4f3e-99d3-1b70cd8012f6.png)

**Comment by Aslemammad** [comment]
I'm going to try this issue!
