### ISSUE TITLE
Restrictive Nesting Leads to Error

### ISSUE THREAD

**Issue by tomitrescak** [solidjs/solid#883]
### Describe the bug

I am not sure whether this is solid error or vite error, but this happened to me first time when interacting with your framework. When I use not-standard nesting, the app crashes. For example nesting `p > div`. See example below

```
<p><div>Will error</div></p>
```

This will crash the app completely and lead to following erro in the console:

```
Uncaught The browser resolved template HTML does not match JSX input:
<div><p></p><div>Will error</div><p></p></div>

<div><p><div>Will error</div></p></div>. Is your HTML properly formed?
```

### Your Example Website or App

https://github.com/tomitrescak/solid-report-1

### Steps to Reproduce the Bug or Issue

> npx degit solidjs/templates/ts my-app
> cd my-app
> npm i # or yarn or pnpm
> npm run dev # or yarn or pnpm

And replace the default App.tsx with the following:

```tsx
import type { Component } from "solid-js";

import styles from './App.module.css';

const App: Component = () => {
  return (
    <div class={styles.App}>
      <p>
        <div>Will error</div>
      </p>
    </div>
  );
};

export default App;
```

### Expected behavior

The "incorrect" nesting should not yield to error.

### Platform

- OS: macOS
- Browser: Chrome, Safari, Firefox
- Version: Latest

**Comment by ryansolid** [comment]
That suggests its invalid HTML. Solid uses templates to clone and walks the created nodes. Browsers will "fix" the HTML for you and then it won't match the JSX we analyzed causing it to get out of sync. We throw so the error is more obvious. Otherwise, we get stuff like "cannot access 'firstChild' of null". I wish this could be done at compile time but am yet to find an easy way.

**Comment by edemaine** [comment]
In case it's helpful, [here is React's code for checking these conditions](https://github.com/facebook/react/blob/cae635054e17a6f107a39d328649137b83f25972/packages/react-dom/src/client/validateDOMNesting.js). I've definitely found these error messages helpful. Alternatively, I wonder if we could diff the serialized DOM with the input to give a helpful error message...

**Comment by tomitrescak** [comment]
Thank you for your explanation. Time to update the codebase with proper html.
