### ISSUE TITLE
Double click event cannot be monitored normally

### ISSUE THREAD

**Issue by xfy196** [solidjs/solid#898]
### Describe the bug

Binding a double-click event to a DOM has no effect

### Your Example Website or App

https://xfy196.github.io/todolist-solidjs-demo/

### Steps to Reproduce the Bug or Issue

1.Input content
2.enter
3.click 本地单击保存
4.has result
5.click 本地双击保存
5.no result

### Expected behavior

I hope his double click event is valid

### Platform

- OS: [ macOS]
- Browser: [Chrome]
- Version: [98.0.4758.109]

**Comment by xfy196** [comment]
This is my source code:
https://github.com/xfy196/todolist-solidjs-demo

**Comment by ryansolid** [comment]
Oh I think I know what is. The DOM event is "dblclick" not "doubleclick". We keep dom conventions so it's `onDblClick`.

**Comment by xfy196** [comment]
Sorry, I use the solidjs plug-in of vscode. The default prompt he gives me is doubleclick. Thank you for your answer

**Comment by ryansolid** [comment]
It's probably that without a TS config the global JSX types (React) are being pulled in and that is misleading since React transforms `onDoubleClick` to `dblclick` event.
