### ISSUE TITLE
Not able to create duplicate Elements 

### ISSUE THREAD

**Issue by whoami-shubham** [solidjs/solid#899]
### Describe the bug

Hi 👋
Thanks for creating this Library.

I am using solid for my recent project and I needed to create duplicate elements for a use case.
I created a JSX variable and using loop I tried to render multiple times. every time it renders only one element.
 and If I try to use this in multiple places it only appears at last place i have used it .
 
  If I use JSX inside loop instead of variable whose value is JSX , then it works. 
  
 This doesn't seems like intended behaviour , e.g  if we have a component that we want to render multiple times and  then we don't want to repeat the JSX again inside loop.

### Your Example Website or App

https://codesandbox.io/s/solidjs-initial-yivzxh?file=/index.tsx:453-459

### Steps to Reproduce the Bug or Issue

1. create a variable e.g 
```js

let element = <div>value</div>;

```
2. try to render this variable multiple times

### Expected behavior

<img width="693" alt="image" src="https://user-images.githubusercontent.com/28999685/159913697-2611f0ca-32bb-4b5f-8fa6-69609fa8e64e.png">

### Screenshots or Videos

<img width="693" alt="image" src="https://user-images.githubusercontent.com/28999685/159917867-eeac68b5-e42f-4d8b-9530-88b378ce98b2.png">

### Platform

- OS: [macOS]
- Browser: [e.g. Chrome]
- Version: [e.g. 99.0.4844.74]

### Additional context

```js
import { render } from "solid-js/web";
import { createSignal, For, Index } from "solid-js";

const value = <div>value</div>;
const arrayValues = new Array(3).fill(value);

const A = () => {
  return (
    <>
      <h3>using For</h3>
      <For each={arrayValues}>{(item, idx) => item}</For>
    </>
  );
};

const B = () => {
  return (
    <>
      <h3>using Index</h3>
      <Index each={arrayValues}>{(item, idx) => item()}</Index>
    </>
  );
};

const C = () => {
  return (
    <>
      <h3>using Spread</h3>
      {arrayValues}
    </>
  );
};

const D = () => {
  const [state, setState] = createSignal(arrayValues);
  return (
    <>
      <h3>using Signal</h3>
      {state()}
    </>
  );
};

const E = () => {
  return (
    <>
      <h3>using JSX variable</h3>
      <For each={new Array(3)}>{(item, idx) => value}</For>
      <h3>using JSX value</h3>
      <For each={new Array(3)}>{(item, idx) => <div>value</div>}</For>
    </>
  );
};

const ThreearrayValues = (props) => {
  return (
    <div onClick={props.onClick}>
      <A />
      <B />
      <C />
      <D />
      <E />
    </div>
  );
};
function App() {
  return (
    <ul>
      <ThreearrayValues onClick={() => {}} />
    </ul>
  );
}

render(() => <App />, document.getElementById("app"));

```

**Comment by thetarnav** [comment]
I guess you cannot have multiple of the same dom element inserted on the page. Only the first one will be will be inserted and the other just ignored.
https://playground.solidjs.com/?hash=1166027319&version=1.3.9

It's like doing
```ts
const el = document.createElement("div");
document.body.appendChild(el);
document.body.appendChild(el);
document.body.appendChild(el);
```

If you want to repeat those elements, they would need to be turned into functions, so that every time a new instance is created and inserted into the dom.
```ts
const el = () => <div>value</div>;
const arrayValues = new Array(3).fill(el);

const App = () => {
  return (
    <ul>
      {arrayValues}
    </ul>
  );
}
```

**Comment by whoami-shubham** [comment]
@thetarnav Thanks for answering this.

**Comment by atk** [comment]
That's not exactly correct. If you insert a DOM node that is already in the DOM, it gets removed from its current and attached to its new position, so you still have one DOM element at the end.

**Comment by Phinome** [comment]
sorry, i still have some question。
playground: https://playground.solidjs.com/anonymous/07fa573b-fe1f-47e1-a150-868017e18fb9
example code:
```jsx
import { render } from "solid-js/web";
import { type JSX, Index } from "solid-js";

interface ListSpansProps {
  sp: JSX.Element
}

function ListSpans(props: ListSpansProps) {
  return (
    <Index each={Array(5).fill(props.sp)}>
      {
        (item, index) => {
        return <button type="button">current {index + 1}{item()}</button>
      }
      }
    </Index>
  )
}

render(() => <ListSpans sp={<span style={{color: 'orange'}}>Element</span>} />, document.getElementById("app")!);

```

how to make `props.sp` render in every button child.
thx.
