### ISSUE TITLE
Directives on a button call onCleanup too early if class is using signal

### ISSUE THREAD

**Issue by illiaChaban** [solidjs/solid#903]
### Describe the bug

I'm using ref={myDirective} instead of use:myDirective because dealing with directives in TS is painful. It worked well for me so far. However, I have noticed weird conditional behavior where onCleanup is called way too early.

If I use smth like `<button class={signal() && 'myClass'}` ref={myDirective} />`, onCleanup is called on button click/mount. (It seems that it's called onClick in the playground example and as soon as it mounts locally for me).

If I don't use signal in the class, it works as expected. Same behavior when i use `class` or `classList`

### Your Example Website or App

[playground](https://playground.solidjs.com/?version=1.3.13#NobwRAdghgtgpmAXGGUCWEwBowBcCeADgsrgM4Ae2YZA9gK4BOAxiWGjIbY7gAQi9GcCABM4jXgF9eAM0a0YvADo1aAGzQiAtACsyAegDucAEYqA3EogcuPfr2ZCouOAGU0Ac2hqsvWhABhNTgoCHpCX38AWQYIXF9XAAtaQylZeUUVOg1tPQsrAogrGXoIZlw0f14A2JdGAAoASn4rXgd-Mj5gZlrfMjhcGtLcAF1eAF4HJxd3Lyg1eoAGRssINp6ITt4MRzh4OIneJomAPl5+wdr6nuHjgGpeAEYVwvWOrrJkwwAhXAg+gZJFK-CBjSa7ZxuTzeeq4Rj0OCNV6CAZMNb1VptXgAHhEaAAbidMVicUDUoZEsJxiBPsC-k1JES1iSsdjvvRcLgqsSWW0hDJqXihOUCXBpDzeQRiOMVCYOVyimBlMzeW1-EE0MwANbUnZCfa4cUq1XMNRQMhkak3OLHACkvAATLwAGTO3gAckpajUtHdkglWKZqqxIGtuAZAba2P07M5-iDLOjZITJOxcrja3VGm11OO4zOFzJIPq+NOvAAhPjGoyACq0DweYK8MnR9MKlM4-R4wmYl4Qf1FMrvXhCuAi-FwQ71OBqZr5lrMjbZOAAOh9Hnq7vo-RHaGFFQn7t8M6RzKzITChHqebOS-Uq-Xm9NF-Cu-3ovdjVPA6sS74sYVKdCDnM4QExaIrhvdpNnvNd603GBak-U81UCYJQnCa8QOg5c4I3d1nwwwhkMxIRcDRHE2yqEAV1owhpH0Jkf0HIRRHELCy2xIY4nEXhGN8ERaGYegDRXDwBgAUWCA1vnwABJEQMTAKBCEIFQv1WMBJBGIA) OR [sandbox](https://codesandbox.io/s/ec8ue8?file=/src/main.tsx)

### Steps to Reproduce the Bug or Issue

1: Go to [playground](https://playground.solidjs.com/?version=1.3.13#NobwRAdghgtgpmAXGGUCWEwBowBcCeADgsrgM4Ae2YZA9gK4BOAxiWGjIbY7gAQi9GcCABM4jXgF9eAM0a0YvADo1aAGzQiAtACsyAegDucAEYqA3EogcuPfr2ZCouOAGU0Ac2hqsvWhABhNTgoCHpCX38AWQYIXF9XAAtaQylZeUUVOg1tPQsrAogrGXoIZlw0f14A2JdGAAoASn4rXgd-Mj5gZlrfMjhcGtLcAF1eAF4HJxd3Lyg1eoAGRssINp6ITt4MRzh4OIneJomAPl5+wdr6nuHjgGpeAEYVwvWOrrJkwwAhXAg+gZJFK-CBjSa7ZxuTzeeq4Rj0OCNV6CAZMNb1VptXgAHhEaAAbidMVicUDUoZEsJxiBPsC-k1JES1iSsdjvvRcLgqsSWW0hDJqXihOUCXBpDzeQRiOMVCYOVyimBlMzeW1-EE0MwANbUnZCfa4SQSlnMNRQMhkAAyaE61JAxt5AHJKWo1LRHYh2rdmgBSXgAJgm40miwdWMk4pVLKZqqxIBucQZYex+nZnP8MZZKbJmZJ2Ll6bW6o02upx3GZwuZJB9Xxp14AEJ8Y1GQAVWgeDzBXhklMFhW5nH6PGEzEvCBGopld68IVwEX4uCHepwNTNCstZkbbJwAB0bo89Ud9H6s7Qwoqi8dvlXSOZxZCYUI9XLZ236j3B6Ppsf4TPF9FR1GjvScrG3Pg0wVZdCHXM57XvCAYluV92k2D99w7I8YFqIC7zVQJglCcIX1g1Cdwww9HR-IjCFwzEhFwNEcX7KoQF3djCGkfQmVAqchFEcQSPrbEhjicReG43wRFoZh6ANXcPAGABRYIDW+fAAEkRAxMAoEIQgVGA1YwEkEYgA)
2. click the button and observe console.log "cleanup directive"
3. comment out conditional class logic
4. observe no early onCleanup logs

### Expected behavior

onCleanup is called at the same time regardless of whether I use signal in the class or no

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by ryansolid** [comment]
Hmm.. yes.. ok yeah spreads even though they don't re-run refs they do end up registering inside the effect that drives the spread.  Which prematurely calls the cleanup. This is a bug.
