### ISSUE TITLE
style attr gets re-evaluated when other attrs need change

### ISSUE THREAD

**Issue by sickill** [solidjs/solid#904]
### Describe the bug

Found a weird behaviour when working on asciinema-player - style attr gets re-evaluated when other attrs need change.

### Your Example Website or App

https://asciinema.org

### Steps to Reproduce the Bug or Issue

I created minimal reproduction example in the Solid Playground.

1. go to https://playground.solidjs.com/?version=1.3.13#NobwRAdghgtgpmAXGGUCWEwBowBcCeADgsrgM4Ae2YZA9gK4BOAxiWGjIbY7gAQi9GcCABM4jXgF9eAM0a0YvADo1aAGzQiAtACsyAegDucAEYqA3EogcuPfr2ZCouOAGU0Ac2hqps+YpU6DW09CytwiBl6CGZcNFoIXgBhAAs0NREACkJ5QjIASn4rXgcEsj5y-DU4XgBeXkzC2oA+IsSS0ogguAA6NVoPTIBySuqAQiH8y3aSoVwmRIFmdW5EXhzaPJ7l-olJaZLJCNm4ecZEzOKO-X0HKDU1Ml5RuEbeBN44ADdxfAcNZgAa0QVxKAB4yIQoIkKPgAF61EAbLbLaK4aQvREvRqSZpI3JkHoyWi0SRg-SQ6HNY7XW4iWhwMgQIZ8Zj3HzYwofb6-f5oIEgma8G68CFQxKYkCc3H4zaE4mk8mUiDU9pTKxHCBWKIxOIfJIMCAuRhvEBXZZdPjAVFGrDPU4GtEAXTqDicLncXnumQADOr2hbyrwMI44PAja63i17bhHUbMjbcG8ANS8ACM-qucwWDVBopM9FwuA+BGItRUBaLCRU7wgSQBgMRIaE4fRqo6HRAiZxefBqXSIlKu3LYCEIhricR3fy0n07Y65MrxZVV39mqsQlE4kyUdaYLjxuFzTt9OY9FbPQ8pwAotVWwAhfAASSyKighEIKny-rAkidQA
2. click on the button several times
3. notice how "style!" gets logged to the console on every click

### Expected behavior

I expected that `style={style()}` attr won't be re-evaluated given the `style()` function doesn't use any prop that click handler mutates, but it does. I found that referencing the same prop inside the component body instead doesn't cause this behaviour - only changes to a prop that's use in one of the attrs causes this. I found this out when changes to my `classList` caused re-eval of `style`, but it seems it's not `classList` specific, as any attr name (`xyz` in my example) reproduces this.

### Platform

- OS: Linux
- Firefox
- Version: 98.0.2

**Comment by atk** [comment]
You return a new object every time style() is called, thus it gets re-evaluated. Use `createMemo` to avoid that: https://playground.solidjs.com/?hash=-939766425&version=1.3.13

**Comment by ryansolid** [comment]
More so though it's that we group things. Creation is generally much more expensive than update. Generally grouping with shallow diff is better than wrapping each in a separate effect, except where structural reconciliation is involved. So re-evaluating expressions may happen but it won't apply them. If it is expensive memo it, otherwise probably not worth worrying about.

**Comment by sickill** [comment]
Aha, I see. Thanks for the clarification.

For my use case it kinda does matter, given asciinema-player mutates props very frequently, sometimes hundreds of times per second (https://github.com/asciinema/asciinema-player/blob/8009671f94a507b8695f48e31e81ca8c6996349e/src/components/Terminal.js#L22 - `props.blink` is frequently updated causing style re-eval). While I don't have a lot going on in my `style` function the unnecessary eval just compounds in my case. 
I can use a memo fine, that was actually my plan B here, so will do that.

Is the "You return a new object every time style() is called, thus it gets re-evaluated" behaviour documented somewhere?

**Comment by ryansolid** [comment]
I don't think it matters here. Because it isn't inlined it de-opts to a style helper anyway that does a diff. Most things do shallow referential to check for changes which @atk is referring to but this one doesn't matter. It's always an object so knows it needs to diff.

**Comment by sickill** [comment]
Hmm, ok.. I don't understand any of it but I guess you don't find it as a bug so I'm going to close it. Thanks.
