### ISSUE TITLE
The terms upstream and downstream are mixed within the codebase

### ISSUE THREAD

**Issue by orenelbaum** [solidjs/solid#915]
In the following files:
- [src/reactive/signal.ts](https://github.com/solidjs/solid/blob/f1b8c21a6c5de3bd469b1ce3d6cb14134a432eed/packages/solid/src/reactive/signal.ts)
- [bench/prototypes/queue-noarray.cjs](https://github.com/solidjs/solid/blob/aeb6c096aca3c8b4871d36b70e88d275432f83d7/packages/solid/bench/prototypes/queue-noarray.cjs)
- [bench/prototypes/message-noarray.cjs](https://github.com/solidjs/solid/blob/aeb6c096aca3c8b4871d36b70e88d275432f83d7/packages/solid/bench/prototypes/message-noarray.cjs)
- [bench/prototypes/queue.cjs](https://github.com/solidjs/solid/blob/aeb6c096aca3c8b4871d36b70e88d275432f83d7/packages/solid/bench/prototypes/queue.cjs)
- [bench/prototypes/message.cjs](https://github.com/solidjs/solid/blob/aeb6c096aca3c8b4871d36b70e88d275432f83d7/packages/solid/bench/prototypes/message.cjs)
The `lookDownstream` and `markUpstream` functions are mixing up the directions, they should be renamed to `lookUpstream` and `markDownstream` respectively.

**Comment by ryansolid** [comment]
I agree. I'm open to a PR for this.

**Comment by fictitious** [comment]
It depends on your view - which way is up. Current naming suggests that observers are "above" the sources that they observe, which kind of makes sense, but is at odds with the general picture of a change that propagates "down" the dependency tree (however, everyone seems to be ok with the trees pictured with their root at the top :smile:).

Maybe it would be better to not use direction at all, and rename for example `markUpsteam` to `markObservers` or `invalidateObservers`, and `lookDownstream` to `lookInSources` or maybe `runStaleSources`.

**Comment by orenelbaum** [comment]
I think that there is an accepted meaning to downstream and upstream in this context and Ryan just mixed them up by accident. It also only makes sense this way since we are not talking generally about up or down, we are talking about upstream and downstream which refer to directions of causality.

**Comment by fictitious** [comment]
If there's an already accepted meaning then sure, I just did not know about it
