### ISSUE TITLE
Default error handling behavior

### ISSUE THREAD

**Issue by edemaine** [solidjs/solid#919]
Consider [this buggy code](https://playground.solidjs.com/?hash=-286161745&version=1.3.13) (based on some actual code I wrote and had a hard time debugging). The actual bug is that `createEffect` isn't `import`ed, so attempting to call it causes an error. But the only error that gets output to the console is `Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'style')` which is caused by the `onMount` code, which assumed the `ref` would be set by this point, but it wasn't because the component didn't get to running the JSX. This makes debugging hard.

@otonashixav tracked this down to [runUpdates's `try` block](https://github.com/solidjs/solid/blob/9cd3f260fc6c7f39d69c752f3d6b3ffb7cd35891/packages/solid/src/reactive/signal.ts#L1392-L1398). When there are no error handlers installed, `handleError` just rethrows the exception, and then the `finally` block runs, which includes the `onMount`, which throws its own error, which takes precedent.

**Question:** Could the `completeUpdates` be moved outside the `finally` block, so that it only runs if there are no uncaught errors? Or is it intentional that scheduled effects run even when there's an uncaught error?

Assuming the behavior is intended, it would be really nice to have a default error handler, perhaps at least in dev mode, that outputs all errors that occur, something like ``onError((e) => console.error(`Uncaught error in Solid component: ${e}`))``.  When there are error handlers, we [actually get the correct error message](https://discord.com/channels/722131463138705510/722131463889223772/960268191815307344). @mdynnl suggested maybe wrapping all `render` calls in an `ErrorBoundary` but I think `onError` is more appropriate if the goal is to write to `console`. Actually, to make this error handler disappear when the user provides error handlers, maybe it would be better to add it directly to [handleError](https://github.com/solidjs/solid/blob/9cd3f260fc6c7f39d69c752f3d6b3ffb7cd35891/packages/solid/src/reactive/signal.ts#L1578) just before re-throwing the error.

Thanks also to @orenelbaum for helping track this down.

**Comment by ryansolid** [comment]
Yeah... there needs to be a finally to clear out the Update/Effects where suitable but perhaps we can write this a little differently and still accomplish this.
