### ISSUE TITLE
refs break with compiled class private fields

### ISSUE THREAD

**Issue by trusktr** [solidjs/solid#922]
### Describe the bug

I found an issue in syntax. Refs don't get assigned to private fields, but regular properties work fine.

### Your Example Website or App

n/a

### Steps to Reproduce the Bug or Issue

This works:

```js
class Foo {
  el
  template = () => <div ref={this.el} />
}
```
but this one fails:
```js
class Foo {
  #el
  template = () => <div ref={this.#el} />
}
```
The output changes from
```js
      const _ref$ = _self$.scene;
      typeof _ref$ === "function" ? _ref$(_el$) : _self$.scene = _el$;
```
to
```js
      const _ref$ = _classPrivateFieldGet(_self$, _scene);
      typeof _ref$ === "function" && _ref$(_el$);
```
so it fails to set the (compiled) private field.

### Expected behavior

The private field should be assigned to, but the compile output doesn't assign to it.

### Platform

Babel with private fields compiled.

### Additional context

Playground works because it doesn't compile private fields. For example:

https://playground.solidjs.com/?hash=2050595631&version=1.3.13

The output tab shows:

```js
      const _ref$ = _self$.#btn;
      typeof _ref$ === "function" ? _ref$(_el$) : _self$.#btn = _el$;
```

**Comment by LXSMNSYC** [comment]
Personally I found this tricky but I would say that the problem comes from upstream (Babel), reason is that since Babel (or the other compilers) pre-compile polyfills, Solid's plugin doesn't have any idea how to handle these polyfills. I would say that this is more of an issue on the compiler rather than Solid itself since Solid can still safely transform the expression without the private fields polyfill.

**Comment by ryansolid** [comment]
Yeah I don't really know what to do with this. The code checks if it is an assignable expression and if so compiles the if a function check or assign. It must decide that the function means that it doesn't have the reference to assign to. I don't think there is anything we can do about this.

**Comment by trusktr** [comment]
What if the compiler also checks for `_classPrivateFieldGet`, besides an assignable expression, and in that case uses `_classPrivateFieldSet`?

**Comment by LXSMNSYC** [comment]
I personally think that's a naive check. Babel may produce a new identifier for those two functions if the user intends to use these exact identifiers.
