### ISSUE TITLE
Spread of `class` and `classList` Do Not Appear to Work in SSR

### ISSUE THREAD

**Issue by dairyisscary** [solidjs/solid#939]
### Describe the bug

When using both `class` and `classList` props in a spread manner, SSR seems to produce invalid serialization of the `class` attribute on the wire.

```jsx
function MyDiv(props) {
  return <div {...props}>{props.children}</div>;
}

<MyDiv class="outer" classList={{ inner: value() }}>hi solid!</MyDiv>
```

when `value()` is truthy i would expect `class="outer inner"` and when `value()` is falsy i would expect `class="outer"` but the actual output over the wire is `class="outer" class=" inner"` when its truthy for instance.

As far as i can tell, this is a quirk of `ssrSpread` in `dom-expressions` somewhere around here:
https://github.com/ryansolid/dom-expressions/blob/main/packages/dom-expressions/src/server.js#L307
wondering if maybe `class` and `classList` must be accounted for together in that loop. Let me know if I should be filing this bug there instead.

### Your Example Website or App

https://playground.solidjs.com/?hash=1636620625&version=1.3.13

### Steps to Reproduce the Bug or Issue

One can take a look at the playground for full example.

### Expected behavior

Various browsers seem to handle this differently but the most common case I've seen is they only pay attention the first `class` attribute which makes styling look wrong

### Platform

- OS: macOS
- Browser: all
- Version: 1.3.15

**Comment by ryansolid** [comment]
You are correct. This is basically impossible to resolve at compile time. The only option is to de-opt all classes and merge at runtime when a spread is present. Adding to my list of why classList was a mistake. Or at least allowing spread of it is (rather than treating it like a directive).

**Comment by dairyisscary** [comment]
amazing!
