### ISSUE TITLE
createSelector breaks with "undefined"

### ISSUE THREAD

**Issue by pfgithub** [solidjs/solid#947]
### Describe the bug

When using createSelector() with `undefined`, a selector looking for undefined stays active even after the value that is being watched is changed

### Your Example Website or App

https://playground.solidjs.com/?hash=204297978&version=1.3.13

### Steps to Reproduce the Bug or Issue

1. click the top two buttons. notice how only one can be active at a time
2. click the bottom button. it works correctly
3. click one of the top two buttons again. notice how the bottom button continues to say "true"

### Expected behavior

All three buttons would behave the same, where clicking any one turns off all the others

### Platform

- OS: macOS 12.1
- Browser: Firefox
- Version: 99

**Comment by ryansolid** [comment]
Yeah I see it. I was using undefined as a way of preventing execution on the previous value the first time but I should do it explicitly.
