### ISSUE TITLE
Children introspection (with children helper) not working correctly with SSR

### ISSUE THREAD

**Issue by mosheduminer** [solidjs/solid#949]
### Describe the bug

I am using the children helper to introspect and wrap children elements. When using SSR (in solid-start), I am finding that the children fail to render.

### Your Example Website or App

https://github.com/mosheduminer/solid-ssr-bug-repro

### Steps to Reproduce the Bug or Issue

1. Clone https://github.com/mosheduminer/solid-ssr-bug-repro
2. Run `npm install` and `npm run dev`
3. Open the browser to localhost:3000

### Expected behavior

I expected the children to render in SSR. They did not.

### Platform

- OS: Windows
- Browser: Edge
- Version: 100.0.1185.44 (Official build) (64-bit) 

### Additional context

This was originally reported in the solidjs discord [here](https://discord.com/channels/722131463138705510/722167424186843267/966020871422631976).

**Comment by ryansolid** [comment]
Looking into it, this is a tricky one. For 2 reasons:
1. These aren't DOM nodes or VDOM nodes. If I made this work you'd get an array of templates `{ t: "<div />" }`.
2. It's a de-opt to all loops as right now `<For>` skips the intermediate array and returns the combined template. 

I wonder what the case that forces this looks like. It's definitely awkward to fix. I guess as long as it can be rendered that is fine.

**Comment by mosheduminer** [comment]
@ryansolid in my case, the <For> renders components that returns _props_, and the wrapper component then renders those props. So I need to be able to introspect the props in order to render. This is the same pattern as <Switch>/<Match>, so I wonder if those components are affected by the same issue.

**Comment by ryansolid** [comment]
In that case we wouldn't be getting templates back. but objects. Yeah that is legit I think we will need to look into that. I'm not sure I can do this without a big deopt. 

It means that a framework that doesn't do introspection like Marko or Svelte will one day be able to outperform us on server rendering as they don't need to do this extra mapping. But for now this still has us double the next closest framework in benchmarks.

**Comment by mosheduminer** [comment]
Okay, got it. Should I update the repro to fit my use case as described (I can do that tomorrow)?

**Comment by mosheduminer** [comment]
@ryansolid I updated the repro to be closer to my actual use case.

**Comment by ryansolid** [comment]
Found a solution that only costs us 4% performance in benchmarks. So stoked. Early testing was showing we'd lose about 35%. So I'm happy with that. More general this way too.
