### ISSUE TITLE
<For/> on createStore() only prints first item in array

### ISSUE THREAD

**Issue by 0bon** [solidjs/solid#950]
### Describe the bug

If there is more than one item in the `problems` array. they are not printed out. Only the first item is printed by the `<For/>` loop. Another possible bug is that setting `setProblem([])` does not empty the store.

```ts
import { createForm } from '@felte/solid';
import { For, Show } from 'solid-js';
import { createStore } from 'solid-js/store';

export default function main() {
    const [problems, setProblem] = createStore<Array<string>>([]);
    const { errors, form } = createForm({
        onSubmit: (values) => {
            fetch(values.url)
                .then((res) => res.text())
                .then((data) => {
                    const servers = data.split(/\r\n/);
                    servers.forEach((item) => {
                        try {
                            // add server
                        } catch (e: unknown) {
                            if (e instanceof Error) {
                                setProblem([...problems, e.message]);
                            }
                        }
                    });
                });
        },
    });
    return (
        <form use:form>
            <Show when={problems.length > 0}>
                <div>{problems.length} items failed to configure</div>
                <For each={problems}>
                    {(item) => <div>{item}</div>}
                </For>
            </Show>
        </form>
    );
}

```

### Your Example Website or App

n/a

### Steps to Reproduce the Bug or Issue

n/a

### Expected behavior

The `<For />` loop should print out all items in the `problems` array, not just the first one. 

### Platform

Linux
npm 8.3.1
solid-js 1.3.15
Latest version of Firefox

**Comment by ryansolid** [comment]
Top level arrays in stories will not work as you are expecting since they only track property access. Ie.. `store.something`. In order to track that we'd need some way of calling it to track it. Simply passing `problems` won't do it. This is something I'd love to be more ergonomic but the recommendation today is if there are arrays you wish to iterate over put them on a nested property.

More information available here: https://www.solidjs.com/docs/latest/api#createstore

**Comment by mdynnl** [comment]
https://www.solidjs.com/docs/latest/api#using-stores
> The top level state object cannot be tracked, so put any lists on a key of state rather than using the state object itself.

https://playground.solidjs.com/?hash=1654881038&version=1.3.13
