### ISSUE TITLE
`createMemo` and `equals` option

### ISSUE THREAD

**Issue by kaisermann** [solidjs/solid#957]
### Describe the bug

I have a `createMemo` signal that must have a custom comparator. According to the docs and types that should be possible, but the `equals` function doesn't seem to be triggered. I downloaded `solid`'s repo and added the following test:

```ts
  test("Create and read a Memo with comparator", () => {
    createRoot(() => {
      const [value, setValue] = createSignal(5);
      const equals = jest.fn((a, b) => a > b);

      const memo = createMemo(() => value(), 0, { equals });
      expect(memo()).toBe(5);

      setValue(3);

      expect(memo()).toBe(5);
      expect(equals).toHaveBeenCalledTimes(1);
    });
  });
```

And it fails:

```
  ● Create signals › Create and read a Memo with comparator

    expect(received).toBe(expected) // Object.is equality

    Expected: 5
    Received: 3

    expect(jest.fn()).toHaveBeenCalledTimes(expected)

    Expected number of calls: 1
    Received number of calls: 0
```

### Your Example Website or App

https://stackblitz.com/edit/js-pvfu9n

### Steps to Reproduce the Bug or Issue

The test above is the simplest as it gets.

### Expected behavior

Expected the `equals` function of a `createMemo` to be executed and prevent unnecessary updates.

### Platform

- OS: macOs
- Browser: n/a
- Version: 1.3.14

**Comment by otonashixav** [comment]
It seems that it won't called unless the memo has at least one observer: https://playground.solidjs.com/?hash=1143719889&version=1.3.16, comment/uncomment the second memo.

**Comment by kaisermann** [comment]
@otonashixav Thanks for the tip! Indeed I had at least one observer in my real-world example but got confused and thought it wasn't working. I can confirm it works on my real-world example now. Thanks 🙏
