### ISSUE TITLE
Support spreading `null` or `undefined` props

### ISSUE THREAD

**Issue by tienpv222** [solidjs/solid#958]
### Describe the bug

Spreading `null` or `undefined` props gives runtime errors.

While it is not exactly the same, such situation is usually supported in places like plain object or `React`. It might be nice if `Solid` provides similar behavior.

Additional consideration: support full native spreading JS object with `boolean`, `number`, etc. ?

### Your Example Website or App

N/A

### Steps to Reproduce the Bug or Issue

N/A

### Expected behavior

Spreading `null` or `undefined` props shouldn't throw exceptions.

### Platform

N/A

### Additional context

Related discussions:

- https://discord.com/channels/722131463138705510/722349143024205824/751816143085240401
- https://discord.com/channels/722131463138705510/722349143024205824/968760047029080094

**Comment by LXSMNSYC** [comment]
> Doing {...(nullable ?? {})} should work, but I find it a bit inconsistent with native behavior. However that's just my personal thought.

Now I found this weird. I've been using TS for more than 3 years and I just learned this just now (since TS wouldn't allow you do this). I'm okay with supporting this but this just kind of felt weird for me :joy:

**Comment by edemaine** [comment]
Maybe you've been using TS too much. 😉 It's [part of ECMAScript](https://github.com/tc39/proposal-object-rest-spread/blob/main/Spread.md#:~:text=Null/Undefined%20Are%20Ignored) (also in [`Object.assign`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign#:~:text=does%20not%20throw%20on%20null)), and quite useful when you have optional arguments.

In the context of Solid, suppose you have an optional prop `props.divProps` that can be an object of props to pass in to a child component (useful when you have more than one such child component that you want to customize).  It's natural to want to write `<div {...props.divProps}>`, which gets ignored when `props.divProps` is null, just like you can currently write `<div foo={foo()}>` which gets ignored when `foo()` is null.

**Comment by tienpv222** [comment]
@ryansolid Please excuse me if I'm misunderstanding. I think 5292c2d didn't handle spreading component props (via `createComponent` with/without `mergeProps`).

**Comment by LXSMNSYC** [comment]
@tienpv222 the commit was made in the compiler: https://github.com/ryansolid/dom-expressions/commit/a8fc08cabcb5850de4b4f6c4f200794e96d8eb5a

**Comment by ryansolid** [comment]
Yeah i missed looking at mergeProps in Solid. We can add additional checks.
