### ISSUE TITLE
Context missing when using Dynamic

### ISSUE THREAD

**Issue by coreymcg** [solidjs/solid#969]
### Describe the bug

I'm using the `@thisbeyond/solid-dnd` drag and drop library. In a standard setup it works fine:

```jsx
function App() {
  return (
    <MyDragDropProvider>
      <MyDraggable id="A">Draggable</MyDraggable>
      <MyDropzone id="B">Dropzone</MyDropzone>
    </MyDragDropProvider>
  );
}
```

https://stackblitz.com/edit/solid-vite-gigzxd?file=src%2Findex.jsx

However, I'm trying to render the above component tree dynamically using `<Dynamic>`. This is needed as we're retrieving a "document" as JSON from the backend and then rendering it using components. Similar rendering an MDX file via `high1/solid-jsx`. 

In this scenario, with the exact same components, the context consumer components are not getting the latest data from the context.

Here's the MDX example:

```mdx
## Hi

<MyDragDropProvider>
  <MyDraggable id="A">Draggable</MyDraggable>
  <MyDropzone id="B">Dropzone</MyDropzone>
</MyDragDropProvider>
```

https://stackblitz.com/edit/solid-vite-gjiro1?file=src%2FMyDraggable.jsx

Here is the example with my code using Dynamic:

https://stackblitz.com/edit/solid-vite-6ooxdn

The following error occurs:

`create-draggable.js:6 Uncaught TypeError: useDragDropContext is not a function or its return value is not iterable
    at createDraggable`

This is because the context is returning null when it should be returning an array. It returns an array in the first example at the top so it seems to be more of an issue with Dynamic rather than solid-dnd.

### Your Example Website or App

https://stackblitz.com/edit/solid-vite-gjiro1?file=src%2FHelloWorld.mdx,src%2FMyDraggable.jsx

### Steps to Reproduce the Bug or Issue

To the the example url. See the errors in the console.

### Expected behavior

Expect to see:

https://stackblitz.com/edit/solid-vite-gigzxd?file=src%2FMyDraggable.jsx

But get an error in the console:

https://stackblitz.com/edit/solid-vite-gjiro1?file=src%2FHelloWorld.mdx,src%2FMyDraggable.jsx

### Platform

- OS: macOS
- Browser: Chrome
- Version: 101

**Comment by ryansolid** [comment]
It looks like the children are being created before the parent.. ie before the Provider. There is logic where deserializeElement calls itself for arrays and that ends up rendering beforehand. I haven't completely worked out the fix for the example, but that is where I'd start.

**Comment by coreymcg** [comment]
Of course! It was the order of creation that was causing the issue. Thank you so much. 

For everyone else's reference, here is the (unoptimized) working code:

```jsx
import { mergeProps, createMemo } from 'solid-js';
import { Dynamic, For } from 'solid-js/web';
import get from 'dlv';
import * as components from './components'

export function DocRenderer(props) {
  const renderedItem = createMemo(() => {
    return props.item ? <RenderNode {...props.item} /> : <div>No item</div>;
  });

  return <div>{renderedItem()}</div>;
}

export function RenderNode(props) {
  if (typeof props === 'string') {
    return props;
  }

  let { children, name, ...rest } = props;
  let component = get(components, name) || props.name.toLowerCase();
  return (
    <Dynamic {...mergeProps({ component }, rest)}>
      <For each={children}>{item => <RenderNode {...item} />}</For>
    </Dynamic>
  );
}

// usage
// <DocRenderer item={doc} />

```
