### ISSUE TITLE
`null` and `undefined` are missing in `createSignal` return type

### ISSUE THREAD

**Issue by julvo** [solidjs/solid#972]
### Describe the bug

When creating a signal with a union type that includes `null` or `undefined`, the resulting signal doesn't include `null` or `undefined`. 

E.g. if we create a signal that can be `null` or a `number` using `createSignal<null | number>(null)`, the return type is `Signal<number>` instead of `Signal<number | null>`

The issue is that the value of the signal is actually `null`, but the type signature doesn't reflect that. That means we loose type-safety.

### Your Example Website or App

https://playground.solidjs.com/?version=1.3.13#NobwRAdghgtgpmAXGGUCWEwBowBcCeADgsrgM4Ae2YZA9gK4BOAxiWGjIbY7gAQi9GcCABM4jXgF9eAM0a0YvADo1aAGzQiAtACsyAegDucAEYqA3EogcuPfr2ZCouOAGU0Ac2hqps+YpU6DW09CysrGXoIZlw0WgheAGEGCBdGAAoASn4rXgd4sj5gZhTcLF4yOFxkqNwAXV4AXgcnF3cvKDUAHgh6GBNxXgAfXl61NQA+dLG1TMsE-IhC3gxHOHhUpt4spomKqprU9JLanYBqXgBGOdzlBf19XgADKCeVsl5aGV4CYmfe-riN4meh8MgACwYahEvAG-z6AwkIxmT1uJSWfCgWxOR0y4QWQlwTAS6VueS6INwuHiPyIcEaKkp1IgKk+EESGmYAGtGiBVkINrhJBMyXl+DjcFlJKK8iAoNKFuT9Ez4iKFjcIAqrEJROJ0jtGnsuoc0rx9BNyiJaMw+sJcAA6DxVACianWdoAQvgAJIiUlgKCEQgqTIasCSOpAA

### Steps to Reproduce the Bug or Issue

1. Create a signal with a nullable type, e.g. `number | null`
2. Observe that resulting signal type doesn't include null, e.g. only `number` instead of `number | null`

### Expected behavior

When using `createSignal<T | null>(null)`, I'd expect the resulting signal to be of type `Signal<T | null>`

### Screenshots or Videos

Example from the Solid playground with `createSignal<number | null>()`
<img width="580" alt="image (18)" src="https://user-images.githubusercontent.com/18549792/167723920-a397e523-b192-4fcb-8db6-abd8ec7e4179.png">

Also an issue when creating a nullable signal using `createSignal<number>()`, where I'd expect the return type to be `Signal<number | undefined>`
<img width="487" alt="image (19)" src="https://user-images.githubusercontent.com/18549792/167723936-d34ecf0e-b5aa-4f62-bdc2-864cb3eec34c.png">

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

### Additional context

The issue may be related to #217, but that issue was focused on initialising without arguments.

**Comment by edemaine** [comment]
This is just a bug with the Playground: https://github.com/solidjs/solid-playground/issues/41

In actual use with `strict: true` turned on, it's properly preserved:

![image](https://user-images.githubusercontent.com/2218736/167730689-307cb996-3fe1-455a-9c7a-e92aea67d11c.png)

**Comment by ryansolid** [comment]
Yeah I'm going to close this one as a duplicate. We have some plans with the playground that will help with this.

**Comment by martinpengellyphillips** [comment]
Hmmm, I see a related issue here still with the setter typing. The setter is only accepting the first value from the union type. Let me know if I should open an issue for this (or perhaps I am just doing something wrong here - I'm a typescript novice still)

This is in vscode:

![createsignal-setter-type-issue](https://user-images.githubusercontent.com/214338/167946623-76393b4d-b219-4009-b82e-b6afa76d711e.png)

**Comment by edemaine** [comment]
This is still actually working. Notice the `<string>` in `<string>(value: string | ...) => string`. This means that the type of `setReferenceDraggableId` is parameterized, and here it's being used in its `string` form, presumably because `draggable.id` is of type `string`.

The [type definition](https://github.com/solidjs/solid/blob/fed400cd59e1984b1bce4908c316a6490db7af30/packages/solid/src/reactive/signal.ts#L128) is complicated, to prevent accidental attempts of passing in a function. But it should do what you actually want (albeit making hard-to-read types).

**Comment by martinpengellyphillips** [comment]
`draggable.id` is `string | number` though 🤔 

And I see this warning (the squiggly lines in the previous image):

```
(property) id: string | number
Argument of type 'string | number' is not assignable to parameter of type 'string | ((prev: ID) => string)'.
  Type 'number' is not assignable to type 'string | ((prev: ID) => string)'.ts(2345)
```

**Comment by edemaine** [comment]
It looks like #978 will fix this. Thanks @otonashixav!
