### ISSUE TITLE
`mergeProps` return type is broken when using generics and intersections types

### ISSUE THREAD

**Issue by riccardoperra** [solidjs/solid#982]
### Describe the bug

I'm trying to upgrade my application to Solid 1.4.0 but I am having troubles related to the new  `mergeProps` return type which broke some types inside my ui components library
https://github.com/riccardoperra/codeimage/runs/6428736073?check_suite_focus=true

The result of the `mergeProps` function is ok for the most cases, but when using types that depends on generics, some properties are missing or completely broken. To me this seems related to a typescript core issue, but I think some of solid types can be improved to try to handle these errors, even if not all

### Your Example Website or App

https://playground.solidjs.com/?hash=-238626028&version=1.4.1

### Steps to Reproduce the Bug or Issue

Here's a playground

https://playground.solidjs.com/?hash=-238626028&version=1.4.1

It consists of:
- main.tsx: small example copied from my repo
- text-solid-1.3.4-types.tsx: an example of mergeProps with old solid types which are not throwing error
- test-solid-1.4.0-fixed-types: an example with a possible fix for solid 1.4.0

### Expected behavior

Solid 1.3.4 was not throwing that error.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/37072694/168440198-8976319d-62fc-47f1-bdef-dda9bb2b5030.png)

### Platform

- Solid 1.4.0

### Additional context

A pr with the possible fix #983

**Comment by ryansolid** [comment]
Should be fixed in 1.4.2. Thanks for the PR.
