### ISSUE TITLE
`props.children` not available in type Component<T>

### ISSUE THREAD

**Issue by yw662** [solidjs/solid#985]
### Describe the bug

It is solid 1.4.1 (with ^1.3.x in package.json)
Within code: 
```tsx
import { Component } from 'solid-js'

export const Tmp: Component<{
  n: number
}> = props => {
  return <>
    {props.children}
  </>
}
```

TypeScript complaints that there is no `children` on `props`.
<img width="325" alt="" src="https://user-images.githubusercontent.com/34736747/168458967-10c1f369-cebd-4ef8-8fbd-a44be435f47c.png">

### Your Example Website or App

localhost

### Steps to Reproduce the Bug or Issue

as shown above.

### Expected behavior

It might be a breaking change or sth, but I cannot find it in the doc.
Should I always explicitly define it when a component need children ?

### Platform

- OS: macOS
- Browser: N.A. (TypeScript)
- Version: 1.4.1

**Comment by yw662** [comment]
yeah it is documented in #887. I hope it can be find somewhere in the doc.

**Comment by edemaine** [comment]
Yes: https://www.solidjs.com/guides/typescript#component-types

Glad you found it though!
