### ISSUE TITLE
Wrong types for `latest` resource field

### ISSUE THREAD

**Issue by elite174** [solidjs/solid#995]
### Describe the bug

At the moment latest is

`latest: T | undefined`

However, If we have the case, when we have an initial value (`someFetcher` returns list):
`const [listResource] = createResource(() => someFetcher, { initialValue: [] });`

We have never have the case when `listResource.latest` is `undefined`

### Your Example Website or App

-

### Steps to Reproduce the Bug or Issue

-

### Expected behavior

`latest` should have type `T` when there's `initialValue`

### Platform

-

**Comment by cstrnt** [comment]
Working on a fix :)
